### ISSUE TITLE
Handle File Input in Controller

### ISSUE THREAD

**Issue by mitulgolakiya** [InfyOmLabs/laravel-generator#1]
Currently file input is not handled via Controller.

**Comment by phillipmadsen** [comment]
concept of file input for generator. something to think about while working on the controller output.
[https://github.com/InfyOmLabs/laravel-generator/issues/103](url)

**Comment by mitulgolakiya** [comment]
Closing in reference of https://github.com/InfyOmLabs/laravel-generator/issues/103
