### ISSUE TITLE
Require infyomlabs/swagger-generator

### ISSUE THREAD

**Issue by CasperLaiTW** [InfyOmLabs/laravel-generator#10]
`laravel-generator` depended on `infyomlabs/swagger-generator`.
Ex: [ModelGenerator](https://github.com/InfyOmLabs/laravel-generator/blob/4d5c63c54c8a5890224e982d09fff9c1fdd46443/src/Generators/ModelGenerator.php#L96)

Should `infyomlabs/swagger-generator` be required in `composer.json`?

**Comment by iboinas** [comment]
It does not depend on it,

You have setting in config file, just put value to false

`
/*
    |--------------------------------------------------------------------------
    | Add-Ons
    |--------------------------------------------------------------------------
    |
    */

    'add_on' => [

        'swagger'   => false,

        'tests'     => false,
    ]
`

**Comment by CasperLaiTW** [comment]
Thank you, @iboinas

I miss.
