### ISSUE TITLE
how to show related data in create/edit page ?

### ISSUE THREAD

**Issue by mtariqsajid** [InfyOmLabs/laravel-generator#1002]
Is there any option to show data of related field in drop down when create page or edit page is open.
right now its show as a input field not as a select field  .

**Comment by mitulgolakiya** [comment]
I'm not 100% sure, but this might help with some tweak. https://infyom.com/open-source/laravelgenerator/docs/relationships

**Comment by mtariqsajid** [comment]
can you please give example of what need to be input when this command is ran
```
php artisan infyom:api_scaffold Post --relations

relationship_type,model_name,field1,field2,field3
```
what should i provide for **relationship type** ?
**filed1** ?

**Comment by mitulgolakiya** [comment]
https://github.com/InfyOmLabs/laravel-generator/blob/develop/src/Generators/ModelGenerator.php#L201

- 1t1 - One to One
- mt1 - Many to One
- 1tm - One to Many
- mtm - Many to Many
- hmt - Has Many Through

**Comment by mtariqsajid** [comment]
> https://github.com/InfyOmLabs/laravel-generator/blob/develop/src/Generators/ModelGenerator.php#L201
> 
> * 1t1 - One to One
> * mt1 - Many to One
> * 1tm - One to Many
> * mtm - Many to Many
> * hmt - Has Many Through

OK, thanks. I will check this out.
