### ISSUE TITLE
The most recent version will not let any of the forms submit. they all return errors.

### ISSUE THREAD

**Issue by phillipmadsen** [InfyOmLabs/laravel-generator#102]
MethodNotAllowedHttpException in RouteCollection.php line 219:

**Comment by mitulgolakiya** [comment]
@phillipmadsen I tested it with fresh installation and it worked fine. Can you post some more details ?

**Comment by phillipmadsen** [comment]
Yes let me do the same and If its still happening ill report it or if I  can find it ill push a fix.

**Comment by phillipmadsen** [comment]
This is no longer an issue.

**Comment by axyr** [comment]
This happens to me when using admin as prefix.

fresh install

**Comment by axyr** [comment]
The update route is set as put and not as patch.
The form is set as patch.

**Comment by mitulgolakiya** [comment]
@axyr will check it and fix it.

**Comment by mitulgolakiya** [comment]
Fixed.
