### ISSUE TITLE
swagger templates Not exist

### ISSUE THREAD

**Issue by hochdruckspezialist** [InfyOmLabs/laravel-generator#1036]
I use the Boilerplate but when i will use swagger i cant generate new contents

/vendor/infyomlabs/swagger-generator/templates/model_docs/model.stub

Not exists

Any Idea?

**Comment by mitulgolakiya** [comment]
Hi @hochdruckspezialist ,

Boilerplates are not updated with the latest version. Please create a fresh new project and install it by yourself.

I will update the boilerplates this week.

**Comment by alicanso** [comment]
boilerplates still not supporting I think. Because I am getting same error.
