### ISSUE TITLE
Awesome Generator.

### ISSUE THREAD

**Issue by mgip** [InfyOmLabs/laravel-generator#1039]
Firstable Congratulations for this amazing proyect, really.

I would install this generator but i have a little problem...

I have already started my project with a template, which I have obtained in codecanyon, I share the link to see it... https://radmin.rakibul.dev/login (Login and Pass inside input value)... Now my doubt, There is a way to customize the generation of the cruds through the "stubs".

I am a newbie in laravel, I would like some documentation or steps to follow.

Thanks a lot.

and congratulations again.

**Comment by mitulgolakiya** [comment]
Hi, @mgip Thank you for your appreciation.

Laravel Generator does not restrict you to use its AdminLTE templates. What you can do is, you can publish the stub files (templates) and can modify them the way you want. so you can use it for your own theme as well.

Here is the guide for that: https://infyom.com/open-source/laravelgenerator/docs/publish-templates
