### ISSUE TITLE
Migration ganeration, if dbType does not include ":".

### ISSUE THREAD

**Issue by msksbt** [InfyOmLabs/laravel-generator#1043]
Hi, thanks for this awesome project. 
( I'm sorry if there are any grammatical mistakes. )

I generated migration from JSON, but it's maked wrong statement.

I tried this:
```
{
..
    "name": "field_name",
    "dbType": "char,26",
..
}
```

but, it maked this:
```
    $table->char,26('field_name');
```         
            
I think that the problem occurs if dbType does not include ':', and there is a problem in follow clode block,
I tried this block to commented out, then the problem seems to be resolved.

https://github.com/InfyOmLabs/laravel-generator/blob/8575e2b6c8b2823b781f57656a9da7b3aac9cf06/src/Common/GeneratorField.php#L35-L40

Thanks.

**Comment by mitulgolakiya** [comment]
@msksbt Good Catch. Feel free to put a PR if you can, or I will take care of it by this week.

**Comment by msksbt** [comment]
@mitulgolakiya OK. I will try to fix and PR. thanks.
