### ISSUE TITLE
php artisan infyom:scaffold for custom table error and question about searchable

### ISSUE THREAD

**Issue by fredy-bambang** [InfyOmLabs/laravel-generator#106]
Hello, thank you for this cool stuff, 
i interested to try it out.

i just try this command below
**php artisan infyom:scaffold TrialTable --tableName=AX123 --paginate=5** 

and get error when do the migration 
**[Symfony\Component\Debug\Exception\FatalErrorException]
Class 'CreateAX123Table' not found** 

when i check the migration it created file with name 
2016_04_08_202724_create_AX123_table.php 
and i open the content 
its return with classname 
**class CreateTrialTablesTable extends Migration**

actually i can fix it manually but i just want to tell this problem.
after i try this generator yesterday.

And the second thing is about 
when i execute php artisan infyom:scaffold 
got feature like 

**Is Searchable (y/N):  []:**
when i type any of the option i got nothing after get the scaffold result and execute the script 
with my browser.and i didn't find it at documentation. 
I actually expect it have filter and sorting feature in this scaffold

maybe i miss it or something. 
if like that can you point to me what i'm miss. 

Sorry for my bad english.

**Comment by mitulgolakiya** [comment]
@fredy-bambang I have fixed table name stuff, will push it in next release.

You can find documentation for search [here](https://github.com/andersao/l5-repository#enabling-in-your-repository)

**Comment by tpharaoh** [comment]
Does that mean for search we need to add another package via composer? Do we need to edit views manually?

**Comment by mitulgolakiya** [comment]
No. Search is currently supported in apis only with this given package. This package is already installed when you install a generator. The search option is currently available when you generate scaffold with datatables. You can find doc [here](http://labs.infyom.com/laravelgenerator/docs/options/scaffold-options)
