### ISSUE TITLE
Laravel 10 Support

### ISSUE THREAD

**Issue by robertmarney** [InfyOmLabs/laravel-generator#1073]
Current release does not support Laravel 10.

There are two open PRs for L-10 Support:

https://github.com/InfyOmLabs/laravel-generator/pull/1061
https://github.com/InfyOmLabs/laravel-generator/pull/1066

I have used https://github.com/InfyOmLabs/laravel-generator/pull/1061 without issue in my limited use cases.

Do you expect to update this package to support Laravel 10?

**Comment by mitulgolakiya** [comment]
Yes, we will be adding support by next week. Bit occupied this week. I have planned it next week.

**Comment by dhsont** [comment]
Is Laravel 10 support released ?

**Comment by robertmarney** [comment]
@dhsont three weeks ago

**Comment by mitulgolakiya** [comment]
@dhsont it's in progress.

**Comment by enderjchacon** [comment]
@mitulgolakiya still in progress?

**Comment by mitulgolakiya** [comment]
@enderjchacon yes, we need to upgrade 4 packages in total. so it's taking bit more time.

**Comment by robertmarney** [comment]
Closed by #1066
