### ISSUE TITLE
Possibly add output option to fields

### ISSUE THREAD

**Issue by phillipmadsen** [InfyOmLabs/laravel-generator#108]
1- Add the option to html output the fields or just output normal.  

2- Another option that is needed is output lowecase or normal.

example:

```html
<label class="radio-inline ">
 {!! Form::radio('$FIELD_NAME$', "$VALUE$", null, ['id' => '$VALUE$', 'class' => '$FIELD_NAME$ $FIELD_NAME$-$VALUE$ ']) !!} $VALUE$
</label>
<!-- outputs -->
<label class="radio-inline ">
{!! Form::radio('type', {{ "Module" }}, null, ['id' => 'Module', 'class' => mb_strtolower('type type-Module ')]) !!} Module
</label>
```
As you can see the output of value should be lowercase in order to work propertly with the css and js of the page.

**Comment by mitulgolakiya** [comment]
@phillipmadsen then you can publish and customize templates as you want something like you suggested. But as this is not a general requirements of everyone. so closing it.
