### ISSUE TITLE
Error Call to undefined method Doctrine\DBAL\Connection::createSchemaManager()

### ISSUE THREAD

**Issue by YHOYO** [InfyOmLabs/laravel-generator#1083]
Im installing laravelgenerator https://infyom.com/open-source/laravelgenerator/docs/10.0/installation

and I want to use the "Generate From Table" https://infyom.com/open-source/laravelgenerator/docs/generator-options#custom-table-name

    php artisan infyom:scaffold Post --fromTable --table=posts --connection=remote

my DB  

![image](https://github.com/InfyOmLabs/laravel-generator/assets/6320408/5f1c83b8-5c33-429a-8af2-bdd50dceaf9c)

and my code in console with the error

    php artisan infyom:scaffold Qrcode --fromTable --table=qrcodes
    
       Error 
    
      Call to undefined method Doctrine\DBAL\Connection::createSchemaManager()
    
        1228▕     }
        1229▕
        1230▕     /**
        1231▕      * Get the Doctrine DBAL database connection instance.
    
      1   vendor\laravel\framework\src\Illuminate\Database\DatabaseManager.php:469
          Illuminate\Database\Connection::getDoctrineSchemaManager()
    
      2   vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php:353
          Illuminate\Database\DatabaseManager::__call("getDoctrineSchemaManager", [])

I did the dependency update, check database configuration, and the infyOm configuration, the qrcodes Tablen but nothing is wrong. 

I post in stackoverflow too https://stackoverflow.com/questions/77011477/error-call-to-undefined-method-doctrine-dbal-connectioncreateschemamanager

**Comment by ImAkPatil** [comment]
1. Update doctrine/dbal version as follows,
`"doctrine/dbal": "^3.5",`
2. Do `composer update`
