### ISSUE TITLE
Typed property InfyOm\Generator\Common\GeneratorConfig::$paths must not be accessed before initialization

### ISSUE THREAD

**Issue by Foxx1990** [InfyOmLabs/laravel-generator#1099]
When I try to use the GUI Generator I get an error. I also cannot use the php artisan make:model command from the command line because I get the same error. What am I doing wrong?

**Comment by mitulgolakiya** [comment]
@Foxx1990 , we are no longer maintaining GUI Generator. I recommend using the console version only.
