### ISSUE TITLE
route:list & swagger

### ISSUE THREAD

**Issue by garenk02** [InfyOmLabs/laravel-generator#120]
Hi, I have 2 questions:

1. Why my API generated not show/working when I do '**php artisan route:list**'
**[ReflectionException]
Class App\Http\Controllers\PlacesAPIController does not exist**

2. How to automatically generate the swagger api docs?

**Comment by mitulgolakiya** [comment]
@garenk02 I think you have generated files then run rollback command. There was one minor bug which was not deleting routes. And also `composer dump-autoload` was not run.

I fixed that. Get the latest code and check again.

For swagger docs, [here](http://labs.infyom.com/laravelgenerator/docs/options/generator-options#swagger) is the doc for that.

**Comment by garenk02** [comment]
Hi, thanks for the fast respond
Actually, I'm very exciting with this package.
One thing that i still confuse is about the swagger, how this package generate the swagger documentation?
I'm using this package for generate/create API, when i'm done generate one API using 'php artisan infyom:api MyExampleController', is it automatically generate the swagger documentation?
If yes, how do (where) I check the documentation result?

**Comment by garenk02** [comment]
Hi @mitulgolakiya 
Can u help me to explain how the swagger generate di REST API documentation?
Because it's not working in my local development (after generate the api)

Many thank's

**Comment by mitulgolakiya** [comment]
@garenk02 can you post your model details of saved JSON Schema files ? And all generated files ?

**Comment by garenk02** [comment]
Hi @mitulgolakiya 

Now when i access:

- http://localhost:8000/docs/
- http://localhost:8000/api/docs

it's already working, but why it always re-generate to default state (empty paths & definitions)

Really need help.

Many thank's

**Comment by mitulgolakiya** [comment]
@garenk02 what do you mean by "default state (empty paths & definitions)" ?
