### ISSUE TITLE
Question :: Create an API

### ISSUE THREAD

**Issue by 3runoDesign** [InfyOmLabs/laravel-generator#122]
Maybe it's a simple question, but how to create an API Request using infyOm?
I saw that has a routes_api.php file but how to use?

😄

**Comment by garenk02** [comment]
@3runoDesign have u already try to run '**php artisan infyom:api Example**' from your terminal/command prompt?
As far as I know that is the way to generate an API. u can see the docs here: **http://labs.infyom.com/laravelgenerator/docs/getting-started/generator**
