### ISSUE TITLE
/get/{id} return error code 500

### ISSUE THREAD

**Issue by garenk02** [InfyOmLabs/laravel-generator#123]
@mitulgolakiya, when I try to fetch (get one data) if the data is not exist in database, why the result return error code 500 with empy/blank respond.

Many thanks

**Comment by mitulgolakiya** [comment]
with apis or scaffold ?

**Comment by garenk02** [comment]
@mitulgolakiya, with api only

I already fix this with change the ->find(id) in my controller to ->findWithoutFail(id) that extends from
abstract class BaseRepository extends \Prettus\Repository\Eloquent\BaseRepository

But now when I try to POST,PUT,PATCH it return error 500 again :(

Seriously need helps

**Comment by garenk02** [comment]
I know the problem was because I add an addtional respond in Handler
