### ISSUE TITLE
New Adjustment / Feature Request

### ISSUE THREAD

**Issue by phillipmadsen** [InfyOmLabs/laravel-generator#124]
In Working with the new builder when I  run something like 
```
php artisan infyom.publish:layout 
```
I  found there is no way to name it or use it in a particular prefix or with a certain layout. 
Here is an example of what i am doing and needing it to generate. 

Run
```
php artisan infyom:scaffold Product --fromTable --tableName=products --prefix=admin --save --skipDumpOptimized
```
And 
```
php artisan infyom:scaffold Product --fieldsFile='resources/model_schemas/Product.json' --prefix=lte --save --skipDumpOptimized
```
Now the problem is when I  run 
```
php artisan infyom.publish:layout 
```
I  cannot tell it what to use or where to use it.
***PROPOSE WE ADD A THEME OR LAYOUT COMMAND***
We could use something like this.  

```
php artisan infyom.publish:layout admin=core-templates 

php artisan infyom.publish:layout lte=adminlte-templates 
```

***This would then create the prefix directory and load the layouts to be used into it.***

```
php artisan infyom:scaffold Product --fromTable --tableName=products --prefix=admin {{--theme=admin }}  --save --skipDumpOptimized

php artisan infyom:scaffold Product --fieldsFile='resources/model_schemas/Product.json' --prefix=lte  {{--theme=lte }}  --skipDumpOptimized

```

**Comment by phillipmadsen** [comment]
```
|- views
    |- {{THEME / LAYOUT NAME }}
      |- layouts
          |- app.blade.php
          |- menu.blade.php
          |- sidebar.blade.php
      |- emails
          |- password.blade.php
      |- auth
          |- login.blade.php
          |- register.blade.php
          |- reset.blade.php
          |- password.blade.php
```

**Comment by mitulgolakiya** [comment]
@phillipmadsen I got the idea what you are trying to do. It's a valid point. But in general, stuff, why someone will use two themes in just same project. People wants consistent layout and theme in all of the pages of the project.

But anyway, I am adding it to the backlog and can do it once we have some specific requirements.

**Comment by mitulgolakiya** [comment]
We have lots of issues for prefix and lots of separate discussions for it. I think we should have one central discussion for this. so closing it in reference of https://github.com/InfyOmLabs/laravel-generator/issues/155.
