### ISSUE TITLE
Confirm before adding API group to routes.php for publish command

### ISSUE THREAD

**Issue by righter** [InfyOmLabs/laravel-generator#126]
If the infyom:publish command is run multiple times, the API route group is added to routes.php even if it was previously added. A simple fix would be to ask the user if they want to add the route group before modifying the file.

**Comment by righter** [comment]
@mitulgolakiya -- I have a branch that fixes this issue if you're interested. I did do a bit of refactoring on user confirmation though. It's now a single method contained within BaseCommand. PublishBaseCommand now extends BaseCommand so it and its children can make use of the BaseCommand method.

If it's more changes than you're comfortable pulling in, no problem. Let me know and I'll issue a pull request.

Here's a link to the diff:

righter@d187116

**Comment by mitulgolakiya** [comment]
@righter Thanks. I will check it
