### ISSUE TITLE
Not Able to install this - Urgent Help

### ISSUE THREAD

**Issue by sandip12** [InfyOmLabs/laravel-generator#127]
Getting this error .

composer require infyomlabs/laravel-generator

  [InvalidArgumentException]
  Could not find package infyomlabs/laravel-generator at any version for your
   minimum-stability (stable). Check the package spelling or your minimum-sta
  bility

require [--dev] [--prefer-source] [--prefer-dist] [--no-plugins] [--no-progress]
 [--no-update] [--update-no-dev] [--update-with-dependencies] [--ignore-platform
-reqs] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative
] [--] [<packages>]...

My composer.json is like 
`{
    "name": "laravel/laravel",
    "description": "The Laravel Framework.",
	"infyomlabs/laravel-generator": "dev-master",
"laravelcollective/html": "5.2.*",
"infyomlabs/core-templates": "dev-master",
"infyomlabs/swagger-generator": "dev-master",
"jlapp/swaggervel": "dev-master",
"doctrine/dbal": "~2.3" ,
"illuminate/html": "~5.0",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "type": "project",
    "require": {
        "php": ">=5.5.9",
        "laravel/framework": "5.2.*",
        "prettus/l5-repository": "^2.5",
        "illuminate/support": "^5.2",
        "laracasts/flash": "^2.0"
    },
    "require-dev": {
        "fzaninotto/faker": "~1.4",
        "mockery/mockery": "0.9.*",
        "phpunit/phpunit": "~4.0",
        "symfony/css-selector": "2.8.*|3.0.*",
        "symfony/dom-crawler": "2.8.*|3.0.*"
    },
    "autoload": {
        "classmap": [
            "database"
        ],
        "psr-4": {
            "App\\": "app/"
        }
    },
    "autoload-dev": {
        "classmap": [
            "tests/TestCase.php"
        ]
    },
    "scripts": {
        "post-root-package-install": [
            "php -r \"copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "php artisan key:generate"
        ],
        "post-install-cmd": [
            "Illuminate\\Foundation\\ComposerScripts::postInstall",
            "php artisan optimize"
        ],
        "post-update-cmd": [
            "Illuminate\\Foundation\\ComposerScripts::postUpdate",
            "php artisan optimize"
        ]
    },
    "config": {
        "preferred-install": "dist"
    }
}
`

**Comment by mitulgolakiya** [comment]
@sandip12 I think you are new to laravel.

so to use packages in laravel, you must add it in `"require"` section. Not directly in `composer.json`. You composer.json should look like this,

```
{
	"name": "laravel/laravel",
	"description": "The Laravel Framework.",
	"keywords": ["framework", "laravel"],
	"license": "MIT",
	"type": "project",
	"require": {
		"php": ">=5.5.9",
		"laravel/framework": "5.2.*",
		"prettus/l5-repository": "^2.5",
		"illuminate/support": "^5.2",
		"laracasts/flash": "^2.0",
		"infyomlabs/laravel-generator": "dev-master",
		"laravelcollective/html": "5.2.*",
		"infyomlabs/core-templates": "dev-master",
		"infyomlabs/swagger-generator": "dev-master",
		"jlapp/swaggervel": "dev-master",
		"doctrine/dbal": "~2.3",
		"illuminate/html": "~5.0"
	},
	"require-dev": {
		"fzaninotto/faker": "~1.4",
		"mockery/mockery": "0.9.*",
		"phpunit/phpunit": "~4.0",
		"symfony/css-selector": "2.8.*|3.0.*",
		"symfony/dom-crawler": "2.8.*|3.0.*"
	},
	"autoload": {
		"classmap": ["database"],
		"psr-4": {
			"App\\": "app/"
		}
	},
	"autoload-dev": {
		"classmap": ["tests/TestCase.php"]
	},
	"scripts": {
		"post-root-package-install": ["php -r \"copy('.env.example', '.env');\""],
		"post-create-project-cmd": ["php artisan key:generate"],
		"post-install-cmd": ["Illuminate\\Foundation\\ComposerScripts::postInstall", "php artisan optimize"],
		"post-update-cmd": ["Illuminate\\Foundation\\ComposerScripts::postUpdate", "php artisan optimize"]
	},
	"config": {
		"preferred-install": "dist"
	}
}
```

Try this and it should fix your problem.
