### ISSUE TITLE
infyom.publish:layout don't use customized layout

### ISSUE THREAD

**Issue by eescalante** [InfyOmLabs/laravel-generator#129]
Hi,
when i try to set my layout by 'php artisan infyom.publish:layout'

It ignores my customized files at 'resources/infyom/infyom-generator-templates' and keeps using the original templates.

It that an issue or is this an expected behivior?

**Comment by mitulgolakiya** [comment]
@eescalante Can you get the latest code  and check again ?
Or just post the detailed steps what you have done and also the files that are generated.

**Comment by mitulgolakiya** [comment]
Working in the latest version.
