### ISSUE TITLE
API errors not working

### ISSUE THREAD

**Issue by malhal** [InfyOmLabs/laravel-generator#130]
To recreate this simply open the api route to an item and pass an invalid id, e.g. a row that doesn't exist.

In the show function in the generated API Controller, in the case of the record not found the JSON response is not returned. Instead the default "sorry" web page is shown. This is because the find method of the repository does a findOrFail fails and throws an exception. This exception is then rendered to a web page in the Exceptions/Handler.php render method.

Although this could be fixed by changing the find on the repository to findWithoutFail I believe a better design for API error handling is to render any exception like a find failing to JSON in the Handler class if the route is an API one. This way all errors caused by exceptions can be rendered to JSON rather than by manually creating error responses in controllers which obviously is very error prone as in the example above. Search for the render method in this page for what I mean:
https://laracasts.com/discuss/channels/code-review/best-way-to-handle-rest-api-errors-throwed-from-controller-or-exception

**Comment by malhal** [comment]
I have a solution to the problem by creating Exceptions/APIHandler and updating the singleton in the api_routes.php. This enables rendering of exceptions to JSON for only API routes without any modifications to the existing Handler class. Happy to do a pull request.

**Comment by mitulgolakiya** [comment]
thanks @malhal. I will take it in a queue to support a custom exception handler.

**Comment by malhal** [comment]
Also I think findWithoutFail is unnecessary. If find does fail then the built in exception handling happens which is what most people would want. The exception might not always be not found and null returned which is what the controllers are assuming. Best just less it fail, exception, thrown, handler generate output.

**Comment by ajayinfyom** [comment]
Issue fixed in the latest version and removed Presttus repository pattern.
