### ISSUE TITLE
Can we have a flag for not adding entries to routes.php and api_routes.php

### ISSUE THREAD

**Issue by vesper8** [InfyOmLabs/laravel-generator#133]
I have to regenerate often as I modify the schema and everytime I have to undo the additions to the two routes files because the routes are already there and it just keeps appending more and more

**Comment by mitulgolakiya** [comment]
@vesper8 great idea. Even we can give a support to skip one or more generate things. I will add a support for it.

**Comment by mitulgolakiya** [comment]
@vesper8 I have added a support for skipping various files like migration, routes, controller, models etc.

If you want to skip routes generation then you can run a command something like,

`php artisan infyom:api_scaffold Post --fieldsFile=resources/model_schemas/Post.json --skip=routes`

Even I added support to skip multiple items like,

`php artisan infyom:api_scaffold Post --fieldsFile=resources/model_schemas/Post.json --skip=routes,migration,model`

I will add a detailed documentation later. But as of now, you can find a full list [here](https://github.com/InfyOmLabs/laravel-generator/blob/f81aea1e398016bd16f3e2098cd0398cac602e5e/src/Commands/BaseCommand.php#L223)
