### ISSUE TITLE
laravel-generator config file not change

### ISSUE THREAD

**Issue by yepco** [InfyOmLabs/laravel-generator#135]
I change laravel-generator.php file but when I run 
`php artisan infyom:api Post`
Create file with default value.
I change model address and namespace but not change

**Comment by mitulgolakiya** [comment]
@yepco Can you post your laravel-generator.php and generated files here. I have tried to change model location and namespace and it worked fine.

**Comment by yepco** [comment]
Thanks
I solved it.
I have another question
I have json file and How I import it in php artisan command?

**Comment by yepco** [comment]
I Use this command
`php artisan infyom:scaffold $MODEL_NAME$ --fieldsFile=absolute_file_path_or_path_from_base_directory`
