### ISSUE TITLE
PHP Fatal error // After setup if prefix is used its looking for AppBaseController in all the prefix dir's

### ISSUE THREAD

**Issue by phillipmadsen** [InfyOmLabs/laravel-generator#137]
PHP Fatal error: Class 'App\Http\Controllers\Admin\AppBaseController' not found in /home/vagrant/home/app/Http/Controllers/Admin/ArticleController.php on line 14

***Got this after running:***

php artisan infyom:api_scaffold Product --fieldsFile='resources/model_schemas/Product.json' --prefix=admin

**Comment by phillipmadsen** [comment]
temporary fix I  put 
```
use App\Http\Controllers\AppBaseController;
```
This uses the AppBaseController in the non prefixed directory. I  have not tested if this will work or cause issues I am just giving you a heads up.

**Comment by phillipmadsen** [comment]
The temp fix did not work. This is also looking for AppBaseController in the api directories

**Comment by mitulgolakiya** [comment]
@phillipmadsen I am already on it and will push a fix by this weekend.

**Comment by mitulgolakiya** [comment]
@phillipmadsen this is fixed in develop branch. Please check and confirm it.

**Comment by phillipmadsen** [comment]
my develop branch is still looking for it and others. 

https://github.com/InfyOmLabs/laravel-generator/issues/179
