### ISSUE TITLE
Class 'InfyOm\CoreTemplates\CoreTemplatesServiceProvider' not found

### ISSUE THREAD

**Issue by syehbiherbian** [InfyOmLabs/laravel-generator#138]
this is my file `composer.json`

"infyomlabs/laravel-generator": "dev-master",
        "infyomlabs/adminlte-templates": "dev-master",
        "laravelcollective/html": "5.2.*",
        "infyomlabs/swagger-generator": "dev-master",
        "jlapp/swaggervel": "dev-master"

but. when i will `php artisan vendor:publish` can't run
this is my problem `Class 'InfyOm\CoreTemplates\CoreTemplatesServiceProvider' not found`

**Comment by mitulgolakiya** [comment]
I think you need to remove that class from `app.php` and include `\InfyOm\AdminLTETemplates\AdminLTETemplatesServiceProvider::class`.

Check docs it [here](http://labs.infyom.com/laravelgenerator/docs/templates/adminlte).

It needs some document update. I will update it.

**Comment by syehbiherbian** [comment]
thank you bro, success
