### ISSUE TITLE
PostGIS geometry type support

### ISSUE THREAD

**Issue by lubieplacki500** [InfyOmLabs/laravel-generator#140]
Hello.
I just started new project based on Laravel and PostGIS and I found your packege and I think is great, but when I generate model from table I get this error

```
[Doctrine\DBAL\DBALException]
Unknown database type geometry requested, Doctrine\DBAL\Platforms\PostgreSqlPlatform may not support it.
```

so I find [creof/doctrine2-spatial](https://github.com/creof/doctrine2-spatial) package which contain geometry and geography types but i don know how to use it with your generator

**Comment by philtweir** [comment]
Hello, I've managed to get this working in a fairly extensible way. However, you will also need laravel-doctrine/orm, creof/doctrine2-spatial and opensoft/doctrine-postgres-types . It requires a fairly small change to laravel-generator, which is on a fork [flaxandteal/laravel-generator@feat/laravel-doctrine-schema-manager](/flaxandteal/laravel-generator/tree/feat/laravel-doctrine-schema-manager).

While I'm still using Eloquent, installing Laravel Doctrine allowed me to use config/doctrine.php to specify additional type mappings, etc. that can then be used with laravel-generator (with the patch above). From the default config/doctrine.php, this patch [config-doctrine-add-postgis.diff.txt](https://github.com/InfyOmLabs/laravel-generator/files/684706/config-doctrine-add-postgis.diff.txt) adds the standard GIS and other required types/functions.

If it's in the general direction of laravel-generator development, I'd be happy to submit a PR for the patch above, as it's not specific to GIS/postgres, but essentially out-sources Doctrine settings to Laravel Doctrine's entity manager, if it finds it is already installed.

Without adding specific changes to laravel-generator (that assume other libraries, like doctrine2-spatial are available), any non-standard columns will get interpreted as string type when analysed by laravel-generator's TableFieldsGenerator - you will likely want to set them to your desired type after generation. However, at least it stops the whole generator from stopping for the sake of one or two columns of one or two tables in the DB.

**Comment by woodstock20** [comment]
hello, i have de same problem but y remplace laravel-generator with that is in  flaxandteal/laravel-generator@feat/laravel-doctrine-schema-manager also install via composer laravel-doctrine/orm, creof/doctrine2-spatial and opensoft/doctrine-postgres-types but i cannot understand the second part with  config-doctrine-add-posgis.diff if you can explain a little more explicit to make it works, iam newer with it and sorry my bad english.

**Comment by philtweir** [comment]
Hi there - sorry, that could have been a clearer explanation! It's a while back, but have tweaked the patch a little - if you have the default `config/doctrine.php` below your Laravel root, then running `patch -p1 < config-doctrine-add-postgis.diff.txt` should add the necessary lines into your Doctrine config.

[config-doctrine-add-postgis.diff.txt](https://github.com/InfyOmLabs/laravel-generator/files/1104687/config-doctrine-add-postgis.diff.txt)

**Comment by mitulgolakiya** [comment]
Ref: https://github.com/InfyOmLabs/laravel-generator/issues/593#issuecomment-471154604
