### ISSUE TITLE
Database nothing return,

### ISSUE THREAD

**Issue by adilsaeed31** [InfyOmLabs/laravel-generator#141]
Hi,

I generate api_scaffold with model name Product and the table name is products, but some reason, i don't know, no result are coming through model query, that is strange behaviours, i have checked that the query perform fine but records not return also in api or in admin LTE side.

Thanks
adil

**Comment by mitulgolakiya** [comment]
@adilsaeed31 can you post your generated files and database table with some sample data. so I can check.

**Comment by adilsaeed31** [comment]
Hi

First you reply me after too much days.

and I created API_SCAFFOLD with name Products and Product both are not
returning anything but the strange thing is that we can create the show and
edit but listing is not available on both side, not in api request call and
not in datatables->table function, db table name is same for both products.

Thanks
Adil

**Comment by mitulgolakiya** [comment]
I need to check your generated files. Please upload your generated files with your database table. Then I can identify the problem.

**Comment by adilsaeed31** [comment]
@mitulgolakiya Can't provide you the project files it's confidential please let me know what else i can sent you you.

Thanks
Adil.

**Comment by mitulgolakiya** [comment]
@adilsaeed31 you don't need to provide full project files. Just the generated files for one table which has an error. Or any other sample table which produces error. Otherwise we can not identify what's exactly missing.
