### ISSUE TITLE
Run  Artisan::call("vendor:publish") before run php artisan migrate

### ISSUE THREAD

**Issue by paranoid-m** [InfyOmLabs/laravel-generator#142]
Hi,
I create laravel package module  with your script.
I want run `Artisan::call("vendor:publish")` before execute migration.
What should I do?

**Comment by mitulgolakiya** [comment]
@yepco [Here](https://github.com/InfyOmLabs/laravel-generator/blob/master/src/Commands/BaseCommand.php#L50) we are running migration command. so you can fork the repo and add your own code here to run publish command.
