### ISSUE TITLE
Datatables Not Working

### ISSUE THREAD

**Issue by mikahoy045** [InfyOmLabs/laravel-generator#143]
Please help. I followed quick installation in https://github.com/yajra/laravel-datatables but whenever I did create new scafold, it's not shown datatables in views, instead shown bootstrap menu. ( I already enabled 'add_on.datatables' => true in laravel-generator.

**Comment by mitulgolakiya** [comment]
@mikahoy045 Have you complete all the steps of installing https://github.com/yajra/laravel-datatables ?

1. composer required package
2. adding service provider
3. Datatables facade
4. php artisan vendor:publish --tag=datatables

If any of this step is pending then it will not work.

Or just post your generated files here. so we can check.

**Comment by mikahoy045** [comment]
1. Composer Required package - Done
2. Adding Service Provider - Done
3. Datatables Facade - Automatically generate based on the site.

But somehow I found it working for infyom:api_scaffold, but not for infyom:scaffold

**Comment by mitulgolakiya** [comment]
@mikahoy045 I will check it. But any specific problem ? Like what's not working ?

**Comment by mikahoy045** [comment]
it shows default view, not shown in datatables view.

**Comment by Passionatedreamer** [comment]
The problem is still persisting. Datatables just show anything on index method. Just gives headings of my model, but not any data.
The table also looks like the normal table of models that I generated before I enabled datatables

**Comment by NightZpy** [comment]
@Passionatedreamer network datatable request works? (look in developer tools in chrome or firefox, tab network)

**Comment by Passionatedreamer** [comment]
@NightZpy Problem solved. The problem was that I was using the latest version of JQuery, Now I'm using the version that Yajra's website has highlighted and it started working. Thankyou your indication showed me the right direction to investigate.

**Comment by mitulgolakiya** [comment]
@Passionatedreamer Great.

**Comment by jackleblack** [comment]
Same problem.

I try with changing jQuery version to 1.10.2 but it remain the same.
