### ISSUE TITLE
Scaffold/Api_Scaffold from table not shown content

### ISSUE THREAD

**Issue by mikahoy045** [InfyOmLabs/laravel-generator#147]
I try to do Api_scaffold from existing table (that existing table already have content filled), but somehow in datatables view are showed but it showed without content in otherwords empty datatables.. is it normal or something I miss?

**Comment by mitulgolakiya** [comment]
@mikahoy045 If you have completed all installation steps, then I think it should work.
Still if you are not able to get it work. Please share your generated files and table design. I can check.
