### ISSUE TITLE
Suggestion - custom blade templates

### ISSUE THREAD

**Issue by adrianogl** [InfyOmLabs/laravel-generator#15]
In [Laravel API/Scaffold/CRUD Generator](https://github.com/mitulgolakiya/laravel-api-generator) it was possible

**Comment by iboinas** [comment]
And now also possible!

**Comment by iboinas** [comment]
`
php artisan infyom:scaffold $MODEL_NAME$
`

**Comment by iboinas** [comment]
php artisan vendor:publish

you go to vendor/infyomlabs/core-templates/templates and check it

you can even copy fields folder to app/resources/infyom/infyom-generator-templates(if you didn't change it on config) , and the command will use this, when finds it. if not, uses the ones from vendor

**Comment by iboinas** [comment]
Pardon me,

php artisan infyom.publish:templates

**Comment by NightZpy** [comment]
I have published core-template files into app/resources/infyom/infyom-generator-templates and doens't works. 

Whats the steps in order?

**Comment by NightZpy** [comment]
Ok, am solve this, the folder is app/resources/infyom/infyom-generator-templates/scaffold

**Comment by mitulgolakiya** [comment]
Its already there on doc: http://labs.infyom.com/laravelgenerator/docs/advanced/publish-templates

**Comment by NightZpy** [comment]
Ok, but doesn't works with views fields auth templates folder, These must be published manually (i.e., copy/paste)!

**Comment by gustavorojas** [comment]
Hello I want to generate but without template, only the code because I used acacha admin lte template 
in composer "acacha/admin-lte-template-laravel": "1.*",
and when I generate I have many erros and the view don't work

**Comment by NightZpy** [comment]
@gustavorojas you can publish the templates used by laravel-generator with 
`php artisan infyom.publish:layout` command, and then edit with acacha :D
