### ISSUE TITLE
Need a update command

### ISSUE THREAD

**Issue by phillipmadsen** [InfyOmLabs/laravel-generator#156]
something like infyom:update

this should check all files, config, and verify links are working. 

just an idea.

I  just installed a fresh version of the package and the routes are not working. /home  is getting an error that it doesn't exist.

**Comment by phillipmadsen** [comment]
Figured it out. My bad I  forgot to run migrate. 
You should add this to the setup installation steps. I  forgot to do it and was following the installation instructions from the site. just an idea

**Comment by mitulgolakiya** [comment]
@phillipmadsen what do you mean by default tables ?

**Comment by phillipmadsen** [comment]
database tables. my bad.

**Comment by phillipmadsen** [comment]
The migration tables in the database need to be migrated. I  just forgot to do this step and thought others might also forget and wonder why its not working.

**Comment by mitulgolakiya** [comment]
@phillipmadsen I think we are now already asking to run migration at last.

Closing issue.
