### ISSUE TITLE
new toggle-switch field image

### ISSUE THREAD

**Issue by phillipmadsen** [InfyOmLabs/laravel-generator#157]
shows how the toggle-switch looks 
![Image of toggle-switch](https://raw.githubusercontent.com/phillipmadsen/stuff/master/img/toggle-switch.png)

**Comment by Fionajeremychik** [comment]
I can't add toggle switch

**Comment by mitulgolakiya** [comment]
Post some description of what exactly you are trying.

**Comment by Fionajeremychik** [comment]
In your online doc, should be toggle-switch but not toggle switch. Now, I can add toggle switch
How can I change the name of ON/OFF to be Approve/Reject?

**Comment by mitulgolakiya** [comment]
It's already `toggle-switch` in the examples column. Maybe you are looking into a valid format column. Check it here: https://labs.infyom.com/laravelgenerator/docs/7.0/fields-input-guide

Also to customize toggle switch, you can publish the templates and do whatever changes you want. https://labs.infyom.com/laravelgenerator/docs/7.0/publish-templates

Just keep toggle-switch if you want to customize one template only.

**Comment by Fionajeremychik** [comment]
How to customize one template. Any information
