### ISSUE TITLE
Route Errors

### ISSUE THREAD

**Issue by phillipmadsen** [InfyOmLabs/laravel-generator#159]
Route [Admin/menus.index] not defined. Route [Admin/menus.index] not defined.

**Comment by phillipmadsen** [comment]
Found the problem in  
```
@include('$ROUTES_AS_PREFIX$$MODEL_NAME_PLURAL_CAMEL$.fields')
```

$ROUTES_AS_PREFIX$ outputs / instead of .

looks like you have $ROUTES_PREFIX$ that outputs the . instead of / which is probably what you meant to use.

**Comment by mitulgolakiya** [comment]
In new version, we have removed `$ROUTES_AS_PREFIX$` dynamic param, instead of we have added `$VIEW_PREFIX$`.
https://github.com/InfyOmLabs/laravel-generator/blob/develop/src/Common/GeneratorConfig.php#L196

**Comment by ayndev** [comment]
Please I'm not able to update to the latest version in order to use VIEW PREFIX. Are you going to add a new tag soon or update the package?

**Comment by mitulgolakiya** [comment]
@ayndev its not merged
