### ISSUE TITLE
Show field radio bug

### ISSUE THREAD

**Issue by iboinas** [InfyOmLabs/laravel-generator#16]
You can check with the json fields example,

Generated index and show, is misbehaving when we check 2 checkboxes.

I suggest this is solved with saving as JSON encoded in text.

But i guess, for the quick scaffolding only will not be a problem.

Even so, who wants to use it right out of the box, will be with this error

**Comment by mitulgolakiya** [comment]
checkbox format in sample fields json was wrong. New format added.
Check it [here](https://github.com/InfyOmLabs/laravel-generator/blob/35fb80d70dcf3467a544477e5de7dad1a93ae196/samples/fields_sample.json#L52)
