### ISSUE TITLE
Add new Fields

### ISSUE THREAD

**Issue by willmkt** [InfyOmLabs/laravel-generator#163]
I think that we could add new fields, including relationship, image and repeater field.

This package was greate, but it has not been supported in some time.

https://github.com/krafthaus/bauhaus

They had a user package with roles and permitions, it was a great generator, but the creator sttoped the supporting it.

https://github.com/krafthaus/bauhaususer

I think we could get some ideas from these packages.

Thanks

**Comment by ShaileshInfyom** [comment]
@willmkt you can integrate role and permissions watching this tutorial with easy way with generator https://youtu.be/hlGu2pa1bdU

And,
you can generate User management with just one command,
watch these tutorials

Way 1:
https://www.youtube.com/watch?v=V7PCL6HCdXo&list=PL0wCC44AhrC3JHzcB5qmjYkm70OaoKegg&index=20

Way 2; 
https://www.youtube.com/watch?v=J38ut_S9Fk4&list=PL0wCC44AhrC3JHzcB5qmjYkm70OaoKegg&index=15

also, relationship, image  now supported

**Comment by ShaileshInfyom** [comment]
Feel free to re-open the issue with more details if you are still any suggestions.
