### ISSUE TITLE
still getting this error

### ISSUE THREAD

**Issue by phillipmadsen** [InfyOmLabs/laravel-generator#166]
updated today but still getting this:

Class 'App\Http\Controllers\Admin\AppBaseController' not found

**Comment by phillipmadsen** [comment]
again today I updated and tried. 
FatalErrorException in ProductController.php line 14:
Class 'App\Http\Controllers\Backend\AppBaseController' not found

**Comment by mitulgolakiya** [comment]
@phillipmadsen I will check it.

**Comment by mitulgolakiya** [comment]
@phillipmadsen Can you check it again with the latest code by removing your existing AppBaseController and publish AppBaseController again ?

**Comment by mitulgolakiya** [comment]
@phillipmadsen now its done. Check it again.

**Comment by mitulgolakiya** [comment]
related to https://github.com/InfyOmLabs/laravel-generator/issues/179. so closing it. Place any of your comment on that issue.
