### ISSUE TITLE
Multi-Database ?

### ISSUE THREAD

**Issue by ahpetrot** [InfyOmLabs/laravel-generator#168]
Need to support more than one connection to a database .

Scaffold command should add  --connection= as a infyom:scaffold cli option

example:

php artisan infyom:scaffold <MODEL> --connection=mysql2 --primary=<ID> --fromTable --tableName=<TALBE>

Current behavior just generates empty models, validation and form fields. 

Current workaround:  
1. switch over active database connection to secondary database
2. run the scaffold command against the target table 
3. switch back
4. make sure you have secondary db connection in 
   a. your .env
   b. your config/database.conf file that take constants from your .env 
5. update your models/<model>.php with 
   public $connection = 'mysql2'  ;   or what ever your define as the secondary connecting in your database.config  ( step 4b).

Thanks

**Comment by vesper8** [comment]
I too would love to be able to specify the database in the artisan command since my project deals with 9 different databases

**Comment by vesper8** [comment]
Please add this --connection switch when using the infyom artisan command.. would be so helpful.. my project has over 12 databases and am constantly having to comment/uncomment things in the .env file.. very tedious

**Comment by vesper8** [comment]
All that's needed to make it work is to modify this line in the TableFieldsGenerator.php

from
```
$this->schemaManager = DB::getDoctrineSchemaManager();
```
to
```
$this->schemaManager = DB::connection($connectionName)->getDoctrineSchemaManager();
```

Of course that will mean you have to capture the connection name as an option and fall back to a default if none is provided.. but that shouldn't be too hard.

**Comment by vesper8** [comment]
And then of course when generating the model don't forget to also add 

```
    public $connection = 'connectionName';
    public $table = 'tableName';
```
