### ISSUE TITLE
ModelName missing in $FIELDS$

### ISSUE THREAD

**Issue by kay899** [InfyOmLabs/laravel-generator#169]
HI,

first of all I want to say a big Thank You for this wonderful package. I am actually testing it since two days and it really works great.

As I am doing a German Webpage, I need to have some translation for my field names.
I solved translations e.g. in the index or show page like this:

`{!! Form::label('$FIELD_NAME$', trans('models.$MODEL_NAME$.$FIELD_NAME$')) !!}`

This is working perfectly and I refactor my langfiles, so that I have an array of translations for each model.

Now I want to do the same for the fields in create view, but here the model name is missing as a parameter. Would it be possible to add these also to that function, so that we could use these:

$MODEL_NAME$
$MODEL_NAME_CAMEL$

Would be wonderful.

Thanks in advance
kay899

**Comment by kay899** [comment]
I changed this locally for the moment with adding this line in 

InfyOm\Generator\Generators\Scaffold\ViewGenerator

`            if (!empty($fieldTemplate)) {
                $fieldTemplate = str_replace('$MODEL_NAME$', $this->commandData->config->mName, $fieldTemplate);
                $fieldTemplate = TemplateUtil::fillFieldTemplate(
                    $this->commandData->fieldNamesMapping,
                    $fieldTemplate,
                    $field
                );
                $this->htmlFields[] = $fieldTemplate;
            }`

Perhaps you want to exctend it like this?

Regards
kay899

**Comment by mitulgolakiya** [comment]
@kay899 Actually we were not passing those fields in fields template. I have pushed a fix in develop branch. Will push it to the master in next release.
