### ISSUE TITLE
Rollback function not rolling back all changes

### ISSUE THREAD

**Issue by kay899** [InfyOmLabs/laravel-generator#170]
I played around with your Rollback function and noticed that it not rolls back all changes.
- DataTables file is not deleted
- Changes in menu.blade.php are not rolled back, even stated by the script in the shells output
- Model Schema JSON files is not deleted (Perhaps this should be confugurable, if that will be deleted also?)
- DB Migration in not rolled back as well (Perhaps a good idea to add this also in Rollback process, perhaps also configurable?

Perhaps you can review these as ideas?

Regards
kay899

**Comment by kay899** [comment]
I noticed in the new version only DB migration is rolled back, but no files any more?

**Comment by mitulgolakiya** [comment]
@kay899 ok, will check it.
