### ISSUE TITLE
CLI to turn on/off DatatTables

### ISSUE THREAD

**Issue by ahpetrot** [InfyOmLabs/laravel-generator#172]
Simple CLI switch to turn on off DataTables integration would be nice.  Right now the only way to not use DataTables , once configured, is to modify the config file.

~Tim

**Comment by mitulgolakiya** [comment]
@ahpetrot great idea. I will implement it and push it in next release.

**Comment by mitulgolakiya** [comment]
@ahpetrot `datatables` cli option is implemented. You can use it as `--datatables=true` OR `--datatables=false` to turn it on/off.
