### ISSUE TITLE
[Error] php artisan route:list

### ISSUE THREAD

**Issue by gsc89** [InfyOmLabs/laravel-generator#174]
I get this error when using the command in the title.

Cannot use InfyOm\Generator\Controller\AppBaseController as AppBaseController because the name is already in use

Any ideas? 

My app still works I just need to look at the list of routes I have. 

Sorry if this is a stupid question I did a google and it was mentioned before but it was supposed to be fixed after that issue was posted.

**Comment by mitulgolakiya** [comment]
@gsc89 its already in progress. Track it here https://github.com/InfyOmLabs/laravel-generator/issues/166
I think the reason of these both issues is same.

**Comment by gsc89** [comment]
Ah ok dorry thanks man! keep up the amazing work its truly great.

**Comment by mitulgolakiya** [comment]
@gsc89 Can you setup it again with a fresh new installation by removing all published stuff and check it again ?

**Comment by gsc89** [comment]
Hi thanks for your time but I can't re-generate any of the files I am currently working on as I am 150+ hours into coding on this project and made far too many changes to the files which were generated.

I will have to manually fix each file based on the code changes I see you have made. Sorry I can't be more help I simply can't regenerate on this project its far too far a long now. 

I take it thats what you meant?

**Comment by wsl** [comment]
I had the same issue and with a scratch project with 
        "infyomlabs/laravel-generator": "dev-master#7270cb5ffc019bc622956c10417670d12641e95c",
in composer.json I now get

  [Symfony\Component\Debug\Exception\FatalErrorException]
  syntax error, unexpected '$NAMESPACE_BASE_CONTROLLER' (T_VARIABLE), expecting identifier (T_STRING) or \\ (T_NS_SEPARATOR) or '{'

when running  php artisan route:list

**Comment by gsc89** [comment]
All of my scaffolding was generated from table

**Comment by mitulgolakiya** [comment]
@wsl it's not fixed in develop branch.

@gsc89 Np. I checked it on my end and not its working fine.

**Comment by axyr** [comment]
This happened to me when using a prefixed route and already heaving a prefixed route group.

This will generate the error `Cannot use InfyOm\Generator\Controller\AppBaseController as AppBaseController because the name is already in use`


```php
Route::group(['prefix' => 'admin'], function () {
    Route::resource('companies', 'CompanyController');
});

Route::get('admin/users', ['as'=> 'admin.users.index', 'uses' => 'UserController@index']);
Route::post('admin/users', ['as'=> 'admin.users.store', 'uses' => 'UserController@store']);
Route::get('admin/users/create', ['as'=> 'admin.users.create', 'uses' => 'UserController@create']);
Route::patch('admin/users/{users}', ['as'=> 'admin.users.update', 'uses' => 'UserController@update']);
Route::delete('admin/users/{users}', ['as'=> 'admin.users.destroy', 'uses' => 'UserController@destroy']);
Route::get('admin/users/{users}', ['as'=> 'admin.users.show', 'uses' => 'UserController@show']);
Route::get('admin/users/{users}/edit', ['as'=> 'admin.users.edit', 'uses' => 'UserController@edit']);

```
