### ISSUE TITLE
Datatables Ajax (Adding Parameters) 

### ISSUE THREAD

**Issue by gsc89** [InfyOmLabs/laravel-generator#175]
OK so I have this table:

![image](https://cloud.githubusercontent.com/assets/1032459/15682464/b4bfb8d2-2755-11e6-9161-c1e773aba8e9.png)

Now there are many parts that join onto this table, the query() function under the generated datatable file looks like so:

```
  public function query()
    {
        $items = Item::query()
            ->with('stores')
            ->with('sexes')
            ->with('types')
            ->with('grades')
            ->with('sizes')
            ->with('materials')
            ->with('prices')
            ->with('types')
            ->with('suppliers');
        return $this->applyScopes($items);
    }

```

On the left there you will notice I have + symbols to expand the rows underneath with the mutliple row content per item. 

I managed to hook this in using JS to use:

```
window.LaravelDataTables.dataTableBuilder
```

As the target variable, I was wondering if its possible to add parameters to the search so that in the query() function of the DataTable.php file I can query based on which boxes are ticked, has anyone done this type of thing before? I couldn't find it anywhere relating to this package. 

Thanks for any help.

**Comment by NightZpy** [comment]
@gsc89 Hi my friend, what plugin was used for generate row children data?

**Comment by gsc89** [comment]
No plugin, I added a column for the expand button. 

Then I used some JS to expand and contract the row, using child object data which would be the one to many parts.

This is what the JS looked like: http://pastebin.com/5xvD0tdp

The code to add the expand column went into the datatable model looked like this: 

```
public function html()
    {
        return $this->builder()
            ->columns(array_merge(
                [
                    'expand' => [
                        'orderable' => false,
                        'searchable' => false,
                        'printable' => false,
                        'exportable' => false
                    ]
                ],
```

**Comment by NightZpy** [comment]
Thanks  @gsc89 , i understand :D

**Comment by gsc89** [comment]
I found I can access the ajax $_GET vars so adding in where statements should be entirely possible when I can find a way to add them into the ajax query made by the data table itself.

It was late in the day yesterday when I got stuck hopefully with some morning eyes and coffee I can figure this out, I will post any code up if I do. 

If anyone else can chip in that would be great.

**Comment by gsc89** [comment]
Might as well close this I have managed to accomplish this but I had to hard code my script replacing the generated call to ->scripts() 

I could do it with the library if I was able to use functions within ->ajax() 

You can use functions for callbacks within parameters to do callback JS functions but doing the same in ajax wraps it in inverted commas preventing you using that for this purpose. 

```
 ->parameters([
                'dom' => 'Bfrtip',
                'scrollX' => true,
                'buttons' => [
                    'csv',
                    'excel',
                    'pdf',
                    'print',
                    'reset',
                    'reload',
                ],
                'drawCallback' => 'function() { window.expandRows(); }',
            ]);
```

The code I ended up using was dead simple.

```
   "ajax": {
                url: '/items',
                dataType: 'json',
                cache:false,
                type: 'GET',
                data: function (d) {
                    console.log(anyFilters);
                    d.filters = anyFilters;
                }
            },
```

anyFilters is an object which has filters which are ticked added to that object and that is included with the url get string, I then loop these in the itemdatatable.php file to apply where conditions to my initial query.

**Comment by phillipmadsen** [comment]
Here is an example of the datatables version 
https://www.datatables.net/examples/server_side/row_details.html

**Comment by dhcmega** [comment]
Is it possible to replicate the Reload button to achieve this? It resends the info in the search field.
The pastebin is deleted btw.

I need to allow the user to filter by date range and click a checkbox column that should flag the record and reload the table. It's complicated because laravel-generator doesn't seem to follow this examples (https://datatables.yajrabox.com/eloquent/add-edit-remove-column in which I guess javascript is the $parameters of html method and elquentcontroller is a mix of query and ajax methods) on top of that there is the extra needed work for server side, which is yajra. So there are 3 packages working together.

Can anyone point me in the right direction to achieve this 2 things please? Extra filter fields and checkbox that updates the record and reloads the table?
Thanks!

**Comment by akshay13aac** [comment]
@gsc89 Hi How i can generate row children data?

**Comment by gsc89** [comment]
sorry @akshay13aac its been 4 years I can't remember haven't used larvel for a long long time now.

**Comment by akshay13aac** [comment]
Thanks @gsc89. @mitulgolakiya Can you help to generate row children data.
