### ISSUE TITLE
Cannot consume/call API from external app

### ISSUE THREAD

**Issue by garenk02** [InfyOmLabs/laravel-generator#177]
hi @mitulgolakiya 
I already finished created API using laravel-generator, but now when i try to consume it from other apps for example using guzzle or curl, why it always return '503 Service Unavailable'? 
I already try using vhost, host, localhost, 127.0.0.1 still not working.

When I call it from postman or browser it's work.

Really need help.

Many thank's

**Comment by mitulgolakiya** [comment]
@garenk02 Have you hosted it on server or you are getting this error on your local as well ?

**Comment by garenk02** [comment]
@mitulgolakiya 
I got this error on my local environment

**Comment by mitulgolakiya** [comment]
@garenk02 Were you able to resolve it with new version or still you are getting error ?

Try the latest version which got out recently.
