### ISSUE TITLE
Bug: on new specify views command

### ISSUE THREAD

**Issue by phillipmadsen** [InfyOmLabs/laravel-generator#194]
When using the new specify views command I  ran the following:

php artisan infyom:api_scaffold Product --fieldsFile='resources/model_schemas/Product.json' --views='index,create,edit' --skip='migration'

It worked great but when I  went to view the outcome there was an error. it did generate the table.blade.php not the fields.blade.php file.

**Comment by mitulgolakiya** [comment]
@phillipmadsen fixed it.
