### ISSUE TITLE
how to Generate from existing table?

### ISSUE THREAD

**Issue by cncap** [InfyOmLabs/laravel-generator#198]
All generate command can used for " for given model", but I only have exists table in exists database, how to get it use generate command from exsit database?

**Comment by cncap** [comment]
I am sorry, I did not look carefully, I have found the answer here: 
http://labs.infyom.com/laravelgenerator/docs/options/generator-options

**Comment by mitulgolakiya** [comment]
@cncap great. Post here if you found any problem.

**Comment by cncap** [comment]
@Mitulgolakiya, Thank you for your reply, I am integrating oauth2.0 and laravel,That great if your project can be integrated into it, after all API access is required to verify over APIS.

**Comment by mitulgolakiya** [comment]
ok, I will add it to the queue.
