### ISSUE TITLE
primary key from table generation

### ISSUE THREAD

**Issue by error500** [InfyOmLabs/laravel-generator#20]
Hi, 
I did a 
    php artisan infyom:api $MODEL_NAME$
with two tables on a postgresql database.
The primary keys names are not 'id' but something else. The model files doesn't find them.

Should only implicit 'id' primary key fields be supported ?

**Comment by mitulgolakiya** [comment]
Its not implemented yet. It's already in know issue. #2.

**Comment by error500** [comment]
Ok sorry again for not search before...
