### ISSUE TITLE
New theme for better Documentation

### ISSUE THREAD

**Issue by mitulgolakiya** [InfyOmLabs/laravel-generator#200]
Hello all,

I was just thinking we should have a better documentation theme. As the package is now growing with lots of features. Some of them are really complex to understand it use. so we need detailed steps to use that.

Please share your ideas of available themes here.

Also, I was just thinking if we can use the theme that laravel is using for its documentation with the footer credits of laravel trademark & designed by Jack McDade.
http://github.com/laravel/laravel.com

But I am not sure about licensing stuff for using open source stuff. so I am not sure if we can use it or we need some special permissions. If anyone has any idea then please share that.

Also, any new theme either paid or free. Please share your suggestions.

Thanks to everyone for your great contribution.

**Comment by mitulgolakiya** [comment]
We are going to re-design the documentation with laravel doc theme.

**Comment by mitulgolakiya** [comment]
New theme is live here: http://labs.infyom.com/laravelgenerator/docs

**Comment by phillipmadsen** [comment]
what do you use to output the html for docs. just wondering.  phpdocumentor as an example. also what theme did you finally end up using.
