### ISSUE TITLE
Need to add option for migration

### ISSUE THREAD

**Issue by phillipmadsen** [InfyOmLabs/laravel-generator#203]
We need to add a storage engine option to the migrations files.

> $table->engine = 'InnoDB';

**Comment by mitulgolakiya** [comment]
@phillipmadsen I think it should not be an option in migrations. when a database is created, the user should specify his choice of db engine and it should work. I will not prefer to add any extra code to migration files. Even after MySQL 5.5.5 `InnoDB` is default engine. If someone wants to change it, he can publish the migration template and specify it there.
