### ISSUE TITLE
Useful SublimeText3 Laravel 5.1+ Snippets

### ISSUE THREAD

**Issue by phillipmadsen** [InfyOmLabs/laravel-generator#204]
I  have started keeping track of the ones I  use the most so if anyone wants to use the snippets I  use all the time you are free to. 

> Laravel 5.1 SublimeText3-Snippets
[https://github.com/phillipmadsen/Laravel-5.1-SublimeText3-Snippets](url)

**Comment by mitulgolakiya** [comment]
great. will check it.
