### ISSUE TITLE
ROUTE_NAMED_PREFIX not properly replaced

### ISSUE THREAD

**Issue by axyr** [InfyOmLabs/laravel-generator#205]
When scaffolding a Company crud :

Route [ROUTE_NAMED_PREFIXcompanies.index] not defined. (View: /Users/martijn/www/tests/laravel/laragenerator/resources/views/companies/show.blade.php)

This happens with a fresh install and default config...

**Comment by axyr** [comment]
its missing the $ before ROUTE_NAMED_PREFIX in the stub file.

**Comment by mitulgolakiya** [comment]
@axyr ok, will fix it.

**Comment by mitulgolakiya** [comment]
Fixed.
