### ISSUE TITLE
Routes lowercased?

### ISSUE THREAD

**Issue by axyr** [InfyOmLabs/laravel-generator#206]
Should routes not be all lowercased?

Right now I have a lot of routes like : 
resumeInvites
referenceSources
jobCategories

looks kinda 'ugly' ...

**Comment by mitulgolakiya** [comment]
@axyr Yes, I think we should use snake_case because what I found is, most of apis are using snake cases in their urls.

http://stackoverflow.com/questions/778203/are-there-any-naming-convention-guidelines-for-rest-apis

http://blog.octo.com/en/design-a-rest-api/#case

**Comment by mitulgolakiya** [comment]
api routes are now snake cased.
folder name for model views is not snake cased.
Also, we are using bit more user-friendly name at various places like views, flash messages etc.
e.g. instead of "UserStatues" in view & flash messages, we are using "User Statues".
