### ISSUE TITLE
Prefixed routes in groups

### ISSUE THREAD

**Issue by axyr** [InfyOmLabs/laravel-generator#207]
Is possible to add prefixed route in a group:

``` php
Route::group(['prefix' => 'admin'], function () {
    Route::resource('companies', 'CompanyController');
    Route::resource('education', 'EducationController');
    Route::resource('searchLogs', 'SearchLogController');
});
```

This looks much nicer then all separate routes for each controller method..

**Comment by mitulgolakiya** [comment]
Actually, it's already in a plan but we have to think about it when it's used with a dynamic prefix, then it's really hard to detect right group.

I am thinking about it but If anyone have any idea then share it here.

**Comment by phillipmadsen** [comment]
This would be something along the lines of a site.build.json the would be instructions on how to build the whole project; using resources and fields files to connect through their relationships. with it being a model only crud as of right now I  oont think there would be a way to specify this or add each one into and existing group.  you could maybe use a  option that would generate the group with the resource in it but they would then have to manually cut and paste the routes file to make it combine them. 

```
--group='admin'

Route::group(['prefix' => 'admin'], function () {
    Route::resource('companies', 'CompanyController');
});

Route::group(['prefix' => 'admin'], function () {
    Route::resource('education', 'EducationController'); 
});

Route::group(['prefix' => 'admin'], function () {
    Route::resource('searchLogs', 'SearchLogController');
});
```

Anyway just thinking out loud.
