### ISSUE TITLE
Store Models in Prefix folders?

### ISSUE THREAD

**Issue by kay899** [InfyOmLabs/laravel-generator#208]
I just wonder if it makes really sense to store the Models in a prefixed folder like it is happening actually?

When I do

`php artisan infyom.scaffold:views Post --prefix=admin`

the model is stored under App\Models\Admin\Post.php.

Could this be configurable?

I would like to have all my Models only in App\Models... folder.

Thanks
kay899

**Comment by mitulgolakiya** [comment]
@kay899 Actually the main purpose of adding a prefix was when we have multiple panels like backend and frontend and we want a separate layout for both then it will be helpful.

But currently, there is no way to just store model without prefix and store everything else with the prefix.

I will add it in future list.

**Comment by kay899** [comment]
@mitulgolakiya That would be perfect. 
Thanks
