### ISSUE TITLE
Migrate:refresh and migrate:rollback error

### ISSUE THREAD

**Issue by mastermind23** [InfyOmLabs/laravel-generator#209]
I create a scaffold through generator builder with datatables. It creates everything Model, Views, Datatables, Migration etc. But when I run migrate:refresh or migrate:rollback, it gives me error that 

"[Symfony\Component\Debug\Exception\FatalThrowableError]
class 'CreateStudentTable' not found"

Any solutions?'

edit: it gives error against latest migration, if CreateResultTable is last then it will give error on that.

**Comment by mitulgolakiya** [comment]
Have you checked if original migration file is there ?

**Comment by laurensclaessen** [comment]
The migration template uses the lowercase table name `Create$TABLE_NAME$Table` to create the Class, but it should use the PascalCase Model name.

**Comment by mastermind23** [comment]
@mitulgolakiya Yes the original migration files exists. I have tested it multiple times and always it gives error with the name of the last migration.

**Comment by mastermind23** [comment]
@laurensclaessen So migration templates do name it like CreatestudentsTable, and it should be CreateStudentsTable. I've renamed it, deleted all database tables manually, migrated it and then run migrate:refresh it still gives the same error

**Comment by mastermind23** [comment]
vendor/infyomlabs/laravel-generator/templates/migration.stub 
Changed Create$MODEL_NAME_PLURAL$Table.
worked fine issue resolved thus far, one of my migrations is giving same error, most probably some syntax error or something, i'll create new migration but my main issue have been resolved.

Thanx @laurensclaessen

**Comment by mastermind23** [comment]
again something went wrong with update of infyom. 

previous all migrations are working fine and can rollback, but creating new model with generator-builder. it fails to migrate, also if i manually migrate that, the same issue returns where i can't rollback the latest migration

**Comment by mitulgolakiya** [comment]
@mastermind23, I was on a vacation. just came today. will review it and will fix it by this weekend.

**Comment by ptsilva** [comment]
@mitulgolakiya 
see #222, this PR fix this issue
