### ISSUE TITLE
Undefined variable: errors 

### ISSUE THREAD

**Issue by error500** [InfyOmLabs/laravel-generator#21]
After a "from tables" generation and all the publish commands i got :

````
ErrorException in eb802082d2e01daa6efc08b644bb03f92293542a.php line 1: Undefined variable: errors (View: D:\wamp\apps\infyom\vendor\infyomlabs\core-templates\views\common\errors.blade.php) (View: D:\wamp\apps\infyom\vendor\infyomlabs\core-templates\views\common\errors.blade.php)
````

**Comment by mitulgolakiya** [comment]
I think you are using Laravel 5.2 and in while using 5.2, you need to surround your web routes with `web` middleware. Check it [here](https://laravel.com/docs/5.2/routing#basic-routing)

**Comment by mitulgolakiya** [comment]
It's in process that we detect it automatically and surround routes in `web` middleware.

**Comment by error500** [comment]
OK.
Sorry for not having search before my writting an issue.

It works fine

**Comment by alejandri** [comment]
Hello i have same error. How solved that error500? or where learn more

**Comment by mitulgolakiya** [comment]
Check above comments https://github.com/InfyOmLabs/laravel-generator/issues/21#issuecomment-186749207
