### ISSUE TITLE
Set the value of foreign key from some different object

### ISSUE THREAD

**Issue by shafihuzaib** [InfyOmLabs/laravel-generator#216]
My model has a field 'department_id', which is set value as per the current authenticated user's department, hence cannot be allowed to set from views. So how to do that? I mean;

      - It is not available in view (as the department is implicit in such a context)

      - But the value for the said field is set automatically.
Please let me know if I should override some methods to get this done, in case it is not available yet.

**Comment by mitulgolakiya** [comment]
There in an option for that, but while you are passing fields via JSON file. [Here](https://github.com/InfyOmLabs/laravel-generator/blob/develop/samples/fields_sample.json) is the sample for it. In that, you will find one key `inForm`, you can pass it as false and it will not be included in your forms.

so you can generate it and then set it by whatever manner you want from a controller.

**Comment by shafihuzaib** [comment]
But when showing it in the table, would it be possible to show the department_name in the view?

**Comment by phillipmadsen** [comment]
To show the view from an id you would need to create a list. Here is an example of one I  made.

ArticleRepository.php

```
/**
     * @return mixed
     */
    public function lists()
    {
        return $this->article->get()->where('lang', $this->getLang())->lists('title', 'id');
    }
```
ArticleController.php

```
 public function create()
    {
        $categories = $this->category->lists(); // this is pulling form the repo
\\ here is a way of doing it with a direct sql query from the db table.
$users = User::select(DB::raw('concat(first_name," ",last_name) as full_name,id'))->lists('full_name', 'id');
 return view('backend.article.create', compact('categories', 'users'));
    }
```
And here is the html form fields I  use. 

{!! Form::select('category', $categories, null, ['class' => 'form-control', 'value'=>Input::old('category')]) !!}
{!! Form::select('user', $users, null, ['class' => 'form-control', 'value'=>Input::old('user')]) !!}

Remember for this to work you relationships need to be set as well. 

Hope it helps
