### ISSUE TITLE
Datatables support Column Visibility and Page Lenght

### ISSUE THREAD

**Issue by jordivela007** [InfyOmLabs/laravel-generator#217]
If you add in app.blade.php these options:

src="https://cdn.datatables.net/buttons/1.2.1/js/dataTables.buttons.min.js"
src="//cdn.datatables.net/buttons/1.2.1/js/buttons.colVis.min.js"

the tablenameDataTable.php now support

parameters: 'colvis' and 'pageLength'

**Comment by mitulgolakiya** [comment]
@jordivela007 ok, will check and will add it.

**Comment by mitulgolakiya** [comment]
added in core-templates app.blade.php & ModelDataTable.php.
done in develop branch.
