### ISSUE TITLE
AppBaseController still changes app:name to App 

### ISSUE THREAD

**Issue by phillipmadsen** [InfyOmLabs/laravel-generator#218]
Even when another Is being used. 

I am currently using Grace/Models/? as an example and when I  run the generator it changes it to App\Models\?

Also having the same issue with BaseRepo

**Comment by mitulgolakiya** [comment]
@phillipmadsen I have totally changed the app base controller publish stuff.

so now we are publishing AppBaseController.php into always `App\Http\Controllers\` or with whatever namespace of the app no matter any prefix is used.

so test it with the latest version with fresh setup and let me know if you are still getting problem.

**Comment by phillipmadsen** [comment]
will do. thanks

**Comment by mitulgolakiya** [comment]
Fixed in develop.
