### ISSUE TITLE
Unique fields

### ISSUE THREAD

**Issue by showFocus** [InfyOmLabs/laravel-generator#221]
The scaffold generator does not allow a model to be updated if it contains a unique field.

For example field a is unique, field b is not. If i update field b it will not save.

**Comment by NightZpy** [comment]
In the updaterequest, set rules method to:

```
    public function rules()
    {
        $rules = Model::$rules;
        //$rules['unique_field'] = $rules['unique_field'] . ',unique_field,' . $this->id;
        return $rules;
    }
```

**Comment by showFocus** [comment]
@NightZpy that didn't work, unfortunately.

**Comment by NightZpy** [comment]
@showFocus Some error?

**Comment by showFocus** [comment]
@NightZpy "The name has already been taken."

**Comment by NightZpy** [comment]
Is strange, for me, works! :(

**Comment by showFocus** [comment]
@NightZpy Strange indeed! Here are my model, controller and Request file.
```
public function rules()
    {
        $rules = Category::$rules;
        $rules['name'] = $rules['name'] . ',name,' . $this->id;
        return $rules;
    }
```
```
public function update($id, UpdateCategoryRequest $request)
    {
        $category = $this->categoryRepository->findWithoutFail($id);

        if (empty($category)) {
            Flash::error('Category not found');

            return redirect(route('categories.index'));
        }

        $category = $this->categoryRepository->update($request->all(), $id);

        Flash::success('Category updated successfully.');

        return redirect(route('categories.index'));
    }
```
```
public static $rules = [
        'name' => 'required|unique:categories,name'
    ];
```

**Comment by NightZpy** [comment]
My UpdateREquest:

```
<?php

namespace App\Http\Requests\API\Kitchen;

use App\Models\Kitchen\Provider;
use App\Http\Requests\API\MyAPIRequest;

class UpdateProviderAPIRequest extends MyAPIRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        $rules = Provider::$rules;
        $rules['name'] = $rules['name'] . ',name,' . $this->id;
        $rules['email'] = $rules['email'] . ',email,' . $this->id;
        return $rules;
    }
}
```

Rule set:

 ```
   public static $rules = [
        'name' => 'required|min:1|max:128|unique:providers',
        'specialty' => 'required|min:1|max:128',
        'district' => 'min:1|max:128',
        'address' => 'min:12|max:512',
        'phone' => 'required|numeric|digits_between:7,20',
        'movil1' => 'numeric|digits_between:7,20',
        'movil2' => 'numeric|digits_between:7,20',
        'contact' => 'min:1|max:128',
        'email' => 'required|email|min:3|max:128|unique:providers'
    ];
```

**Comment by NightZpy** [comment]
In your rule, delete name at last of the rule definition!

**Comment by showFocus** [comment]
@NightZpy No, that didn't work.

**Comment by mitulgolakiya** [comment]
I will be working on it in next week. Will post update once its done.

**Comment by showFocus** [comment]
This is what I came up with, in my update request

```
public function rules()
    {
        $rules = Category::$rules;
        if ($this->isMethod('patch'))
        {
            $id = $this->categories;
            $rules['name'] = $rules['name'].',name,'.$id;
        }
        return $rules;
    }
```

**Comment by mitulgolakiya** [comment]
@showFocus What is `$this->categories` ?

**Comment by showFocus** [comment]
It's a reference to the 'id' of the model instance. Without it you can't pass the id of the model instance to the next statement. You get an 'undefined variable' error

**Comment by jackleblack** [comment]
For me the hack work with my table name :

> $rules = Client::$rules;
        $rules['nom'] = $rules['nom'] . ',nom,' . $this->clients;
        return $rules;

**Comment by rattfieldnz** [comment]
I have just come across this problem today, and have found the following worked for me:

1. In the view file (which contains the form to update a particular entity), create a hidden input field, e.g:

    ```
{!! Form::model($user, ['route' => ['users.update', $user->id], 'method' => 'patch']) !!}
	    
		{{ Form::hidden('user_id', $user->id, array('id' => 'user_id')) }} ## The hidden input field ##
		
		## The rest of the fields are in the partial below: ##
		@include('users.fields')

    {!! Form::close() !!}
```
	
2. Modify your entity's request object's rules() method as follows:

   ```
/**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        $rules = User::$rules;
        if($this->isMethod('patch')){
		
		    // Retrieve the entity's i.d from the hidden input field.
            $id = $this->input('user_id');
			
            $rules['username'] = $rules['username'].', '.$id;
            $rules['email'] = $rules['email']. ', '.$id;
            //dd($rules);
        }
        return $rules;
    }
```

3. In your entity's Model class, make sure your rules array looks like the following:

   ```
 // Here, I have two unique fields that could need updating.
    // 
    // NOTE: I put the min/max/email requirements at the end, and that did not work. Putting
    //       them at the front, as in this example, worked for me. 

    public static $rules = [
        'username' => 'min:5|max:25|required|unique:users,username',
        'password' => 'required|min:6',
        'email' => 'email|required|unique:users,email',
        'firstname' => 'required|max:100',
        'lastname' => 'max:100',
        'phone' => 'max:15'

    ];
```

4. Once you have done the above three steps, updating your entities should work as intended (unless you also have other logic implementations that could affect updating).

**Comment by whereisjefe** [comment]
I figured i would share the simple change that has been working for me and requires updating only one file/function. It also helps to prevent the case where the update function will allow you to update the field to a value already in the database. 

**In this example I'm working with the model `Job`**

Verify that your model has valid rules set
```php
    public static $rules = [
        'job_name' => 'required',
        'job_code' => 'required|unique:jobs'
    ];
```
Then open the update request file for the model `App\Http\Requests\UpdateJobRequest.php` 

By default, the scaffold generator will create the following rules function.  

```php
    public function rules()
    {
        return Job::$rules;
    }
```
Change it to the following...
```php
    public function rules()
    {
        $rules = Job::$rules;

        // get ID of the job being edited.
        $requestID = (int)$this->job;

        // get job code from the request (form data), cast the value per your models design.
        $requestCode = (int)$this->job_code;

        // fetch current job code from db, if there is a better way to do this part, please let me know
        $job = Job::where('id', $requestID)->first();

        // get current job code
        $currentCode = $job->job_code;
   
        /**
         * Now check if the "job_code" field will be updated.
         * If the "job_code" field isn't being updated, we need to change the rule to ignore the unique value.
         * If "job_code" is being updated we want to make sure it's unique.
         */
        if($requestCode == $currentCode){
            // update didn't change job code, so we want to ignore this id for the unique validation.
            $rules['job_code'] = $rules['job_code'].',id,'.$requestID;
        } 
        
        return $rules;
    }
```

Now the validation rules will ignore the `job_code` field if it's not being changed in the request. However, if the value is being changed, the validator  will check if it's unique.

**Comment by mostadev** [comment]
Thats Worked for me
`public static $rules = [
    'title'  => [
      'required',
      'min:2',
      'max:255',
    ],
    'locale' => [
      'required',
      'min:2',
      'max:255',
    ],
  ];`

CreateLanguageRequest.php

`public function rules()
    {
      $rules = Language::$rules;
      $rules['title'][] = 'unique:languages';
      $rules['locale'][] = 'unique:languages';
      return $rules;
    }`

UpdateLanguageRequest.php

`public function rules()
  {
    $rules = Language::$rules;
    $rules['title'][] = Rule::unique('languages')->ignore($this->language);
    $rules['locale'][] = Rule::unique('languages')->ignore($this->language);
    return $rules;
    // return Language::$rules;
  }`

**Comment by MrAntunes** [comment]
I was a bit confused  with previous comments, so the simpler solution (as posted before in some comments, but more explicit :P):

- Your model's name is 'Utilizador' and you want the email field to be unique and avoid "update error validation"
`public static $rules = [
	
		'email' => 'required|email|unique:users,email,',
		'name' => 'required|string|min:4'
    ];`
- So go to your 'UpdateUtilizadorRequest' and change function rules:
`public function rules()
	{
		$rules          = Utilizador::$rules;
		$rules['email'] = $rules['email'].$this->utilizadors;
		
		return $rules;
	}`

Don't forget your current object use the "plural name" or else you won't get current object id.

**Comment by sbolognini** [comment]
Are there updates on this issue?
