### ISSUE TITLE
Is there a Nested Routed Method Available ? 

### ISSUE THREAD

**Issue by adnanmayo** [InfyOmLabs/laravel-generator#227]
i want to add a  nested resource routes..like products.sizes is there a method available in CLI ?

**Comment by phillipmadsen** [comment]
Yes you can use the prefix shortcut.  something along the lines of:


php artisan infyom:scaffold Size --prefix='products'

**Comment by adnanmayo** [comment]
It will just make prefix

 i want to do like this
admin/products/1/sizes

php artisan infyom:scaffold Size --prefix='products'
It can not be acheived from this command




Route::resource('products.sizes','SizeController')

**Comment by phillipmadsen** [comment]
So you are trying to make two other tables available to your products model?  I  assume the /1/ is the product and then the sizes is the options of that product?  

In the one I  am building at the moment I  have something similar and all you would really want to use is the model and fields with relationships. Example of how I  set one up is like this.
```
- prodcuts
  - features
  - options
  - variations
```
I  then used hasMany and belongsTo relationships and added the forms to enter repeating inputs for those right inside my products model.

At this time if you are trying to create something like the what I  have made it is being worked on but not ready at this time. You will manually have to build them in using relationships and etc.
