### ISSUE TITLE
Impossible to use generator with field file

### ISSUE THREAD

**Issue by jackleblack** [InfyOmLabs/laravel-generator#228]
I encoutered the error "Invalid argument supplied for foreach()" when I use the command :

> php artisan infyom:api post --fieldsFile=fields_sample.json

The file fields_sample.json is in the root directory, it's the original sample.

**Comment by phillipmadsen** [comment]
try 

php artisan infyom:api Post --fieldsFile='resources/model_schemas/fields_sample.json'

**Comment by jackleblack** [comment]
Thanks for you reactivity phillip.

This fix doens't help me.

**Comment by phillipmadsen** [comment]
My bad I  meant to also help you with the foreach() problem but forgot to tell you. Everytime I  get this error there is a syntax error or wrong field format in my fieldsfile. check that or maybe post it and I  will take a look.

**Comment by jackleblack** [comment]
It's the original file ..

**Comment by mitulgolakiya** [comment]
it seems like the problem is with JSON format. it should be in an array. Just like [this](https://github.com/InfyOmLabs/laravel-generator/blob/develop/samples/fields_sample.json) file.

it should be like,

```
[
{
},
{
}
]
```

**Comment by jackleblack** [comment]
Thanks you @mitulgolakiya,the problem is indeed from comment, I post the correct file :

> [
>     {
>         "fieldInput": "id:increments",
>         "htmlType": "",
>         "validations": "",
>         "searchable": false,
>         "fillable": false,
>         "primary": true,
>         "inForm": false,
>         "inIndex": false
>     },
>     {
>         "fieldInput": "title:string,20",
>         "htmlType": "text",
>         "validations": "required",
>         "searchable": true,
>         "inForm": true,
>         "inIndex": true
>     },
>     {
>         "fieldInput": "email:string",
>         "htmlType": "email",
>         "searchable": true
>     },
>     {
>         "fieldInput": "post_date:dateTime",
>         "htmlType": "date"
>     },
>     {
>         "fieldInput": "words:integer",
>         "htmlType": "number"
>     },
>     {
>         "fieldInput": "attachment:string",
>         "htmlType": "file"
>     },
>     {
>         "fieldInput": "password:string",
>         "htmlType": "password",
>         "inIndex": false
>     },
>     {
>         "fieldInput": "post_type:string",
>         "htmlType": "select:Type1,Type2,Type3,Type4",
>         "validations": "",
>         "searchable": true
>     },
>     {
>         "fieldInput": "post_day:enum",
>         "htmlType": "enum:Mon,Tue,Wed,Thu,Fri,Sat,Sun",
>         "validations": "",
>         "searchable": true
>     },
>     {
>         "fieldInput": "post_author_gender:string",
>         "htmlType": "radio:Male,Female",
>         "validations": "",
>         "searchable": false,
>         "fillable": true,
>         "primary": false,
>         "inForm": true,
>         "inIndex": false
>     },
>     {
>         "fieldInput": "body:text",
>         "htmlType": "textarea",
>         "validations": "",
>         "searchable": false,
>         "fillable": true,
>         "primary": false,
>         "inForm": true,
>         "inIndex": false
>     },
>     {
>         "fieldInput": "private_post:string",
>         "htmlType": "checkbox:Yes",
>         "validations": "",
>         "searchable": true,
>         "fillable": true,
>         "primary": false,
>         "inForm": true,
>         "inIndex": false
>     },
>     {
>         "fieldInput": "is_active:boolean",
>         "htmlType": "bool-checkbox:checked",
>         "validations": "",
>         "searchable": true,
>         "fillable": true,
>         "primary": false,
>         "inForm": true,
>         "inIndex": false
>     },
>     {
>         "fieldInput": "is_published:boolean",
>         "htmlType": "toggle-switch",
>         "validations": "",
>         "searchable": true,
>         "fillable": true,
>         "primary": false,
>         "inForm": true,
>         "inIndex": false
>     }
> ]

**Comment by mitulgolakiya** [comment]
@jackleblack great. so is it now resolved or still you are getting problem ?

**Comment by phillipmadsen** [comment]
My bad guys I  should have removed that before push it was meant as notes of what was being done. I  meant to remove it but guess it got pushed before I  could remove it. Sorry.
