### ISSUE TITLE
Datatables Not Working

### ISSUE THREAD

**Issue by jackleblack** [InfyOmLabs/laravel-generator#230]
Please help. Similar to issue resolved 53

I use this boilerplate : https://github.com/rappasoft/laravel-5-boilerplate/wiki#features
I add https://github.com/yajra/laravel-datatables OK.
I enabled 'add_on.datatables' => true in laravel-generator.
I generate my scaffold from fieldsFile OK.

But I cannot retrieve my data, I have only the header of a bootstrap table.

The network respond : 
> <table  class="table" id="dataTableBuilder" width="100%"><thead><tr><th >Nom</th><th >Prenom</th><th >Telephone</th><th >Email</th><th  width="10%">Action</th></tr></thead></table>

I already try to change my jQuery version to 1.10.2.

**Comment by adnanmayo** [comment]
did you run `php artisan vendor:publish `

**Comment by jackleblack** [comment]
Yes I have, always the same.

**Comment by MatheusNaldi** [comment]
What have you did to resolve this?

**Comment by jackleblack** [comment]
I modifiy "table.blade.php" : 

`{!! $dataTable->table(['width' => '100%']) !!}

@push('scripts')
{!! $dataTable->scripts() !!}
@endpush`

And I add this in my layout :
`        
        <script src="//cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js"></script>
        <script src="https://cdn.datatables.net/1.10.12/js/dataTables.bootstrap.min.js"></script>
        <link rel="stylesheet" href="https://cdn.datatables.net/1.10.12/css/dataTables.bootstrap.min.css">

        <script src="https://cdn.datatables.net/buttons/1.0.3/js/dataTables.buttons.min.js"></script>
        <script src="../vendor/datatables/buttons.server-side.js"></script>

        
        @stack('scripts')
        `
