### ISSUE TITLE
Swagger documentation for Models

### ISSUE THREAD

**Issue by Ashwin012** [InfyOmLabs/laravel-generator#231]
Small error in Swagger documentation for Models.
The " are missing for the required fields.
The following file should be updated : 

/vendor/infyomlabs/laravel-generator/src/Generators/ModelGenerator.php

Public function generateSwagger(...
...
        $template = str_replace('$REQUIRED_FIELDS$', '"' . implode('"' . ', ' . '"', $this->generateRequiredFields()) . '"', $template);

Thanks for the great work!

**Comment by mitulgolakiya** [comment]
@Ashwin012 its fixed. check with the latest changes.

**Comment by Ashwin012** [comment]
Thanks Mitul, great work on this package!

**Comment by vishalVDevmurari** [comment]
how to turn on swagger 
there is no documentation on it 
please help me asap
