### ISSUE TITLE
Issue with php artisan infyom.publish:layout command

### ISSUE THREAD

**Issue by lamberttraccard** [InfyOmLabs/laravel-generator#232]
I made customizations to the default templates `resources/infyom/infyom-generator-templates`.

Using the `php artisan infyom.publish:layout` command with metronic templates, my layouts templates won't update. 

Any help please ?

**Comment by mitulgolakiya** [comment]
@lamberttraccard I'll review it and will let you know.

**Comment by mitulgolakiya** [comment]
@lamberttraccard I fixed it. Check with the latest version.
