### ISSUE TITLE
Make custom query

### ISSUE THREAD

**Issue by garenk02** [InfyOmLabs/laravel-generator#233]
Can u give example how to make custom query?

Many thanks

**Comment by mitulgolakiya** [comment]
@garenk02 what type of custom query ? Can you post any example or more details ?

**Comment by garenk02** [comment]
Actually I need the comphrehensive documentation on how your package (infyom labs) using the prettus repository with custom query (join, union, etc), and how do if I want do show some field from custom query (join, union, etc).

Many thank's

**Comment by NightZpy** [comment]
You can add query into BaseRepository template or a middle Class with the query (BaseRepository > MyBaseRepository). Or only into Model associate repo!

**Comment by mitulgolakiya** [comment]
@garenk02 Our [BaseRepository](https://github.com/InfyOmLabs/laravel-generator/blob/develop/src/Common/BaseRepository.php) class is extending repository class of prettus repository. so you can modify your template by any way which is compatible with prettus repository. so  I think its fully compatible.
