### ISSUE TITLE
Trait MakeModelTrait not found

### ISSUE THREAD

**Issue by FlorientR** [InfyOmLabs/laravel-generator#234]
Hi,

When I generate api_scaffold Model, ```ModelApiTest``` and ```ModelRepositoryTest``` use ```MakeModelTrait```.

But ```MakeModelTrait``` is on ```traits``` folder.

So for resolve this problem, I add on ```composer.json``` : 

```
"autoload-dev": {
        "classmap": [
            "tests/TestCase.php",
            "tests/traits",
            "tests"
        ]
    },
```

;)

**Comment by mitulgolakiya** [comment]
@FlorientR great catch. I will add this to the documentation.

**Comment by mitulgolakiya** [comment]
I think it's already there in docs: http://labs.infyom.com/laravelgenerator/docs/master/generator-options#test-cases

**Comment by FlorientR** [comment]
Ho yes sorry.... 

Thanks
