### ISSUE TITLE
checkbox not working

### ISSUE THREAD

**Issue by lorvent** [InfyOmLabs/laravel-generator#235]
Hello,
checkbox is not working, if i choose checkbox as htmltype then it throws error.

and looking at sample json https://github.com/InfyOmLabs/laravel-generator/blob/develop/samples/fields_sample.json#L75 for checkbox, we need to pass value aswell

but in generator builder https://github.com/InfyOmLabs/generator-builder/blob/master/views/builder.blade.php#L394

you are not showing extra field for it, so when i hit "generate" it throws error.

Also, on a sidenote..... i have set php max_execution_time to **300** yet, my generate always times out.

**Comment by mitulgolakiya** [comment]
duplicate of https://github.com/InfyOmLabs/laravel-generator/issues/236

**Comment by lorvent** [comment]
Actually not exact duplicate, but since you said gui is in beta...it may be related to that.
