### ISSUE TITLE
doesn't work on Laravel 5.1

### ISSUE THREAD

**Issue by janbolat** [InfyOmLabs/laravel-generator#238]
Hello,

just installed your package, it seems it doesn't work on Laravel 5.1.
my composer.json:

 ```
 "infyomlabs/laravel-generator": "dev-master",
 "laravelcollective/html": "5.1.*",
 "infyomlabs/core-templates": "dev-master"
```
When I try to generate CRUD:

`php artisan infyom:scaffold Bond`

it returns me this error:

`PHP Fatal error:  Call to undefined method InfyOm\Generator\Commands\Scaffold\ScaffoldGeneratorCommand::hasOption() in /var/www/site/html/vendor/infyomlabs/laravel-generator/src/Common/GeneratorConfig.php on line 262`

Apparently [Laravel 5.1] (https://github.com/laravel/framework/blob/5.1/src/Illuminate/Console/Command.php) doesn't have that method, but [5.2](https://github.com/laravel/framework/blob/5.2/src/Illuminate/Console/Command.php) does.

It seems you added this method 2 hours ago in [48c3889ef1d107c92b31960562e8bae2dafa9009](https://github.com/InfyOmLabs/laravel-generator/blob/48c3889ef1d107c92b31960562e8bae2dafa9009/src/Common/GeneratorConfig.php)

How can I make it work on 5.1?

**Comment by mitulgolakiya** [comment]
@janbolat will fix it soon.

**Comment by mitulgolakiya** [comment]
@janbolat its fixed. checked with the latest version.

**Comment by janbolat** [comment]
thanks, it works!
