### ISSUE TITLE
Missing file inside the package

### ISSUE THREAD

**Issue by microdesign** [InfyOmLabs/laravel-generator#240]
This error happend right after I type exit and you package must generate the code

[ErrorException]                                                                                                                                                               
  file_get_contents(/Volumes/Storage/Projects/net-manager_new/vendor/infyomlabs/swagger-generator/templates/model/model.stub): failed to open stream: No such file or directory 
Also, in your package folder have only two directories:

core-templates
laravel-generator

there is not a folder called 'swagger-generator'

**Comment by mitulgolakiya** [comment]
@microdesign I think you are missing swagger-generator package. Read installation steps carefully here: http://labs.infyom.com/laravelgenerator/docs/master/installation#add-packages
