### ISSUE TITLE
Laravel generator creates migration class without proper camelCase

### ISSUE THREAD

**Issue by rasouza** [InfyOmLabs/laravel-generator#241]
Once you run `php artisan infyom...` to generate your API, it creates the migration without uppercase in the second word (in my case: `CreatetemplatesTable`instead of `CreateTemplatesTable`). So when you need to rollback, laravel can't find the proper class to rollback due to mispelled name. The workaround is to rename the migration class, `composer dump-autoload` and then rollback.

**Comment by mitulgolakiya** [comment]
@rasouza its fixed in develop branch. will merge it soon.
