### ISSUE TITLE
Any plan for I18N and L10N?

### ISSUE THREAD

**Issue by lsc20051426** [InfyOmLabs/laravel-generator#243]
Currently, the generated blade template only contains ENGLISH content.
Is there any plan to add Internationalization and Localization?

FYI: https://laravel.com/docs/5.2/localization

**Comment by mitulgolakiya** [comment]
Yes, once we complete current major things, I have this feature in a plan.

**Comment by ajayinfyom** [comment]
**Localization** Support added.

Setup Localization docs : https://labs.infyom.com/laravelgenerator/docs/6.0/localization
