### ISSUE TITLE
Have you prepared for laravel 5.3

### ISSUE THREAD

**Issue by thandonguocmo2020** [InfyOmLabs/laravel-generator#245]
5.3 laravel upcoming new and changing many advantages laravel infyom packet matches.

**Comment by john5db** [comment]
this is the first package i like to see in laravel 5.3 .

waiting to see it working with L5.3

**Comment by mitulgolakiya** [comment]
@thandonguocmo2020 @john5db yes, its already on plan as next. Right now, I am working on some major refactoring for relationships and supprot for vuejs templates.

Once, its done. I am planning to have a version for 5.3.

**Comment by mitulgolakiya** [comment]
Closing in reference of https://github.com/InfyOmLabs/laravel-generator/issues/258
