### ISSUE TITLE
php artisan infyom:scaffold users --fromTable --tableName=users --prefix=admin

### ISSUE THREAD

**Issue by youngerrainbow** [InfyOmLabs/laravel-generator#249]
on usercontroller.php    use App\Http\Controllers\Admin\AppBaseController as InfyOmBaseController;

but  appBaseController is  under  Http\Controllers\      not with Admin   so need to remove this Admin.

**Comment by mitulgolakiya** [comment]
@youngerrainbow test with the latest version with full setup from scratch. It's fixed.
