### ISSUE TITLE
[Enhancement]: Compatibility rappasoft/laravel-5-boilerplate

### ISSUE THREAD

**Issue by proverbial-ninja** [InfyOmLabs/laravel-generator#250]
I'm a big fan of laravel generaator project ... I also use rappasoft to quickly set up my environment however mixing these two projects is hard .. These two projects combined would really shorten dev time ... please consider this.

**Comment by mitulgolakiya** [comment]
@kmarima great one. I will fork that repo and will try to integrate generator into it. OR I will write some post on how to integrate it with rappasoft/laravel-5-boilerplate.

**Comment by vesper8** [comment]
I have been using these two projects together for months now and have had no trouble at all.. wondering why you say it's hard

**Comment by jackleblack** [comment]
I also use these 2 wonderfull tools !

**Comment by lsc20051426** [comment]
I am also using these 2 tools.How about Let's writing a doc for combining these 2 tools together? @jackleblack @vesper8

**Comment by riterrani** [comment]
Anyone can show his laravel_generator.php config file?
I am trying to generate the controllers inside Backend, and the views inside backend, and I am having some problems.

**Comment by kmarima** [comment]
Kind of figured it out
`<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Paths
    |--------------------------------------------------------------------------
    |
    */

    'path' => [

        'migration'         => base_path('database/migrations/'),

        'model'             => app_path('Models/'),

        'datatables'        => app_path('DataTables/'),

        'repository'        => app_path('Repositories/'),

        'routes'            => base_path('routes/Backend/Dashboard.php'),

        'api_routes'        => base_path('routes/api.php'),

        'request'           => app_path('Http/Requests/'),

        'api_request'       => app_path('Http/Requests/API/'),

        'controller'        => app_path('Http/Controllers/Backend/'),

        'api_controller'    => app_path('Http/Controllers/API/'),

        'test_trait'        => base_path('tests/traits/'),

        'repository_test'   => base_path('tests/'),

        'api_test'          => base_path('tests/'),

        'views'             => base_path('resources/views/'),

        'schema_files'      => base_path('resources/model_schemas/'),

        'templates_dir'     => base_path('resources/infyom/infyom-generator-templates/'),

        'modelJs'           => base_path('resources/assets/js/models/'),
    ],

    /*
    |--------------------------------------------------------------------------
    | Namespaces
    |--------------------------------------------------------------------------
    |
    */

    'namespace' => [

        'model'             => 'App\Models',

        'datatables'        => 'App\DataTables',

        'repository'        => 'App\Repositories',

        'controller'        => 'App\Http\Controllers\Backend',

        'api_controller'    => 'App\Http\Controllers\API',

        'request'           => 'App\Http\Requests',

        'api_request'       => 'App\Http\Requests\API',
    ],

    /*
    |--------------------------------------------------------------------------
    | Templates
    |--------------------------------------------------------------------------
    |
    */

    'templates'         => 'adminlte-templates',

    /*
    |--------------------------------------------------------------------------
    | Model extend class
    |--------------------------------------------------------------------------
    |
    */

    'model_extend_class' => 'Eloquent',

    /*
    |--------------------------------------------------------------------------
    | API routes prefix & version
    |--------------------------------------------------------------------------
    |
    */

    'api_prefix'  => 'api',

    'api_version' => 'v1',

    /*
    |--------------------------------------------------------------------------
    | Options
    |--------------------------------------------------------------------------
    |
    */

    'options' => [

        'softDelete' => true,

        'tables_searchable_default' => false,
    ],

    /*
    |--------------------------------------------------------------------------
    | Prefixes
    |--------------------------------------------------------------------------
    |
    */

    'prefixes' => [

        'route' => 'admin',  // using admin will create route('admin.?.index') type routes

        'path' => '',

        'view' => '',  // using backend will create return view('backend.?.index') type the backend views directory

        'public' => '',
    ],

    /*
    |--------------------------------------------------------------------------
    | Add-Ons
    |--------------------------------------------------------------------------
    |
    */

    'add_on' => [

        'swagger'       => false,

        'tests'         => true,

        'datatables'    => true,

        'menu'          => [

            'enabled'       => true,

            'menu_file'     => 'layouts/menu.blade.php',
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | Timestamp Fields
    |--------------------------------------------------------------------------
    |
    */

    'timestamps' => [

        'enabled'       => true,

        'created_at'    => 'created_at',

        'updated_at'    => 'updated_at',

        'deleted_at'    => 'deleted_at',
    ],

];
`

**Comment by skys215** [comment]
Any progress?

**Comment by skys215** [comment]
After trying to integrate, found out that they are using different repository and it is using coreui now(I assumed that they were using adminlte before? I'm not sure). So integrating it will need to change also the adminlte-templates I guess. It would be a huge project and it won't have capability for older version. 
I suggest to write a brand new package rather than transforming this package.

**Comment by skys215** [comment]
I have written a new package to use under laravel-boilerplate.
It's right [here](https://github.com/labolagen/laravel-generator)

**Comment by RayhanYulanda** [comment]
Please consider make permission feature and role @ajayinfyom

**Comment by mitulgolakiya** [comment]
I think people interested in using these two packages together can either do manual changes or use the package that @skys215 has developed.

@skys215 good job 👍
