### ISSUE TITLE
I harken to the days long past where...

### ISSUE THREAD

**Issue by neosin** [InfyOmLabs/laravel-generator#254]
one could download a script and have it run right out of the box without composer and the myriad other hoops necessary now days with Laravel... RIP Laravel 3.2 you are sorely missed

**Comment by tpharaoh** [comment]
Quick admin from laraveldaily has a site which is close then. Free in beta
but full version will be cost/site

Still need composer but 2 commands and you are ready.

I don't use it but I am impressed.
