### ISSUE TITLE
datatables in adminlte template is not working..

### ISSUE THREAD

**Issue by bencyn** [InfyOmLabs/laravel-generator#255]
while trying to load a new model route i get this error

No hint path defined for [datatables]. (View: C:\xampp\htdocs\laravel\adminLte\resources\views\orders\table.blade.php) (View: C:\xampp\htdocs\laravel\adminLte\resources\views\orders\table.blade.php)

**Comment by mitulgolakiya** [comment]
@bencyn have you installed `yajra/laravel-datatables` properly? which is described [here](http://localhost/InfyOm/Generator/generator-docs/docs/generator-options#datatables).

**Comment by bencyn** [comment]
Thanks reviewed my process and its working.

**Comment by simontong** [comment]
I'm also having this problem, what is the cause and how to fix it?
