### ISSUE TITLE
using ValidatorInterface::RULE_CREATE & RULE_UPDATE & image upload

### ISSUE THREAD

**Issue by garenk02** [InfyOmLabs/laravel-generator#256]
Hi @mitulgolakiya ,

I'm really appreciate & exciting with your package.
Now I have some questions:
1. Can u give example how to use/implement the ValidatorInterface::RULE_CREATE & RULE_UPDATE that came from Presttus package?
2. How if I want to do file upload on create and/or update? Would u give same example?

Many thank's

**Comment by rebootcode** [comment]
- if no wiki, can this be closed with no support!

**Comment by mitulgolakiya** [comment]
@garenk02 @rebootcode I think you should write a custom function for create and update in the generated repository which will overwrite that function. not sure what your schema is, but you can handle file upload in that function and then call parent create/update function to save a data.

**Comment by mitulgolakiya** [comment]
@garenk02 @rebootcode BTW, Presttus package is almost inactive for one year. so I'm planning to remove it and just deploy pure repository where you can write custom code into directly create/update/all/find functions.

**Comment by mitulgolakiya** [comment]
Presttus removed.
