### ISSUE TITLE
Hyphens

### ISSUE THREAD

**Issue by gsc89** [InfyOmLabs/laravel-generator#259]
Is there some issue with using hyphens in column names on tables then generating the model from table? 

It generated the code but the view keeps assuming the column name is "subscription" for:

```
            <td>{!! $orders->horizon-subscription-quantity !!}</td>
            <td>{!! $orders->horizon-subscription-price !!}</td>
```

Error on the view is: 

```
ErrorException in 1b0ea489441d7e4b02575b655127642d592062f9.php line 69:
Use of undefined constant subscription - assumed 'subscription' (View: /var/www/vhosts/.com/app/resources/views/orders/table.blade.php) (View: /var/www/vhosts/.com/app/resources/views/orders/table.blade.php)
```

**Comment by mitulgolakiya** [comment]
@gsc89 I think its not a good practice. you should use _ (underscore) instead hyphens.

**Comment by gsc89** [comment]
I realized that thanks, but this is an existing database someone else made.
