### ISSUE TITLE
Api Response using Pagination

### ISSUE THREAD

**Issue by LucianoVandi** [InfyOmLabs/laravel-generator#264]
Hi there, when I use $this->repo->paginate(n) the response looks like this:

``` json
"success": true,
"data": {
   "total": 10,
   "per_page": 10,
   ...
   "data": [
      {...},
      {...},
      {...},
   ]
},
"message": ""
```

So if I want to access an item I need to do something like $res->data->data[0]->name.

I'm thinking to extend ResponseUtil to make it more readable like $res->data->items[0]->name, but I'm not sure if it's the proper way... some advice? :)

**Comment by mitulgolakiya** [comment]
@LucianoVandi I like the approach. I will change it to `$data->items` in next version.

**Comment by mitulgolakiya** [comment]
You can extend it as of now and can change it via template customization.

**Comment by LucianoVandi** [comment]
Thanks @mitulgolakiya! What do you mean with change it via template customization? Without the need of extending the util class?

While looking for a solution I started playing with League\Fractal, I really like that kind of abstraction for transformers and I think it could play very well with InfyOm generator.

I've already set up JWT so including Fractal will meet all my needs without having to install Dingo.

Besides a Fractal resource give you back a response that follow the specification of JSON API [(link)](http://jsonapi.org/format/#conventions)

**Comment by perezale** [comment]
Hi! this issue is kind of old...but anyway, I noticed that nowadays generator applies LimitOffsetCriteria, which uses limit and skip Model operations. 
I would like to keep using this query scheme but get the same output as Luciano's original message (Including current page no. , total, link page, etc) when using pagination.

Note; If I change my generated api controllers to use paginate($limit ..) the response is as expected.

Thanks in advance

**Comment by gelinger777** [comment]
@mitulgolakiya  what is the status of this? Can we get API list request with pagination?

**Comment by mitulgolakiya** [comment]
@gelinger777 for pagination in api list you can use `limit` and `offset` parameters in your api request. It's already built-in.

`limit` - to limit the number of records
`offset` - to skip the number of records

**Comment by abewartech** [comment]
![image](https://github.com/InfyOmLabs/laravel-generator/assets/29395602/c725149b-8eda-49bc-9d00-cbd244fd48c0)

not working

**Comment by abewartech** [comment]
now working with this adjust

`public function index(Request $request): JsonResponse
    {
        $perPage = $request->get('limit', 10); // Default to 10 if limit is not provided

        // Retrieve all bookingUmrohPilgrims using the repository's "all" method
        $allBookingUmrohPilgrims = $this->bookingUmrohPilgrimRepository->all(
            $request->except(['skip', 'limit'])
        );

        // Manually paginate the results
        $bookingUmrohPilgrims = $allBookingUmrohPilgrims->slice(
            $request->get('skip', 0),
            $perPage
        );

        // Return a JSON response containing the paginated data and pagination meta
        return $this->sendResponse([
            'data' => $bookingUmrohPilgrims->toArray(), // Paginated data
            'pagination' => [
                'total' => $allBookingUmrohPilgrims->count(), // Total number of records
                'per_page' => $perPage, // Records per page
                'current_page' => $request->get('skip', 0) / $perPage + 1, // Current page number
                'last_page' => ceil($allBookingUmrohPilgrims->count() / $perPage), // Last page number
            ],
        ], 'Booking Umroh Pilgrims retrieved successfully');
    }`
