### ISSUE TITLE
No hint path defined for [core-templates]

### ISSUE THREAD

**Issue by nasAtchia** [InfyOmLabs/laravel-generator#265]
Hi, I'm getting this error when I click on the Add New Button or the Edit Button in the dataTable:

`ErrorException in FileViewFinder.php line 112:
No hint path defined for [core-templates]. (View: /var/www/html/project/resources/views/users/create.blade.php)`

The View Button for a single record works fine though. FYI I'm using the adminlte templates. Any help please :)

**Comment by mitulgolakiya** [comment]
@nasAtchia Have you included `\InfyOm\CoreTemplates\CoreTemplatesServiceProvider::class,` service provider in your `config/app.php` ?

**Comment by nasAtchia** [comment]
@mitulgolakiya In the doc it says: 

> Remove any previous included templates stuff. like,

"infyomlabs/core-templates": "dev-master" from your composer.json

\InfyOm\CoreTemplates\CoreTemplatesServiceProvider::class, from your config/app.php

Then add this:

> InfyOm\AdminLTETemplates\AdminLTETemplatesServiceProvider::class,

Do I need to include both service provider?

**Comment by mitulgolakiya** [comment]
@nasAtchia which templates you are using ? AdminLTE or Core ?
Based on that, you have to include service provider for that package.

**Comment by nasAtchia** [comment]
@mitulgolakiya AdminLTE. Ok Thanks :)

**Comment by rabol** [comment]
I get this error as  well - I followed the installation
Any hint?

**Comment by vishalinfyom** [comment]
@rabol if you are using core-ui templates then you need to add following provider to config
```
\InfyOm\CoreTemplates\CoreTemplatesServiceProvider::class
```
if you are using admin-lte templates then you need to add following provider to config
```
InfyOm\AdminLTETemplates\AdminLTETemplatesServiceProvider::class
```
i hope this helps

**Comment by mitulgolakiya** [comment]
@rabol CoreTemplates is deprecated. Try to use CoreUI Templates or AdminLTE Templates.
If you are using CoreUI Templates then service provider will be, `InfyOm\CoreUITemplates\CoreUITemplatesServiceProvider`.
