### ISSUE TITLE
What markup documentor do you use for the docs?

### ISSUE THREAD

**Issue by phillipmadsen** [InfyOmLabs/laravel-generator#266]
what do you use to output the html for docs. just wondering. phpdocumentor as an example. also what theme did you finally end up using.

**Comment by mitulgolakiya** [comment]
@phillipmadsen We were using `parsedown-extra` for output HTML in a previous theme. But with a new theme, I have written every page in individual blade page.

Current theme is not compatible with parsedown. But will change it later once I got time.
