### ISSUE TITLE
Incorrect Wrapper Closure

### ISSUE THREAD

**Issue by gsc89** [InfyOmLabs/laravel-generator#268]
Just used (what I think is the default template) and the layout.app that was generated contained 

`@if (Auth::guest())` 

The else statement of that if statement has the black side bar inside it. The closing of the:

`
@else
    <div id="wrapper" class="">`

Needs to be after the main content otherwise the side bar menu appears over the top of the content area

![image](https://cloud.githubusercontent.com/assets/1032459/17936986/8bd0915c-6a18-11e6-8090-4645978f7311.png)

For speedI corrected this myself with:

```
`@if (Auth::guest())
@else
    </div>
@endif
<!-- /#page-content-wrapper -->`
```

**Comment by mitulgolakiya** [comment]
@gsc89 Can you post your full layout file somewhere ?

**Comment by mitulgolakiya** [comment]
closing.
