### ISSUE TITLE
Uncaught TypeError: Cannot read property 'Buttons' of undefined

### ISSUE THREAD

**Issue by ergonomicus** [InfyOmLabs/laravel-generator#269]
Boilerplate worked fine, but when I tried to add generators to an existing project I get this in console:

Uncaught TypeError: Cannot read property 'Buttons' of undefined
Uncaught TypeError: Cannot read property 'ext' of undefined
Uncaught TypeError: $(...).DataTable is not a function

Index page is not working, only table headers are loaded.

Anyone already had this situation?

**Comment by mitulgolakiya** [comment]
@ergonomicus I think you are may be missing some js and css files for datatables. Check here for a full list of files needed in our app layout. https://github.com/InfyOmLabs/core-templates/blob/master/templates/scaffold/layouts/app.stub

**Comment by ergonomicus** [comment]
You are right, I was missing script call in my blade file.

Thanks a lot!
