### ISSUE TITLE
core-templates error because of web middleware

### ISSUE THREAD

**Issue by phillipmadsen** [InfyOmLabs/laravel-generator#27]
@include('core-templates::common.errors') 

returns this:

ErrorException in 738befae3e778accfa7edc7bda672348bdebf4da.php line 1:
Undefined variable: errors (View: /home/vagrant/grace/blade.clip/vendor/infyomlabs/core-templates/views/common/errors.blade.php) (View: /home/vagrant/grace/blade.clip/vendor/infyomlabs/core-templates/views/common/errors.blade.php)

**Comment by mitulgolakiya** [comment]
May we you are using Laravel 5.2. So you need to use `web` middleware to get your routes working.
Duplicate of #21

**Comment by mitulgolakiya** [comment]
closed in ref of https://github.com/InfyOmLabs/core-templates/pull/5
