### ISSUE TITLE
How to enable datatables caching?

### ISSUE THREAD

**Issue by ergonomicus** [InfyOmLabs/laravel-generator#270]
Like stated in title, how to enable/set up cache?

**Comment by mitulgolakiya** [comment]
@ergonomicus I think you should refer [yajra/laravel-datatables](https://github.com/yajra/laravel-datatables) for more information.

Also worth to consider:
https://github.com/yajra/laravel-datatables/issues/252
https://github.com/yajra/laravel-datatables/issues/130

**Comment by ergonomicus** [comment]
Thanks for taking time to answer my question, though I find it very disappointing. I'll have to stick with my current solution.
