### ISSUE TITLE
Routes in api.php not found

### ISSUE THREAD

**Issue by vwijaya03** [InfyOmLabs/laravel-generator#273]
i create route

Route::group(array('prefix' => 'api/v1.1'), function()
{
	Route::get('/user', 'UserController@index');	
});

and when i try it, the route not working NotFoundHttpException.
how make it work ?

**Comment by mitulgolakiya** [comment]
@vwijaya03 Can you let me know which generator version and laravel version you are using ?
Are you using the latest version of a generator which is just released 2 days ago?
