### ISSUE TITLE
missing info in fields.blade.php

### ISSUE THREAD

**Issue by kirchaj** [InfyOmLabs/laravel-generator#276]
I ran the generator and created a very simple scaffold with 1 field status_text    text   required

Everything appears to be created correctly but the fields.blade.php file which only has text below (no entry field)

<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('orderStatuses.index') !!}" class="btn btn-default">Cancel</a>
</div>

**Comment by phillipmadsen** [comment]
I will replicate it and take a look.  Give me a few

**Comment by mitulgolakiya** [comment]
@kirchaj what exact input you passed to field input ? this one: `status_text text required` ?

I think it should be `status_text string text` or `status_text text textarea`.

It should be in this format: `field_name db_type html_type`.

**Comment by kirchaj** [comment]
Mitulgolakiya,
I believe you are correct.  It had something to do with my entry to the field input.  I am unsure of the exact entry I made. I have been using it correctly since and the problem has not reoccurred.
Kirchaj
