### ISSUE TITLE
Uncaught Unknown button type: colvis 

### ISSUE THREAD

**Issue by john5db** [InfyOmLabs/laravel-generator#278]
I am getting error while creating crud in laravel 5.3 .
following error in in browser console, And no data  in datatable.
```php
Uncaught Unknown button type: colvis     dataTables.buttons.min.js:16 
```

**Comment by mitulgolakiya** [comment]
@john5db Are you using the latest core-templates package 5.3 version ? Or have you include `dataTables.buttons.min.js` & `buttons.colVis.min.js` in your layout ?

You can find it here: https://github.com/InfyOmLabs/core-templates/blob/develop/templates/scaffold/layouts/app.stub#L130

**Comment by john5db** [comment]
i am using adminlte template

**Comment by mgazelle** [comment]
Please add the following line around 145 in the app.blade.php file after the datatables script

<script src="https://cdn.datatables.net/buttons/1.0.3/js/buttons.colVis.js"></script>

**Comment by mitulgolakiya** [comment]
@john5db I tested it with latest version published app.blade.php and its working fine.
