### ISSUE TITLE
Datatables and --paginate

### ISSUE THREAD

**Issue by underdpt** [InfyOmLabs/laravel-generator#279]
Hi,

If you enable datatables and try to use --paginate cli option, the index view throws an exception:

> ErrorException in 92e0fbdd6dabebd3308bea8d08b7173992e5d066.php line 37: Undefined variable: empresas (View: D:\desarrollos\canaldenuncias\web\resources\views\admin\empresas\index.blade.php)

It seems it's trying to access the model variable, but that's not defined. 
Looking at index.blade.php i found this:
`        @include('core-templates::common.paginate', ['records' => $empresas])`

If I remove that line, the exception dissapears.

I think using --paginate with datatables should set the pagination option on the datatable service.
Thanks!

**Comment by underdpt** [comment]
I'm sorry this seems to be because an older template was published by my theme creator, and the template isn't synced with the latest updates from the package.
Once synced the templates, it seems to work correctly.

**Comment by karneaud** [comment]
I'm running into this problem....how did you solve it exactly????
