### ISSUE TITLE
Datatables: missing scripts

### ISSUE THREAD

**Issue by underdpt** [InfyOmLabs/laravel-generator#281]
Hi,

When generating scaffold with datatables, the package creates a table.blade.php like this:
```php
{!! $dataTable->table(['width' => '100%']) !!}

@section('scripts')
    <link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.0.3/css/buttons.dataTables.min.css">
    <script src="https://cdn.datatables.net/buttons/1.0.3/js/dataTables.buttons.min.js"></script>
    <script src="vendor/datatables/buttons.server-side.js"></script>
    {!! $dataTable->scripts() !!}
@endsection
```
In my case, it doesn't loads the buttons.server-side.js as it's missing a bar and tries to load it from the relative path of the url, which this time is "admin" but could be anything. To load it from the root path (public) it should be:
```php
    <script src="/vendor/datatables/buttons.server-side.js"></script>
```
or even better:
```php
    <script type="text/javascript" src="{{ asset('vendor/datatables/buttons.server-side.js') }}"></script>
```

I also updated datatables and buttons plugin to latest versions and removed autofill plugin (it's not used if i'm not mistaken). This is my final table.blade.php, for anyone with the same issue:
```php
{!! $dataTable->table(['width' => '100%']) !!}

@section('scripts')
    <link rel="stylesheet" href="//cdn.datatables.net/1.10.12/css/jquery.dataTables.min.css">
    <link rel="stylesheet" href="//cdn.datatables.net/buttons/1.2.2/css/buttons.dataTables.min.css">
    <script src="//cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js"></script>
    <script src="//cdn.datatables.net/buttons/1.2.2/js/dataTables.buttons.min.js"></script>
    <script type="text/javascript" src="{{ asset('vendor/datatables/buttons.server-side.js') }}"></script>
    {!! $dataTable->scripts() !!}
@endsection

```

**Comment by mitulgolakiya** [comment]
@underdpt great catch. What I realized is, this include scripts code is redundant that is added in every `table.blade.php`. so I have prepared separate partials for that CSS and js file and that will be included in a `table.blade.php`.

To test it, you need to re-publish your layouts.
