### ISSUE TITLE
labels are not generated for SELECT and RADIO

### ISSUE THREAD

**Issue by janbolat** [InfyOmLabs/laravel-generator#283]
Hello,
I am trying to generate `select` and `radio` buttons with labels from json file. But it doesn't generate labels. I even tried to use examples from fields_sample.json:
`{
        "name": "category_short",
        "dbType": "string",
        "htmlType": "select,Technology:tech,LifeStyle:ls,Education:edu,Games:game"
},
{
        "name": "author_gender",
        "dbType": "integer",
        "htmlType": "radio,Male:1,Female:0"
},`

It generates only values both for labels and values itself. Here is the screenshot:
![screenshot from 2016-09-01 11 48 13](https://cloud.githubusercontent.com/assets/6511056/18156704/03f7c994-703a-11e6-846d-3e449bd6b733.png)

This is a snippet from my json file:
`{
        "name": "finish_time",
        "dbType": "integer",
        "htmlType": "select,It is an emergency:0,Within 1 week:1,1-2 weeks:2,More than 2 weeks:3",
        "searchable": false,
        "fillable": true,
        "inForm": true,
        "inIndex": true
},`

**Comment by mitulgolakiya** [comment]
@janbolat fixed.
