### ISSUE TITLE
Who can explain me define $MODEL_NAME_CAMEL$ in php file stub 

### ISSUE THREAD

**Issue by thandonguocmo2020** [InfyOmLabs/laravel-generator#286]
help I need something like that in : 
\vendor\infyomlabs\laravel-generator\templates\scaffold\controller\controller.stub

         $theme = $this->gettheme();
         $name_set_magic$ = ucfirst($MODEL_NAME_CAMEL$);
        Theme::set$name_set_magic$($$MODEL_NAME_CAMEL$);

**Comment by motia** [comment]
PHP function names are case insensetive so you can just put:
`Theme::set$MODEL_NAME_CAMEL$($$MODEL_NAME_CAMEL$);`

Otherwise, Theme::set$MODEL_NAME$($$MODEL_NAME_CAMEL$); if your model names are TitleCased.
Or Theme::set$MODEL_NAME_HUMAN$ if they don't contain underscores.

**Comment by thandonguocmo2020** [comment]
Good.  Thank Your comment 

😊
