### ISSUE TITLE
examples

### ISSUE THREAD

**Issue by kirchaj** [InfyOmLabs/laravel-generator#289]
Does anyone have examples of the generator and what it produces?  Specifically, I am interested in how to implement the relationships and what it produces.  I am fairly new to laravel and documentation is a little slim for a newbie like me.  Seeing the end result would certainly help.

kirchaj

**Comment by Hayanno** [comment]
Same here ! An example on how to implements relationship (mtm in my case) would be amazing.

**Comment by mitulgolakiya** [comment]
closing in reference of https://github.com/InfyOmLabs/laravel-generator/issues/118
