### ISSUE TITLE
Question about prefix

### ISSUE THREAD

**Issue by phillipmadsen** [InfyOmLabs/laravel-generator#29]
A while back I  asked if you would be adding a prefix so one could build out normal crud and then build it again but with say and Admin prefix and it would prefix everything that is needed to make it work. such as routes/ links assets and anything else that would need to be changes. 
Ping pong generators has one that works great but they do not have a system built as good as this one. You said you were going to add this option. I  am just wondering if you have a status on that or if you are still going to do to. 

let me now thanks

**Comment by mitulgolakiya** [comment]
yes, I am already on it and will push it in next few days.

**Comment by phillipmadsen** [comment]
Thank you. if you would like I  can fork this and fix errors as I  find them and push them fixed back to you. might help you out a bit.

**Comment by phillipmadsen** [comment]
I  have also build a factory that autopopulates for the crud.

**Comment by mitulgolakiya** [comment]
sure. That will be great if you can push them.

**Comment by phillipmadsen** [comment]
Ok I  will do that for now on.

**Comment by phillipmadsen** [comment]
What is your status on the prefix?

Just wondering.

**Comment by mitulgolakiya** [comment]
I have just started working on it this week. May be will push it on this weekend.

**Comment by mitulgolakiya** [comment]
@phillipmadsen I just started working on prefix stuff. [here](https://github.com/InfyOmLabs/laravel-generator/commit/844d82591b1e47ea02eebf7eed8703224b742149) is the first commit I pushed about prefix. This commit also contains some major architectural changes. so doing some deep testing.

Meanwhile if you can do a testing for prefix on your side then it will help me to find out a bugs.

Use `prefix_option` branch for both `laravel-generator` and `core-templates`.

**Comment by mitulgolakiya** [comment]
Try to run command with `--prefix="admin"`. or any prefix.

**Comment by mitulgolakiya** [comment]
I have just merged this into master and closing this one.
