### ISSUE TITLE
Defaults value in database migration doesn't work (infyom:scaffold)

### ISSUE THREAD

**Issue by briano-jabico** [InfyOmLabs/laravel-generator#291]
Greetings,

I'm using the 5.3 command-line interface to generate a migration for a line_items table. I've got a few fields for which I'd like to add database defaults. This is something Laravel supports, and the InfyOm generator **almost** supports it.

Here's the command I'm running.
```bash
php artisan infyom:scaffold LineItem --fieldsFile=database/infyom-plans/LineItem.json --skip=controllers,repository,requests,scaffold_requests,routes,views,tests,menu
```

Here's an excerpt from that file.
```json
{"name": "name",         "dbType": "string",            "validations": "required", "inIndex": false},
{"name": "person_count", "dbType": "integer:default,1", "validations": "required|max:9999", "inIndex": false},
```

Here's an excerpt from what it's generating.
```php
$table->string('name');
$table->integer('person_count')->default(, 1);
```

Here's what I'd like it to be generating: no comma before the 1 in `->default(`
```php
$table->string('name');
$table->integer('person_count')->default(1);
```

I believe this is the reason: https://github.com/InfyOmLabs/laravel-generator/blob/5.3/src/Common/GeneratorField.php#L108-L110

And I believe this would fix it, though I'm not sure if it would impact anything else:
```php
$this->migrationText .= implode(', ', $inputParams);
```

Can you take a look?

Thanks!

**Comment by mitulgolakiya** [comment]
@briano-jabico Great catch. Yes, that would be a possible fix. Will fix it.

**Comment by mitulgolakiya** [comment]
@briano-jabico fixed.

**Comment by briano-jabico** [comment]
Sorry about being slow to get back to you; I've been involved in other things. I can confirm that the fix works. Thanks!
