### ISSUE TITLE
Ambiguous route for show action

### ISSUE THREAD

**Issue by underdpt** [InfyOmLabs/laravel-generator#292]
Hi,

The generated scaffold routes contais one route like:

`Route::get('admin/{empresas}', ['as'=> 'admin.empresas.show', 'uses' => 'EmpresaController@show']);`

That route makes it impossible to properly generate another model's scaffold, because it's main route would be:

`Route::get('admin/test', ['as'=> 'admin.test.index', 'uses' => 'TestController@index']);`

This route would generate an url like:

`http://project/admin/test`

But that url it's going to be processed by the admin.empresas.show route, using "test" as the id for the model to show.

I'm changing the prefix_routes.stub from:
`Route::get('$ROUTE_PREFIX$$MODEL_NAME_PLURAL_CAMEL$/{$MODEL_NAME_PLURAL_CAMEL$}', ['as'=> '$ROUTE_NAMED_PREFIX$$MODEL_NAME_PLURAL_CAMEL$.show', 'uses' => '$PATH_PREFIX$$MODEL_NAME$Controller@show']);`

To:
`Route::get('$ROUTE_PREFIX$$MODEL_NAME_PLURAL_CAMEL$/{$MODEL_NAME_PLURAL_CAMEL$}/show*, ['as'=> '$ROUTE_NAMED_PREFIX$$MODEL_NAME_PLURAL_CAMEL$.show', 'uses' => '$PATH_PREFIX$$MODEL_NAME$Controller@show']);`
(note the /show after the route).

**Comment by mitulgolakiya** [comment]
@underdpt I am not sure, how generator generated this route:

`Route::get('admin/{empresas}', ['as'=> 'admin.empresas.show', 'uses' => 'EmpresaController@show']);`

Because it always generates `resource`. Can you put some more information on this ?

**Comment by underdpt** [comment]
I see two stubs for routes:
```
prefix_routes.stub
routes.stub
```
The first one is being used on my project, I think because on the config file i have the route prefix set:

```php
    'prefixes' => [
        'route' => 'admin',  // using admin will create route('admin.?.index') type routes
        'path' => '',
        'view' => 'admin',  // using backend will create return view('backend.?.index') type the backend views directory
        'public' => '',
    ],
```

The second one is the one with the resource route, but that's not being use when generating the scaffold.

So it's not always using the resource, isn't it? Maybe that's the problem, we should adapt the prefix_routes.stub to use `resource`?
