### ISSUE TITLE
How to display image in datatables?

### ISSUE THREAD

**Issue by swash13** [InfyOmLabs/laravel-generator#293]
I need to display image in datatables. How to add <img> tag and display for example image of the post ?
That's what i mean:
https://gyazo.com/7766af3258367c0116421a157f64f424

**Comment by mitulgolakiya** [comment]
@swash13 you can do directly do it while generating files. You can generate your files with datatable then you need to do it manually.

You can find some reference here: https://datatables.net/forums/discussion/32924/is-it-possible-to-show-image-in-datatable

**Comment by swash13** [comment]
i can't find where to change it in generator ? Can you explain a little bit more?
