### ISSUE TITLE
Error Generating PDF Files

### ISSUE THREAD

**Issue by mgazelle** [InfyOmLabs/laravel-generator#299]
From all views when generating PDF files, an error occurs:

PHPExcel_Writer_Exception in DomPDF.php line 34:
Unable to load PDF Rendering library

Debugging the code it looks like the PHPExcel is looking for a file in the dompdf called dompdf_config.inc.php which is missing from the package and according to the versions of dompdf is not needed anymore

**Comment by marcoc1987** [comment]
i've the same issuse, it's solved?
I've spend many time with this provlem...

**Comment by reiter777** [comment]
you need to install this version of doom pdf "dompdf/dompdf": "0.6.2". then run composer update and thats it.

**Comment by VRuzhentsov** [comment]
@reiter777 This is not a solution, when using php 7.1 =(
They got another bug with php 7.1, and fixed it in "dompdf/dompdf": "0.8.0".

**Comment by devaescasio** [comment]
Hi,

I'm having the same problem, just like @VRuzhentsov mentioned that it is not a solution when using PHP 7.1. 
I need to use the php 7.1 due my app using the spatie/laravel-permission.
