### ISSUE TITLE
search

### ISSUE THREAD

**Issue by redmagi** [InfyOmLabs/laravel-generator#301]
i search by http://localhost/contents?search=2&searchFields=website_id
with ContentsRepository
`<?php

namespace App\Repositories;

use App\Models\Contents;
use InfyOm\Generator\Common\BaseRepository;

class ContentsRepository extends BaseRepository
{
    protected $fieldSearchable = [
        'title' => 'like',
        'website_id' => '=',
    ];

```
public function all($columns = array('*'))
{
    return $this->model->website()->get($columns);
}

public function model()
{
    return Contents::class;
}
```

}`

but no condition in sql like **select \* from `contents` where `contents`.`deleted_at` is null order by `sort` asc**

i try remove `
    public function all($columns = array('*'))
    {
        return $this->model->website()->get($columns);
    }`

sql is **select \* from `contents` where (`contents`.`website_id` = '2') and `contents`.`deleted_at` is null order by `sort` asc**

now can filter content.

why genrate function  public function all? it can make side effect?

**Comment by mitulgolakiya** [comment]
we do not generate `all` function in the latest code.
