### ISSUE TITLE
What is colvis at DataTable?

### ISSUE THREAD

**Issue by betoflakes** [InfyOmLabs/laravel-generator#302]
My datatables wasn't working, so re-create and re-create the api scaffolding, so I copied the previous version of laravel generator and it worked, so then I found the parameter 'colvis' create the error that not allow load the datatable.

What is the functionality? Or I needed to remove before to load the table? Is was just me?

```php
public function html()
    {
        return $this->builder()
            ->columns($this->getColumns())
            ->addAction(['width' => '10%'])
            ->ajax('')
            ->parameters([
                'dom' => 'Bfrtip',
                'scrollX' => false,
                'buttons' => [
                    'print',
                    'reset',
                    'reload',
                    [
                         'extend'  => 'collection',
                         'text'    => '<i class="fa fa-download"></i> Export',
                         'buttons' => [
                             'csv',
                             'excel',
                             'pdf',
                         ],
                    ],
                    'colvis' //This create an error and not allow create datatable, so what is it?
                ]
            ]);
}
```

**Comment by mitulgolakiya** [comment]
@betoflakes you can find more information here: https://datatables.net/reference/button/colvis

And try to use the latest version of a generator and re-publish your layout with the backup of an original one. It should work. Maybe you are missing the script files of colvis which is introduced in a new version.

**Comment by betoflakes** [comment]
Thank you, man. I will do more research about it.
