### ISSUE TITLE
Images in datatable

### ISSUE THREAD

**Issue by swash13** [InfyOmLabs/laravel-generator#303]
Hello, i've already asked this question and i get a link here:
https://datatables.net/forums/discussion/32924/is-it-possible-to-show-image-in-datatable

But i still can't understand where to change this in generator ?
I will be very thankfully to get more details and what steps i should do. Thank you.

**Comment by mitulgolakiya** [comment]
@swash13 You can use render function in columns definition to display image.

Support you have a Post model which has 3 fields,

- Title
- Image
- Body

And Image contains some url. Then you can use render function for Image field. Goto your generated `PostDataTable.php` file and find `getColumns()` function.

There you can use something like following,

```
return [
    'title' => ['name' => 'title', 'data' => 'title'],
    'image' => ['name' => 'image', 'data' => 'image', 'render' => '"<img src=\""+data+"\" height=\"50\"/>"'],
    'body' => ['name' => 'body', 'data' => 'body']
];
```

Let me know if this helps. I am going to write a full article on the blog which is coming soon in a few days.

**Comment by swash13** [comment]
Almost helps. Let me explain the situation.
I'm saving images in database without path, just "image.jpg" for example.
And the path is /uploads/companies/{company_id}/"image.jpg".
With you example i can't get company_id field. Thanks for your advice.
