### ISSUE TITLE
fields file in config not being used. 

### ISSUE THREAD

**Issue by madsynn** [InfyOmLabs/laravel-generator#309]
if the the path in the config is being used for the fields file we should not need to put absolute path we should be able to just use something like this. 

php artisan infyom:api_scaffold User  --fieldsFile='User.json' 

**instead of**

php artisan infyom:api_scaffold User  --fieldsFile='resources/model_schemas/User.json'

**Comment by mitulgolakiya** [comment]
@madsynn nice idea. I will work to support JSON files directly from configured model_schema directory.

**Comment by mitulgolakiya** [comment]
@madsynn Support added to directly specify schema file from schema directory.
