### ISSUE TITLE
relations not working

### ISSUE THREAD

**Issue by madsynn** [InfyOmLabs/laravel-generator#310]
php artisan infyom:scaffold Account --relations

doesnt work.

**Comment by mitulgolakiya** [comment]
@madsynn Can you post some more details ?

**Comment by phillipmadsen** [comment]
@mitulgolakiya 

when i enter the following command into the console it does not work. 
> php artisan infyom:scaffold Account --relations

It returns --relations is not a command

**Comment by mitulgolakiya** [comment]
Not able to reproduce in the latest version.
