### ISSUE TITLE
API Version defined in configuration is not being used

### ISSUE THREAD

**Issue by ton212** [InfyOmLabs/laravel-generator#311]
Hello

I just setup laravel-generator with `api_prefix = 'api'` and `api_version = 'v1'`. But when I run `php artisan infyom:api_scaffold Test` the `TestAPIController` is placed directly in  `app/Http/Controllers/API/` without separate namespace for each version, and also the route registed by the package is not has `v1` prefix too.

I this normal or it's has something to do with my configuration?

Thank you

**Comment by mitulgolakiya** [comment]
The normal procedure is, you have to set `api_prefix` and `api_version` while setting up generator. so it will take values from there and will create a group in `routes.php` in which `api_routes.php` will be included, something like following:

```
Route::group(['prefix' => 'api', 'namespace' => 'API'], function () {
    Route::group(['prefix' => 'v1'], function () {
        require config('infyom.laravel_generator.path.api_routes');
    });
});
```

so then those values will be always used as your prefix and namespace. It does not load dynamically when you call APIs or you generate files.

**Comment by ton212** [comment]
I use the latest version of plugin with Laravel 5.4, so there is no `routes.php` but `routes/api.php`. When I generate an API via console the routes automatically added to `api.php` then I'll have to move it in to a route group manually?

**Comment by mitulgolakiya** [comment]
@ton212 Laravel 5.4 ? Or 5.3 ? Because 5.4 is not yet supported.

**Comment by ton212** [comment]
My mistake, I mean 5.3

**Comment by mitulgolakiya** [comment]
@ton212 you can refer docs for 5.3 installation here: http://labs.infyom.com/laravelgenerator/docs/5.3/installation

There are some additional edits required to work with it 5.3.

**Comment by ton212** [comment]
I did all the steps, but the route group is never generates by the package, and API version too.

**Comment by mitulgolakiya** [comment]
In Laravel 5.3 api.php file already exist and already included by laravel. so its not generated and its not needed.

**Comment by mitulgolakiya** [comment]
your generated routes will be automatically added to `routes/api.php`.

**Comment by ton212** [comment]
That right for the `api/` prefix but the API version defined in plugin configuration is not added to the route.

So I have to put it in manually right?

**Comment by mitulgolakiya** [comment]
yes

**Comment by ton212** [comment]
OK then.

Will it be an update to this in the future release of the plugin? (Just curious for how API version in config file works in the plugin)

Best regards,
Tonsai Singhkangwan
