### ISSUE TITLE
Datatables, wrong colvis button

### ISSUE THREAD

**Issue by Germanaz0** [InfyOmLabs/laravel-generator#315]
On template datatable.stub, there is a "Colvis" button, it has been retired from datatables extension and throws an error while rendering the datatable.

I had to comment that line which mentions colvis.

Reference: https://datatables.net/extensions/colvis/

**Comment by mitulgolakiya** [comment]
@Germanaz0 colvis is completely working fine for me and other users. Can you post some more details about your layout files and generated view files and the error you are getting ?

**Comment by mitulgolakiya** [comment]
@Germanaz0 colvis is retried, and we are using buttons project https://datatables.net/extensions/buttons/ and from there we are using colvis button plugin from buttons https://datatables.net/extensions/buttons/examples/column_visibility/index.html.
