### ISSUE TITLE
Can't skip relations

### ISSUE THREAD

**Issue by naquiuddin** [InfyOmLabs/laravel-generator#318]
I am trying to skip relationship for a field, but for some reason it is throwing error. Can't we skip relations for few fields?

```
$ php artisan infyom:scaffold Org --save --relations
Specify fields for the model (skip id & timestamp fields, we will add it automatically)
Read docs carefully to specify field inputs)
Enter "exit" to finish

 Field: (name db_type html_type options) []:
 > place_id string text s,if

 Enter validations:  []:
 > required|max:255

 Enter relationship (Leave Black to skip): []:
 >



 [ERROR] A value is required.


 Enter relationship (Leave Black to skip): []:
 >
```

**Comment by mitulgolakiya** [comment]
@naquiuddin which version of laravel and laravel generator version you are using ?

**Comment by naquiuddin** [comment]
Hey @mitulgolakiya ,

Here is my composer.json config

```
 "require": {
        "php": ">=5.6.4",
        "laravel/framework": "5.3.*",
        "yajra/laravel-datatables-oracle": "~6.0",
        "barryvdh/laravel-ide-helper": "^2.1",
        "infyomlabs/laravel-generator": "5.3.x-dev",
        "laravelcollective/html": "dev-master",
        "jlapp/swaggervel": "dev-master",
        "infyomlabs/adminlte-templates": "5.3.x-dev",
        "doctrine/dbal": "~2.3"
    },
```

**Comment by mitulgolakiya** [comment]
@naquiuddin fixed. please test again.

**Comment by apeh1706** [comment]
i'm using this version 

  "require": {
        "php": ">=7.0.0",
        "fideloper/proxy": "~3.3",
        "laravel/framework": "5.5.*",
        "laravel/tinker": "~1.0",
        "infyomlabs/laravel-generator": "5.5.x-dev",
        "laravelcollective/html": "^5.5.0",
        "infyomlabs/adminlte-templates": "5.5.x-dev",
        "infyomlabs/swagger-generator": "dev-master",
        "appointer/swaggervel": "dev-master",
        "doctrine/dbal": "~2.3"

and it seem can't skip the relation too ... 
please help me
