### ISSUE TITLE
How can add checkbox with the datatable

### ISSUE THREAD

**Issue by al-ani** [InfyOmLabs/laravel-generator#327]
I went to add checkbox to the data table like this
(the link was not working, now it is work) 
[https://datatables.net/extensions/select/examples/initialisation/checkbox.html](https://datatables.net/extensions/select/examples/initialisation/checkbox.html)
can the generator add Checkbox or I should add manually, and if I should I add manually how can I do that ?

**Comment by mitulgolakiya** [comment]
maybe more of the question for yajra datatable repo, but I would suggest you define the custom column in `ModelDatatable.php` just like we do for Action column.
