### ISSUE TITLE
Login / Registration, Terms checkbox

### ISSUE THREAD

**Issue by gsc89** [InfyOmLabs/laravel-generator#328]
Checkbox on Chrome / IE is invisible on the login and registration pages, see below.

![image](https://cloud.githubusercontent.com/assets/1032459/19306911/cbaa8044-906f-11e6-8435-d3b1790cb3a3.png)

**Comment by ShaileshLadumoR** [comment]
add this link <link rel="stylesheet" href="https://rawgit.com/fronteed/iCheck/1.x/skins/all.css">

**Comment by paulheijman** [comment]
Add the following stylesheet to the views with missing checkboxes:
`<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/iCheck/1.0.2/skins/square/_all.css">`

**Comment by mitulgolakiya** [comment]
@paulheijman great catch. just added it in adminlte-templates repo.
