### ISSUE TITLE
dataTables column value if not found

### ISSUE THREAD

**Issue by swash13** [InfyOmLabs/laravel-generator#329]
Good day. How to make in dataTables default value if not found.
For example i have UsersDataTable where i have ['name' => 'company_id', 'data' => 'company.name'].
When i delete company with force delete i set company_id to null and datatable cause error.
I need to do something like this but with datatable, not php $company ? $company->name : 'No company'

**Comment by mitulgolakiya** [comment]
@swash13 If I'm not wrong and understand it correctly, you have a relationship `company` on User record. so better you create mutate attribute, something like `company_name` directly on User model where you can check `$user->company ? $user->company->name : 'No company'` and then user that attribute as a value in datatable.
