### ISSUE TITLE
Broken Model & Migration Generation

### ISSUE THREAD

**Issue by phillipmadsen** [InfyOmLabs/laravel-generator#331]
## NEEDS FIX IN 5.1 BRANCH

**USING THE FOLLOWING COMMAND**

> php artisan infyom:api_scaffold Dealer --fieldsFile='resources/model_schemas/Dealer.json'
- [ ] OUTPUT MODEL  https://gist.github.com/phillipmadsen/1a83e1d7f29b61d3a7959f5c73729575
- [ ] OUTPUT MIGRATION  https://gist.github.com/phillipmadsen/7e5145c907f8c556473c1e01370cca16

**The parts that need to be fixed are as follows.**

| CURRENT | FIXED |
| --- | --- |
| $table->string('id'); | $table->increments('id'); |
| $table->integer('location_id')->unsigned(); | $table->unsignedInteger('location_id')->index(); |
| $table->foreign('location_id')->references('id')->on('locations'); | $table->foreign('location_id')->references('id')->on('locations')->onUpdate('cascade')->onDelete('cascade'); |
| NEEDS ENGINE | $table->engine = 'InnoDB'; |

**AFTER CHANGES OUTPUT OF MIGRATION WOULD BE:**

```
    public function up()
    {
        Schema::create('dealers', function (Blueprint $table) {
           $table->increments('id');
            $table->string('dealer');
            $table->string('contact_person')->nullable();
            $table->string('mobile')->nullable();
            $table->string('phone')->nullable();
            $table->string('hours_opening_mf')->nullable();
            $table->string('hours_closing_mf')->nullable();
            $table->string('hours_opening_sat')->nullable();
            $table->string('hours_closing_sat')->nullable();
            $table->string('hours_opening_sun')->nullable();
            $table->string('hours_closing_sun')->nullable();
            $table->string('company_phone')->nullable();
            $table->string('toll_free')->nullable();
            $table->string('public_email')->nullable();
            $table->string('support_email')->nullable();
            $table->unsignedInteger('location_id')->index();
            $table->softDeletes();
            $table->engine = 'InnoDB';
            $table->foreign('location_id')->references('id')->on('locations')->onUpdate('cascade')->onDelete('cascade');
        });
    }
```

**Comment by phillipmadsen** [comment]
Just got to the fields file and it only generated the foreign key input.  guess there is a problem here also. ill look into it and get back to you.

**Comment by phillipmadsen** [comment]
Ok the table generated has no fields or headers in it.

**Comment by phillipmadsen** [comment]
What file generates the headers and cells for the table and i will look into it?

**Comment by mitulgolakiya** [comment]
Working fine with the latest code.
