### ISSUE TITLE
--fromTable and *_at field

### ISSUE THREAD

**Issue by cgarnier** [InfyOmLabs/laravel-generator#340]
Hello,
Using fromTable option with a table with no _at fileds cause issues when adding, removing items with the api.
Maybe i miss something in the configuration.

Is it possible to add a generator to create the necessary migrations scripts that will add the datetime fields ?

**Comment by sickhack** [comment]
try settings for Timestamp Fields from config/infyom/laravel_generator.php

**Comment by mitulgolakiya** [comment]
@cgarnier you can enable or disable timestamps fields based on your table definition and can change the name of fields as well in `config/infyom/laravel_generator.php`.
