### ISSUE TITLE
Swagger? How? cmd?

### ISSUE THREAD

**Issue by phillipmadsen** [InfyOmLabs/laravel-generator#343]
Swagger

After adding packages, run the following command: { no command ???}

You can also generate swagger annotations for your apis. swagger option is false by default and can be enabled from config. set 
'add_on.swagger' => true.

**Comment by phillipmadsen** [comment]
What is the command to generate the swagger docs and what are the paths to it?

**Comment by phillipmadsen** [comment]
From Swagervel Site:

Installation

Add Jlapp\Swaggervel\SwaggervelServiceProvider to your providers array in app/config/app.php above your route provider, to avoid any catch-all routes

Run php artisan vendor:publish to push swagger-ui to your public folder.

> The second part does not add the swagger-ui to the public path???

**Comment by raarts** [comment]
I have the same problem. What is the command to generate the swagger docs?

**Comment by raarts** [comment]
I found it, the api docs are in /api/docs

**Comment by mitulgolakiya** [comment]
@phillipmadsen @raarts its already in their installation steps. You need to open /api/docs url.
https://github.com/slampenny/Swaggervel#example

**Comment by gelinger777** [comment]
@mitulgolakiya  sorry to reopen this issue, but it's very interrelated question. Could you please descibe me how to regenerate the json file which comes at myproject.com/docs ? 
I have added a custom parameter in API controller and have marked up  extra parameter 


 ```
 *      @SWG\Parameter(
     *         name="my-key",
     *         in="header",
     *         description="Token for every request in header",
     *         required=true,
     *         type="string",
     *     ),
```


but it did not come to the json file.

**Comment by gelinger777** [comment]
ok, apparently you have to remove the api-docs.json  file from /storage/docs/ and it will be regenerated automatically. If somebody needs.
