### ISSUE TITLE
How to export only selected rows in datatables

### ISSUE THREAD

**Issue by swash13** [InfyOmLabs/laravel-generator#345]
How to export only selected rows in datatables ?

I have for example 20 rows, but i need to export to excel file only 5. How to do this ?
Also how to export relations ?
For example, i need to export selected orders with details list in each order

**Comment by mitulgolakiya** [comment]
maybe this can help. https://datatables.net/extensions/buttons/examples/print/select.html

But there is an open issue in yajra, which says, it's not yet supported.
https://github.com/yajra/laravel-datatables/issues/829

**Comment by rraadd88** [comment]
Hi, I could not locate the example for the demo: https://datatables.net/extensions/buttons/examples/print/select.html on github repos of datatables.
I found most of the other demos in the github repo and they are very helpful.
Does the example for [Export options - row selector](https://datatables.net/extensions/buttons/examples/print/select.html) or [Select integration - export selected rows](https://datatables.net/extensions/buttons/examples/initialisation/select.html) not exist on github or I am not trying hard enough? 

(Ideally it would be handy if the links to the example files (hosted on github) show up on the datatables docs pages.)
