### ISSUE TITLE
Update migration.stub  [ case of model name with an underscore "_" ]

### ISSUE THREAD

**Issue by aboidriss** [InfyOmLabs/laravel-generator#347]
Hi,
When generating my model that contains an underscore : "author_book" , the generator generated the migration class with the name : "class Createauthor_booksTable extends Migration "
And when migrating , "php artisan migrate" , i got this error : 

  [Symfony\Component\Debug\Exception\FatalErrorException]
  Class 'CreateAuthorBooksTable' not found

My solution was the modification of migration.stub variable : 
$MODEL_NAME_PLURAL$ to $MODEL_NAME_PLURAL_CAMEL$
which gives : CreateauthorBooksTable and solves the problem.
So i ask the repos owner to add that change, or if there is a way to get "CreateAuthorBooksTable" in stead of "CreateauthorBooksTable" it will be better.

**Comment by mitulgolakiya** [comment]
@aboidriss I think underscore in the model name is not a good choice. As per best practices, you should pass the model name as `AuthorBook` and then everything should work fine. Still, it's up to you as I do not have a proper idea why you need underscore in the class name.
