### ISSUE TITLE
Unknown database type json requested, Doctrine\DBAL\Platforms\MySQL57Platform may not support it.

### ISSUE THREAD

**Issue by hendra1** [InfyOmLabs/laravel-generator#348]
Hi 
I'm trying to scafold from existing schema.
I'm using Mysql 5.7 which using json type field.
But found an error while trying to scafold

`Unknown database type json requested, Doctrine\DBAL\Platforms\MySQL57Platform may not support it.`

Is there any solution?

Thanks

**Comment by minkbear** [comment]
got same here

**Comment by minkbear** [comment]
just add below in `vendor\infyomlabs\laravel-generator\src\Utils\TableFieldsGenerator.php`

```php
$platform = $this->schemaManager->getDatabasePlatform();
$platform->registerDoctrineTypeMapping('enum', 'string');

// Add this line.
$platform->registerDoctrineTypeMapping('json', 'string');
```

The error is gone.

**Comment by mitulgolakiya** [comment]
@minkbear I think we should use `text` instead of `string`, because it can be a long string.
I will add it and push it soon.
