### ISSUE TITLE
Add to schema file and generator

### ISSUE THREAD

**Issue by phillipmadsen** [InfyOmLabs/laravel-generator#35]
This is the current data for a field:

{
    "fieldInput": "id:increments",
    "htmlType": "",
    "validations": "",
    "searchable": false,
    "fillable": false,
    "primary": true
  },

**When using a crud with many fields we need to add a way to  include and exclude from the index.blade.php page in the table.blade.php output.**  

This is what it needs. 

{
    "fieldInput": "id:increments",
    "htmlType": "",
    "validations": "",
    "incInIndexTable": "false",  // THIS IS TO IDENTIFY THE FIELDS TO ADD THE THE TABLE OUTPUT
    "searchable": false,
    "fillable": false,
    "primary": true
  },

Also another type that would be very useful is boolean checkbox. right now you have checkbox group but not just a normal checkbox. 

Something along the lines of this:

{
    "fieldInput": "checkbox_test:boolean",
    "htmlType": "default:Checked"
  },

Anyway keep up the awesome work you are great.

**Comment by mitulgolakiya** [comment]
This thing is already on list. We are going add an option to IncludeInForm, IncludeInList etc.

**Comment by mitulgolakiya** [comment]
support added for `inForm` and `inIndex` params in schema file.

Check the latest json file schema here: https://github.com/InfyOmLabs/laravel-generator/blob/master/samples/fields_sample.json

**Comment by vesper8** [comment]
How can I have created_at, updated_at and deleted_at not added to forms if I am generating my scaffolding from existing tables ?
