### ISSUE TITLE
Translate datatable

### ISSUE THREAD

**Issue by marcoc1987** [InfyOmLabs/laravel-generator#351]
Hello.
I've traslated all fields, but i can't translate:
- Column visibility
- Search 
- Action
on datatables. Where i can modify this translations?

**Comment by mitulgolakiya** [comment]
https://github.com/yajra/laravel-datatables/issues/557

**Comment by ShaileshInfyom** [comment]
@marcoc1987 

Yes, you can modify those translations.
* For Action

Open Data Table class which is generated by generator. for eg. NewsDataTable
now you can see one method is  `public function html()`
you can set title like 
`->addAction(['width' => '10%', 'title' => 'Action'])`

* For Column visibility & Search
it's managed by datatabel. so you can check here https://github.com/yajra/laravel-datatables/issues/557
