### ISSUE TITLE
new Feature Request 

### ISSUE THREAD

**Issue by phillipmadsen** [InfyOmLabs/laravel-generator#352]
We need to add a option to the fieldsFile for <small></small> in the fields for notes about the input

> Here is a couple examples:

```html
<!-- $FIELD_NAME_TITLE$ Field -->
<div class="form-group col-sm-6 {{ $errors->has('$FIELD_NAME$')? 'has-error' : '' }}">
    {!! Form::label('$FIELD_NAME$', '$FIELD_NAME_TITLE$:', ['class' => 'control-label']) !!}
    {!! Form::text('$FIELD_NAME$', null, ['class' => 'form-control', 'value' => old('$FIELD_NAME$')]) !!}
    {!! $errors->has('$FIELD_NAME$')? '<p class="help-block"> '.$errors->first('$FIELD_NAME$').' </p>':'' !!}
    <small>This is a note about the input </small>
</div>

<!-- $FIELD_NAME_TITLE$ Field -->
<div class="form-group {{ $errors->has('$FIELD_NAME$')? 'has-error' : '' }}">
    {!! Form::label('$FIELD_NAME$', '$FIELD_NAME_TITLE$:', ['class' => 'col-sm-3 control-label']) !!}
    <div class="col-sm-7">
    {!! Form::text('$FIELD_NAME$', null, ['class' => 'form-control', 'value' => old('$FIELD_NAME$')]) !!}
    <small>This is a note about the input </small>
    </div>
    {!! $errors->has('$FIELD_NAME$')? '<p class="help-block"> '.$errors->first('$FIELD_NAME$').' </p>':'' !!}
</div>
```
![bare start bootstrap template](https://cloud.githubusercontent.com/assets/7799233/20815388/ede7cb16-b7da-11e6-8b8a-1cf07da09044.png)

**Comment by devaescasio** [comment]
Hi @mitulgolakiya,

Any update regarding this?  When passed to BaseRepository the old() doesn't work anymore. or we just skip the Repository during scaffold?

Thanks

**Comment by mitulgolakiya** [comment]
@devaescasio not yet. I will check it soon and will get back to you.

**Comment by mitulgolakiya** [comment]
@phillipmadsen @aescasiodev This small note is user specific thing. Maybe everybody does not like it. I will leave it to the user, if they want something like that, then they can customize templates. Also, we do not use `old` method anywhere, so it's even fine.
