### ISSUE TITLE
please don't let this project die :(

### ISSUE THREAD

**Issue by vesper8** [InfyOmLabs/laravel-generator#354]
give us an update at least.. or better yet.. come back and show this otherwise awesome and super popular project some love!!!! 4 commits in the last 2 months makes me very sad.. this project has so much promise.. it kicks the butt of any other laravel crud generator out there! please come back and tag a new stable release for Christmas!! :))

**Comment by mitulgolakiya** [comment]
Thanks, @vesper8, Actually since last two months, I'm extremely busy with client stuff and also we have new year holidays, so didn't got time for it.

But I'm trying to focus on it and have a new stable version out by end of this month.

**Comment by vesper8** [comment]
@mitulgolakiya will you be giving this awesome project any love soon? it's still the best CRUD generator out there in my opinion.. but it needs some love!

**Comment by mitulgolakiya** [comment]
@vesper8 I know, but I am extremely busy with my other stuff, so not getting even an hour for other projects. But I am planning to get some time for it.
