### ISSUE TITLE
cannot customize templates/model/model.stub

### ISSUE THREAD

**Issue by vesper8** [InfyOmLabs/laravel-generator#355]
Getting a very odd error when I try to customize model.stub

I have been successful in making customizations to many other stubs by publishing the templates and then deleting the ones I don't need to customize and only keeping the stubs that have customizations. All of this works fine. Except it doesn't work for the model.stub

To give you an idea... just the existence of the ORIGINAL UNMODIFIED model.stub file will cause

php artisan infyom:model MyModel -n --fromTable --tableName=myTable

to horribly fail. It produces a MyModel.php like this:

```
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

<?php

namespace App\Models;

use Eloquent as Model;
$SOFT_DELETE_IMPORT$
$DOCS$
class MyModel extends Model
{
$SOFT_DELETE$
    public $table = 'myTable';
    
    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';

$SOFT_DELETE_DATES$

    public $fillable = [
        'description'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'description' => 'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        
    ];

    
}

class MyModel extends Model
{
    use SoftDeletes;

    public $table = 'myTable';
    
    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';


    protected $dates = ['deleted_at'];


    public $fillable = [
        'description',
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'description' => 'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        
    ];

    
}
```

If I made a modification to the model.stub inside the vendor folder however all is fine.

So why is this happening? Why does the presence of the unmodified original model.stub file inside my published templates folder cause this to happen? Maybe because I am obliged to include other stubs in the published templates folder even though they are unmodified?

I thought this might be the case so I performed this test with a completely unaltered published templates folder (no modifications whatsoever after infyom.publish:templates

And the same error occurs if I try to generate a new model

**Comment by skinpixel** [comment]
It would seem that $DOCS$ on the model is calling it's self, removing this is a simple solution, just use you doc block in the file instead.

**Comment by mitulgolakiya** [comment]
I tested it with the latest code and it works fine.
