### ISSUE TITLE
Allow nullable field in Migrations

### ISSUE THREAD

**Issue by perezale** [InfyOmLabs/laravel-generator#358]
Hi, I'm wondering if it could be possible to add support for nullable fields, as Laravel Migrations do support them.

I'm currently working on a fix for this, considering an empty $validations = ''.
If it's empty then it's not required. Therefore, it should be a nullable field.

I'll be sending a PR as soon as I get this done.

**Comment by perezale** [comment]
Ohh... sorry, this section http://labs.infyom.com/laravelgenerator/docs/5.3/getting-started#field-inputs is clear enough.

**Comment by timoteo7** [comment]
"fieldInput": "finality:string,30:nullable"
