### ISSUE TITLE
skip repository

### ISSUE THREAD

**Issue by disitec** [InfyOmLabs/laravel-generator#359]
¿Is there a way to skip the creation of the repository file? I am using my custom controller stub that does not use it.

Thank you.

**Comment by mitulgolakiya** [comment]
@disitec currently there is no way to generate controller without a repository, but if you want to do something like that, you can [publish templates](http://labs.infyom.com/laravelgenerator/docs/5.3/publish-templates) and create your own templates of controllers and then use generator. But still, it will create repository files, that you can easily delete.
