### ISSUE TITLE
with multiple relations on search query

### ISSUE THREAD

**Issue by vijaythecoder** [InfyOmLabs/laravel-generator#360]
I tried to find docs, source code and issues but no luck. Is there an option to get the results with multiple relations?
http://api.example.dev/api/orders?with=employee,customer ? it works great with single relation.
if this is not available yet? can you please let me know the place of the source file? I will try to tweak and contribute

**Comment by mitulgolakiya** [comment]
@vijaythecoder I think you should pass it something like http://api.example.dev/api/orders?with=employee;customer
