### ISSUE TITLE
Proposal -- Add https://vuetifyjs.com

### ISSUE THREAD

**Issue by betoflakes** [InfyOmLabs/laravel-generator#361]
It will be interesting add this theme template to the generator.

**Comment by farhanali-kathawala** [comment]
Reference : #171

**Comment by ajayinfyom** [comment]
We are not maintaining VueJs Generator in this package from last few versions.

**Comment by mitulgolakiya** [comment]
In the latest version, we have given the support to customize templates. so you can publish the templates and customize the way you want as per your need to a theme.

so if anyone interested in this, then he can develop his own packages as well for these templates.
