### ISSUE TITLE
when scaffolding the wrong namespace is applied (App instead of my own defined)

### ISSUE THREAD

**Issue by Jossnaz** [InfyOmLabs/laravel-generator#367]
```

ReflectionException in Container.php line 749:
Class Caup\Http\Controllers\Admin\TagController does not exist

```

because the controller is defined in the namespace `App` which is wrong and was not like that earlier.

i installed it today!

**Comment by mitulgolakiya** [comment]
@Jossnaz its already part of installation steps. http://labs.infyom.com/laravelgenerator/docs/5.3/installation#customize-configuration
