### ISSUE TITLE
Problem with uppercase

### ISSUE THREAD

**Issue by ddiaz427** [InfyOmLabs/laravel-generator#372]
Hi.

I am making an APP on a DB with tables names and fields name are in UPPERCASE, But I am having problems with the lib. For example:

php artisan infyom:scaffold predialUsos --primary=id --datatables=true  --fromTable --tableName=PRED_TR_USOS

but the list and the update did not works, because the filedsname are in uppercase and the lib does not read correctly.

Is there some option or config to handler uppercase 

Thanks for your time.

**Comment by vishalinfyom** [comment]
> --datatables=true

@ddiaz427 make sure you have `yajra/laravel-datatables` installed into your project. you can find more details at : http://labs.infyom.com/laravelgenerator/docs/5.8/generator-options#datatables

**Comment by mitulgolakiya** [comment]
@ddiaz427 not sure if you figured this out, but the way laravel work is in snake_case, and maybe that's the thing which is creating a problem.

If you still have a problem then share some more details and I can try to look into it.
