### ISSUE TITLE
Scaffold does not generate a proper create view-textareas for fields missing

### ISSUE THREAD

**Issue by twoheadedmona** [InfyOmLabs/laravel-generator#373]
Hello, 

I just tried this platform out and encountered a small issue. 
When running the command php artisan infyom:api_scaffold Model the view for create is not completely generated, the textareas for every field in the Model is not generated. I assume there should be a text field for every field in the Model. 
I hope you fix this issue. 

Have a nice day

**Comment by farhanali-kathawala** [comment]
![InfyOm Generator 3-12-2019 4-59-19 PM](https://user-images.githubusercontent.com/37834439/54196908-94240200-44e8-11e9-9964-7f9b48e68dfa.png)

@twoheadedmona have you followed the given format here . http://labs.infyom.com/laravelgenerator/docs/5.8/getting-started#generator-inputs
 If so, then it will be work perfectly

**Comment by mitulgolakiya** [comment]
@twoheadedmona if the problem persists then share some more details with fields or generated files and re-open the issue.
