### ISSUE TITLE
Migration option or new default

### ISSUE THREAD

**Issue by phillipmadsen** [InfyOmLabs/laravel-generator#374]
We should either make these the default or make it an option. 

$table->engine = 'InnoDB';
$table->timestamp('updated_at')->useCurrent();
$table->timestamp('created_at')->useCurrent();

**Comment by mitulgolakiya** [comment]
@phillipmadsen I don't this is a general requirement. If a user wants to do this, it's always possible by changing the template. so would leave it to a user.
