### ISSUE TITLE
Package features

### ISSUE THREAD

**Issue by joskfg** [InfyOmLabs/laravel-generator#377]
Hello,

I'm testing this generator and I had a few doubs:

1. Is it possible to generate nested resources? I tried and I allways got first level resources. Laravel support nested resources but I don't see them in the generator. Do you have some example?
2. Are you planning to improve the generator to allow the developers to generate a complete CRUD API using a documentation input like Swagger2.0? Is it possible to implement it?
3. Is it possible to use something else apart from Eloquent to act like a datasource? I saw the model_extend_class option but didn't find too much documentation about it.

Thanks!

**Comment by mitulgolakiya** [comment]
1. Prefix option can be used to generated nested resources.
2. It can be a good idea but can not commit anything on the timeline. maybe someone from the community can do it and then put a PR.
3. I'm not much clear about what you are asking here related to datasource. If you need something like that, then publish templates and customize that where you can pass some datasource and your views can utilize that.
