### ISSUE TITLE
backslash gets saved as double backslash

### ISSUE THREAD

**Issue by Jossnaz** [InfyOmLabs/laravel-generator#378]
see here:

http://stackoverflow.com/questions/41992092/slash-gets-saved-as-double-backslash-in-laravel-5-3-eloquent

or in text

i have this string

`Caup\Mail\ChooseCauseNowReminderMail`
it gets saved in the database as

`Caup\\Mail\\ChooseCauseNowReminderMail`
if i save it again, it even adds more back slashes. So a backslash gets replaced with double back slash, and on each save, more back slashes are added how can i avoid this?

**Comment by pazDontExist** [comment]
same problem here...

**Comment by mitulgolakiya** [comment]
@Jossnaz @pazDontExist maybe you figured it out, but this is not generated the related issue. I think your problem is related to string. I think you can make some hack by switching from `{{ }}` to `{!! !!}` or vice versa.

**Comment by Jossnaz** [comment]
think it might have been related to me using laravel with wordpress
