### ISSUE TITLE
When publishing views stubs are not moved like they used to be. 

### ISSUE THREAD

**Issue by phillipmadsen** [InfyOmLabs/laravel-generator#38]
**infyom.publish:templates**  is not copying the views stubs into the resources directory. The old system used to is there a reason for this or just simply overlooked?

**Comment by john5db** [comment]
I also want to change default views stubs. It is must.

**Comment by Trexology** [comment]
Same issue here. Seems to be a bug

**Comment by iboinas** [comment]
you can copy them by hand, and they will work

**Comment by iboinas** [comment]
they will be used, check the source code

**Comment by mitulgolakiya** [comment]
Fixed.
