### ISSUE TITLE
Support for Laravel 5.4

### ISSUE THREAD

**Issue by gandra** [InfyOmLabs/laravel-generator#382]
Great Job!
Sorry for posting here do not know for other option. You can mark it as feature eventually.

I am wondering when will be support for LAravel 5.4.
Accordiong to the [documentation](http://labs.infyom.com/laravelgenerator/docs/5.3/introduction) supported laravel versions are 5.1, 5.2 & 5.3.

**Comment by whereisjefe** [comment]
been on 5.4 for about 2 weeks and i have not had any problems

**Comment by hkarvasonis** [comment]
I used that on Laravel 5.4 and i get an error on BaseRepository about the getForeignKey() function that needs to be replaced by the getQualifiedForeignKeyName() function.

**Comment by reiter777** [comment]
@hkarvasonis are you still having the same problem? been working on 5.4 for 3 weeks and its ok

**Comment by AlexKR** [comment]
ApiTestTrait is also broken for laravel 5.4. There are changed logic for respone and removed functions like `assertResponseOk`

**Comment by mitulgolakiya** [comment]
@gandra @whereisjefe @hkarvasonis @reiter777 @AlexKR I am going to start working on laravel 5.4 support. will post the update soon.

**Comment by yelnyaface** [comment]
so ... its been 2 month now, is the laravel 5.4 compatible support done? or is this project abandoned?

**Comment by solidevolution** [comment]
What about this issue? Is there a perspective date for release supporting laravel 5.4?

We got broken unit tests after laravel update from 5.3.* to 5.4.*.

**Comment by yelnyaface** [comment]
is there currently any unofficial guide to make this package work with laravel 5.4?

**Comment by mitulgolakiya** [comment]
I have just added a support for laravel 5.4. Checkout 5.4 branch. Also, a guide is added on docs site [here](http://labs.infyom.com/laravelgenerator/docs/5.4/installation).

**Comment by dhcmega** [comment]
Hi
https://github.com/InfyOmLabs/laravel-generator/blob/develop/src/Common/BaseRepository.php still needs the method to be renamed:

getForeignKey -> getQualifiedForeignKeyName

**Comment by fdm-cj** [comment]
LayoutPublishCommand:

$path = config('infyom.laravel_generator.path.routes', app_path('routes/web.php'));
the path for laravel 5.5 should be:
$path = config('infyom.laravel_generator.path.routes', 'routes/web.php');

because routes is not in the app directory anymore
