### ISSUE TITLE
Postgresql

### ISSUE THREAD

**Issue by luisfmelo** [InfyOmLabs/laravel-generator#383]
Hey, When I try to generate from table,

`$ php artisan infyom:scaffold Keys --fromTable --tableName=keys `

Thia happens:

                                                                                                        

> 
>   [Doctrine\DBAL\DBALException]                                                                          
>   Unknown database type oid requested, Doctrine\DBAL\Platforms\PostgreSQL92Platform may not support it.  
>                                                                                                          

I'm using laravel 5.4, and postgres 9.5.5.

Anyone can help me?

**Comment by kirchaj** [comment]
I wonder if you need to install https://github.com/doctrine/dbal
????

**Comment by mitulgolakiya** [comment]
Ref: https://github.com/InfyOmLabs/laravel-generator/issues/593#issuecomment-471154604
