### ISSUE TITLE
fieldsFile example JSON needs to be updated

### ISSUE THREAD

**Issue by chellman** [InfyOmLabs/laravel-generator#384]
At least that's what it seems like.

Checkboxes should be specified using htmlType: checkbox, not htmlType: checkbox:1.  In `src/Utils/HTMLFieldGenerator.php`, there's a switch on $field->htmlType, which looks for 'checkbox' with no modifiers.  When I use 'checkbox:1', the field is not added to the CRUD form, but when I use just 'checkbox', it is.

**Comment by mitulgolakiya** [comment]
@chellman based on this guide, http://labs.infyom.com/laravelgenerator/docs/5.8/fields-input-guide, `checkbox,1` is the expected value as input for the generator. not `checkbox:1`.

**Comment by chellman** [comment]
This ticket is old, so I'm not 100% sure I was referring to, but I think it was this file:

https://github.com/InfyOmLabs/laravel-generator/blob/develop/samples/fields_sample.json#L83

```json
"htmlType": "checkbox:1"
```

So it sounds like it should be this instead:

```json
"htmlType": "checkbox,1"
```

Correct?

**Comment by mitulgolakiya** [comment]
@chellman great catch. it's fixed now.
