### ISSUE TITLE
Multi column search box

### ISSUE THREAD

**Issue by rebootcode** [InfyOmLabs/laravel-generator#388]
Is it possible to have search box implemented below each column ?

**Comment by rebootcode** [comment]
any update @mitulgolakiya  ?

**Comment by rebootcode** [comment]
Is it possible to have search box below each column ?

**Comment by mitulgolakiya** [comment]
@rebootcode just found a way. Creating a blog post for that. Will post update soon.

**Comment by mitulgolakiya** [comment]
@rebootcode Here is the post for it. http://blog.infyom.com/multi-column-search-box-in-datatables-with-infyom-laravel-generator
