### ISSUE TITLE
Adminlte template timestamp Form field not showing the date

### ISSUE THREAD

**Issue by yelnyaface** [InfyOmLabs/laravel-generator#390]
hi, this is my first time using infyom generator,

I tried generating a table from database, but then realized the edit page timestamp is not showing in the form:

http://prntscr.com/edn10v

**Comment by yehximin** [comment]
it seems the form do not support timestamp format YYYY-MM-DD HH:MM:SS,

do anyone know how to make the edit form show YYYY-MM-DD HH:MM:SS? instead of YYYY-MM-DD?

**Comment by mitulgolakiya** [comment]
Duplicate of #71
