### ISSUE TITLE
web.php path is changed

### ISSUE THREAD

**Issue by amin101** [InfyOmLabs/laravel-generator#391]
while running `php artisan infyom.publish:layout` get error:
`[ErrorException]                                                                                                 
  file_get_contents(C:\xampp\htdocs\sherkat\app\routes/web.php): failed to open stream: No such file or directory `

laravel 5.4 route directory is not in app anymore . it is in root

**Comment by mitulgolakiya** [comment]
@amin101 still its not supporting laravel 5.4. May be that's can be a problem. But its coming soon. You can track that here https://github.com/InfyOmLabs/laravel-generator/issues/382.
