### ISSUE TITLE
Default API route url?

### ISSUE THREAD

**Issue by yehximin** [InfyOmLabs/laravel-generator#392]
hi, what is the default API route URL? how do I access the route API to view the JSON?

say I have project in:
`http://localhost/project_a/`

`will the API route be http://localhost/project_a/api/restaurants/1?`

**Comment by kleytonroan** [comment]
I never used api route, but I think that's using a /api/ URI to the URL, in your case, I think that your URL will be http://localhost/api/project_a/ it will fired at api routes, in there you should control api version by using prefix, like /api/v1/..., /api/v2/..., it's better to control future changes in the context of URL api like:

```
Route::group(['prefix' => 'v1', 'middleware' => 'auth:api'], function() {
    //...
});
Route::group(['prefix' => 'v2', 'middleware' => 'auth:api'], function() {
    //...
});
```

**Comment by mitulgolakiya** [comment]
@yehximin what laravel version you are using? Generally, it should be, `http://localhost/project_a/api/v1/restaurants` if you haven't customized anything from config.
