### ISSUE TITLE
Generator not generating right pagination value

### ISSUE THREAD

**Issue by yelnyaface** [InfyOmLabs/laravel-generator#394]
I generated api + scaffold with:

`php artisan infyom:api_scaffold restaurants --fromTable --tableName=tf_restaurant --primary=res_id --paginate=20 --save`

the pagination is `20`

but when I view it, I get `10` instead, is the paginate function broken?

**Comment by yehximin** [comment]
Is there anyway to change the `rows per page` after generation? I want to change it to `20`

**Comment by mitulgolakiya** [comment]
seems like working good in the latest code.
