### ISSUE TITLE
Searching more than 1 Column - Datatable

### ISSUE THREAD

**Issue by rebootcode** [InfyOmLabs/laravel-generator#397]
Currently there is only 1 search box. how can we search data for 2 column at a time.

For example "name" and "city" ( John , Newyork ) in data table list generated by scaffold generator.

**Comment by yehximin** [comment]
infyom almost never reply, for your case I think u should ask ur question at:
https://github.com/yajra/laravel-datatables

**Comment by mitulgolakiya** [comment]
@rebootcode track it here https://github.com/InfyOmLabs/laravel-generator/issues/388

**Comment by mitulgolakiya** [comment]
duplicate of https://github.com/InfyOmLabs/laravel-generator/issues/388
