### ISSUE TITLE
 Illuminate\Foundation\Composer moved to Illuminate\Support\Composer for Laravel 5.2 

### ISSUE THREAD

**Issue by anand-patel** [InfyOmLabs/laravel-generator#4]
[ErrorException]
  Argument 1 passed to InfyOm\Generator\Commands\API\APIGeneratorCommand::__construct() must be an instance of Illuminate\Foundation\Composer, instance of Illuminate\Support\Composer given, called in C:\wamp\www\poteau\vendor\infyomla
  bs\laravel-generator\src\InfyOmGeneratorServiceProvider.php on line 51 and defined

[https://laravel.com/docs/5.2/upgrade#upgrade-5.2.0](url)

**Comment by mitulgolakiya** [comment]
Then I think we need two separate branches to support each versions. Will solve it quickly.

**Comment by mitulgolakiya** [comment]
Or I think we should just disable dump-autoload things as of now and can figure out the best way later on.

**Comment by mitulgolakiya** [comment]
@anand-patel I just removed `composer dump-autoload` stuff as of now. Check it again with 5.2 and let me know if you still have any problem.

**Comment by anand-patel** [comment]
It's working now.

**Comment by CasperLaiTW** [comment]
@mitulgolakiya 
Maybe you can use my way, laracasts/Laravel-5-Generators-Extended#83

It's support 5.2 and 5.1

**Comment by mitulgolakiya** [comment]
@CasperLaiTW I have just add a issue for that #7 for it.
