### ISSUE TITLE
possible to modify $FIELD_BODY$??

### ISSUE THREAD

**Issue by Trexology** [InfyOmLabs/laravel-generator#40]
If possible i would like to modify the value of $FIELD_BODY$ in the stub

**Comment by mitulgolakiya** [comment]
You can publish templates and do whatever edits you want. [Here](http://labs.infyom.com/laravelgenerator/docs/advanced/publish-templates) is the document for it.

**Comment by Trexology** [comment]
$FIELD_BODY$ is a single field in the stub which output

<td>{!! $vehicle->id !!}</td>
<td>{!! $vehicle->carplate !!}</td>
<td>{!! $vehicle->seaters !!}</td>
<td>{!! $vehicle->bookingType !!}</td>

i would like the final output to be something like

<td class="something">{!! $vehicle->id !!}</td>
<td class="something">{!! $vehicle->carplate !!}</td>
<td class="something">{!! $vehicle->seaters !!}</td>
<td class="something">{!! $vehicle->bookingType !!}</td>

I dun see anywhere i can modify this

**Comment by mitulgolakiya** [comment]
@Trexology I will add support for templating of table fields.

**Comment by mitulgolakiya** [comment]
added.
