### ISSUE TITLE
No hint path defined for [datatables]. (View: C:\xampp\htdocs\infyom_fresh\resources\views\restaurants\table.blade.php) (View: C:\xampp\htdocs\infyom_fresh\resources\views\restaurants\table.blade.php)

### ISSUE THREAD

**Issue by yelnyaface** [InfyOmLabs/laravel-generator#401]
`No hint path defined for [datatables]. (View: C:\xampp\htdocs\infyom_fresh\resources\views\restaurants\table.blade.php) (View: C:\xampp\htdocs\infyom_fresh\resources\views\restaurants\table.blade.php)`

with:

`php artisan infyom:api_scaffold restaurant --fromTable --tableName=fc_restaurant --datatables=true --primary=res_id --paginate=15 --save`

**Comment by yehximin** [comment]
guess this answer never gonna be answered like all the question here

**Comment by farid41studio** [comment]
how to resolve this ?

**Comment by vipertecpro** [comment]
I resolved this issue, let's see what i did first, from my local system to server I've updated everything including vendor folder with all the packages but i forget to update `composer.json`, VERY VERY SILLY OF ME. 
I hope I'm not the only one silly :p
