### ISSUE TITLE
Convert VueJS to v2

### ISSUE THREAD

**Issue by aescasio** [InfyOmLabs/laravel-generator#404]
Hi,

I'm avid fan in using laravel-generator, and I would like to know, how can replace VueJS 1 to VueJS 2, I'm using the laravel-generator 5.3, or this is this in future "integration/in progress" already for laravel 5.4? like in this link: #382 

Thanks and Regards,

**Comment by ajayinfyom** [comment]
We are not maintaining VueJs Generator in this package from last few versions.

**Comment by mitulgolakiya** [comment]
Yes, even we are planning to remove that source code starting from Laravel 7.0 support in this package. so closing this issue.
