### ISSUE TITLE
GUI API Generator Allowed memory size of 134217728 bytes exhausted

### ISSUE THREAD

**Issue by wl496928838** [InfyOmLabs/laravel-generator#408]
[Sun Apr  2 11:41:03 2017] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 104857656 bytes) in

**Comment by NightZpy** [comment]
@wl496928838 try add more memory to php.

**Comment by mitulgolakiya** [comment]
yes, @wl496928838 try to add more memory to your php.ini.
Also, can you post how many fields you are trying to generate?

**Comment by mitulgolakiya** [comment]
Closing this issue. re-open with some more details if needed.
