### ISSUE TITLE
infyom:scaffold ModelName --datatables=true Error

### ISSUE THREAD

**Issue by Erth0** [InfyOmLabs/laravel-generator#410]
When i run the scaffold with the --datatables=true flag im getting an error wich is

`FatalThrowableError in ProiodaController.php line 32:
Call to undefined method App\DataTables\ProiodaDataTable::render()`

Any help for this !!!

**Comment by Meklad** [comment]
the only solution i know, set the datatables to true in the infyom config file, and it will done for any scaffold you will create, i hope that help ... best regards

**Comment by Erth0** [comment]
i tried that alredy but same thing i upgrade from laravel 5.4 to 5.2 and works like charm!! thank you btw
