### ISSUE TITLE
Infyom Scaffold: How to return to index page all Articles belongs to Auth User

### ISSUE THREAD

**Issue by Meklad** [InfyOmLabs/laravel-generator#411]
i created Article Scaffold, and i want to return all articles belongs to specific auth user, note that ArticleDataTable.php is the file response of return all data to the index of articles, and i hope that my problem  is clear to understand.

**Comment by rebootcode** [comment]
Open ArticleDataTable.php

1. Go to `query` method
2. Find code that looks like :- 
```
$articles = Article::query();
```
3. Replace with below code :- 
```
$articles = Article::query();
$articles->where('user', \Auth::user()->id);
```
