### ISSUE TITLE
model swagger error after publish template to resource 

### ISSUE THREAD

**Issue by LarryZhang** [InfyOmLabs/laravel-generator#413]
I am trying  to generate model swagger docs, and I found that final model file has error . then I figure out that         $template = get_template('model.model', 'swagger-generator');
will get the model.model from the /resources/infyom/infyom-generator-templates/model/model.stub   
and I think this is big error

**Comment by LarryZhang** [comment]
#334  same issue

**Comment by dukenst2006** [comment]
What's the swagger URL, to have API documentation?
Try to use those:
www.example.com/docs <- swagger JSON files are visible
www.example.com/api-docs <- swagger ui is visible.
It's give Error NotFoundHttpException

**Comment by skys215** [comment]
@dukenst2006 
First of all, you need use the `swagger-generator` from `infyom`. But this package just add the swagger documentation in to the code. You need another package to browse them.



Install `swaggervel` package from https://github.com/slampenny/Swaggervel.

Add `Jlapp\Swaggervel\SwaggervelServiceProvider::class` in to the `Provider` section in the `config/app.php`.

Run vendor publish. `php artisan vendor:publish --provider="Jlapp\Swaggervel\SwaggervelServiceProvider"` (If your laravel version is 5.5, then you can type`php artisan vendor:publish` only. It will ask you to select which provider you want to publish).

After that, you can browse `/api/docs` and `/docs`.

But, it still doesn't support Laravel v5.4+. To use under Laravel v5.4+, you need to manually delete two lines in the [L51-52](https://github.com/slampenny/Swaggervel/blob/master/src/Jlapp/Swaggervel/routes.php#L51) or check the laravel version first as mentioned [here](https://github.com/slampenny/Swaggervel/pull/86).

**Comment by skys215** [comment]
@LarryZhang 
I found the same problem too. 
Still finding for workarounds.

**Comment by skys215** [comment]
@mitulgolakiya 
Is this issue going to solve?

**Comment by mitulgolakiya** [comment]
@skys215 we have new year holidays here. I will check it this weekend and will see if I can resolve it quickly.

**Comment by skys215** [comment]
Currently I'm changing the helpers.php in the vendors file until the author fixes this problem.
Change `get_template_file_path` function like this:
```php
    function get_template_file_path($templateName, $templateType = 'infyom-generator-templates')
    {
        $templateName = str_replace('.', '/', $templateName);

        $templatesPath = base_path('resources/infyom/'.$templateType.'/');

        $path = $templatesPath.$templateName.'.stub';

        if (file_exists($path)) {
            return $path;
        }

        return base_path('vendor/infyomlabs/'.$templateType.'/templates/'.$templateName.'.stub');
    }
```

**Comment by skys215** [comment]
@mitulgolakiya
How is it going? 
Any solutions for this? Or need to refactor more code which is related to this issue, so would take more time to fix it?

**Comment by mitulgolakiya** [comment]
@skys215 I have just fixed template error. It seems like `slampenny/Swaggervel` is no longer maintained. I am planning to have updated swagger ui package this weekend and will let you know once it's done.

**Comment by skys215** [comment]
Ok, I'll have a check of new commits.

**Comment by gelinger777** [comment]
@mitulgolakiya  are you sure you have fixed the problem? I have configured slampenny/Swaggervel and  did publish but seems in /vendor/swaggervel folder which is in the /public folder js and css files are missing 

```
GET https://apitest.localhost/vendor/swaggervel/swagger-ui.css net::ERR_ABORTED 404 (Not Found)
docs:69 GET https://apitest.localhost/vendor/swaggervel/swagger-ui-bundle.js net::ERR_ABORTED 404 (Not Found)
docs:70 GET https://apitest.localhost/vendor/swaggervel/swagger-ui-standalone-preset.js net::ERR_ABORTED 404 (Not Found)
docs:75 Uncaught ReferenceError: SwaggerUIBundle is not defined
    at window.onload (docs:75)
window.onload @ docs:75
load (async)
(anonymous) @ docs:73
favicon-32x32.png:1 GET https://apitest.localhost/vendor/swaggervel/favicon-32x32.png 404 (Not Found)
favicon-16x16.png:1 GET https://apitest.localhost/vendor/swaggervel/favicon-16x16.png 404 (Not Found)


```

**Comment by mitulgolakiya** [comment]
@gelinger777 I would say you give a try to use this new package `appointer/swaggervel` as per this issue https://github.com/InfyOmLabs/laravel-generator/issues/579 and reported that it works well.

**Comment by gelinger777** [comment]
@mitulgolakiya yes, you are right. In the docs you left the old name of the package. It messed me up a bit things. 

http://labs.infyom.com/laravelgenerator/docs/5.7/generator-options  here you can find jlapp/swaggervel  and wrong link 
Please fix .

**Comment by mitulgolakiya** [comment]
@gelinger777 good finding. I updated it but in installation step only. Updated the docs everywhere now.
