### ISSUE TITLE
form empty after infyom:scaffold

### ISSUE THREAD

**Issue by fedeverdi** [InfyOmLabs/laravel-generator#416]
Hello !

I used php artisan infyom:scaffold etc ...

All ok, migration ok, data table ok .. but when I try to add something ... the form is empty. I can see only the submit and cancel buttons.

Ideas ?

Thx !

**Comment by fedeverdi** [comment]
Sorry .. I passed wrong parameters ....

**Comment by mehdirazajaffri** [comment]
i am facing the same issue , can you tell me how you resolved that ?
