### ISSUE TITLE
new error that need fixing

### ISSUE THREAD

**Issue by phillipmadsen** [InfyOmLabs/laravel-generator#420]
1. tried to run php artisan infyom:publish and it ran but didnt publish the following files.
   1. AppBaseController.php did not publish
   1. core-templates is missing
1. the warning that routes file already exits route is wrong 
>   Existing routes.php file detected. Should we add an API group to the file? (y|N) : (yes/no) [no]:

**needt so be**
>   Existing ***routes/web.php*** file detected. Should we add an API group to the file? (y|N) : (yes/no) [no]:

1. tried to run infyom.publish:templates and it errors out with isPrimary() and core-templates directory is missing.
1. publish templates command publishes the controllers , models stubs instead of the views stubs, no view stubs anywhere in whole site and package without adding core-templates manually. did you move them or are they being made a new way i am not aware of.
1. I added core-templates manually 
1.  needed config file fixes
   1. 'routes'  => app_path('Http/routes.php'), >>  'routes' => base_path('routes/web.php'),
1. I make changes to stub files to match the theme and tempate but they are not being used and are staying the default which i cannot find.

**Comment by mitulgolakiya** [comment]
already fixed.
