### ISSUE TITLE
Folder with Views has hardcoded snake model

### ISSUE THREAD

**Issue by xaviersand** [InfyOmLabs/laravel-generator#421]
Hello,

i don't like snake writing for the views, this is why i changed the stubs, replacing 
`$VIEW_PREFIX$$MODEL_NAME_PLURAL_SNAKE$` with `$VIEW_PREFIX$$MODEL_NAME_PLURAL_CAMEL$`

The only thing is that the folder name with the views is not being changed.
`\vendor\infyomlabs\laravel-generator\src\Common\GeneratorConfig.php`  Line 193 has hardcoded snake:

``` 
$this->pathViews = config(
            'infyom.laravel_generator.path.views',
            base_path('resources/views/')
        ).$viewPrefix.$this->mSnakePlural.'/';
```

this should be parametrable, right ?

**Comment by mitulgolakiya** [comment]
@xaviersand the only reason of using snake case was, laravel is almost using snake_case everywhere like, magic functions, database fields etc.
But if you have your own choice, then you can change it your own way. You can fork the repo and change the line and can use your own repo.
And it's not in a near future plan, to have it parameter able. but I would take it in a queue for a future.
