### ISSUE TITLE
Generate Password

### ISSUE THREAD

**Issue by maulanibr** [InfyOmLabs/laravel-generator#422]
How can I encrypt password form in another blade view (ex: Admin)  so that it can be verified by login page by default ?

**Comment by yelnyaface** [comment]
are you using the same table for both admin and user? for the default laravel encryption use bcrypt($password)

**Comment by maulanibr** [comment]
yes. Ive used same table and I want to know infyom laravel encryption for user password.

**Comment by yelnyaface** [comment]
infyom is not using any custom password encryption method,

I have create multiauth with the infyom package before,

and this is what I do in my admin controller for 'register':

```
    protected function create(array $data)
    {
        return Admin::create([
            'name' => $data['name'],
            'email' => $data['email'],
            'password' => bcrypt($data['password']),
        ]);
    }

```
I believe this is more of a laravel question than about infyom

**Comment by yelnyaface** [comment]
an easier way is to just create another route pointing to user/register, then u dont have to write any new method or code

**Comment by yelnyaface** [comment]
```
    Route::post('admin/login', 'LoginController@login')->name('admin.login');
```
do this admin data is same as user data

**Comment by mitulgolakiya** [comment]
@maulanibr infyom generator is doing any encryption for any field by default. you can encrypt whatever you want in your generated files as @yelnyaface suggested.
