### ISSUE TITLE
My users does not have an email

### ISSUE THREAD

**Issue by jiac0911** [InfyOmLabs/laravel-generator#424]
I have 2 question:

1. Before I start even learning I need to know if it would work on a existing database.

2. I need my users to be able to log in with an user not an email, what this means is that a user doesn't have an email so it is not necesary the @example.com. To make clear some users could be: jhon or george, this package could work so they can log in with that users?

**Comment by mitulgolakiya** [comment]
@jiac0911 this package will create just a scaffold for you. so even if it is generating scaffold with an email, you can change your fields, form or controllers at any time the way you want. 
It is not using any static package inbuilt class, so you are free to do whatever you want. And as it's also utilizing laravel auth scaffold only, so you can customize anything that is supported by laravel.

And this package can generate forms from your database as well, check [here](http://labs.infyom.com/laravelgenerator/docs/5.4/generator-options#generate-from-table), but it's not fully working, you have to do the modification by yourself to make it fully working.
