### ISSUE TITLE
Where should i add Custom Methods

### ISSUE THREAD

**Issue by deep88** [InfyOmLabs/laravel-generator#425]
I am pretty new to repository pattern as well as this package. I want to know where should I add extra methods, for maximum code reuse. 
For instance, I have a method updateLastName()  whose mere responsibility is updating the last name in the database, Should I add this method to UserController directly and use methods provided by repository package, or in UserRepository, so that I can use the same method with multiple views in different methods? which one is the right approach?

**Comment by mitulgolakiya** [comment]
@deep88 basically you can put your functions in the repository if it's going to be used in multiple controllers. and as per best practice, any operation that you are going to perform on the database, that should be done in the repository I think.
