### ISSUE TITLE
Datatabless error

### ISSUE THREAD

**Issue by AlexKR** [InfyOmLabs/laravel-generator#427]
`Class 'Yajra\Datatables\Services\DataTable' not found` for Laravel 5.4
More info here: https://yajrabox.com/docs/laravel-datatables/7.0/upgrade

**Comment by cenoura** [comment]
I'm on `"infyomlabs/laravel-generator": "5.4.x-dev"`, using `"yajra/laravel-datatables-oracle": "^7.2"` and `"yajra/laravel-datatables-buttons": "^1.1"` and everything is ok.
Did you registered the Datatables related Service Providers on `config/app.php` file?

**Comment by mitulgolakiya** [comment]
@AlexKR @cenoura right now it's only supporting datatables version `6.0` not `7.0`

**Comment by dhcmega** [comment]
Hi, is there a fix? Should I remove Datatables 7 and replace it with v6?

**Comment by mitulgolakiya** [comment]
@dhcmega yes, it will work fine with 6.0..

**Comment by dhcmega** [comment]
it worked, thanks.

**Comment by mitulgolakiya** [comment]
Will be creating new feature request for version 7.0 support.
