### ISSUE TITLE
Command don't execute  php artisan infyom:publish

### ISSUE THREAD

**Issue by fsaires** [InfyOmLabs/laravel-generator#429]
When i typing php artisan infyom:publish

I receive this error: 

[Symfony\Component\Console\Exception\CommandNotFoundException]
  There are no commands defined in the "infyom" namespace.

Anyone can help me? 

I use laravel 5.4

**Comment by cenoura** [comment]
Did you update your `composer.json`to `5.4.x-dev`?
Did you registered the ServiceProvider in your `config/app.php` file?
Just executed the command here and everything is ok.

**Comment by mitulgolakiya** [comment]
@fsaires have you gone through the proper steps to install generator with laravel 5.4?

**Comment by tranghaviet** [comment]
run `php artisan config:clear'
Everytime you modify config files you must run above command to make everything work.

**Comment by falaFulani** [comment]
After running php artisan infyom:publish. I get "There are no commands defined in the "infyom" namespace. Kindly help out

**Comment by sarjandesai** [comment]
i am trying to install it on Laravel 5.4 and i have followed all the depicted steps 
@ http://labs.infyom.com/laravelgenerator/docs/6.0/installation 
'
Only changes i made is to version from  6.0.x to 5.4.x  .

"laravelcollective/html": "^5.4.0",
"infyomlabs/laravel-generator": "5.4.x-dev",
"infyomlabs/adminlte-templates": "5.4.x-dev"

Still getting  " There are no commands defined in the "infyom" namespace."

Any suggestions?

**Comment by mitulgolakiya** [comment]
@sarjandesai you are following 6.0 docs for 5.4 installations. Try to follow these steps: http://labs.infyom.com/laravelgenerator/docs/5.4/installation
