### ISSUE TITLE
These would be a great additions to the generator

### ISSUE THREAD

**Issue by phillipmadsen** [InfyOmLabs/laravel-generator#43]
1.  Make a Remove or Delete  or undo from a history command. This would remove all generated files like it was never there.
### artisan php infyom-remove:api_scaffold  Blog
1.  Make a enable / disable command
### artisan php infyom:diable:api_scaffold Blog

or 
### artisan php infyom:enable:scaffold Blog

or 
### artisan php infyom:options  Blog --enable=api, scaffold --disable=swagger

Anyway just thinking out loud. This would enable developers to add commands to the views to control each aspect of each generated section / crud. 

As usual your system is great.

**Comment by mitulgolakiya** [comment]
@phillipmadsen good idea and you are always a good contributor in all of my projects. so will add it to the feature list.

**Comment by krantos** [comment]
I'm agree with this idea.

**Comment by mitulgolakiya** [comment]
@phillipmadsen I think by rollback command, we can remove the generated stuff.

Can you explain what is the exact purpose of enabling/disable api ? Like what should be done in code ?

**Comment by phillipmadsen** [comment]
@mitulgolakiya 
This would be like giving the whole crud a on / off switch. 

lets say the blog was not being used but might be in the future so you dont want it gone you just want it to disappear . so by deactivating the crud all routes and links would disappear in the places that it was enabled.  so example would be all links and heading in admin menu, all routes generated for it also and any links created for it in the frontend. 

does this make sense?

**Comment by mitulgolakiya** [comment]
I think rollback command was the original requirement for this issue and if a user wants to disable something or disappear that depends on in which and how many views, he put links for a route. all those needs to be removed or commented. so that's up to user.
