### ISSUE TITLE
Problem to generate views

### ISSUE THREAD

**Issue by eullercdr** [InfyOmLabs/laravel-generator#433]
Dears, 

I have a problem when package is generate views. The error is.

laravel mkdir(): Invalid argument

See my configurations

https://gist.github.com/eullercdr/3bdd1ac016ea932474d2e234a655e0e2

Somebody help can help me?

Thanks a lot.

**Comment by mitulgolakiya** [comment]
the only reason I can see is to check, if this directory actually exist?
`app_path('Units/Panel/resources/views/'),`

Please check and let me know if still issue persist.
