### ISSUE TITLE
Getting the generator to work with Slim

### ISSUE THREAD

**Issue by naeazach** [InfyOmLabs/laravel-generator#437]
Are there any instructions on getting this running with Slim (http://docs.slimframework.com/).  A lot of the install instructions don't seem to be compatible....

**Comment by illuminate3** [comment]
This is a laravel specific package. I guess you could fork it and make the necessary changes to make it do what you want though.

**Comment by mitulgolakiya** [comment]
yes, as of now, we do not have any plan to support for slim yet. But maybe in future.
