### ISSUE TITLE
How to save and retrieve files

### ISSUE THREAD

**Issue by brtwister2** [InfyOmLabs/laravel-generator#438]
How to use scaffold_api to generate columns that saves and returns files?
I was expecting something like this but doesn't work: 
    {
        "name": "attachment",
        "htmlType": "file",
        "dbType": "binary"
    }

**Comment by mitulgolakiya** [comment]
maybe this can help: 

http://labs.infyom.com/laravelgenerator/docs/5.4/generator-options#save-model-schema

http://labs.infyom.com/laravelgenerator/docs/5.4/generator-options#fields-from-file
