### ISSUE TITLE
Is there a duplication here?

### ISSUE THREAD

**Issue by abdullaheid** [InfyOmLabs/laravel-generator#439]
In the following code, **it seems that the code of the 'number' case is as the same as the previous cases**, so, is there any reasonable reason to separate that case from the others?.

```php 
   public static function generateHTML(GeneratorField $field, $templateType){
            ...
            case 'text':
            case 'textarea':
            case 'date':
            case 'file':
            case 'email':
            case 'password':
                $fieldTemplate = get_template('scaffold.fields.'.$field->htmlType, $templateType);
                break;
            case 'number':
                $fieldTemplate = get_template('scaffold.fields.'.$field->htmlType, $templateType);
                break;
            ...
```
https://github.com/InfyOmLabs/laravel-generator/blob/develop/src/Utils/HTMLFieldGenerator.php

**Comment by mitulgolakiya** [comment]
@abdullaheid I think yes. needs to be removed. will take it in a queue after proper testing.

Great catch @abdullaheid.
