### ISSUE TITLE
Maybe a Tracking / Changes / Updates / Created / Deleted Log Record

### ISSUE THREAD

**Issue by phillipmadsen** [InfyOmLabs/laravel-generator#44]
Create a crud history file showing all  changes updates creations edits overwrites and removals so we an troubleshoot large project builds later. 

Just an idea once again. I  usually write me own but it would be another great addon. 

example would be either on each file or a master record or maybe both sort of like wordpress revisions just without the rollback.
```
| NAME               |  LOCATION                               |  OVERWRITTEN  | UPDATED  | LAST MODIFIED    | Deleted  |
----------------------------------------------------------------------------------------------------------------------
UserController.php   | app/Http/Controllers/UserController.php | yes           | yes      | 03/02/2016 02:28 | no       |
```

**Comment by mitulgolakiya** [comment]
Rollback command added in latest version. Find the doc [here](http://labs.infyom.com/laravelgenerator/docs/advanced/commands)
