### ISSUE TITLE
There was an error in the model when custom template.

### ISSUE THREAD

**Issue by clh021** [InfyOmLabs/laravel-generator#441]
I want to customize the generation of templates to achieve internationalization
According to the introduction of the custom method has been working properly, however
Model generation error, many comments and fields are not replaced

But when I removed the model directory from my custom template, it returned to normal.
As shown in the following path:
```
	deleted:    resources/infyom/infyom-generator-templates/model/model.stub
	deleted:    resources/infyom/infyom-generator-templates/model/relationship.stub
```
Maybe this is a BUG, but has not yet affected me, because the model does not need international

**Comment by mitulgolakiya** [comment]
@clh021 Can you submit the customized file that you have created? Then I can look into it for some more details.
