### ISSUE TITLE
XSS attack on Index page with Table list item.

### ISSUE THREAD

**Issue by rebootcode** [InfyOmLabs/laravel-generator#443]
How to prevent XSS attack on datatable list ? 

https://datatables.net/manual/security  Datatables does mention to put `render` option as `$.fn.dataTable.render.text()` and not null.

**Comment by krokite** [comment]
Has no one else faced this attack ?

**Comment by rebootcode** [comment]
No INPUT ? - There is XSS Attack on "index.blade.php" . All HTML tags are parsed and executed, making web app vulnerable to multiple attacks.

**Comment by rebootcode** [comment]
In datatable file , return with `->escapeColumns(['name'])` to escape HTML text.
