### ISSUE TITLE
Scaffold View: Relationship Select options and users_id

### ISSUE THREAD

**Issue by srdavidsilva** [InfyOmLabs/laravel-generator#445]
When running scaffold with json, relationships are done correctly in models, however, in views instead of displaying a select with relationship data, it displays a common input text.

Also, I believe it is prudent that users_id text fields be hidden with an `Auth::user()->` id to speed up the work.

My question is, are these things already working and am I doing wrong?
Thank you very much for the attention, the project is sensational!

**Comment by mitulgolakiya** [comment]
@srdavidsilva sorry for the late reply.

But this package is yet not ready to work fully with relationships. the main goal of having a support of relationships was to generate relationships in models only and having foreign keys in migrations. so a user's don't have to do that manually.

It does not have support for that in views now. You can do that manually once your files generated.

**Comment by xwiz** [comment]
Is anyone working on this (Generating dropdown options from relation) ? I'd like to work on it.

**Comment by mitulgolakiya** [comment]
@xwiz if you can work then most welcomed.
