### ISSUE TITLE
Calling controller at main URL

### ISSUE THREAD

**Issue by AnibalDuarte** [InfyOmLabs/laravel-generator#446]
This is not a problem, but a doubt: I recently took on a project in which I have to work with Laravel and the InfyOm admin. However parallel to this Admin should work a landing page and I am not able to make the main URL of the project point to the correct controller, it always redirects to the '/ login'.

How should this be programmed on the routes?

**Comment by mitulgolakiya** [comment]
@Anderuimm can you share little bit more details? May be the route you are accessing will be protected by  middleware. you can take that route out from there and it should just work.

Are you using [generator-builder](https://github.com/InfyOmLabs/generator-builder) ? and talking about that route?
