### ISSUE TITLE
Master Child Form??

### ISSUE THREAD

**Issue by Muhammadinaam** [InfyOmLabs/laravel-generator#447]
Can I create a master /child form with this package:

This is like one entity is master and other entity is child or detail, like in sale order form:

sale_orders (master table)
id, date_of_order, customer_id, date_of_delivery.

sale_order_details (child/detail table)
id, sale_order_id, item_id, qty, rate, amount.

Then form for above two tables is like this:

![image](https://user-images.githubusercontent.com/22542738/28350661-f371eee8-6c63-11e7-8156-7bba27482cd8.png)

**Comment by mitulgolakiya** [comment]
@Muhammadinaam no. You need to do this manually by your own way. The Aim of this package is to create simple CRUD with some customizable options and to reduce & save a time of generating various files and simple redundant apis.
