### ISSUE TITLE
Sortable column headers?

### ISSUE THREAD

**Issue by eduardoarandah** [InfyOmLabs/laravel-generator#448]
I noted that when I write this to the index view, I get a sorted list

`?orderBy=name&sortedBy=desc`

but blade template table.blade.php don't have any sortable links on table headers

am I missing something?

**Comment by mitulgolakiya** [comment]
@eduardoarandah you can modify your generated files to have a support for sorting data by given column in request params.
You can refer datatables docs for that from [here](https://yajrabox.com/docs/laravel-datatables/master/order-column) and modify your generated files based on that doc and your request input parameters.
