### ISSUE TITLE
Repositories and Relations question

### ISSUE THREAD

**Issue by kyleburnett71** [InfyOmLabs/laravel-generator#449]
After you generate your api_scaffold from a table, and including --relations, how exactly do you alter your controller to make use of the relation?

For example, I have "tasks" and they are the child of "projects". And on the list of tasks, I'd like to provide the name of the project instead of the ID.

The generated controller...

public function index(Request $request)
{
    $this->tasksRepository->pushCriteria(new RequestCriteria($request));
    $tasks = $this->tasksRepository->all();

    return view('tasks.index')
        ->with('tasks', $tasks);
}

And in the model I have:

public function projects()
{
    return $this->belongsTo(\App\Models\Project::class);
}

So, how do I leverage this relationship that has been established? I do not see how the model is accessible to -- or injected back into -- the controller.

Thanks for any guidance.

**Comment by kyleburnett71** [comment]
Ah, got it. You access the model via the items returned from the repository. On the template...

 @foreach($tasks as $task)
     {!! $task->project->name !!}
@endforeach

**Comment by anuj509** [comment]
how to get this in API ?
