### ISSUE TITLE
Datatable return empty table

### ISSUE THREAD

**Issue by njxqlus** [InfyOmLabs/laravel-generator#450]
Hello! 
My table.blade.php contains 
```
@section('css')
    @include('layouts.datatables_css')
@endsection

{!! $dataTable->table(['width' => '100%']) !!}

@section('scripts')
    @include('layouts.datatables_js')
    {!! $dataTable->scripts() !!}
@endsection
```
On page I have `<table  class="table" id="dataTableBuilder" width="100%"></table>`

Maybe I miss something? How I must add data to the table?

**Comment by mitulgolakiya** [comment]
@njxqlus which version of `yajra/laravel-datatables` you are using?

**Comment by njxqlus** [comment]
@mitulgolakiya I use yajra/laravel-datatables 6.* and Laravel 5.4

**Comment by mitulgolakiya** [comment]
@njxqlus can you host your generated files somewhere with the db schema you generated and let me know?

You can also send it directly to my email (me@mitul.me).

So I can check it better way.

**Comment by mostafahadian** [comment]
Hi @njxqlus and @mitulgolakiya
I had the exact same problem as @njxqlus.
I changed the code to the following, and it was fixed:

`@section('css')
    @include('layouts.datatables_css')
@endsection

{!! $dataTable->table(['width' => '100%']) !!}

@push('scripts')
    @include('layouts.datatables_js')
    {!! $dataTable->scripts() !!}
@endpush`

* Note that the only lines that are modified are the last line and the line @section('scripts').
