### ISSUE TITLE
Add Datatables options?

### ISSUE THREAD

**Issue by jrmypttrsn** [InfyOmLabs/laravel-generator#451]
This might be fairly obvious, but I can't find any related info in the InfyOm Laravel docs. How do I add various Datatables options, such as changing the number of rows displayed on a page, fixed headers, or autofill.

Thanks.

**Comment by mitulgolakiya** [comment]
@janbolat at the end it's generating the files. so you can modify/customize anything you want in those files. You can refer the docs for DataTables for that and do that manually.
