### ISSUE TITLE
creation error when hasMany doesn't exist.

### ISSUE THREAD

**Issue by dhcmega** [InfyOmLabs/laravel-generator#452]
Hi
When creating a new record, BaseRepository tries to find relations and updated them. But if there is not relation, as when the user is creating both, the main record and the hasMany relation, the creations fails because the related model doesn't exists.
```
                        if (count($new_values) > 0) {
                            $related = get_class($model->$key()->getRelated());

                            foreach ($new_values as $val) {
                                $rel = $related::find($val);
                                $rel->$model_key = $model->id;
                                $rel->save();
                            }
                        }
```
This update should check if the find actually found anything before trying to save. Am I right?
Thanks!

**Comment by JGamboa** [comment]
did you solve it?

**Comment by dhcmega** [comment]
Hi, I don't remember, it's been a long time ago, like 18 months.
The code I pasted is the original one, is yours the same?

**Comment by JGamboa** [comment]
Is the same, but i made a pull request with a solution for create and update.

**Comment by ajayinfyom** [comment]
From 5.6+,  We published our custom Base Repository pattern and removed use of Prettus/l5-repository pattern.
