### ISSUE TITLE
Use of array_values method on the array should break sync()

### ISSUE THREAD

**Issue by dhcmega** [InfyOmLabs/laravel-generator#453]
Hi
I hope I am not wrong and confused about this:
sync() needs an array of ids
array_values returns an array starting with index 0, it will break.
It generates this code:
`
insert into pickup_location_product (created_at, pickup_location_id, price, product_id, updated_at) values (2017-07-28 00:06:42, 0, 15, 159, 2017-07-28 00:06:42)
`

` 
case 'Illuminate\Database\Eloquent\Relations\BelongsToMany':
$new_values = array_get($attributes, $key, []);
if (array_search('', $new_values) !== false) {
     unset($new_values[array_search('', $new_values)]);
}
$model->$key()->sync(array_values($new_values));
break;
`

Line 60 https://github.com/InfyOmLabs/laravel-generator/blob/develop/src/Common/BaseRepository.php

**Comment by ajayinfyom** [comment]
@dhcmega  there's no issue with array indices.
always array has default numeric indices, it doesn't matter for us.
if we send an array of ids like [1,2,3], also it has indices 0,1,2.
