### ISSUE TITLE
routes.php failed to open stream: No such file or directory

### ISSUE THREAD

**Issue by mrKorg** [InfyOmLabs/laravel-generator#454]
The command generating a table 
`php artisan infyom:scaffold Product --fromTable --tableName=products`
get the error

> [ErrorException]
  file_get_contents(E:\OpenServer\domains\laravelinfyom\app\Http/routes.php): failed to open stream: No such file or directory
![43ac8093ad](https://user-images.githubusercontent.com/18467525/28814105-e4eb6e76-76a4-11e7-8fd2-5b15cce3fac7.jpg)

The problem is that the routes are in a folder /routes to the root
and there is no routes.php
only chennels api console and web route
How can I change in the settings the path to the file and get its name

**Comment by mitulgolakiya** [comment]
@mrKorg which version of laravel you are using? Make sure, you are using the right version of the package.

Also, can you post your composer.json here?

**Comment by mrKorg** [comment]
Laravel Framework 5.4.30

`{
    "name": "laravel/laravel",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "type": "project",
    "require": {
        "php": ">=5.6.4",
        "laravel/framework": "5.4.*",
        "laravel/tinker": "~1.0",
        "yajra/laravel-datatables-oracle": "7.5"
    },
    "require-dev": {
        "fzaninotto/faker": "~1.4",
        "mockery/mockery": "0.9.*",
        "phpunit/phpunit": "~5.7",
        "infyomlabs/laravel-generator": "5.4.x-dev",
        "laravelcollective/html": "^5.4.0",
        "infyomlabs/adminlte-templates": "5.4.x-dev",
        "doctrine/dbal": "~2.3"
    },
    "autoload": {
        "classmap": [
            "database"
        ],
        "psr-4": {
            "App\\": "app/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "scripts": {
        "post-root-package-install": [
            "php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "php artisan key:generate"
        ],
        "post-install-cmd": [
            "Illuminate\\Foundation\\ComposerScripts::postInstall",
            "php artisan optimize"
        ],
        "post-update-cmd": [
            "Illuminate\\Foundation\\ComposerScripts::postUpdate",
            "php artisan optimize"
        ]
    },
    "config": {
        "preferred-install": "dist",
        "sort-packages": true,
        "optimize-autoloader": true
    }
}
`

**Comment by mrKorg** [comment]
And what to specify in laravel_generator.php that would be all files view sozdavayte in resources/views/admin ?

**Comment by mrKorg** [comment]
![e45bb89d48](https://user-images.githubusercontent.com/18467525/28815560-774ba614-76aa-11e7-9c1e-6b21a46b1777.jpg)

**Comment by mitulgolakiya** [comment]
I think your config is wrong. it should look like following.
https://github.com/InfyOmLabs/laravel-generator/blob/5.4/config/laravel_generator.php

**Comment by mrKorg** [comment]
Thank you very much
