### ISSUE TITLE
How to set config that the admin files lying inside the admin folder?

### ISSUE THREAD

**Issue by mrKorg** [InfyOmLabs/laravel-generator#455]
Hi
I want all controllers for the admin panel and all the view lay in the admin folder.
I use
```
'path' => [
       ...
        'routes'            => base_path('routes/admin.php'),
        'controller'        => app_path('Http/Controllers/Admin/'),
        'views'             => base_path('resources/views/admin/'),
        ...
    ],
    'namespace' => [
      .....
        'controller'        => 'App\Http\Controllers\Admin',
        ....
    ],
    'prefixes' => [
        'route' => 'admin', 
        'path' => '',
        'view' => 'admin',
        'public' => '',
    ],
```
After I get this result:
```
Controllers
-- Admin
--- ProductController.php
```
and views (l move "layouts" in admin)
```
views
-- admin
--- layouts
--- admin
---- products
----- files .... each has @extends('layouts.app')
```
where there is no namespace admin
and in route admin.php
```
Route::get('admin/products', ['as'=> 'admin.products.index', 'uses' => 'ProductController@index']);
....
```
Where there is no namespace Admin.

What could be the problem?

**Comment by matthib** [comment]
I am having the same problem. Basically I would like to use the scaffold in an admin area together with the AdminLTE Theme, but it seems I can't tell the generator to look for the files in the admin folder / namespace.
Like @mrKorg i moved the views/layouts to views/admin/layouts, but they are still extended extends('layouts.app'). How can I tell the generator to extend these files from admin.layouts.app ?

**Comment by mitulgolakiya** [comment]
@matthib from where you are including this admin.php route file? You can specify namespace directly there. so if it's included from web.php then you can do something like,

```
Route::group(['namespace' => 'Admin'], function () {
    include "admin.php";
});
```

about extend `admin.layout`. you can publish templates. Check docs [here](http://labs.infyom.com/laravelgenerator/docs/5.5/publish-templates).

Then you can update all files where it uses `@extends('layouts.app')`, and replace with `@extends('admin.layout')`.
That way, your new generated files will take these updated files.

*ALSO MAKE SURE, YOU DELETE ALL OTHER FILES FROM PUBLISHED TEMPLATES, THAT YOU DON'T NEED TO CHANGE*.

**Comment by matthib** [comment]
@mitulgolakiya 
Thank you for the quick reply!
I followed your advice to publish the templates and changed all the templates to @extends('admin.layout') and it works great :+1: 

I also deleted the unused template files, but I am wondering why it is so important to delete them, even if I didn't change them?

Using an 'admin' prefix in the config (I guess it is the path one?) helps to create the controllers in the Admin namespace, like Admin\ACMEController@index, so I got this one covered as well.

**Comment by mitulgolakiya** [comment]
@matthib so once you publish the files, your templates are taken from there when generator creates files. It does not use the files from vendor directory.

so whatever new changes are coming to those files will not be reflected. so it's always good to publish only files which you need.
