### ISSUE TITLE
DataTable.stub errors

### ISSUE THREAD

**Issue by Enep241** [InfyOmLabs/laravel-generator#456]
when using the $ModelDataTable class in my scaffold controller, it launched some errors ......
I think that the package laravel-datables is not well incorporated in the generator. So i modified the stub file to get this : 
`<?php
namespace $NAMESPACE_DATATABLES$;

use $NAMESPACE_MODEL$\$MODEL_NAME$;
use Form;
use Yajra\Datatables\**Facades**\DataTable;
use Yajra\Datatables\Html\Builder;
...........
........
.....

    private function builder()
    {
        return parent::getHtmlBuilder();
    }    
`

**Comment by mitulgolakiya** [comment]
@Enep1995 can you test it with the latest version?

Also which datatable and laravel version you are using? Also, can you let me know what schema or fields you are trying to generate?

**Comment by mitulgolakiya** [comment]
@Enep241 we checked all the versions with datatables with the latest code and seems working fine. Open another issue with specific details if the problem still persists.
