### ISSUE TITLE
please support point type for postgresql 

### ISSUE THREAD

**Issue by unizhu** [InfyOmLabs/laravel-generator#459]
Since point type is not supported by Doctrine core. So I edit the 
`TableFieldsGenerator.php` 
and add a line
`$platform->registerDoctrineTypeMapping('point', 'string');`
after json type.

It works. Please support the point type on next release. 
thx

**Comment by mitulgolakiya** [comment]
@unizhu support added. Ref: https://github.com/InfyOmLabs/laravel-generator/issues/593#issuecomment-471154604
