### ISSUE TITLE
Route not needed: Route::get('owners/delete/{id}')

### ISSUE THREAD

**Issue by pjmartorell** [InfyOmLabs/laravel-generator#46]
The generated route `Route::get('owners/delete/{id}')` it's not necessary. I suspect you created to bypass the problem of browsers that don’t recognize the `DELETE` verb, but with the routes generated by `Route:resource(…)` it's enough. 

You can directly call the `whatever.destroy` route from the index view using a form. You need to modify the table.blade.php to use a submit button using a form, which allows you to use the hidden verb `DELETE`.

**Comment by mitulgolakiya** [comment]
fixed.
