### ISSUE TITLE
Datatables - double column sorting icons

### ISSUE THREAD

**Issue by jrmypttrsn** [InfyOmLabs/laravel-generator#460]
![double-sorting-icons](https://user-images.githubusercontent.com/16291625/29194332-a962a666-7dee-11e7-9ff8-67d90c1f027a.jpg)

Does anyone know where I can remove one set of the sorting icons? I have adminlte enabled. I'm just not sure where to look for the code that is causing both sets of icons to be displayed. Thanks.

**Comment by mitulgolakiya** [comment]
@jrmypttrsn you can do that by specifying `ordering` to false in `html` method of your ModelDataTable file.

Like this,

```
return $this->builder()
    ->columns($this->getColumns())
    ->minifiedAjax()
    ->addAction(['width' => '80px'])
    ->parameters([
        'dom'     => 'Bfrtip',
        'ordering'   => false,
        'buttons' => [
            'create',
            'export',
            'print',
            'reset',
            'reload',
        ],
    ]);

```

**Comment by dhcmega** [comment]
Doing so disables both. Thanks.
