### ISSUE TITLE
Few issues

### ISSUE THREAD

**Issue by phillipmadsen** [InfyOmLabs/laravel-generator#461]
> When i try to use datatables id does not change the table or files to use it. 

```
 'add_on' => [
        'swagger'       => false,
        'tests'         => true,
        'datatables'    => true,
        'menu'          => [
            'enabled'       => true,
            'menu_file'     => 'layouts/menu.blade.php',
        ],
    ],
```
> when setting custom routes only some of the files are modified
```
    'prefixes' => [
        'route' => 'admin',  // THIS SHOULD ONLY CHANGE IT IN THE ROUTES no NAMESPACE
        'path' => '', // THIS SHOULD CHANGE ALL PATHS ex NameSpace it
        'view' => '',  // THIS SHOULD ONLY PREFIX BLADE FILES DIRECTORY
        'public' => '', // THIS IS FOR ADDING ADDITIONAL ASSETS AND IMAGES NEEDED IN THE BLADE FILES
    ],
```

## 'route' => 'admin',  
EXAMPLE WOULD BE THE FOLLOWING
```
Route::get('admin/users', ['as'=> 'admin.users.index', 'uses' => 'UserController@index']);
// SO  COULD BE USED IN SOMETHING LIKE THIS
Route::middleware('auth')->group(function ()
{
        Route::prefix('admin')->group(function ()
        {
              Route::get('users', ['as'=> 'admin.users.index', 'uses' => 'UserController@index']);
        });
});
```
NOTICE NO NAMESPACE CHANGE IN THIS PART 
```
'uses' => 'UserController@index']
```
AND THE CONTROLLER WOULD BE LIKE THIS 
```
    public function index(UserDataTable $userDataTable)
    {
        return $userDataTable->render('users.index'); // NOTICE NO ADMIN IN VIEW PATH
    }
```
--------------

## 'PATH' => 'admin',  
EXAMPLE WOULD BE THE FOLLOWING
```
Route::get('admin/users', ['as'=> 'admin.users.index', 'uses' => 'Admin\\UserController@index']);

```
NOTICE THE NAMESPACE CHANGE IN THIS PART 
```
'uses' => 'Admin\\UserController@index']
```
AND THE CONTROLLER WOULD BE LIKE THIS 
```
    public function index(UserDataTable $userDataTable)
    {
        return $userDataTable->render('ADMIN.users.index'); // NOTICE NO ADMIN IN VIEW PATH
    }
```

--------------------------------
## 'VIEW' => 'backend', with 'PATH' => 'admin',  
EXAMPLE WOULD BE THE FOLLOWING
```
Route::get('admin/users', ['as'=> 'admin.users.index', 'uses' => 'Admin\\UserController@index']);

```
NOTICE THE NAMESPACE CHANGE IN THIS PART 
```
'uses' => 'Admin\\UserController@index']
```
AND THE CONTROLLER WOULD BE LIKE THIS 
```
    public function index(UserDataTable $userDataTable)
    {
        return $userDataTable->render('BACKEND.users.index'); // NOTICE NO ADMIN IN VIEW PATH
    }
```

--------------------------------
## 'VIEW' => 'backend',  
EXAMPLE WOULD BE THE FOLLOWING
```
Route::get('users', ['as'=> 'users.index', 'uses' => 'UserController@index']);

```
NOTICE NO NAMESPACE CHANGE IN THIS PART 
```
'uses' => 'UserController@index']
```
AND THE CONTROLLER WOULD BE LIKE THIS 
```
    public function index(UserDataTable $userDataTable)
    {
        return $userDataTable->render('backend.users.index'); // NOTICE BACKEND IN VIEW PATH
    }
```
--------------------------

## 'PUBLIC' => 'THEME1',

***THIS IS FOR ASSET LINKING INSIDE THE BLADE FILES IF USING DIFFERENT ASSET LOCATION OTHER THEN THE DEFAULT.  SAY FOR MULTIPLE THEMES.***

EXAMPLE WOULD BE LIKE THIS

THEME1 ASSETS | THEME2 ASSETS
------------ | -------------
public/theme1/ | public/theme2/
{!! asset('/theme1/') !!} | {!! asset('/theme2/') !!}

-----------------------

> I hope this made sense.  But for the datatables not working i have not looked into it to find out why its  not working.  You should run through these and adjust them though so we can use them.

**Comment by phillipmadsen** [comment]
You should add this to your instruction so pple can understand this part also.

Great to speak with you again also

**Comment by vishalinfyom** [comment]
Hello @phillipmadsen 

Given issue is fixed here : https://github.com/InfyOmLabs/laravel-generator/commit/d16ea348da40698ebae25e6b1b366899e54faa6f
