### ISSUE TITLE
Website impossible to read because of low contrast text

### ISSUE THREAD

**Issue by COLABORATI** [InfyOmLabs/laravel-generator#467]
Your actual product seems to be of high quality, however the website is showing some typical low quality indicators, especially you are using very **low contrast text** on your website - what started as a funny design idea many years ago is now copied over and over again by people without any knowledge of visibility design - this is a very bad thing and you should not follow that trend - it is an indicator of low quality brain when people publish text that is not readable. I am sure you do not want people to think like this about your products! 

Please add some contrast to your website text - do not listen to your "designer" - also please read http://contrastrebellion.com/

**Comment by mitulgolakiya** [comment]
@COLABORATI thanks for the suggestion. I tried to update some CSS and colors.

Also, we have a plan to upgrade to the totally new theme in near future. so will try to keep it in mind next time that we use contrast text theme.
