### ISSUE TITLE
laravel 5.5 ?

### ISSUE THREAD

**Issue by yuandalu** [InfyOmLabs/laravel-generator#470]
laravel 5.5 ?

**Comment by john5db** [comment]
waiting

**Comment by mitulgolakiya** [comment]
As laravel 5.5 is now released, I will start working on it soon.

**Comment by mitulgolakiya** [comment]
@yuandalu @john5db @devaescasio @advisor- @danielpuent3, @jilster @chrisye909 @cyrlx

Hello Guys, I just pushed support for Laravel 5.5 in to` develop` branch with Datatables 8.0. Also updated docs to for 5.5. (http://labs.infyom.com/laravelgenerator/docs/develop/installation).

I haven't got proper time to test it. Will be testing later today but you guys are most welcome to test it whenever you get time and report any bugs if you found.

Will be waiting to hear you guys :)

**Comment by devaescasio** [comment]
@mitulgolakiya 

Great!!! and big thanks for this.  Yeah, I've noticed yajra datatables exporting to pdf has errors too.

If you don't mind please make old() works too in your based repository so it could used only 1 fields.blade.php.

Thanks once again,

**Comment by mitulgolakiya** [comment]
@devaescasio ok, will check it out and will try to get it fixed.

**Comment by mrarticuno** [comment]
@mitulgolakiya Very nice, but found that the plurals are wrong for some reason.

For example, if I create a table Noticia related with a Categoria in my DB this is how he output the releationship:
Noticia Model:
![image](https://user-images.githubusercontent.com/3270231/30306134-fcb610a6-974c-11e7-9003-a6d9b98a1caf.png)
Categoria Model:
![image](https://user-images.githubusercontent.com/3270231/30306159-1381d298-974d-11e7-892d-9882cfc155e0.png)


Any idea why this is happening and how I can solve this ?

**Comment by sloothword** [comment]
To get it to work under 5.5 i had to change `->getQualifiedForeignKeyName()` to `->getQualifiedForeignKey()` everywhere in `BaseRepository->updateRelations`.

**Comment by mitulgolakiya** [comment]
Closing in Ref of #513
