### ISSUE TITLE
Datatables 8

### ISSUE THREAD

**Issue by dhcmega** [InfyOmLabs/laravel-generator#472]
Hi

Generated code is not DataTables 8 compatible and v8 is needed for Laravel v5.5

https://yajrabox.com/docs/laravel-datatables/master/upgrade

Thanks!

Edit: 
This is what I had to do to make it work again.

1) In \App\DataTables\MyClassDataTable.php

added:

```
use Yajra\DataTables\DataTables;

    protected $datatables;

    public function __construct(DataTables $dataTables)
    {
        $this->datatables = $dataTables;
    }
```

Because this instantiation was removed form the extended DataTable class.

**Comment by Corys8646** [comment]
Thanks for this..Was able to upgrade to L5.5 and Yajra 8.0 last night.

**Comment by mitulgolakiya** [comment]
@dhcmega thanks for this. I had already started working on Datatables 8 with laravel 5.5. It will be available soon.

**Comment by mitulgolakiya** [comment]
@dhcmega @Corys8646 Datatables 8.0 support is added with Laravel 5.5. It's still under testing and development. But you are most welcome to test if you want and report any possible bugs.

You can find docs [here](http://labs.infyom.com/laravelgenerator/docs/develop/installation).
