### ISSUE TITLE
Undefined index: schema.table

### ISSUE THREAD

**Issue by aliasdoc** [InfyOmLabs/laravel-generator#473]
Hi,

When I try to generate from table with this command:

`php artisan infyom:scaffold Consumer --fromTable --tableName=authorization.OAUTH2_CONSUMER`

It return this error:
`[ErrorException]                                
  Undefined index: authorization.OAUTH2_CONSUMER`

My table DDL (PostgreSQL 9.6):
```

CREATE TABLE "authorization"."OAUTH2_CONSUMER" (
	"ID" int4 NOT NULL DEFAULT nextval('"authorization"."OAUTH2_CONSUMER_ID_seq"'::regclass),
	"TYPE" varchar(256) NOT NULL,
	"NAME" varchar(256) NOT NULL,
	"URL" varchar(256) NULL,
	"REDIRECT_URL" varchar(256) NULL,
	"ICON" varchar(256) NULL,
	"DESCRIPTION" varchar(2048) NULL,
	"CLIENT_ID" varchar(256) NOT NULL,
	"CLIENT_SECRET" varchar(256) NOT NULL,
	"ISSUED_AT" timestamp NULL,
	"EXPIRES_IN" int4 NULL,
	"CREATED_AT" timestamp NOT NULL,
	"UPDATED_AT" timestamp NOT NULL,
	CONSTRAINT oauth2_consumer_pk PRIMARY KEY ("ID")
)
WITH (
	OIDS=FALSE
) ;

```

What is the problem ??

Thanks.

EDIT:

Error is caused in `TableFieldsGenerator.php `
```

-- TableFieldsGenerator.php --
...
 private function checkForRelations($tables)
    {
        // get Model table name and table details from tables list
        dump($tables);
        echo $modelTableName."\n";
        $modelTableName = $this->tableName;
        $modelTable = $tables[$modelTableName];  <--- ERROR

...


```

dump of `$tables`  content:
```

 "authorization."OAUTH2_CONSUMER"" => InfyOm\Generator\Utils\GeneratorTable {#1031
    +primaryKey: "ID"
    +foreignKeys: []
  }

```
error is caused by quotes around OAUTH2_CONSUMER -> `"authorization."OAUTH2_CONSUMER ""`
and `$modelTableName` = `authorization.OAUTH2_CONSUMER`

**Comment by zhekaus** [comment]
I've got the same problem. Have you solved it already?

**Comment by mitulgolakiya** [comment]
@aliasdoc I am not sure if it's fully compatible with postgres.
Can you try to give just a table name only without schema? and give a schema in a database configuration file?

**Comment by aliasdoc** [comment]
Hi @mitulgolakiya, I resolve my problem, error is caused by quotes around OAUTH2_CONSUMER -> `"authorization."OAUTH2_CONSUMER ""`
and `$modelTableName` = `authorization.OAUTH2_CONSUMER`
