### ISSUE TITLE
Seeder Faker Integration!

### ISSUE THREAD

**Issue by chriscalip** [InfyOmLabs/laravel-generator#480]
who wants it? can we have it?

**Comment by mitulgolakiya** [comment]
@chriscalip can we get some more information on this, what is the exact requirement?
@dmassiani @VictorGorban

**Comment by vishalinfyom** [comment]
@chriscalip Support added : 

https://github.com/InfyOmLabs/laravel-generator/issues/964#issuecomment-888851391
