### ISSUE TITLE
ErrorException

### ISSUE THREAD

**Issue by devaescasio** [InfyOmLabs/laravel-generator#483]
During installation of fresh Laravel 5.5 and Infyom - Laravel generator 5.5

`php artisan infyom.publish:layout`

`  [ErrorException]
  copy(C:\Dev\Laravel\HRIS\vendor/infyomlabs/core-templates/templates/scaffold/layou
  ts/app.stub): failed to open stream: No such file or directory
`
upon checking directory there's no such file "core-templates" in "vendor/infyomlabs/"

**Comment by et-nik** [comment]
Change config. Replace 'teplates' parameter from 'core-templates' to 'adminlte-templates' in laravel_generator.php config. Default parameter have a deprecated value.

I also create pull request -- https://github.com/InfyOmLabs/laravel-generator/pull/482
