### ISSUE TITLE
Error in generate views with scaffold

### ISSUE THREAD

**Issue by vanessasoutoc** [InfyOmLabs/laravel-generator#485]
[ErrorException]                                                                                                            
  file_get_contents(/home/vanessa/Projetos/mazzatechteste/vendor/infyomlabs/core-templates/templates/scaffold/views/blade_ta  
  ble_body.stub): failed to open stream: No such file or directory  

help me

**Comment by vanessasoutoc** [comment]
add in to composer.json 
required-dev{
"infyomlabs/core-templates": "5.3.x-dev"
}

**Comment by mitulgolakiya** [comment]
yes, @vanessasoutoc. core-templates are deprecated and no longer maintained. You can use adminlte templates instead of that.
