### ISSUE TITLE
How to config to show first table's column in index view

### ISSUE THREAD

**Issue by tranghaviet** [InfyOmLabs/laravel-generator#486]
Hi there,

How to config to show first table's column in index view instead of modify index view (like below) when use scaffold.
`index.blade.php`
```
...
<thead>
        <tr>
            <th>ID</th>// must add this
            <th>Name</th>
            <th>Display Name</th>
            <th>Description</th>
            <th colspan="3">Action</th>
        </tr>
    </thead>
@foreach($roles as $role)
        <tr>
            <td>{!! $role->id !!}</td>// must add this
            <td>{!! $role->name !!}</td>
            <td>{!! $role->display_name !!}</td>
            <td>{!! $role->description !!}</td>
...
```

**Comment by mitulgolakiya** [comment]
@tranghaviet I think you can [publish templates](http://labs.infyom.com/laravelgenerator/docs/5.5/publish-templates) and do these modifications and that' how you can have this in your `index.blade.php`.

Let me know if this helps.

**Comment by mitulgolakiya** [comment]
Closing this issue. Please re-open it if needed.
