### ISSUE TITLE
php artisan infyom:api $MODEL_NAME --paginate=10    invalid 

### ISSUE THREAD

**Issue by zhaomengqiao** [InfyOmLabs/laravel-generator#488]
No difference is found with no paginate

**Comment by zhaomengqiao** [comment]
limit:Limit the number of returned results
search:Global search on all searchable fields
offset:Offset from where results should be returned
sortedBy:Sort result by given field

How do I use this

**Comment by zhaomengqiao** [comment]
laravel 5.5

**Comment by tehuel** [comment]
are you replacing $MODEL_NAME with the actual name of the model you want to generate?

**Comment by mitulgolakiya** [comment]
@zhaomengqiao can you post the exact command that you are trying to run?

**Comment by hi-man** [comment]
it's adminlte known issue  https://github.com/InfyOmLabs/adminlte-templates/issues/2

**Comment by mitulgolakiya** [comment]
completed and merged in templates repo.
