### ISSUE TITLE
Consider integrating datatable select plugin to the template?

### ISSUE THREAD

**Issue by Trexology** [InfyOmLabs/laravel-generator#489]
As the title suggested?

add
 '<script src="https://cdn.datatables.net/select/1.2.3/js/dataTables.select.min.js"></script> '
to datatable_js.blade?

**Comment by mitulgolakiya** [comment]
@Trexology you can do it by your self. You can publish templates and add whatever you want into that and use those templates.

[Here](http://labs.infyom.com/laravelgenerator/docs/5.5/publish-templates) is the docs for that.

Once your templates are published, you can add this plugin into it and delete all unmodified template files. Then try to generate the scaffold, it will use your published templates.

As this plugin is not required by all the users, we can't directly add it to the template.
