### ISSUE TITLE
Remove dependency to infyomlabs/adminlte-templates

### ISSUE THREAD

**Issue by tehuel** [InfyOmLabs/laravel-generator#490]
I think the generator should work without this template package, and adding it should be optional.

The scaffold generator could just generate basic html, and be able to customize it by publishing files.

(If this is currently possible sorry for the unnecessary issue, and please help me to make it work that way.)

**Comment by mitulgolakiya** [comment]
@tehuel It's already possible, you can use any customized package and specify it in [`config/laravel_generator.php => templates`](https://github.com/InfyOmLabs/laravel-generator/blob/5.5/config/laravel_generator.php#L80)

And as this package is not added into composer.json dependency of this package and added as an external dependency. so you can use any other template package with it/

We already had several packages in past but it was really difficult to keep every package up to date with each and every change. so we just deprecated all packages and focused on only adminlte packages.

You can find other packages here and you can try to implement your own packages and use them in your package if you are using any other theme.

- [flatlab-templates](https://github.com/InfyOmLabs/flatlab-templates)
- [metronic-templates](https://github.com/InfyOmLabs/metronic-templates)
- [core-templates](https://github.com/InfyOmLabs/core-templates)
