### ISSUE TITLE
Filtering by date range

### ISSUE THREAD

**Issue by dhcmega** [InfyOmLabs/laravel-generator#492]
Hi all, this is how I am filtering by date range. 

1) Data tables class, in my case GuestsDataTables.php

```
 public function query()
    {
        $guests = Guest::query();

        if(!is_null(request()->start_date)) {
            $guests->where('created_at', '>=', request()->start_date);
        }
        if(!is_null(request()->end_date)) {
            $guests->where('created_at', '<=', request()->end_date);
        }
        
        $guests->with('extras')->select('guests.*');

        return $this->applyScopes($guests);
    }
```

```
    public function html()
    {
        $attributes = ['data' => 'function(d) {
            d.start_date = $("#start_date").val();
            d.end_date = $("#end_date").val();
         }'];
        return $this->builder()
            ->columns($this->getColumns())
            ->addAction(['width' => '15%'])
            ->ajax($attributes)
            ->parameters([
                'dom' => 'Bfrtip',
                'scrollX' => true,
                'language' => [
                    'url' => asset('json/Spanish.json')
                ],
                'buttons' => [
                    'reset',
                    'reload',
                    'start_date',
                    'end_date',
                    [
                        'extend' => 'collection',
                        'text' => '<i class="fa fa-download"></i> Exportar',
                        'buttons' => [
                            'csv',
                            'excel',
                            'pdf',
                        ],
                    ],
                ],
                'order' => [[9, 'desc']],
            ]);
    }
```

2) Then the published js from the package datatables ('vendor/datatables/buttons.server-side.js')

```
    DataTable.ext.buttons.start_date = {
        className: 'buttons-reload',

        text: function (dt) {
            return 'Desde <input id="start_date" name="start_date" type="date">';
        },

        action: function (e, dt, button, config) {
            dt.draw(false);
        }
    };
    
    DataTable.ext.buttons.end_date = {
        className: 'buttons-reload',

        text: function (dt) {
            return 'Hasta <input id="end_date" name="end_date" type="date">';
        },

        action: function (e, dt, button, config) {
            dt.draw(false);
        }
    };
```

I publish this in case is useful for someone else.

But want I would like to know, is if there is a better way of doing it.
How are you doing it? How can I improve it? Is the "correct" way of doing it?

Thanks!

Edit 1:
Them problem with the above code is that what I have done works ok for buttons, but for dropdowns, datepickers and checkboxes doesn't work properly.

I found out that there is a blade for creating custom filters, yay, this is the file https://github.com/yajra/laravel-datatables-demo/blob/master/resources/views/datatables/collection/custom-filter.blade.php

I don't know where to add it or call it, any hint?
Thanks again.

Edit 2:
Ok, so it turns out that the custom-filter is just an HTML code you add to the index.blade. Now the problem is that the form is being actually submitted instead of redrawing, the code for doing it should be something like:

```
                'initComplete' => "function() {
                    $('#search-form').on('submit', function(e) {
                        this.draw();
                        e.preventDefault();
                    });
                }"
```
But it doesn't work, as said, it submits.

Edit 3:
I just need to find a way for this code to work with laravel-generator: https://datatables.yajrabox.com/collection/custom-filter

Edit 4:
This is how I trigger a table reload:
`$('.dataTable').DataTable().ajax.reload();`

**Comment by mitulgolakiya** [comment]
Closed. more of a question for datatables and out of scope for a generator.
