### ISSUE TITLE
generator ignores a foreign key name when imports table

### ISSUE THREAD

**Issue by zhekaus** [InfyOmLabs/laravel-generator#493]
In case of importing tables from the database, the generator ignores an actual foreign key column name and always supposes that it’s equal to `concat('tableName', '_id')`.
It’s quite cumbersome to fix all the foreign key column names throughout the generated API if they don’t comply to the default Eloquent behavior.

**Comment by ajayinfyom** [comment]
Reference of: #475

**Comment by mitulgolakiya** [comment]
fixed.
