### ISSUE TITLE
How to add custom row button in datatables

### ISSUE THREAD

**Issue by venkstas** [InfyOmLabs/laravel-generator#494]
Hi there!

I have build datatables of Articles for example.
However what I need is a button on each record in the datatable : Activate/Deactivate (for example)
Which will trigger some ajax/js func etc.
I also need to add some functions to convert the column data.
For example I have title in the columns.But what if I need to strtoupper($title) for example?

How can I do these things?
I can see that there is a method getColumns in the DataTableClass but there is not much of information.

**Comment by ShaileshInfyom** [comment]
yes, you can add it. please follow this step.

* you can find `getColumns` method in to datatable classs which is generated by generator.
* add column in that array. for ex. ` 'Activate' => ['name' => 'activate', 'data' => 'activate'],`
so, your method should be display like
```
  private function getColumns()
    {
        return [
            'name' => ['name' => 'name', 'data' => 'name'],
            'Activate' => ['name' => 'activate', 'data' => 'activate'],
            'date' => ['name' => 'date', 'data' => 'date']
        ];
    }
```

* Now find `ajax()` method. it place at top in class.
 you can edit column like. see below example.. whatever html you can add here.
```
 ->editColumn('activate', function ($data) {
                return '<input type="checkbox" id="chk_id"  class="group-checkable" value="' . $data->id . '">';
            })
```

so, finally `ajex()` method should be look like
```
 public function ajax()
    {
        return $this->datatables
            ->eloquent($this->query())
            ->addColumn('action', 'news.datatables_actions')
            ->editColumn('activate', function ($data) {
                return '<input type="checkbox" id="chk_id"  class="group-checkable" value="' . $data->id . '">';
            })
            ->make(true);
    }
```
