### ISSUE TITLE
Tinyint(4) is imported as boolean

### ISSUE THREAD

**Issue by zhekaus** [InfyOmLabs/laravel-generator#497]
When I generate API using existing table in MySQL Database,  `tinyint(4)` is imported as `boolean` instead of `tinyInteger`.  

`tinyint(4)` must be imported as `tinyInteger`,
`Boolean` = `tinyint(1)`

**Comment by vishalinfyom** [comment]
@zhekaus We are using `doctrine/dbal` package to get tables columns and its types, the package it self return type `boolean` for datatype `tinyint` thats why its happen.
