### ISSUE TITLE
Radio field isn't generating properly

### ISSUE THREAD

**Issue by mdmahbubhelal** [InfyOmLabs/laravel-generator#505]
Field definition:

`{
        "name": "type",
        "dbType": "boolean",
        "htmlType": "radio,Company:1,Trader:0",
        "validations": "required",
        "searchable": true,
        "fillable": true,
        "primary": false,
        "inForm": true,
        "inIndex": true
    }`

[https://imgur.com/m7p1zaJ](url)

**Comment by mitulgolakiya** [comment]
@mdmahbubhelal Can you post some more details? I am not able to figure out what's the problem. Because it's already working fine.
