### ISSUE TITLE
Activate DataTable option for generated CRUD views

### ISSUE THREAD

**Issue by mahmoodkohansal** [InfyOmLabs/laravel-generator#506]
Hi, is there any way to add datatable features like sort columns and search in table to old generated views?
I forgot adding laravel datatable package and enable option before generating many scaffold views and now I need my views have datatable options. Is there any easy solution?

**Comment by mitulgolakiya** [comment]
I'm not sure. but I do not see any easy solution here because blade and datatables are totally separate things.
