### ISSUE TITLE
Can't install bootstrap templates 

### ISSUE THREAD

**Issue by Keiron** [InfyOmLabs/laravel-generator#507]
Problem 1
    - The requested package infyomlabs/core-templates 5.5.x-dev exists as infyomlabs/core-templates[5.1.x-dev, 5.2.x-dev, 5.3.x-dev, dev-data_tables, dev-develop, dev-master, dev-refactoring_for_eloquent_rules] but these are rejected by your constraint.

**Comment by mgr1286** [comment]
Same issue with core templates.
Laravel version 5.6
It's occurring while composer update after changing the template in composer.json.

**Comment by flamreal** [comment]
2019
issue still here

**Comment by mitulgolakiya** [comment]
@Keiron @mgr1286 @flamreal bootstrap templates are no longer maintained. Try to use adminlte templates.

**Comment by mitulgolakiya** [comment]
Here is the post about that. https://blog.infyom.com/adminlte-templates-in-mainstream-development-for-laravel-generator
