### ISSUE TITLE
Many To Many Relationships

### ISSUE THREAD

**Issue by mostadev** [InfyOmLabs/laravel-generator#509]
I've an existing migrations and tables created already and i used these statements in scaffolding
php artisan infyom:scaffold Site --fromTable --tableName=sites

Site Model has a many to many relationship with Providers Model via sites_providers table and i already defined this relation within Post Model

The Problem is where/how to define this relation within update / create functions till now i used the traditional method that i made them within SiteController but i want to define it within model to use it within the API when i create it for this Model....

**Comment by mitulgolakiya** [comment]
@mostadev I think this more of user-defined things that how you want to store your data. so closing it. If any particular or more specific general use case is there, which I'm missing then re-open the issue with specific example.
