### ISSUE TITLE
Can be assign relations? Or new feature?

### ISSUE THREAD

**Issue by NightZpy** [InfyOmLabs/laravel-generator#51]
Would be good relations can be assigned by command or json!

Maybe:  

`php artisan infyom:scaffold Post --relations="hasMany(Comment), belongsTo(User)"`

Or

`php artisan infyom:scaffold Post --hasMany=Comment --belongsTo=User`

**Comment by mitulgolakiya** [comment]
We already have this on list.

**Comment by NightZpy** [comment]
Oh, so good! :dancer:

**Comment by codingquark** [comment]
I was going to start work on this feature, but since you already have it on the list, I would be glad to help.

**Comment by NightZpy** [comment]
I can see the list? Is public? Where is? :D

**Comment by codingquark** [comment]
There is some progress on this I have made. The package internally uses [fractal](http://fractal.thephpleague.com/). Hence, using presenters and transformers, we can include the relationships.

**Comment by gsc89** [comment]
Created another issue not to ask for this as a feature but to ask how people are "currently" dealing with them.

Obviously such a feature will take a long time to add so me waiting for that is not going to work which is why I asked about how people deal with them now. 

These are how my pages are looking now:

Datatable with child rows to show BelongsToMany: http://i.imgur.com/baTsjhg.png

Edit page I am still working on but I think you get the idea?: http://i.imgur.com/QZGClLr.png

**Comment by NightZpy** [comment]
@gsc89 would share your code?

**Comment by gsc89** [comment]
@NightZpy I am still working on it, its not in any fit state to be released / shared at this time, and as it is specific code to the system I am working on as I said it means its not something that can be plugged and played into any system this is the whole problem with relationships.

**Comment by mitulgolakiya** [comment]
@NightZpy @codingquark @gsc89 It's almost completed. It's still just supporting adding relationship functions in model. Creating views for various relationship type is next thing to work.
You can check code in develop branch. I will share docs soon.

**Comment by NightZpy** [comment]
@mitulgolakiya, thanks for that! I will soon test this feature and join to vuejs! <3

**Comment by mitulgolakiya** [comment]
@NightZpy What my plan is, if we can separate out VueJs support with a total separate package, like we have for bootstrap, adminlte, metronic etc. Then it will good.

I am going to review the whole process in detail of VueJs and then will come up with some solution and will post it in issue #171.

**Comment by NightZpy** [comment]
@mitulgolakiya Of course, is better choice. Currently the vuejs crud procces have more features for support relations. I can share to you (it's in a private project for a client)!

**Comment by mitulgolakiya** [comment]
@NightZpy great. I know that CRUD generation for VueJs also needs some more steps than regular generator classes of blade.

But I am thinking to add support to extend it, so it can be possible with it. Still not any robust plan, but it's in a queue. :)

**Comment by NightZpy** [comment]
Really the new steps:
- install packages in the package.json with npm install.
- (in my way) add crud.js to every index file that use vuejs and config.js (file with specific config for the current model).

I 'll give you access so you can see!

**Comment by NightZpy** [comment]
@mitulgolakiya remember that vuejs is agnostic to frontend styels, can be used with metronic, bootstrad, etc...

One package for every css framework for vuejs.

**Comment by philtweir** [comment]
If it would be useful, I found guidocella/eloquent-populator pretty essential for faking when using relations - can prepare a PR if that's something that would be acceptable as an optional dep?
