### ISSUE TITLE
Multiple datatables in one view

### ISSUE THREAD

**Issue by jagroop** [InfyOmLabs/laravel-generator#510]
is there any possible workaround to render multiple tables on single view
the way we do for single table:

```return $bookDataTable->render('books.index');```

dependencies : 

        "infyomlabs/laravel-generator": "5.5.x-dev",
        "laravelcollective/html": "^5.5.0",
        "infyomlabs/adminlte-templates": "5.5.x-dev",
        "spatie/laravel-permission": "^2.7",
        "yajra/laravel-datatables-oracle": "~8.0",
        "yajra/laravel-datatables-buttons": "^3.1"

thanks !

**Comment by mitulgolakiya** [comment]
@jagroop not sure you figured it out, but this is more of the question for yajra datatables package. Maybe that's where you can get a better and quick answer.
