### ISSUE TITLE
Generated tests to use the Tests Namespace

### ISSUE THREAD

**Issue by morrismukiri** [InfyOmLabs/laravel-generator#516]
I get a `PHP Fatal error:  Class 'TestCase' not found in` error on a newly created API and Repository test generated by api_scaffold

The TestCase class and the trait CreatesApplication are in the `namespace Tests`. 

My autoload-dev looks like this:
```
"autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        },
        "classmap": [
            "tests/TestCase.php",
            "tests/ApiTestTrait.php",
            "tests/traits"
        ]
    },
```

**Comment by mitulgolakiya** [comment]
After this fix, anyone who wants to fix this will need to delete `config/infyom/laravel_generator.php` and run `php artisan vendor:publish` command to publish a new file.

If you have modified config file then take a back of that file first, then apply those changes again to `config/infyom/laravel_generator.php`
