### ISSUE TITLE
updateRelations looks for relation using the variable name.

### ISSUE THREAD

**Issue by dhcmega** [InfyOmLabs/laravel-generator#517]
Hi
This is the code from BaseRepository:

```            
if (isset($model) &&
     method_exists($model, $key) &&
     is_a(@$model->$key(), 'Illuminate\Database\Eloquent\Relations\Relation')
) {
```

for the case of group_id (a belongsTo relation) it will not work, as the relation is called group.
Am I correct?
I changed the name to group, now it works, but collective didn't find the value, so I have to add code to each of my many select dropdowns to use group instead of group_id to set the original value before the update.

Is there a better way to solve this?
Thanks!

**Comment by dhcmega** [comment]
Ok, something really weird is happening now.
```
(1/1) FatalThrowableErrorType error: Too few arguments to function App\Models\Menu::unread(), 0 passed in vendor/infyomlabs/laravel-generator/src/Common/BaseRepository.php on line 51 and exactly 1 expected
--
in Menu.php line 190
at Menu::unread()in BaseRepository.php line 51
```
Line 51 is the line above, in my first post.
```
is_a(@$model->$key(), 'Illuminate\Database\Eloquent\Relations\Relation')
```
It's actually calling the method. I don't understand why or how. But this is very risky as this `updateRelations` would be calling all methods?

This is happening with version 5.5.x-dev

**Comment by ajayinfyom** [comment]
We published our custom Base Repository pattern and removed use of Prettus/l5-repository pattern.
