### ISSUE TITLE
Non-searchable field is searchable in DataTable

### ISSUE THREAD

**Issue by skys215** [InfyOmLabs/laravel-generator#521]
Hi,
I've set a field as non-searchable, i.e. `"searchable": false`.
Then the scaffold doesn't add this field as searchable in the repository file, which is right.
The problem is, when I type something in the search box of DataTable, it will still search this non-searchable field.

After investigation, I found that:
1. [$MODEL_NAME$DataTable.php](https://github.com/InfyOmLabs/laravel-generator/blob/0e1cfa1ee1e0a888eda7aba4e36c80a475352c40/templates/scaffold/datatable.stub#L5) is not using repository in the `query` function, [it is using model](https://github.com/InfyOmLabs/laravel-generator/blob/0e1cfa1ee1e0a888eda7aba4e36c80a475352c40/templates/scaffold/datatable.stub#L32), which has no any settings releated to `searchable`.
Possible solution: use `Repository` rather then `Model` in `query` function of `$MODEL_NAME$DataTable.php` file. 
2. Also in the `$MODEL_NAME$DataTable.php` file, in the `getColumns` function, it has not set 
 the field as `'searchable'=>false`.
Possible solution: add `searchable` while generating `$MODEL_NAME$DataTable.php` file in [here](https://github.com/InfyOmLabs/adminlte-templates/blob/develop/templates/scaffold/views/datatable_column.stub).
3. Found this after further investigation, [controller.stub](https://github.com/InfyOmLabs/laravel-generator/blob/d0ee6d048f62e5385fb36dd51e806ad09146ac7a/templates/scaffold/controller/controller.stub#L32) is using `RequestCriteria`, but `datatable_controller.stub` is not using `RequestCriteria` since the first commit.
Possible solution: also add `RequestCriteria` into the datatable_controller. I can't think of the situation which doesn't need `RequestCriteria`right now. Maybe there's some reason that why didn't add the `RequestCriteria` at first.

Hope to see you reply soon.

**Comment by skys215** [comment]
@mitulgolakiya 
Is this a bug or a feature？

**Comment by mitulgolakiya** [comment]
@skys215 we have fixed searchable thing. On using a repository, I would leave it up to the user, if he wants to use, he can publish templates and do it by himself. since it's a purely choice of the user. Even lots of people requested to get rid of the repository pattern but unfortunately, so far, we do not have that option.

**Comment by skys215** [comment]
OK, thanks for the fix.

**Comment by maybe0608** [comment]
how can we publish templates i always have error when i run this command : php artisan infyom.publish:templates
