### ISSUE TITLE
controller not found in GeneratorBuilderController

### ISSUE THREAD

**Issue by morningmemo** [InfyOmLabs/laravel-generator#522]
namespace InfyOm\GeneratorBuilder\Controllers;

use App\Http\Controllers\Controller as Controller;
use Artisan;
use File;
use InfyOm\GeneratorBuilder\Requests\BuilderGenerateRequest;
use Response;

class GeneratorBuilderController extends Controller
{
...

If I change the name of the app and the app name used in my application's controller is abc,
the above code can not find the controller and I get an error.
It seems that the controller namespace should be modified to the value set in my config file.

**Comment by RayhanYulanda** [comment]
If you want to ask about Generator GUI  Builder you should ask [here ](https://github.com/InfyOmLabs/generator-builder)

**Comment by ShaileshInfyom** [comment]
@morningmemo this issue is not valid here. please follow this comment https://github.com/InfyOmLabs/laravel-generator/issues/522#issuecomment-725142651 if you still getting
