### ISSUE TITLE
Generated API JSON encode fails when POSTING w/ foreign key violation

### ISSUE THREAD

**Issue by perezale** [InfyOmLabs/laravel-generator#525]
- Laravel Version: 5.5
- PHP Version: 7.1.7
- Database Driver & Version: PostgreSQL 9.4.13

### Description:
Performing an API Post on a resource including a wrong foreign key cannot output the correct error message.
The JSON message is that it failed encoding the error. Outputs: 'Malformed UTF-8 characters'
I had to change sent headers to Accept html instead of JSON to find out that it was a foreign key problem, as html output is Ok.

### Steps To Reproduce:
Perform an API Post with wrong foreign key with headers:
[{"key":"Content-Type","value":"application/json","description":""},{"key":"Accept","value":"application/json","description":""}]

### Example output when using Accept: application/json
`{
    "message": "Uncaught InvalidArgumentException: Malformed UTF-8 characters, possibly incorrectly encoded in /var/www/vendor/laravel/framework/src/Illuminate/Http/JsonResponse.php:71\nStack trace:\n#0 /var/www/vendor/symfony/http-foundation/JsonResponse.php(50): Illuminate\\Http\\JsonResponse->setData(Array)\n#1 /var/www/vendor/laravel/framework/src/Illuminate/Http/JsonResponse.php(27): Symfony\\Component\\HttpFoundation\\JsonResponse->__construct(Array, 500, Array)\n#2 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(434): Illuminate\\Http\\JsonResponse->__construct(Array, 500, Array, 192)\n#3 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(185): Illuminate\\Foundation\\Exceptions\\Handler->prepareJsonResponse(Object(Illuminate\\Http\\Request), Object(InvalidArgumentException))\n#4 /var/www/app/Exceptions/Handler.php(47): Illuminate\\Foundation\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(InvalidArgumentException))\n#5 /var/www/vendor/laravel/framework",
    "file": "/var/www/vendor/laravel/framework/src/Illuminate/Http/JsonResponse.php",
    "line": 71,
    "trace": []
}`

### Example output without using Accept: application/json
lluminate \ Database \ QueryException (23503)
SQLSTATE[23503]: Foreign key violation: 7 ERROR: insert or update on table "statuses" violates foreign key constraint ... (continues w/ laravel 5.5 HTML error message)

Edit: PUT requests with wrong foreign key & accepting application/json  respond correctly in valid JSON. So it's happening only with POST requests. 
Just to mention, fields and field data is pure english ,dates and uuids. (no special chars)

**Comment by mitulgolakiya** [comment]
I would leave this up to the developer, because a developer may have a pretty good idea, what other complex validations he should put. so after the CRUD generation, it should be managed manually.
