### ISSUE TITLE
AdminLTE Menu not working

### ISSUE THREAD

**Issue by zorrigas** [InfyOmLabs/laravel-generator#527]
Menu not working on last version of laravel-generator with AdminLTE, to fix need update some files, follow the guide 

https://adminlte.io/docs/2.4/upgrade-guide

**Comment by iscisse** [comment]
Hello Zorrigas, 
I am running Laravel Framework 5.7.23 and PHP 7.2.12
I have created 2 items with the scaffold and i am trying to group them under a collapsible section. How do I make so when a sub item is selected the current tree stays active?
Here i my sample code:
<li class="header">MAIN NAVIGATION</li>
<li class="{{ Request::is('home') ? 'active' : '' }}">
    <a href="/home"><i class="fa fa-dashboard"></i><span>Dashboard</span></a>
</li>
<li class="treeview">
    <a href="#">
      <i class="fa fa-gear"></i> <span>Configuration</span>
      <span class="pull-right-container">
        <i class="fa fa-angle-left pull-right"></i>
      </span>
    </a>
    <ul class="treeview-menu">
    <li class="{{ Request::is('regions*') ? 'active' : '' }}">
        <a href="{!! route('regions.index') !!}"><i class="fa fa-edit"></i><span>Regions</span></a>
    </li>
    
    <li class="{{ Request::is('countries*') ? 'active' : '' }}">
        <a href="{!! route('countries.index') !!}"><i class="fa fa-edit"></i><span>Countries</span></a>
    </li>
    </ul>
</li>
