### ISSUE TITLE
5.5 publish layout error

### ISSUE THREAD

**Issue by phillipmadsen** [InfyOmLabs/laravel-generator#529]
just a heads up from installing 5.5, 

In LayoutPublishCommand.php line 86:

  file_get_contents(/home/vagrant/updash/app/routes/web.php): failed to open stream: No such file or directory

The file is there not sure why the error.  Thought you might want to know.

**Comment by matijakovacevic** [comment]
error is because routes folder was moved to root folder instead of the app/, from a few versions back

**Comment by mitulgolakiya** [comment]
This was fixed as #561
