### ISSUE TITLE
Support Laravel 5.6

### ISSUE THREAD

**Issue by artemirq** [InfyOmLabs/laravel-generator#535]
Laravel 5.6 released c: And i don't update while laravel-generator package support Laravel <= 5.6

**Comment by Shadow2004** [comment]
I see that the pull request for this has passed all checks so when could we expect a release with this in it ?

**Comment by artemirq** [comment]
@Shadow2004 There have been no updates from infyom labs for a long time... Maybe development is abandoned... :(

**Comment by mitulgolakiya** [comment]
@Shadow2004 @artemirq PR merged.

**Comment by mitulgolakiya** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Support for 5.6](https://trello.com/c/BGDPKgzM/1-support-for-56)
