### ISSUE TITLE
Delete scaffold created

### ISSUE THREAD

**Issue by NJV19** [InfyOmLabs/laravel-generator#544]
Is it possible to delete one scaffold created already? Is there any comand or can you let me know which is the best way to delete a complete model created?

Thanks.

**Comment by dhsont** [comment]
you can do that with rollback command passing your model name

ex:
~~~
php artisan infyom:rollback Bus api_scaffold
~~~

**Comment by mitulgolakiya** [comment]
@NJV19 report if something is not working.
