### ISSUE TITLE
Get data from relationship into datable using htmlBuilder

### ISSUE THREAD

**Issue by cesarureno** [InfyOmLabs/laravel-generator#548]
How can get custom data from relationship? I need display country name

<img width="1346" alt="screen shot 2018-04-14 at 02 07 09" src="https://user-images.githubusercontent.com/1313729/38765514-c4a04738-3f88-11e8-9172-fd28bf8cb6cb.png">

**Comment by dhcmega** [comment]
Hi
Use the "with" method on the query to eager load the relation and add the column:

```
'country_id' => ['name' => 'countries.name', 'data' => 'countries.name', 'title' => 'Country'],
```

**Comment by cesarureno** [comment]
Thank you @dhcmega

**Comment by dhcmega** [comment]
@cesarureno Hi, can you please tell which style you've used for the table? I need something like your screenshot. Thanks!

**Comment by cesarureno** [comment]
I used a theme https://pixinvent.com/stack-responsive-bootstrap-4-admin-template/html/ltr/horizontal-menu-template-nav/dt-styling.html

**Comment by mitulgolakiya** [comment]
Blog Post for this: https://blog.infyom.com/how-to-display-relationship-data-into-yajra-datatables-with-infyom-laravel-generator

**Comment by dhcmega** [comment]
@mitulgolakiya 
It might be a good idea to add NAME tag along side with DATA to that post. Even though it's not the scope of the post.

Not doing so, when using search, it will trigger a MySQL error if relation is composed of multiple words.

No including `'name' => 'surveyQuestion.question',` will generate this error:

`Column not found: 1054 Unknown column 'survey_question.question'`

(note the missing S in table's name)

**Comment by mitulgolakiya** [comment]
@dhcmega 
> (note the missing S in table's name)

I didn't get this line.

**Comment by dhcmega** [comment]
Hi! Sorry, maybe I'm wrong. I remember I have tested it and if you don't include the 'name' element in the array, only 'data' with the eloquent relation, when using search feature the table name gets rendered as the relation in snake case in singular, without the final S that the table will probably have.
In my test, the table name is `survey_questions` and the relation is 'surveyQuestion', but it gets converted to 'survey_question.question' and MySQL give and error.
This problem gets solved by also adding 'name' element.
Does it make sense?
Thanks again

**Comment by mitulgolakiya** [comment]
yes.

**Comment by ShaileshInfyom** [comment]
here is [tutorial](How to display relationship data into Yajra DataTables with InfyOm Laravel Generator)

**Comment by shailesh-ladumor** [comment]
here is [tutorial](https://youtu.be/sJrDpFl3Pcw)
