### ISSUE TITLE
Is Vuejs working ?

### ISSUE THREAD

**Issue by JafarAkhondali** [InfyOmLabs/laravel-generator#549]
Hi,
I got confused about VueJs support, There are some commands in cli but there is not documentation in your website and i'm not sure about it's usage and maximum laravel version.

**Comment by JafarAkhondali** [comment]
Laravel version: 5.6
Php: 7.2.3

When i used `infyom:vuejs --fromTable users` command, i got the following error

```

  at /srv/http/AnzimServer/vendor/infyomlabs/laravel-generator/src/Generators/VueJs/ControllerGenerator.php:39
    35|         $i = 0;
    36|         $filter = '';
    37|         $searchableCount = 0;
    38|         foreach ($fields as $field) {
  > 39|             if ($field['searchable']) {
    40|                 $searchableCount++;
    41|             }
    42|         }
    43|         foreach ($fields as $field) {

```

**Comment by yswtrue** [comment]
Same problem.

**Comment by mitulgolakiya** [comment]
@JafarAkhondali @yswtrue @dhsont #375 merged. Can you test it and check if it's working or not. Re-open it if the problem persists.

**Comment by mitulgolakiya** [comment]
Dupliate: #531
