### ISSUE TITLE
... And where view user's?

### ISSUE THREAD

**Issue by kkkasio** [InfyOmLabs/laravel-generator#550]
Good evening, I have a question, your crud generator is wonderful. but I have personal doubts ... I must understand that only the part of the correct admin is generated? for the user I must create the views and routes since the cruds are ready!
Is that correct?

I am referring to who will actually use the application, how should I work it? so far I do not intend to use api, just web, should I create your views manually? Thanks for developing this fantastic package!

**Comment by iscisse** [comment]
I am looking at it. It looks like we have to create them.

**Comment by mitulgolakiya** [comment]
Yes, @iscisse . Based on the user's preference, it should be created by themselves. Maybe they can use `fromTable` option. That will be better because different users can have different choices on blade/datatable, swagger/not, api/scaffold/both etc.
