### ISSUE TITLE
Query filtering in ModelDataTable.php

### ISSUE THREAD

**Issue by dhcmega** [InfyOmLabs/laravel-generator#553]
#Hi
I am trying to understand how to modify the queries.
Method is originaly like this:

```
    /**
     * Get query source of dataTable.
     *
     * @param \App\Models\Post $model
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function query(Vote $model)
    {
        return $model->newQuery();
    }
```

I need to add "with", "select" and "where".
This is the only way I made it work, but seems odd that newQuery has to be in the middle...

```
        return $model->with('poll', 'option', 'account')->newQuery()->where('votes.poll_id', '=', 5)->select('votes.*');
```

Is this the way it should be?

Thanks!

EDIT1:
It seems that the newQuery() method returns an instance that needs to be saved, so:
```
        $model = $model->newQuery();

        $model->with('poll', 'option', 'account');

        $model->where('votes.poll_id', '=', 5);

        return $model->select('votes.*');
```

**Comment by mitulgolakiya** [comment]
seems like already resolved. but more of question of yajra datatables repo.
