### ISSUE TITLE
How to use "orWhere" on findWhere

### ISSUE THREAD

**Issue by lucaswx2** [InfyOmLabs/laravel-generator#559]
I can't find out how to use orWhere method with findWhere method, how can i do it?

**Comment by rylxes** [comment]
example : `findWhere(['active' => '1', 'user_id' => $id])`, where active and user_id are table columns

**Comment by iscisse** [comment]
Hello I am having the same issue.
I have tried :
1- " $this->fournisseurRepository->pushCriteria(new RequestCriteria($request));
 $fournisseurs = $this->fournisseurRepository->findWhere('vendortype_id'','1')->paginate(15);"
2 - "$this->fournisseurRepository->pushCriteria(new RequestCriteria($request));
$fournisseurs = $this->fournisseurRepository->Where('vendortype_id','=','1')->paginate(15);"

So what I did for now I went into table.balde.php and did the following:
 @foreach($fournisseurs as $fournisseur)
    @if( $fournisseur->vendortype_id == '1')

I know this is not the right method but I needed to get my page working for now.
Any help will be great..

**Comment by mitulgolakiya** [comment]
I am not sure, exactly which place `orWhere` on findWhere needs to be used. But overriding repository function would be the best choice.
