### ISSUE TITLE
Override config laravel_generator.php

### ISSUE THREAD

**Issue by gustavovendramini** [InfyOmLabs/laravel-generator#560]
How can I overrride https://github.com/InfyOmLabs/laravel-generator/blob/develop/config/laravel_generator.php without modify the src on vendor?

**Comment by rylxes** [comment]
`php artisan vendor:publish`  should do the work after installation

**Comment by gustavovendramini** [comment]
I mean how do I do my own configuration file, ie have my own laravel_generator.php inside my project.

**Comment by rylxes** [comment]
when you run `php artisan vendor:publish` successfully, you should see the file in your config/infyom folder, you can change that as you like
