### ISSUE TITLE
PostgreSQL generator from Table

### ISSUE THREAD

**Issue by luigimarmo** [InfyOmLabs/laravel-generator#562]
When I try to generate from table with command:
`$ php artisan infyom:scaffold Address --fromTable --tableName=address`
i get following error:

> In AbstractPlatform.php line 479:
> Unknown database type mpaa_rating requested, Doctrine\DBAL\Platforms\PostgreSQL100Platform may not support it.
> 

I'm using laravel 5.5 and "PostgreSQL 10.4 (Ubuntu 10.4-0ubuntu0.18.04) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 7.3.0-16ubuntu3) 7.3.0, 64-bit".
Project dependecies include already "doctrine/dbal": "^2.8"

Anyone can help me?

**Comment by mitulgolakiya** [comment]
@luigimarmo I'm not sure, it's compatible with postgres when you generate from table. Maybe you need to map some field types to different field types. But not sure it will work or not.
