### ISSUE TITLE
findWithoutFail with withTrashed()

### ISSUE THREAD

**Issue by dhcmega** [InfyOmLabs/laravel-generator#563]
Hi
I'm trying to achieve something like this:
```
$menu = $this->menuRepository->withTrashed()->findWithoutFail($id);
```
But I cannot make it work.
Any ideas?
Thanks!

**Comment by mitulgolakiya** [comment]
@dhcmega with new laravel 5.8 release, it should be possible as we have removed the dependency of prettus/l5-repository and base repository file is generated and published to code, so you can override all the CRUD functions as per your need. Check detailed post [here](https://blog.infyom.com/introducing-laravel-58-support-to-infyom-laravel-generator).

![image](https://user-images.githubusercontent.com/1908535/54068033-ad6d4a00-426d-11e9-8f04-2916f71771c9.png)

This is the base repository published to `app/Repositories` folder, you can override `find` method into your `MenuRepository.php` file put withTrashed code there. Even you can do same for `all` method as well.

If it's global then you can do it directly in `BaseRepository.php` as well.
