### ISSUE TITLE
laravel 5.7 support request

### ISSUE THREAD

**Issue by avasiliev87** [InfyOmLabs/laravel-generator#565]
Hello, When would this package support laravel 5.7?

**Comment by mitulgolakiya** [comment]
Soon. We already have a PR for that, I will test it soon and will update the docs.

**Comment by osman-mohamad** [comment]
any changes about this ?

**Comment by upstream-nsk** [comment]
`"infyomlabs/laravel-generator": "dev-master",`
worked for me ;)

**Comment by osman-mohamad** [comment]
@upstream-nsk it is old bransh

**Comment by Zugmaschine** [comment]
"infyomlabs/laravel-generator": "dev-master",
dont work for me ....

**Comment by sagarpatel9697** [comment]
@mitulgolakiya when will we get a package for laravel 5.7

**Comment by mitulgolakiya** [comment]
Merged PR to develop branch. will push docs and another dedicated branch soon.

**Comment by mitulgolakiya** [comment]
added docs as well.
