### ISSUE TITLE
Using Laravel 5.6 with Bootstrap layout. 

### ISSUE THREAD

**Issue by Zugmaschine** [InfyOmLabs/laravel-generator#568]
Anyone have successful installed this setup?
Any Tipps?

**Comment by sagarpatel9697** [comment]
Can you please elaborate your question? Have you tried to set up a package as per instruction in the documentation? Please specify your query in brief so we can help you easily. I m good with the package in Laravel 5.6 and doesn't get any hurdle with an installation process.

**Comment by mitulgolakiya** [comment]
@Zugmaschine bootstrap templates are not actively maintained. Try to use Adminlte-templates.
