### ISSUE TITLE
Datatable: Where to set language for buttons (export, reload, reset, etc)

### ISSUE THREAD

**Issue by dhcmega** [InfyOmLabs/laravel-generator#569]
Hi
I have added the JSON file that translate all messages and texts, but buttons are still in english. How can I translate them too?

```
                'language' => [
                    'url' => asset('js/datatables/json/' . \App::getLocale() . '.json')
                ],
```
Thanks!

**Comment by mitulgolakiya** [comment]
@dhcmega I think this should work. https://github.com/yajra/laravel-datatables/issues/1418
But I would say this is more of question-related to Laravel DataTables package. probably you can find the answer there.

**Comment by dhcmega** [comment]
Hi, I solved like this:

https://github.com/yajra/laravel-datatables/issues/1620
