### ISSUE TITLE
wrong routing to 404

### ISSUE THREAD

**Issue by fmchan** [InfyOmLabs/laravel-generator#570]
i am using 5.4 to apply to my laravel 5.4 project
i just do some simple tests.

```
php artisan infyom:api_scaffold District
name string,30 text
required
```

and routing shows correctly
`GET|HEAD  | districts | districts.index | App\Http\Controllers\DistrictController@index`

however, when i visit /districts, it redirects to 404

**Comment by mitulgolakiya** [comment]
@fmchan can you share some more information on this? as it looks like some configuration problem of your local server as well. Reopen this issue, if you are still facing it, because nobody reported this kind of problem.

**Comment by fmchan** [comment]
> @fmchan can you share some more information on this? as it looks like some configuration problem of your local server as well. Reopen this issue, if you are still facing it, because nobody reported this kind of problem.

i have figured out that there was other route conflicting with this route. problem solved
