### ISSUE TITLE
project too big,400mb,285mb node_modules

### ISSUE THREAD

**Issue by sanjaylama** [InfyOmLabs/laravel-generator#572]
I just installed laravel 5.7 and also installed infyomlabs generator following the instructions.
Clean project have not written anything but project is already 418mb.
It is normal?
This way the project files is going to be very big.
Also how about using adminlte 3? I think it is not using version 3 now.
Can i upgrade it?

**Comment by mitulgolakiya** [comment]
@sanjaylama this is not a question of scope to this package. Just find what folder is taking a space. Because this package has nothing to do with project size.

**Comment by mitulgolakiya** [comment]
I will take AdminLTE 3 as a feature for future.
