### ISSUE TITLE
How to automatically add API route into a Group

### ISSUE THREAD

**Issue by masehitam** [InfyOmLabs/laravel-generator#574]
I realized that swagger leads to endpoints with versioning for example: **_http://127.0.0.1:8000/api/v1/persons_** while my controller is on **_http://127.0.0.1:8000/api/persons_**.
I can make group route on like this, and it solved the problem.
```
Route :: group (['prefix' => 'v1', 'middleware' => 'api'], function () {
     Route :: resource ('persons', 'PersonAPIController');
});
```
but I think there must be a better way than this, without having to manually add every time I create a new controller. is there better way to do this ?

another question is when I make the second version of the API, where do I have to create the code? in the same folder but different names? or with a different folder?

thanks...

**Comment by mitulgolakiya** [comment]
@masehitam kind of late reply. But here is the solution for your first question of not having `v1`. You will see `AppBaseController` and in that, in swagger docs, find `basePath`variable and remove `v1` from there and it should resolve your problem.

About another question of having a separate folder or same folder. It totally depends on how many changes and what changes you are going to have. so you should do that analysis and I think you should find your answer. based on that, either,

1. You can create a separate folder for everything (Repository, Controller etc)
2. Use the same repository but create another folder for Controller with a new namespace called `v2`.
