### ISSUE TITLE
Call to undefined function Swagger\scan()

### ISSUE THREAD

**Issue by GaurangGhinaiya** [InfyOmLabs/laravel-generator#579]
Hi i am using Laravel version 5.7.x. and i follow all step describe [here](http://labs.infyom.com/laravelgenerator/docs/5.7/installation).  And i am getting this [error](http://labs.infyom.com/laravelgenerator/docs/5.7/installation) 
`Call to undefined function Swagger\scan()`

**Comment by mitulgolakiya** [comment]
@GaurangGhinaiya Can you let me know which swagger package you are using? From your composer.lock file?

**Comment by hasmukhkalsariya** [comment]
@mitulgolakiya 
I'm also getting same issue in my project.
I'm using Laravel - 5.7.x and `jlapp/swaggervel` Swagger package.

**Comment by mitulgolakiya** [comment]
@hasmukhkalsariya 
I think this is some compatibility issue in `jlapp/swaggervel`. There is an open PR for that.

You should give a try with this package. `appointer/swaggervel`. Let me know if it works.

**Comment by GaurangGhinaiya** [comment]
@mitulgolakiya @hasmukhkalsariya 
I use this package.  `appointer/swaggervel` and this works fine for me in Laravel 5.7.x

**Comment by mitulgolakiya** [comment]
Then I would close this issue, as it's not related to a generator. But I updated doc to use `appointer/swaggervel` package instead of `jlapp/swaggervel`.
