### ISSUE TITLE
how to make datatable show custom field from joined table

### ISSUE THREAD

**Issue by unitedlover0** [InfyOmLabs/laravel-generator#582]
i have payments datatable with field  'id', 'transaction_id',  'date','amount', 'payment_method_id', 'additional_note'
and payment_methods table with field 'id', 'name'
my question is in payments datatable how to show payment_methods.name instead of payment_method_id?
here the generated datatables https://pastebin.com/P2aVCmKD

nb: probably same with #412  but for me still fail to load joined field

**Comment by mitulgolakiya** [comment]
@unitedlover0 I think this is what you are looking for https://github.com/InfyOmLabs/laravel-generator/issues/548
