### ISSUE TITLE
change route generate code 

### ISSUE THREAD

**Issue by nasservb** [InfyOmLabs/laravel-generator#584]
hi all 
when i try to generate from table system raise error : 
` php artisan infyom:scaffold businesses --fromTable --tableName=businesses`

`Model created:
businesses.php

Repository created:
businessesRepository.php

Create Request created:
CreatebusinessesRequest.php

Update Request created:
UpdatebusinessesRequest.php

Controller created:
businessesController.php

Generating Views...
table.blade.php created
index.blade.php created
field.blade.php created
create.blade.php created
edit.blade.php created
show_fields.blade.php created
show.blade.php created
Views created:

   ErrorException  : file_get_contents(D:\Program Files (x86)\EasyPHP-Devserver-
17\eds-www\laravel-5.7.15\app\Http/routes.php): failed to open stream: No such f
ile or directory

  at D:\Program Files (x86)\EasyPHP-Devserver-17\eds-www\laravel-5.7.15\vendor\i
nfyomlabs\laravel-generator\src\Generators\Scaffold\RoutesGenerator.php:26
    22|     public function __construct(CommandData $commandData)
    23|     {
    24|         $this->commandData = $commandData;
    25|         $this->path = $commandData->config->pathRoutes;
  > 26|         $this->routeContents = file_get_contents($this->path);
    27|         if (!empty($this->commandData->config->prefixes['route'])) {
    28|             $this->routesTemplate = get_template('scaffold.routes.prefix
_routes', 'laravel-generator');
    29|         } else {
    30|             $this->routesTemplate = get_template('scaffold.routes.routes
', 'laravel-generator');

  Exception trace:
`

i search in code and find solve method : 
in this file 
\vendor\infyomlabs\laravel-generator\src\Common\GeneratorConfig.php
line 188
`  $this->pathRoutes = config('infyom.laravel_generator.path.routes', app_path('Http/routes.php'));`
must change to : 
`$this->pathRoutes = config('infyom.laravel_generator.path.routes', base_path('routes/web.php'));`

because in new version of laravel the routes path is changed .
thanks for your fantastic project.

**Comment by mitulgolakiya** [comment]
@nasservb just make sure, you are using the correct version of laravel with correct package version? Can you let me know which package version and which laravel version you are using?

**Comment by nasservb** [comment]
i use all the default setting .
laravel-5.7.15
my composer.json: 
`{
 "require": {
        "php": "^7.1.3",
        "fideloper/proxy": "^4.0",
        "laravel/framework": "5.7.*",
        "laravel/tinker": "^1.0",
	"infyomlabs/laravel-generator": "5.7.x-dev",		
	"laravelcollective/html": "^5.7.0",
	"infyomlabs/adminlte-templates": "5.7.x-dev",
	"infyomlabs/swagger-generator": "dev-master",
	"appointer/swaggervel": "dev-master",
	"doctrine/dbal": "~2.3"
    }
}`
all this setting is wrote on your site 
http://labs.infyom.com/laravelgenerator/
->Get started Button
->installation link in page bottom.
http://labs.infyom.com/laravelgenerator/docs/5.7/installation

i use the last version on laravel. 
and also when i try to add api_routes
that raise the error like that error and i solve that by change  
in this file:
\vendor\infyomlabs\laravel-generator\src\Common\GeneratorConfig.php
line 175
$this->pathRoutes = config('infyom.laravel_generator.path.routes',  app_path('Http/api_routes.php'));
must change to :
$this->pathRoutes = config('infyom.laravel_generator.path.routes', base_path('routes/api.php'));

**Comment by erickhavel** [comment]
Same here, Laravel v5.7.24 and `"infyomlabs/laravel-generator": "5.7.x-dev"`

**Comment by mitulgolakiya** [comment]
@erickhavel have you completed all installation steps? Can you check if there is a file exist `config/infyom/laravel_generator.php` ?

**Comment by mitulgolakiya** [comment]
Should be working now. Closing it.
