### ISSUE TITLE
hasMany create

### ISSUE THREAD

**Issue by JGamboa** [InfyOmLabs/laravel-generator#586]
When creating a model with relations the all save method fails, example:
I have a Document model that hasMany activities

    public function actividadesEconomicas()
    {
        return $this->hasMany('App\Models\Activities');
    }

on the json i do this

{
	"TipoDTE": 33,
	"tipo_documento_id": 1,
	"empresa_id" : 1,
	"fechaEmision": "2018-01-31",
	"total": 25000,

	"activities": 
		[{"acteco": 90001}, {"acteco": 90002}]
	
and the response is :
"Method Illuminate\\Database\\Eloquent\\Collection::save does not exist.",
}

**Comment by JGamboa** [comment]
my proposal to fix this 

when patch (update) it will forcedelete al previus data and then insert the new one.
for new values on create it will make an insert instead of a save

$new_values = array_get($attributes, $key, []);
                        if (array_search('', $new_values) !== false) {
                            unset($new_values[array_search('', $new_values)]);
                        }

                        list($temp, $model_key) = explode('.', $model->$key($key)->getQualifiedForeignKeyName());
                        $i=0;
                        foreach ($model->$key as $rel) {

                            if (!in_array($rel->id, array_column($new_values, 'id'))) {
                                $rel->forceDelete();
                            }

                            foreach($new_values as $index => $values){
                                if(isset($values['id']) && $values['id'] == $rel->id){
                                    $update = $new_values[$index];
                                    foreach($update as $key_update => $value_update){
                                        $rel->$key_update = $value_update;
                                    }
                                    $rel->save();
                                    unset($new_values[$index]);
                                }

                            }
                        }

                        if (count($new_values) > 0) {
                            $related = get_class($model->$key()->getRelated());
                            foreach ($new_values as $val) {
                                $val[$model_key] = $model->id;
                                $rel = new $related();
                                $rel->insert($val);
                                /*
                                $rel = $related::find($val);
                                $rel->$model_key = $model->id;
                                $rel->save();
                                */
                            }
                        }
                        break;

**Comment by ajayinfyom** [comment]
Reference: #452
