### ISSUE TITLE
ENum Fied issue

### ISSUE THREAD

**Issue by pakcybershagufta** [InfyOmLabs/laravel-generator#591]
How we generate enum fields for paramater

**Comment by pakcybershagufta** [comment]
I want Display paramater and value 0 or 1 in enum api call swagger documenattaion? help req

**Comment by mitulgolakiya** [comment]
@pakcybershagufta I have added enum example here. http://labs.infyom.com/laravelgenerator/docs/5.7/getting-started

I will add support into swagger soon for that.

**Comment by mitulgolakiya** [comment]
Right now, you can manually update swagger docs to support that. Here is an example: http://petstore.swagger.io/#/pet/findPetsByStatus

**Comment by pakcybershagufta** [comment]
> Right now, you can manually update swagger docs to support that. Here is an example: http://petstore.swagger.io/#/pet/findPetsByStatus

How manually steps please ?Advance thanks

**Comment by pakcybershagufta** [comment]
I m asking for swagger not for migration?

**Comment by mitulgolakiya** [comment]
@pakcybershagufta the same example is there. Check the swagger doc in above link. https://petstore.swagger.io/v2/swagger.json

![image](https://user-images.githubusercontent.com/1908535/53495091-34c7fa00-3ac5-11e9-90ce-c1b2f8d42e8e.png)

**Comment by pakcybershagufta** [comment]
One more help required how define Authorization: Bearer token

Header (in :header )
Authorization: Bearer token

**Comment by mitulgolakiya** [comment]
I think you should ask this into swagger repo. you will better answer from there.

**Comment by ShaileshInfyom** [comment]
> One more help required how define Authorization: Bearer token
> 
> Header (in :header ) Authorization: Bearer token

you can refer this tutorial https://youtu.be/ytXsvPR0IBA. Feel free to re-open the issue with more details if you are still facing this issue.
