### ISSUE TITLE
How to set default value for create form

### ISSUE THREAD

**Issue by ibakhsh** [InfyOmLabs/laravel-generator#592]
Hi
i am using your awesome generator for crud operations with few tweaks of my own, i see that both create and edit include the fields which is handy in my case, i only need to know how to set the default value for the create form ?

**Comment by mitulgolakiya** [comment]
@ibakhsh If you want to do it from cli while generating a scaffold, then I don't think there is no way right now to do that. Maybe after views generation, you need to do that manually in the code.
