### ISSUE TITLE
Publish swagger templates

### ISSUE THREAD

**Issue by Nohac** [InfyOmLabs/laravel-generator#595]
It is possible to publish normal templates using `php artisan infyom.publish:templates`. Shouldn't there also be an option to publish the swagger templates as well?

**Comment by laravelcoder** [comment]
@nohac 
Swagger templates are not blade files and are generated by the package. I had a problem where they were not working also but found it was a bug in the package template and i fixed it. you can do the same to yours and it should work after at the following url /api/docs 

> Swagger not showing up fix
#596 
Hope it helps you.

**Comment by mitulgolakiya** [comment]
@Nohac Can you describe the reason you want to publish swagger templates?

**Comment by mitulgolakiya** [comment]
@Nohac in the latest version (5.5 or later), when you use `php artisan infyom.publish:templates`, swagger templates are also published under `controller_docs` and `model_docs` directory.
