### ISSUE TITLE
Fix for Swagger Docs

### ISSUE THREAD

**Issue by laravelcoder** [InfyOmLabs/laravel-generator#596]
Here is the fix so you can actually view the swagger api docs on your site like the docs say its is supposed to. 

The docs say to go to yourdomain.com/api/docs to view them but there is a flaw in the vendor index file that is generated when you run the command:

php artisan vendor:publish --tag=views
```
Copied Directory [/vendor/appointer/swaggervel/src/views] To [/resources/views/vendor/swaggervel]
Publishing complete.
```
Simply go to [/resources/views/vendor/swaggervel] and open the index file. 

> Replace all occurrences of this:
```php
$host . $uiResourcePath
```
> with this:
```php
$host .'/'. $uiResourcePath
```
Anyway i have had this problem mulitiple times using swagger and always forget to post the fix. Here you go everyone.

**Comment by mitulgolakiya** [comment]
If it's an edit into a package of swagger docs then I think, it's out of scope for this repo. Closing it.

**Comment by LunarDevelopment** [comment]
Just a quick thank you to @laravelcoder this saved me a fair amount of investigation.
