### ISSUE TITLE
BaseRepository::updateRelations GetQualifiedForeignKey renamed in laravel 5.8

### ISSUE THREAD

**Issue by xkovacikm** [InfyOmLabs/laravel-generator#602]
Hello there,

According to https://laravel.com/docs/5.8/upgrade, Laravel again changed method name **getForeignKey**. And it throws error in BaseRepository::updateRelations() method because of it.

The `getForeignKey` and `getQualifiedForeignKey` methods of the BelongsTo relationship have been renamed to `getForeignKeyName` and `getQualifiedForeignKeyName` respectively, making the method names consistent with the other relationships offered by Laravel.

**Comment by mitulgolakiya** [comment]
@xiaohuilam with Laravel 5.8, we have published default base repository where we haven't added code for update relations. so this is not the case. I realized that the function has lots of problems and lots of duplicate issues are created over and over, so had planned to add it sometimes later to BaseRepository to 5.8.

**Comment by xkovacikm** [comment]
Yeah, sorry i didn't know that before. I just finished reading your blog and it's more clear for me now.

But i have few words for you: 
As you stopped using prettus/l5-repository now, you made your new repository **backwards incompatible**. I just cannot switch old BaseRepository for new BaseRepository in my code.
Also your lightweight repository does not provide caching, criterias etc... 

For me it's a big minus and i will be forced to use old BaseRepository for now

**Comment by Katenkka** [comment]
Haven't seen this issue when creating PR #614 , so what do you suggest? @mitulgolakiya

**Comment by mitulgolakiya** [comment]
@xkovacikm nope. I have still left all the files in a repo that we have with dependency. If you are migrating your code, your existing repositories which are using BaseRepository form package will be still valid.

Also, if you still want to use package while using 5.8 then you can customize your template to use repository class from the backend, so I do not see what's a problem here.
