### ISSUE TITLE
Some API routes do not recognize any fields

### ISSUE THREAD

**Issue by gmancoder** [InfyOmLabs/laravel-generator#607]
I am running into an issue with POSTing to a generated API route. When I do so, it does not recognize the fields I am passing in the request body. It throws an error about a default value constraint and looking at the SQL its trying to run, it only includes created_at and updated_at.

Please help!

**Comment by mitulgolakiya** [comment]
@gmancoder we need some more details on this. What you have generated with which fields. If you can post generated files as well that can probably help more.

**Comment by gmancoder** [comment]
@mitulgolakiya Thanks for the reply. I've uploaded the WIP project to my github: https://github.com/gmancoder/it-data-web. The model I was testing was the TelevisionShows model. There are others that do the same thing (don't include fields passed into API POST) but some work just fine. 

Note - I deployed an infyom generated project last week with no issues whatsoever.

**Comment by mitulgolakiya** [comment]
@gmancoder can you post some more data, please? We are not able to reproduce the issue or we are missing something. Can you post some exact steps and request params that you are passing into POST?

**Comment by ruanpepe** [comment]
Same error #793

**Comment by ShaileshInfyom** [comment]
@gmancoder we can not produce this issue and I think this issue no longer live for you too. Thanks. Feel free to re-open the issue with more details if you are still facing this issue.
