### ISSUE TITLE
Undefined index: fillable when using fields_sample.json

### ISSUE THREAD

**Issue by 11digitlabs** [InfyOmLabs/laravel-generator#61]
When I'm running `php artisan infyom:api Post --fieldsFile=fields_sample.json` , using the sample file in the vendor directory, i get

![1 vagrant homestead projects playground apiground vagrant 2016-03-10 14-43-41](https://cloud.githubusercontent.com/assets/2484390/13669806/9156d8e8-e6ce-11e5-9c4c-5a8b0e11ef87.png)

Any ideas?

**Comment by phillipmadsen** [comment]
What does your fields_sample.json look like?

**Comment by 11digitlabs** [comment]
Its the one in the vendors folder, attaching it here

[fields_sample.json.txt](https://github.com/InfyOmLabs/laravel-generator/files/168601/fields_sample.json.txt)
