### ISSUE TITLE
AdminLTE layout-top-nav not working

### ISSUE THREAD

**Issue by jhosepharaujo** [InfyOmLabs/laravel-generator#611]
I added the class 'layout-top-nav' in body tag  but the layout not changed. The logo not show and the menu not change to top continuing the same place. Any fix to that?

**Comment by ShaileshInfyom** [comment]
@jhosepharaujo Which version you using?

**Comment by ShaileshInfyom** [comment]
question related to adminlte https://adminlte.io/docs/2.4/layout

**Comment by mitulgolakiya** [comment]
In this case, everything will be already published in your code. so you can better find it and fix it. Not a generator issue.

**Comment by jhosepharaujo** [comment]
> @jhosepharaujo Which version you using?

I using 5.7 version.
