### ISSUE TITLE
How to get rid of adminlte

### ISSUE THREAD

**Issue by LarryTX** [InfyOmLabs/laravel-generator#617]
laravel-generator seems to be hopelessly mired in the totally antiquated adminlte. In case no one has been looking, Bootstrap 4 came out eons ago. AdminLTE elected not to have a Bootstrap 4 template ready when it came nor did they have one ready within a reasonable amount of time thereafter. Ergo, we can only conclude that the decision was made to let it die an undignified death. I have long since moved on to use Grid, Flexbox and all those things, now a part of our day-to-day activities due to Bootstrap 4. I wouldn't even remember how to construct an interface in those long dead trappings of Bootstrap 3, nor would I ever want to.

Yet, laravel-generator seems to be as much in the prehistoric past at AdminLTE and Bootstrap 3. Even your directions seem to provide for no ways to avoid these massively archaic vestiges of days long gone by. You used to provide for a "core" template that might have provided provided for such ways. Your instructions label every kind of template that might have provided a way forward as being "deprecated."

At the very least, if you can't move laravel generator to something in the current century like, for instance, CoreUI, can you at least provide some semblance of instructions and guidance on how to customize it to use something much more modern than the dying and next to dead AdminLTE.

**Comment by mitulgolakiya** [comment]
@LarryTX the only reason we chosen adminlte was based on its popularity and based on its downloads. At the time AdminLTE was giving more nice UI then core-templates which was a bootstrap templates.

The reason behind only maintaining adminlte-templates was, we have very limited resources and as I already said in other posts that we are not making any money from this tool. It's just when we get time, we work on this.

We know that all people do not love adminlte and needs different templates and that was the reason we published multiple templates. But with very limited time and resources, it's almost impossible to maintain all the templates and keep them up to date and without great community support. so we decided to maintain one template and maintain it well.

But even we haven't limited the users to customize their templates with other templates/themes. They can always publish templates to their code via [publish template command](http://labs.infyom.com/laravelgenerator/docs/5.8/publish-templates). All templates including layout, curd, fields will be published and you are free to modify them as per your need. 

Lot's of people already using that. so there is no limit on customization of templates. You can go and publish templates, integrate core-ui, bootstrap 4 or any other theme.

**Comment by mitulgolakiya** [comment]
@LarryTX CoreUI templates: https://github.com/InfyOmLabs/coreui-templates
