### ISSUE TITLE
API Request Response

### ISSUE THREAD

**Issue by pakcybershagufta** [InfyOmLabs/laravel-generator#623]
I want little to add success false in api request call ?How i can change help please?

**Comment by mitulgolakiya** [comment]
@pakcybershagufta you can go and change the `sendResponse` function into AppBaseController.

**Comment by pakcybershagufta** [comment]
I want change api REQUEST Class response change .Which is with status code 422 .Validation response not whole.

**Comment by pakcybershagufta** [comment]
![image](https://user-images.githubusercontent.com/12270532/54806894-3a1bfd00-4c9d-11e9-8e27-4df5724af155.png)
CHeck attached screen shot i want success false in above response

**Comment by pakcybershagufta** [comment]
use InfyOm\Generator\Request\APIRequest;

class CreateCartAPIRequest extends APIRequest

APIRequest class should i add response method or what i should do

**Comment by pakcybershagufta** [comment]
- [ ]

**Comment by pakcybershagufta** [comment]
> @pakcybershagufta you can go and change the `sendResponse` function into AppBaseController.

i dont want change whole response i just want to change response of validation error

**Comment by mitulgolakiya** [comment]
Then probably you should read more here. https://laravel.com/docs/5.8/validation#customizing-the-error-messages

Also, maybe in case of APIs, you will need to customize report function in `app/Exceptions/Handler.php`, handle `ValidationException` and send the response you want. As this validation has been sent by `FormRequest` class from `failedValidation` function.

**Comment by pakcybershagufta** [comment]
If you want to customize validation response only for selected Request class, you need to add failedValidation() message to this class:

protected function failedValidation(\Illuminate\Contracts\Validation\Validator $validator)
{
    $response = new JsonResponse(['data' => [], 
             'meta' => [
                'message' => 'The given data is invalid', 
                'errors' => $validator->errors()
             ]], 422);

    throw new \Illuminate\Validation\ValidationException($validator, $response);
}

This way you don't need to change anything in Handler and have this custom response only for this single class.

And if you want to change format globally for all responses you should add to app\Exceptions\Handler.php file the following method:

protected function invalidJson($request, ValidationException $exception)
{
    return response()->json([
             'data' => [], 
             'meta' => [
                'message' => 'The given data is invalid', 
                'errors' => $exception->errors()
             ]
             ], $exception->status);
}
