### ISSUE TITLE
add tableName method

### ISSUE THREAD

**Issue by amin101** [InfyOmLabs/laravel-generator#63]
I dont see any method to return model table's name. if there isnt one , i suggest to add this method to `BaseRepository`:

```
 public function tableName()
    {
        return $this->model->getTable();
    }
```
also its important to be an intermediate repository between *Model*Repository and BaseRepository to enable user to add his own methods

**Comment by mitulgolakiya** [comment]
@amin101 As in general people don't need it. But if you need it then you can publish templates and can add this method to repository.stub.

So as of now, closing it. Will re-open in future.
