### ISSUE TITLE
Problem with index view (not listing)

### ISSUE THREAD

**Issue by wellescastro** [InfyOmLabs/laravel-generator#65]
When i was using the scaffold generator from tables the only way that i found to do the index view from any resource work was commenting the line "use SoftDeletes;" from the models.

**Comment by mitulgolakiya** [comment]
@wellescastro I didn't got the exact problem. Can you describe bit more ?

**Comment by wellescastro** [comment]
My models only work if i don't call the SoftDelete class, otherwise when i call for example a Resource::all(), it's empty. I was investigating and i see that there's a problem inside the boot function when try add a global scope, maybe a problem with the SoftDeleteScope:

    /**
     * Boot the soft deleting trait for a model.
     *
     * @return void
     */
    public static function bootSoftDeletes()
    {
        static::addGlobalScope(new SoftDeletingScope);
    }

**Comment by wellescastro** [comment]
I figure out my problem, my migrations were with mistakes, then the $builder->whereNull() in SoftDeletingScope was not working
