### ISSUE TITLE
Docs: change service provider for CoreUI template

### ISSUE THREAD

**Issue by thiagobraga** [InfyOmLabs/laravel-generator#658]
In the documentation, under [Add Service Providers](http://labs.infyom.com/laravelgenerator/docs/5.8/installation#service-providers) section, there should be the provider for CoreUI template if the user has changed it in `composer.json`.

```
...
\InfyOm\Generator\InfyOmGeneratorServiceProvider::class,
\InfyOm\CoreUITemplates\CoreUITemplatesServiceProvider::class
```

**Comment by ShaileshInfyom** [comment]
@thiagobraga you can see here http://labs.infyom.com/laravelgenerator/docs/5.8/coreui-templates#service-provider

http://labs.infyom.com/laravelgenerator/docs/5.8/installation#service-providers Adminlte is default. so, doc is fine.

**Comment by thiagobraga** [comment]
Hi @ShaileshInfyom, thanks for your response.

I agree with you, however, partially. For a beginner user wanting to use CoreUI, it will follow the installation pages, configure CoreUI in `composer.json` and include AdminLTE in service providers. But this will not work.

It could have a link to the Core UI template installation section just below the "Add service providers" box, just like the explanation in `composer.json` box, because that link you sent me was not intuitive. At least not for me. It's just for the sake of completeness.

Thanks :)

**Comment by ShaileshInfyom** [comment]
@thiagobraga  adminlte is default template. now you want use coreUI then you need to follow core template doc. already `Remove existing template` section given in doc. you can see [here ](http://labs.infyom.com/laravelgenerator/docs/5.8/coreui-templates#remove-existing-templates). so any one want to use coreUI template need to follow this [doc](http://labs.infyom.com/laravelgenerator/docs/5.8/coreui-templates).

**Comment by mitulgolakiya** [comment]
@thiagobraga I will update something in docs to make it more clear.
