### ISSUE TITLE
More than one relation in generator

### ISSUE THREAD

**Issue by androidedev** [InfyOmLabs/laravel-generator#659]
I don't know if can be done otherwise but I don't saw it in documentation nor code. 

It could be usefull to have a 'relations' field in json file that can generate more than one relation in the Model, I have done it and can make a pull request if you want, you can take look [here](https://github.com/androidedev/laravel-generator/commit/2d5105c9d47988128bd2b9423325f6eab884d43a
)

Is not a breaking change because can be used along with 'relation' field and doen't break anything, the generator can process both, one of them or none.

**Comment by vishalinfyom** [comment]
@androidedev we already support `relations` into fields file, look https://github.com/InfyOmLabs/laravel-generator/blob/develop/samples/fields_sample.json#L89

and if you want to pass more than one relations you just need to follow this : https://github.com/InfyOmLabs/laravel-generator/blob/develop/samples/fields_sample.json#L92

**Comment by androidedev** [comment]
Thank you @vishalinfyom I don't saw it, I close this then.
