### ISSUE TITLE
route:list error

### ISSUE THREAD

**Issue by Luismij** [InfyOmLabs/laravel-generator#663]
Hi
i'm getting this error when i run route:list:

In Container.php line 779:
                                                                
  Class App\Http\Controllers\API\HomeController does not exist  

How can i fixed?

laravel-generator v. 5.7
laravel 5,7

thanks

**Comment by mitulgolakiya** [comment]
@Luismij Do you have a file `HomeController` on the given folder path? Like `app/Http/Controllers/API`?

Also, did you changed any configuration and performed all steps of installation?
