### ISSUE TITLE
How to integrate Users with scaffold?

### ISSUE THREAD

**Issue by mariovalney** [InfyOmLabs/laravel-generator#666]
```
php artisan infyom:scaffold User --fromTable --tableName=users --ignoreFields=email_verified_at,remember_token
```

Requires a lot of customization like:

- Merge `User.php` with `Models\User.php` (and change all references)
- Create a way to add a random password if empty and hash the provided one (editing repository)
- Remove password from list

Is there a better way or Users are not intended to be managed?

**Comment by mitulgolakiya** [comment]
@mariovalney Unfortunately I don't think so. I will add it as a feature.

**Comment by ajayinfyom** [comment]
Added Support to Publish User Crud with default fields.

Check its docs from here: https://labs.infyom.com/laravelgenerator/docs/6.0/generator-commands#default-users-model-crud

**Comment by mariovalney** [comment]
Awesome work, guys. Thank you!

**Comment by ShaileshInfyom** [comment]
see the demo here https://youtu.be/V7PCL6HCdXo

**Comment by ShaileshLadumor** [comment]
see demo here https://youtu.be/V7PCL6HCdXo

**Comment by thewebartisan7** [comment]
Is missing the generated model_schema User.json when you generate for User model.

**Comment by martinrosbier** [comment]
Just in case, I had to change the route for users from:
Route::resource('users', 'UserController')->middleware('auth');
to:
Route::resource('users', App\Http\Controllers\UserController::class)->middleware('auth');

I was getting this error:
Illuminate\Contracts\Container\BindingResolutionException
Target class [UserController] does not exist.
