### ISSUE TITLE
Not sure if something was overwritten or changes.

### ISSUE THREAD

**Issue by phillipmadsen** [InfyOmLabs/laravel-generator#68]
the fields file imports that were working last week are not working any more. they have lost the 'field' single quotes around them. as well as default(missing quotes). 

just a heads up

**Comment by phillipmadsen** [comment]
These are the fields that are no longer adding single quotes to the output.  

{
    "fieldInput": "select_test:string",
    "htmlType": "select:Option1,Option2,Option3,Option4,Option5",
    "searchable": true
  },
  {
    "fieldInput": "enum_test:enum",
    "htmlType": "enum:Mon,Tue,Wed,Thu,Fri,Sat,Sun",
    "searchable": true
  },
  {
    "fieldInput": "radio_test:string",
    "htmlType": "radio:Male,Female"
  },
  {
    "fieldInput": "checkbox_test:string",
    "htmlType": "checkbox:Check1,Check2"
  },

## This field was missing from your fieldsFile but was working and is no longer working. 

  {
    "fieldInput": "test:string:default,i-used-to-work",
    "htmlType": "checkbox:Check1,Check2"
  },
***generates:***

$table->string('test')->default(i-used-to-work); 

***needs to be:***

$table->string('test')->default('i-used-to-work'); 

### also in the mitul version of the generator you had checkbox boolean 

***Are you bringing it back. Dont get me wrong I  like the group option but there are alot of things we need the basic for.***

### Old One:
(need to bring back)
 {
        "field":"remember:boolean",
        "type":"checkbox",
        "validations": ""
    },

### New Group Version:
  {
    "fieldInput": "checkbox_test:string",
    "htmlType": "checkbox:Check1,Check2"
  },

**Comment by phillipmadsen** [comment]
Here is the code that generates the boolean version of Checkbox:

 public static function checkbox($templateData, $field)
    {
        $textField = "<div class=\"checkbox\">\n";
        $textField .= "\t\t<label>";
        $textField .= "{!! Form::checkbox('\$FIELD_NAME\$', 1, true) !!}";
        $textField .= '$FIELD_NAME_TITLE$';
        $textField .= '</label>';
        $textField .= "\n\t</div>";
        $templateData = str_replace('$FIELD_INPUT$', $textField, $templateData);
        $templateData = self::replaceFieldVars($templateData, $field);
        return $templateData;
    }

**Comment by phillipmadsen** [comment]
Here is a bootstrap version of the label output also:

```php
  public static function generateLabel($field)
    {
        $label = Str::title(str_replace('_', ' ', $field['fieldName']));
        $template = "{!! Form::label('\$FIELD_NAME\$', '\$FIELD_NAME_TITLE\$:',['class' => 'control-label $FIELD_NAME_TITLE$']) !!}";
        $template = str_replace('$FIELD_NAME_TITLE$', $label, $template);
        $template = str_replace('$FIELD_NAME$', $field['fieldName'], $template);
        return $template;
    }
```

**Comment by phillipmadsen** [comment]
Found the problem, You removed the original checkbox and replaced it with the boolean one. You probably want both option available because they are both very useful. something like this would probably be what you want to do. 

```php
            case 'checkbox-group':
 -                    $fieldTemplate = TemplateUtil::getTemplate('scaffold.fields.checkbox_group', $this->templateType);
 -                    $radioTemplate = TemplateUtil::getTemplate('scaffold.fields.checkbox', $this->templateType);
 -                    $inputsArr = explode(',', $field['htmlTypeInputs']);
 -                    $radioButtons = [];
 -                    foreach ($inputsArr as $item) {
 -                        $radioButtonsTemplate = TemplateUtil::fillFieldTemplate(
 -                            $this->commandData->fieldNamesMapping,
 -                            $radioTemplate,
 -                            $field
 -                        );
 -                        $radioButtonsTemplate = str_replace('$VALUE$', $item, $radioButtonsTemplate);
 -                        $radioButtons[] = $radioButtonsTemplate;
 -                    }
 -                    $fieldTemplate = str_replace('$CHECKBOXES$', implode("\n", $radioButtons), $fieldTemplate);
            break;
 
            case 'checkbox':
 +                    $fieldTemplate = TemplateUtil::getTemplate('scaffold.fields.checkbox', $this->templateType);
 +                    $value = $field['htmlTypeInputs'];
 +                    $fieldTemplate = str_replace('$VALUE$', $value, $fieldTemplate);
            break;

```

**Comment by phillipmadsen** [comment]
needs a slight change on the boolean checkbox in your fields stubs change:

    <label class="checkbox-inline">
        {!! Form::checkbox('$FIELD_NAME$', "$VALUE$", null) !!} $VALUE$
    </label>  

to:

    <label class="checkbox-inline">
        {!! Form::checkbox('$FIELD_NAME$', "$VALUE$", null) !!} $FIELD_NAME$
    </label>

**Comment by mitulgolakiya** [comment]
I tested it again with checkbox and its working fine.
