### ISSUE TITLE
About HTMLFieldGenerator class

### ISSUE THREAD

**Issue by abdullaheid** [InfyOmLabs/laravel-generator#682]
Hi,

From time to time, I pick one open-source project to read and learn from, and if I have something to contribute to that project, whatever that thing, I will do.

> I have picked up yours, and **I have learned** from it. Thank you.

However, during my reading for `HTMLFieldGenerator` class, I came with an idea of contribution for this class, and because **I didn't read everything related to the structure of this project that helps me to** `fork` **it**, I will try to contribute by that idea here.

## Problem

However, `HTMLFieldGenerator,` **as I understood**, trying to generate `field-template` and return it based on the **field type**. As you know, each time that you would like to add, delete, or modify any `field-template-generator,` **you will go and** `modify` **the** `HTMLFieldGenerator.generateHTML` **method to do that**.

## Solution

**Let's take the benefits of the** `Polymorphism` **here**. For example, if we created a new `interface/abstract class` to represent the `field-template-generator` in general, and call it, for example, `FieldTemplateGenerator,` then, **each time we need to create a new** `field-template-generator,` **we will** `inherit` **from this class**. This way, we will **separate** the `field-template-generator` **from** the main `HTML-generator.`

> That separation will help us to avoid modifying `HTML-generator` itself, and put our focus in the `field-template-generator` class.

## Example

To get the big picture, I will try to explain that in a short way.

```php
abstract class FieldTemplateGenerator{
      //..
     abstract public function generate(/*...*/);
}
    
// concrete field generator
    
class CheckboxFieldGenerator extends FieldTemplateGenerator{
       public function generate(...){
             //..
             return $template;
       }
}
    
class HTMLFieldGenerator{
       public static function generateHTML(...){
            //...
            return $generator->generate(...);
       }
}
```

This way, if you would to like to add new `field-template-generator`, all that you need is to create new class for that, and when you have something to modify, you will not modify the `HTMLFieldGenerator`. Moreover, now, designing a `field-template-generator` became **extendable**.

> I have used the short way to explain the classes, and you should take care of the classes design if you have decided to deal with this issue same way.

Thank you.

**Comment by ajayinfyom** [comment]
@abdullaheid its good idea. but i see its too lengthy process here.

right now we generate HTML from **ViewGenerator.php**.  its generated html for each fields directly (one line of code).

if we implement to your idea firstly need to create generateHTML  for each html type than
while generating view to check each field type and go to its related FieldGenerator class.

also now added support of Localization so also need to manage that stuff.
