### ISSUE TITLE
CoreUI styles

### ISSUE THREAD

**Issue by sefsinalas** [InfyOmLabs/laravel-generator#683]
Hi. I follow installation instructions for CoreUI templates but every time I use the generator it creates a datatables view that is...ugly. 

I expect something like this: https://coreui.io/demo/#tables/datatables.html
But I'm getting this:
![2019-06-08_11-59](https://user-images.githubusercontent.com/1595040/59148943-7716a680-89e5-11e9-8ba3-1d1e7ce33c22.png)

I think that the problem is that there are some clases missed when the generator creates the view. For example, if I add the class 'page-link' to the paginator, I can get at least a little improvement:
![2019-06-08_12-07](https://user-images.githubusercontent.com/1595040/59148984-1340ad80-89e6-11e9-925f-352e1093f9ca.png)

But...:
1- I can't find where to do this change. Can you help me?
2- This is something that happens to everybody? Or it's happening just to me?

**Comment by ShaileshInfyom** [comment]
@sefsinalas you getting break of datatable pagination becuase coreui provide datatable in Pro version not in free version.. you can see in coreui demo. https://coreui.io/demo/#tables/datatables.html
![image](https://user-images.githubusercontent.com/28335166/59172846-cf75b180-8b67-11e9-8759-86ede92a759a.png)
 so, if you expect  like coreUi demo then you need pro version and need to added missing datarable js/css
