### ISSUE TITLE
Security in InfyOm | Securing API through API-Keys

### ISSUE THREAD

**Issue by Grashee** [InfyOmLabs/laravel-generator#684]
Hey guys,

is there a plugin for securing up the API. 
For example with API-Keys or user:password authentication?

Thanks for anyone who can help!
Best regards,
Grashee

**Comment by ShaileshInfyom** [comment]
you can you https://github.com/tymondesigns/jwt-auth for api authentication

**Comment by mitulgolakiya** [comment]
@Grashee The aim of this package is not to lock users to specific security packages, you are free to use any package for your api security based on your need. The main goal of this package is to save time in api development.
