### ISSUE TITLE
fail to recognize dingo api routes

### ISSUE THREAD

**Issue by farshadff** [InfyOmLabs/laravel-generator#686]
in my project i am using dingo api package but after installing and configuring the swaggervel and the documentation said and after editing my routes like below :
```
Route::prefix('api')
            ->middleware('api')
            ->as('api.')
            ->namespace($this->namespace."\\API")
            ->group(base_path('routes/api.php'));
```
then i vendor publish and finally ;
```
php artisan infyom:publish model name
```
it detects the crud of model and place them there in swagger ui now  my question is what will happen to my custom methods that i wrote in some controller ?? shouldn't this package detect them and annotate them too ?? or this package just detects the crud of model ??

**Comment by mitulgolakiya** [comment]
@farshadff first of all, I think there is some typo in command that you wrote. we do not have any command like `php artisan infyom:publish model name`.

But if your swagger is working and swagger ui is fine. Then for any custom method in the controller, if it has swagger annotation written, then it will appear in swagger UI.

This package does not manage swagger annotations, swaggervel manage that.

Let me know if it helps.
