### ISSUE TITLE
GET API SQLSTATE[42000]: Syntax error or access violation: SQL: select  from `my_table_name` where `my_table_name`.`deleted_at` is null

### ISSUE THREAD

**Issue by biholaindrasinh** [InfyOmLabs/laravel-generator#688]
Windows 7 Wamp Server
infyomlabs/laravel-generator "5.8.x-dev"
php artisan infyom:api MyTableName
field1_id integer text s
field2_id integer text s
field3_id text textarea s, ii
Running GET API /api/v1/myTableNames

**Comment by mitulgolakiya** [comment]
@biholaindrasinh can you post a full error or the table schema that you have?

Seems like you have some SoftDelete problem.

**Comment by biholaindrasinh** [comment]
I can't share my table schema that's why I have added a general description regarding it. Let me know if any specific you want to know.

**Comment by biholaindrasinh** [comment]
![image](https://user-images.githubusercontent.com/5697078/61693089-8dd24c00-ad4c-11e9-934f-b9c08e2a8778.png)

**Comment by biholaindrasinh** [comment]
Here is a stack trace:
https://gist.github.com/biholaindrasinh/9f3a3e77ce02fe640403e9a31e9f9c97

**Comment by biholaindrasinh** [comment]
![image](https://user-images.githubusercontent.com/5697078/61712927-051bd600-ad75-11e9-9d06-9b0e3df686e3.png)
If I remove this 3 request parameters then it's working.

**Comment by mitulgolakiya** [comment]
@biholaindrasinh are you passing any query parameter while calling the API?

**Comment by biholaindrasinh** [comment]
No, I was not passing any parameters but it should return all the resources if we don't pass any parameters.

**Comment by mitulgolakiya** [comment]
@biholaindrasinh I think you are using an old base repository. Can you paste a code of BaseRepository somewhere?

Also did you set up a fresh project? or it's an old project? And you made some upgrade?

**Comment by biholaindrasinh** [comment]
It's an ongoing project. It looks like a problem in prettus/l5-repository: ~2.6

**Comment by mitulgolakiya** [comment]
Yes, I would say for your new generated files, you the BaseRepository that we published. Give it a try with a fresh new project and you will get an idea how new BaseRepository works and we are no longer need old `prettus/l5-repository`.
