### ISSUE TITLE
Document for generator should clear some step.

### ISSUE THREAD

**Issue by quangtynu** [InfyOmLabs/laravel-generator#699]
http://labs.infyom.com/laravelgenerator/docs/5.8/boilerplates
I read the guide is not clear about step buy step for install fress copy.
Pls show some step in detail for beginner

**Comment by mitulgolakiya** [comment]
@quangtynu boilerplates do not need any setup. All installation steps are already done in that.

**Comment by quangtynu** [comment]
So pls di like that. 
1. Git clone... Command
2. Cd to ... Command
3. Run update... Command
5. Run php artisan serve .. Commanf
6. Login user, pass
Localhost:8000????
I mean for beginner.

**Comment by mitulgolakiya** [comment]
Yes. do not forget to setup your env.
