### ISSUE TITLE
Relationships method name. 

### ISSUE THREAD

**Issue by tecnoe** [InfyOmLabs/laravel-generator#706]
I have the following issue when I generate a model from a table duplicate relationships methods.
Example I have contacts table with 2 foreignkeys.
Table contacts:
    created_by
    owner 
both columns references id on users table. If I run.

```
php artisan infyom:scaffold User --fromTable --tableName=users
```

```
public function alternateContacts()
    {
        return $this->hasMany(\App\Models\AlternateContact::class);
    }

public function alternateContacts()
    {
        return $this->hasMany(\App\Models\AlternateContact::class);
    }
```

It is possible to add the the foreignkey as a method name, for example owner and createdBy, with the related columns to avoid this issue.

**Comment by mitulgolakiya** [comment]
@tecnoe We pushed a fix. Try to update packages by composer update and see if it works and let us know.
