### ISSUE TITLE
Documentation Improvement: Prefix Option Comma Separation

### ISSUE THREAD

**Issue by rabrowne85** [InfyOmLabs/laravel-generator#708]
I've been trying to get to grips with the laravel-generator and one of the things I was struggling with was the `--prefix` option for the generator commands. It's not clear from the documentation that you can generate nested structures by using `--prefix=First,Second,Third`. I had to find this by digging into the code.

It's also a little counter intuitive that you have to use the `,` and not `/` like everywhere else.

**Comment by mitulgolakiya** [comment]
Yes, I think prefix should be separated by slash instead of a comma. will look into it.

**Comment by rabrowne85** [comment]
If that’s the case, I’m happy to look at the code and push a pull request with the required changes. Can try and make it backward compatible as well. Just let me know if you want me to help.

**Comment by mitulgolakiya** [comment]
@rabrowne85 yes, you are most welcomed to do that.

**Comment by ajayinfyom** [comment]
Now prefix separated by slash instead of a comma,

prefix docs: https://labs.infyom.com/laravelgenerator/docs/6.0/generator-options#prefix-option
