### ISSUE TITLE
default laravel date fields do not work properly in scaffolding

### ISSUE THREAD

**Issue by vesper8** [InfyOmLabs/laravel-generator#71]
The default timestamps created_at and updated_at do not work properly in the generated scaffolding.

The created_at does not get updated when using the calendar plugin that comes with the scaffolding. And neither the created_at or updated_at reflect the current value if they are set to a valid timestamp when editing.

**Comment by ShaileshInfyom** [comment]
you should add this code into modal.
```public function getDateAttribute($value)
   {
       return $value;
   }```
