### ISSUE TITLE
Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by dyatana** [InfyOmLabs/laravel-generator#711]
hi everyone,

I want to fill my select fields with information from database table, but I have this error
Invalid argument supplied for foreach() (View: C:\xampp\htdocs\webportal\resources\views\departements\fields.blade.php) (View: C:\xampp\htdocs\webportal\resources\views\departements\fields.blade.php)

fields.blade.php

<div class="form-group col-sm-6">
    {!! Form::label('deptsection_id', 'Section du département:') !!}
    {!! Form::select('deptsection_id', $depsections , null, ['class' => 'form-control']) !!}
</div>

DeptSectionController.php

use App\Models\DeptSection;
public function create()
    {
        $depsections = DeptSection::pluck('libelle','id');

        return view('departements.create', compact('depsections'));
    }

Any help is welcome !!

**Comment by ShaileshInfyom** [comment]
@dyatana 

Tested and working fine at our end. make sure you passing proper array?
