### ISSUE TITLE
Little mistake on coreui-templates/templates/scaffold/views/blade_table_body.stub

### ISSUE THREAD

**Issue by unomasmas** [InfyOmLabs/laravel-generator#714]
File: /vendor/infyomlabs/coreui-templates/templates/scaffold/views/blade_table_body.stub
At lines 14 and 15 you have:
```
<a href="{!! route('$ROUTE_NAMED_PREFIX$$MODEL_NAME_PLURAL_CAMEL$.show', [$$MODEL_NAME_CAMEL$->id]) !!}" class='btn btn-ghost-success'><i class="fa fa-eye"></i></a>
<a href="{!! route('$ROUTE_NAMED_PREFIX$$MODEL_NAME_PLURAL_CAMEL$.edit', [$$MODEL_NAME_CAMEL$->id]) !!}" class='btn btn-ghost-info'><i class="fa fa-edit"></i></a>

```
In order to get PrimaryKey setted (if different from id) there should be:
```
<a href="{!! route('$ROUTE_NAMED_PREFIX$$MODEL_NAME_PLURAL_CAMEL$.show', [$$MODEL_NAME_CAMEL$->$PRIMARY_KEY_NAME$]) !!}" class='btn btn-ghost-success'><i class="fa fa-eye"></i></a>
<a href="{!! route('$ROUTE_NAMED_PREFIX$$MODEL_NAME_PLURAL_CAMEL$.edit', [$$MODEL_NAME_CAMEL$->$PRIMARY_KEY_NAME$]) !!}" class='btn btn-ghost-info'><i class="fa fa-edit"></i></a>

```

**Comment by unomasmas** [comment]
Also at **line 12**. Must be replaced **id** with **$PRIMARY_KEY_NAME$**.
`{!! Form::open(['route' => ['$ROUTE_NAMED_PREFIX$$MODEL_NAME_PLURAL_CAMEL$.destroy', $$MODEL_NAME_CAMEL$->$PRIMARY_KEY_NAME$], 'method' => 'delete']) !!}`
Otherwise, it will throw an exception: "The DELETE method is not supported for this route. Supported methods: GET, HEAD, POST."

The same happens on the file **/vendor/infyomlabs/coreui-templates/templates/scaffold/views/edit.stub** at **line 21**. Now it has:
`{!! Form::model($$MODEL_NAME_CAMEL$, ['route' => ['$ROUTE_NAMED_PREFIX$$MODEL_NAME_PLURAL_CAMEL$.update', $$MODEL_NAME_CAMEL$->id], 'method' => 'patch']) !!}`
Has to be changed with:
`{!! Form::model($$MODEL_NAME_CAMEL$, ['route' => ['$ROUTE_NAMED_PREFIX$$MODEL_NAME_PLURAL_CAMEL$.update', $$MODEL_NAME_CAMEL$->$PRIMARY_KEY_NAME$], 'method' => 'patch']) !!}`

**Comment by ShaileshInfyom** [comment]
> replaced **id** with **$PRIMARY_KEY_NAME$**.

changes done [ here](https://github.com/InfyOmLabs/coreui-templates/pull/16)
