### ISSUE TITLE
suggestion: fix checkbox template issue

### ISSUE THREAD

**Issue by amin101** [InfyOmLabs/laravel-generator#72]
there should be a hidden input before each checkbox, unless we cant uncheck a checkbox when editting a post. take a look[ here](http://laravel.io/forum/09-26-2014-handling-unchecked-checkbox-by-updating)

```
{!! Form::hidden('myCheck',0) !!}
{!! Form::checkbox('myCheck',1) !!}
```

**Comment by phillipmadsen** [comment]
just us these:

CHECKED:
{!! Form::checkbox('myCheck',1, true) !!}

UNCHECKED:
{!! Form::checkbox('myCheck',1, false) !!}

**Comment by amin101** [comment]
did you checked the link?  
when you uncheck a checkbox nothing is passed to POST request, so your checkbox new status(unchecked) wont be persistened in database,you have unchecked programmatically and it doesnt affect to its status or value in database.

**Comment by mitulgolakiya** [comment]
Fixed
