### ISSUE TITLE
Model/Controller Override

### ISSUE THREAD

**Issue by sbolognini** [InfyOmLabs/laravel-generator#720]
Is there a way for generating models, controllers as base classes and provide the related inherited classes?

I explain my doubt:
- I generate the full scaffold
- I change some stuff, like required fields or something else in the generated classes
- I make a small change in the db (for example I add a new column in a table)
- I regenerate the scaffold
- I lost the previous changes I applied to the generated files

So maybe a way of mantaining changes upon generations should be provided.

**Comment by mitulgolakiya** [comment]
@sbolognini No. currently there is no way to do this. How generator work is, it gets templates and fields OR if you are generating from the table, then it detects new fields added in the table and generates CRUD for that again.
But it can not detect your manual changes in your existing files. I can keep it in the future roadmap.
