### ISSUE TITLE
Primary key required when generating from existing tables

### ISSUE THREAD

**Issue by sbolognini** [InfyOmLabs/laravel-generator#721]
I generated a full scaffold starting from an existing table.
This table has a primary key with autoincrement.
The generated views (and model) require the id upon saving or updating.

**Comment by mitulgolakiya** [comment]
@sbolognini Can you explain it in little bit more details? we are not able to get it.
Your primary key in the existing table has a different name than `id`? that's what you mean?

**Comment by mitulgolakiya** [comment]
@sbolognini Issue is fixed and the primary key is no longer required field when using `fromTable` option.
Thanks for catching it out. Also, do not forget to list your project under #631 list (if you want). :)
