### ISSUE TITLE
Generate from table api_scaffold infyom version 6

### ISSUE THREAD

**Issue by TokkenSchneider** [InfyOmLabs/laravel-generator#722]
![20190911_154358](https://user-images.githubusercontent.com/15619210/64729373-0763fc00-d4ab-11e9-8d36-c675a19e16f8.jpg)
I got this errors when i try to generate scaffold from table. When i skip model, everything works well. With model included, got this pluralizer error

**Comment by TokkenSchneider** [comment]
Please someone  help me

**Comment by Victor1015** [comment]
x2 have the same issue too!

**Comment by johnvargasosornio** [comment]
somebody know what happened?

**Comment by mitulgolakiya** [comment]
@TokkenSchneider can you post a full error? I can not see full error in screenshot.

**Comment by mitulgolakiya** [comment]
@TokkenSchneider @johnvargasosornio @Victor1015 can you give us a schema of users table with which this error is coming?

**Comment by johnvargasosornio** [comment]
Schema::create('users', function (Blueprint $table) {
$table->bigIncrements('id');
$table->string('name');
$table->string('email')->unique();
$table->timestamp('email_verified_at')->nullable();
$table->string('password');
$table->rememberToken();
$table->timestamps();

and my composer.json:

{
    "name": "laravel/laravel",
    "type": "project",
    "description": "The Laravel Framework.",
    "keywords": [
        "framework",
        "laravel"
    ],
    "license": "MIT",
    "require": {
        "php": "^7.1.3",
        "appointer/swaggervel": "dev-master",
        "doctrine/dbal": "~2.3",
        "fideloper/proxy": "^4.0",
        "infyomlabs/adminlte-templates": "5.8.x-dev",
        "infyomlabs/laravel-generator": "5.8.x-dev",
        "infyomlabs/swagger-generator": "dev-master",
        "laracasts/flash": "^3.0",
        "laravel/framework": "5.8.*",
        "laravel/tinker": "^1.0",
        "laravelcollective/html": "^5.8.0",
        "phpmailer/phpmailer": "^6.0"
    },
    "require-dev": {
        "beyondcode/laravel-dump-server": "^1.0",
        "filp/whoops": "^2.0",
        "fzaninotto/faker": "^1.4",
        "mockery/mockery": "^1.0",
        "nunomaduro/collision": "^3.0",
        "phpunit/phpunit": "^7.5"
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true
    },
    "extra": {
        "laravel": {
            "dont-discover": []
        }
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/"
        },
        "classmap": [
            "database/seeds",
            "database/factories"
        ]
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "scripts": {
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi"
        ],
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate --ansi"
        ]
    }
}


I have that issues with all tables :(

**Comment by mitulgolakiya** [comment]
Issue Fixed. Everyone, Please verify let report/re-open the issue if you still have the problem.
Also, do not forget to pull the latest code via composer update.
Also, if you are using the generator and made something from Generator then you can list your project here #631 if you want. @TokkenSchneider @johnvargasosornio @Victor1015 

Happy Coding :)
