### ISSUE TITLE
Timestamps disabled but still processed in model insert/update

### ISSUE THREAD

**Issue by sbolognini** [InfyOmLabs/laravel-generator#729]
I disabled timestamps from generator config

```
'timestamps' => [
        'enabled'       => false,
        'created_at'    => 'created_at',
        'updated_at'    => 'updated_at',
        'deleted_at'    => 'deleted_at',
    ],
```

then I generated model, but when inserting/updating records this error is shown

**Column not found: 1054 Unknown column 'updated_at' in 'field list'**

The issue can be solved adding

`public $timestamps = false;`

in the model definition, but the generator should add it automatically when timestamps are disabled in the config.

**Comment by mitulgolakiya** [comment]
Fixed.
