### ISSUE TITLE
Checkbox unwanted label when generating from .json file

### ISSUE THREAD

**Issue by sbolognini** [InfyOmLabs/laravel-generator#730]
```
{
        "name": "checkbox",
        "dbType": "integer",
        "htmlType": "checkbox",
        "validations": "required",
        "searchable": true,
        "fillable": true,
        "primary": false,
        "inForm": true,
        "inIndex": true
    },
```

result:
![Schermata 2019-09-16 alle 15 16 20](https://user-images.githubusercontent.com/4761746/64961084-f9d8b880-d894-11e9-92c2-4861ad46122b.png)

The value of the checkbox should not be printed unless specified.

**Comment by ShaileshInfyom** [comment]
Fixed in both template (admin-adminlte, core-ui)
https://github.com/InfyOmLabs/adminlte-templates/pull/44
https://github.com/InfyOmLabs/coreui-templates/pull/18
