### ISSUE TITLE
String length not being considered when generating from model schema

### ISSUE THREAD

**Issue by sbolognini** [InfyOmLabs/laravel-generator#733]
{
        "name": "name",
        "dbType": "string,30",
        "htmlType": "text",
        "validations": "required",
        "searchable": true,
        "fillable": true,
        "primary": false,
        "inForm": true,
        "inIndex": true
    },

if I generate scaffold from this schema the html field have not the length size and validation doesn't consider that lenght.
What's the point in adding that length if the generator doesn't consider it?

And, when generating from table the created schema file doesn't contain the length defined in the db column (eg. varchar(30)

**Comment by sbolognini** [comment]
Solved by myself

**Comment by ShaileshInfyom** [comment]
@sbolognini `dbType` only deal with database not html and validation. and validation option already there. i think you already used in your solution.

Thanks

**Comment by sbolognini** [comment]
Yes, that part of the issue was solved.
Anyway, when adding a max limit in validations, the resulting field in the generated view should have a "size" attribute to reflect the max value
