### ISSUE TITLE
View form not considering the inForm attribute 

### ISSUE THREAD

**Issue by sbolognini** [InfyOmLabs/laravel-generator#734]
When generating from a .json file that, for example, contains this record

    {
        "name": "name",
        "dbType": "string,30",
        "htmlType": "text",
        "validations": "required|max:30",
        "searchable": true,
        "fillable": true,
        "primary": false,
        "inForm": false,
        "inIndex": false
    },

the index and edit/create form correctly do not show the field.
but, the field is visible in the view form
this should be managed: or the same form will be visible in both edit and view form or an additional parameter like "inView" should be added.

Just an example for you: managing the User model there's a field like remember_token. I want that field to not be visible in any form, but currently it's visible in the view form

**Comment by ShaileshInfyom** [comment]
implemented [here ](https://github.com/InfyOmLabs/laravel-generator/pull/737)
