### ISSUE TITLE
File uploading issues

### ISSUE THREAD

**Issue by dyatana** [InfyOmLabs/laravel-generator#743]
Hi everyone,
i'm laravel beginer and i want to know how to configure Controller and Repository files to make upload file to my local path

thanks.

**Comment by vishalinfyom** [comment]
@dyatana Right now generator does not support file upload by default. You need to modify your controllers + repository by your self to handle file upload.

Duplicate : https://github.com/InfyOmLabs/laravel-generator/issues/710
