### ISSUE TITLE
InfyOm Laravel GUI Schema Generator

### ISSUE THREAD

**Issue by harish81** [InfyOmLabs/laravel-generator#744]
As we know Infyom's `laravel-generator` remove headache while working with `laravel`, I have made `InfyOm Laravel GUI Schema Generator` Where you can generate schema file easily.
Try it out at here : https://harish81.github.io/infyom-schema-generator/
Feel Free to contribute: https://github.com/harish81/infyom-schema-generator

> This is not a real issue.
> Sorry For Posting in issue, Actually I want to Help artisans.

**Comment by mitulgolakiya** [comment]
Great work!!
