### ISSUE TITLE
I Dont want admin panel, only the GUI Scaffold generator

### ISSUE THREAD

**Issue by samuk190** [InfyOmLabs/laravel-generator#745]
When I make a crud it says -> layouts.datatables_css not found and 
'layouts.datatables_js not found and it doesnt show any result of created "persons" for example.

I read that if I publish layout it will fix, but I dont want to generate a auth controller and admin panel views because I have one already.

Using: data tables
package: Generator GUI Interface

**Comment by vishalinfyom** [comment]
@samuk190 if you just want GUI scaffold generator then you can follow the steps from our official documentation site : http://labs.infyom.com/laravelgenerator/docs/6.0/gui-interface

**Comment by samuk190** [comment]
> @samuk190 if you just want GUI scaffold generator then you can follow the steps from our official documentation site : http://labs.infyom.com/laravelgenerator/docs/6.0/gui-interface

I did, well, I used the publish layout and it replaced my login files so I had to reimport then from backpack and it worked fine. 

There's a way to create search box with the gui scaffold generator?

**Comment by vishalinfyom** [comment]
@samuk190 can you explain this in more brief 
> There's a way to create search box with the gui scaffold generator?

**Comment by samuk190** [comment]
> @samuk190 can you explain this in more brief
> 
> > There's a way to create search box with the gui scaffold generator?

In other's components like Laravel BackPack, the search box comes by default on CRUDS.
I don't see a reliable way of implementating that search box on Infyom

**Comment by vishalinfyom** [comment]
@samuk190 we are not giving search box for simple views (Without Datatables), by using datatables you are able to search records, will consider this as feature.

**Comment by samuk190** [comment]
> @samuk190 we are not giving search box for simple views (Without Datatables), by using datatables you are able to search records, will consider this as feature.

Thanks
