### ISSUE TITLE
Change Color CoreUI

### ISSUE THREAD

**Issue by Luismij** [InfyOmLabs/laravel-generator#749]
Hi,
how can i change the primary color for CoreUI template?
I want to change the variables, but i do not know how.
Thanks

**Comment by mitulgolakiya** [comment]
@Luismij Right now, we use CDN URLs of coreui. If you want to change the colors then you should install coreui with npm package and then you will be able to override their scss and that's how you can do it.

Maybe you will need to use laravel mix and then include the final output to `app.blade.php`.

**Comment by Luismij** [comment]
@mitulgolakiya can you be more specific with the instructions?
Thanks

**Comment by mitulgolakiya** [comment]
@Luismij maybe this can help: https://coreui.io/v1/docs/getting-started/options/
