### ISSUE TITLE
Purpose of Checkbox Group

### ISSUE THREAD

**Issue by mitulgolakiya** [InfyOmLabs/laravel-generator#75]
@phillipmadsen I just merged you pull request #69 and found like it is creating multiple checkboxes with the same input. so if we select all three then the last selected value will be stored in the database rather than all three values. That's why I removed the checkbox group option in my old commits.

Do you have any specific use case of need for checkbox group? Can you post it here? so I can think of that and can make changes that way and re-enable it.

Currently, I just disabled it temporary.

**Comment by phillipmadsen** [comment]
Yes example would be.

options: field

option1:boolean
option2:boolean
option3:boolean

if(in_array(options, option1 === true))
return .....
endif

----------------

I  should have editted this better and made each one save individually in the db but style them in  a group.  I  will see what I  can do to make it do this. sorry for not explaining this better.


***You should build in a default crud for profile/ account tied to the user model with option on crud generation like --profile  or --account***

just a thought it would be easy and very useful.

**Comment by mitulgolakiya** [comment]
@phillipmadsen Maybe people can use customize templates when they need it by their own way. Or we will re-open it once we find some specific requirements.
