### ISSUE TITLE
Can't properly do anything with --skip=views option

### ISSUE THREAD

**Issue by VictorGorban** [InfyOmLabs/laravel-generator#752]
I've tried it with api_scaffold, api and scaffold. 
Quick used commands example:
1.    `php artisan infyom:api_scaffold --fromTable --tableName=categories --skip=views  Category`
1.1  all created, but in the end I got the `Exception`:  `ErrorException  : file_get_contents(/home/victorgorban2/Desktop/WEB/Laravel Angular Ecommerce/backend/resources/views/layouts/menu.blade.php): failed to open stream: No such file or directory`. Of course the file is not found! I didn't create it!!!
2.    `php artisan infyom:rollback Category api_scaffold`
2.1  all deleted, but I got the same `Exception`:    `ErrorException  : file_get_contents(/home/victorgorban2/Desktop/WEB/Laravel Angular Ecommerce/backend/resources/views/layouts/menu.blade.php): failed to open stream: No such file or directory
`. Really?

Every time I try to rollback

**Comment by ShaileshInfyom** [comment]
@VictorGorban Working fine.

**API Scaffold**

![image](https://user-images.githubusercontent.com/28335166/66289799-4c891b80-e8fb-11e9-8261-2d1f579d72fc.png)

**Scaffold**
![image](https://user-images.githubusercontent.com/28335166/66289944-9a058880-e8fb-11e9-8a20-c35ccf73d6d9.png)

**Rollback API Scaffold**

![image](https://user-images.githubusercontent.com/28335166/66290008-ccaf8100-e8fb-11e9-9878-9fcf22286ace.png)

**Comment by mitulgolakiya** [comment]
@VictorGorban Let us know what version of generator and templates you are using. Or try to provide some more steps and re-open the issue again.

We are closing this as of now, since its working as per our testing.
