### ISSUE TITLE
Reduce on the size of the table

### ISSUE THREAD

**Issue by 16isaac89** [InfyOmLabs/laravel-generator#764]
How do i reduce the number of elements returned and rendered on the table because incase of multiple values, others are hidden like in the image 
![snipping](https://user-images.githubusercontent.com/23630466/66702389-e263e280-ed0f-11e9-8919-9fb52e04f5d2.PNG)

**Comment by ajayinfyom** [comment]
@16isaac89 you can skip being displayed in index view by using `ii`  option

ex.  `body text textarea ii`

more info read document: http://labs.infyom.com/laravelgenerator/docs/5.8/getting-started

**Comment by mitulgolakiya** [comment]
@16isaac89 or you can even remove fields from DataTable class that is created. There will be a function `getColumns`. Keep only those columns that you want want to display.
