### ISSUE TITLE
Missing prettus/l5-repository as required dependency.

### ISSUE THREAD

**Issue by JonathanGuo** [InfyOmLabs/laravel-generator#768]
## Fatal Error
Class `Prettus\Repository\Eloquent\BaseRepository` not found

## Description

Since the commit 7cf8946ba70fd27ca065146d91fcf0be5baa84a0, it drops the dependency `prettus/l5-repository`.

However the `InfyOm\Generator\Common\BaseRepository` still extends `\Prettus\Repository\Eloquent\BaseRepository`. The workaround is the devs need to install `prettus/l5-repository` in the projects.

I think `prettus/l5-repository` is needed since it's required for the `BaseRepository` class.

**Comment by mitulgolakiya** [comment]
@JonathanGuo after Laravel 6 support, published BaseRepository does not use `prettus/l5-repository`.
https://github.com/InfyOmLabs/laravel-generator/blob/develop/templates/base_repository.stub

Let us know which version you are using of Laravel and you did a fresh installation or upgraded your project?

**Comment by JonathanGuo** [comment]
Yes, the code base was upgraded from Laravel 5.8, which was originally started from 5.3 anyway.

Just had a quick look on the website, I can't find any upgrade guide. Do I miss something?

**Comment by mitulgolakiya** [comment]
Laravel 5.3 was not managed anymore and deprecated since months. so there was no upgrade guide when this dependency was removed.

**Comment by lomotech** [comment]
did you have any upgrade guide from using prettus package to without using prettus package?
