### ISSUE TITLE
Paginagion not being take off command line

### ISSUE THREAD

**Issue by jschlies1** [InfyOmLabs/laravel-generator#77]
See infyomlabs/laravel-generator/src/Common/GeneratorConfig.php:205. paginate should be in list, no????

**Comment by jschlies1** [comment]
I think I have the fix for this and wish to contribute other features in the future. Is this repos taking pull requests?? If yes, do I need permission/auth? I can clone but am unable to push to origin??

**Comment by mitulgolakiya** [comment]
@jschlies1 yes, it should be there. I will fix it. But if you want to push a fix then you can fork a repo and can put a pull request.

**Comment by jschlies1** [comment]
ok
