### ISSUE TITLE
drop down menu

### ISSUE THREAD

**Issue by MaryTabbs** [InfyOmLabs/laravel-generator#774]
How do I create a dropdown menu .....am using the infyom generator

**Comment by vishalinfyom** [comment]
@MaryTabbs Please read this fields input guide to generate different types of fields. 
http://labs.infyom.com/laravelgenerator/docs/5.8/fields-input-guide

For dropdown you can use option `select` for pre-defined value OR you can use `selectTable` to select records from some table, you can find more details on above docs.

**Comment by RayhanYulanda** [comment]
Can i use selectTable in schema file?

**Comment by mitulgolakiya** [comment]
@RayhanYulanda I think yes.
