### ISSUE TITLE
documentation possible update needed for install

### ISSUE THREAD

**Issue by leerlemoniii** [InfyOmLabs/laravel-generator#775]
after installing via cloning I found a few things that are not addressed in the documentation for install.
1. you need to change the file .env.example to .env
2. you need to generate application keys
php artisan key:generate

while this is normal for laravel install it is not clear that this needed to be done, thus leading to several hours trying to diagnose getting 500 errors for me anyways.

**Comment by mitulgolakiya** [comment]
@leerlemoniii these are not steps to be performed for this package. Those are laravel installation step which needs to be performed while laravel application setup.

And installation of this package is initialized after laravel installation. That's why they are not included in docs.

**Comment by leerlemoniii** [comment]
not to be picky about this, but doing a laravel install is not required for building from the steps here
http://labs.infyom.com/laravelgenerator/docs/6.0/boilerplates
In fact I am not even sure how you would clone this into a intalled laravel project without screwing up that project.  

Though I do kinda see the point, but then the docs should state that you need to follow laravel install guide "after??" cloning the above repo??

**Comment by mitulgolakiya** [comment]
@leerlemoniii The use of boilerplate is not intended to support and install in existing projects. Documentation straightly says, if you are setting up a fresh new laravel project then only you should plan to use boilerplates.

https://labs.infyom.com/laravelgenerator/docs/6.0/boilerplates#introduction

If you are planning to install it in a project then follow standard installation steps.

I see the point of after clone, so I will update the doc to add post-installation steps.
