### ISSUE TITLE
Drop Prettus as Base Repository

### ISSUE THREAD

**Issue by xwiz** [InfyOmLabs/laravel-generator#776]
Hi, great work with Laravel 6 compatibility. I'm an avid use of laravel-generator and I've always thought that the dependency on prettus l5 repository is needless. The Base Repository included in infyom with a few additional methods is enough as a repository. I can create a pull request using the repository class we always use in our projects. Repositories are supposed to be just data layers and Prettus is kinda twisted in the sense that instead of simply deriving from Eloquent, it uses and depends on eloquent and laravel classes making it hard to maintain

**Comment by mitulgolakiya** [comment]
@xwiz in Laravel Generator 6.x branch, we already dropped the support, but the old versions were using it, so we just leave that as it is.
`src/Common/BaseRepository.php` was kept for someone if he is migrating the code from lower to 6.x. Otherwise, it's not used anywhere.
We are planning to remove it very soon.

**Comment by slamgundam** [comment]
it is safe that i upgrade L5.8 to L6.x?

currently laravel-generator is using l5-repository as backboned

**Comment by ajayinfyom** [comment]
@slamgundam laravel-generator no more using l5-repository.
we have created custom BaseRepository.

**Comment by mitulgolakiya** [comment]
@slamgundam yes, probably you can still use l5-repository for your old controllers and create new CRUD with a new based repository. Or if you are not using any complex things of l5-repository then you can update all your existing repositories to use new BaseRepository.
