### ISSUE TITLE
route helper acting weird since latest update

### ISSUE THREAD

**Issue by vesper8** [InfyOmLabs/laravel-generator#78]
I just did a composer update and got the latest dev-master changes and I noticed a change in behavior.

In my scaffold view... the edit and show buttons that used to work properly are now sending me to the api route instead.

What I mean, let's say I have a model "State". By going to /states you see the scaffolding of all my states with the show, edit and destroy buttons.

Those buttons use route('states.show', [$data->id]) and route('states.edit', [$data->id]) to generate the route url.

Prior to composer update this would link to /states/1 and /states/1/edit, but after the update it now links to /api/v1/states/1 and /api/v1/states/1/edit

Which obviously doesn't work... Is this a bug you introduced or is there something I am missing?

The delete button also suffers from the same issue.

**Comment by mitulgolakiya** [comment]
Can you post your generated files with `config/infyom/laravel_generator.php` and `routes.php` and `api_routes.php` ?

**Comment by mitulgolakiya** [comment]
Tested everything and working fine.
