### ISSUE TITLE
How custom messages validations rules

### ISSUE THREAD

**Issue by christiantigre** [InfyOmLabs/laravel-generator#783]
public $fillable = [
        'name', 
];

protected $casts = [
        'name' => 'string',
];

public static $rules = [
        'name' => 'required|max:11',
];

I need add custom messages 
I try 
1)
public static messages()
    {
        return [
            'name.required' => 'Name is required please',     
            'name.max' => 'Name max limit 11',       
        ];
    }

2)
public static $messages = [
            'name.required' => 'Name is required please',     
            'name.max' => 'Name max limit 11',       
        ];
    

but eny work, return messages
-The name field is required.

How I can custom this messages error??

**Comment by vishalinfyom** [comment]
@christiantigre Please add `messages()` method in your form request, e.g. : 

```
public function messages()
{
    return [
        'name.required' => 'Name is required please',
        'name.max' => 'Name max limit 11',
     ];
 }
```

You can find more details [here ](https://laravel.com/docs/6.x/validation#customizing-the-error-messages)
