### ISSUE TITLE
How to reload a generated CRUD into the Visual builder?

### ISSUE THREAD

**Issue by FreddyCrugger** [InfyOmLabs/laravel-generator#787]
Hello,

I could not find a forum where I could ask questions so I came here.
I just downloaded your latest version and was trying the Visual builder(generator).
It looks good but I just created a table and made a mistake(forgot 2 fields), How to reload the crud fields into the generator please?

Thank you.

**Comment by ajayinfyom** [comment]
@FreddyCrugger You can use Rollback Command for rollback all generated files and generate new crud.
rollback docs: https://labs.infyom.com/laravelgenerator/docs/6.0/generator-commands#rollback
