### ISSUE TITLE
Incorrect references to language variables in localized files

### ISSUE THREAD

**Issue by Extractivity** [InfyOmLabs/laravel-generator#793]
Hello. First of all, great idea for a package; could be an immense time saver for me, thank you.

**Problem**

After creating localized api-scaffolding from an existing table, the created blade files contain incorrect references to language variables, i.e. instead of the actual translated term `Bezeichnung` I get a path to the translation like `models/BenutzerRolle.fields.Bezeichnung` in CRUD views.

**Example**

I create files for an existing table: `php artisan infyom:api_scaffold --tableName=BenutzerRolle --fromTable --save --localized --plural=BenutzerRollen BenutzerRolle`

Now `resources/views/benutzer_rollen/fields.blade.php` contains the line `{!! Form::label('Bezeichnung', __('models/BenutzerRolle.fields.Bezeichnung').':') !!}` as label for a text field, although the file `models/BenutzerRolle` does not exist.

If I publish templates and edit `resources/infyom/infyom-generator-templates/scaffold/fields/text_locale.stub` to replace `models/$TABLE_NAME$` with `models/$MODEL_NAME_PLURAL_CAMEL$` and then run the scaffolding again, `resources/views/benutzer_rollen/fields.blade.php` now contains the 'correct' reference to `models/benutzerRollen`, which is an existing file created by the scaffolding.

As it looks to me now, I'll have to fix all references in all _locale templates. Am I missing something? Thank you.

**Comment by ruanpepe** [comment]
Could anyone solve this?

**Comment by ajayinfyom** [comment]
Fixed.
