### ISSUE TITLE
Cant Input Date

### ISSUE THREAD

**Issue by erbaafidotama** [InfyOmLabs/laravel-generator#795]
I use AdminLTE for template infyom. I use scaffold and one field have date type. When I try input data in form, I cant input field date type. always blank. This is code in my project:
`@section('scripts')
    <script type="text/javascript">
        $('#tgl_lahir').datetimepicker({
            format: 'YYYY-MM-DD HH:mm:ss',
            useCurrent: false
        })
    </script>
@endsection`

I did not change anything. how resolve my problem?
Thx

**Comment by ShaileshInfyom** [comment]
@erbaafidotama as a quick fix replace input type date to text.

`{!! Form::text('tgl_lahir', null, ['class' => 'form-control','id'=>'tgl_lahir']) !!}`

we will fix it soon.

**Comment by ShaileshInfyom** [comment]
here fixed https://github.com/InfyOmLabs/adminlte-templates/pull/55

**Comment by ajayinfyom** [comment]
issue Fixed.
