### ISSUE TITLE
Created By field using id of logged in user

### ISSUE THREAD

**Issue by rajkumarpb** [InfyOmLabs/laravel-generator#797]
As mentioned in title, I would like to add the id of logged in user to be added in created_by field in table for every insert and in modified_by field if edit. How can I achieve this with infyom generator? Sorry if it's very basic question but I'm a noob in Laravel.

**Comment by tolu-six** [comment]
Hi rajkumarpb,
You can get the logged in user id, by using the auth middleware, which you then map with the created_by or modified_by and finally save

**Comment by ajayinfyom** [comment]
@rajkumarpb  currently, there is no way to do this, will add support for it.

**Comment by mitulgolakiya** [comment]
We do not plan to do that as a part of this package. There are several other ways that can be accomplished if needed. Best way will be,

You publish the templates and then modify the template the way you need. I think best way will be,


1. Modify migration stub to add created_by and updated_by field
2. Create one common trait which listens for model creating and updating events and then updates the fields accordingly. so update the model stub file

And other files that seem to be updated. We will try to write some tutorials on this and attach the link here.
