### ISSUE TITLE
Auto declare primary key in generate model

### ISSUE THREAD

**Issue by HtooWaiKhant** [InfyOmLabs/laravel-generator#798]
I generated a full scaffold starting from an existing table. And Primary key in the existing table has a different name than id. so how can i declare when auto generate model. 
Eg - protected $primaryKey = 'hello_id';

**Comment by ajayinfyom** [comment]
@HtooWaiKhant you can do with passing  `--primary=custom_name_id`

Already its mention in docs: https://labs.infyom.com/laravelgenerator/docs/6.0/generator-options#custom-primary-key

**Comment by HtooWaiKhant** [comment]
but i have to generate from generator builder.

**Comment by ajayinfyom** [comment]
@HtooWaiKhant  oh sry but you didn't mention that thing in the issue. ok, I will check it with generator builder.

**Comment by HtooWaiKhant** [comment]
yeah! i forgot to mention. thanks for your help.
