### ISSUE TITLE
Core UI stopped working

### ISSUE THREAD

**Issue by meetthosar** [InfyOmLabs/laravel-generator#799]
Login page lost its CSS and drop down is not working after login.

Yesterday, coreui unpkg is updated to 3.0.0. It is creating problem.

Any help?? Little urgent!

**Comment by vishalinfyom** [comment]
@meetthosar we already updated it today, please re-publish layouts files by hittiing command : 

```php artisan infyom.publish:layout ```

**Comment by meetthosar** [comment]
Yeah, worked. You guys are doing great job!
