### ISSUE TITLE
The "--paginate" option does not exist. 

### ISSUE THREAD

**Issue by gombaniro** [InfyOmLabs/laravel-generator#80]
when executing this command "php artisan infyom:api User" The error keeps showing up

**Comment by codingquark** [comment]
Same here.

Laravel version: `5.2.23`
Laravel generator version: `dev-master`

**Comment by mitulgolakiya** [comment]
@gombaniro @codingquark, it was a bug at some level. But first of all, `--paginate` option is supported in scaffold generator only. It's not for API. API has a parameter options which can be found [here](http://labs.infyom.com/laravelgenerator/docs/options/api-params).

Still I fixed the bug in Scaffold generator. Try again.

**Comment by codingquark** [comment]
Can confirm it is solved. Thanks!
