### ISSUE TITLE
Suggestion - allow decimal numbers in htmlType

### ISSUE THREAD

**Issue by monkeybanana550** [InfyOmLabs/laravel-generator#800]
I was searching for ways to dynamically accept values in which contain decimal values. Currently, InfyOms only allow numeric `htmlType,` and to allow such values (the only approach I knew so far) is to disable the numeric and apply `required|numeric|max:5|regex:/^-?[0-9]+(?:\.[0-9]{1,2})?$/` in the `public static $rules` within your desired `model` name.

**Comment by mitulgolakiya** [comment]
@monkeybanana550 can you please add some more detail with proper examples? I'm not able to understand the issue.

Feel free to reopen the issue after adding more details.
