### ISSUE TITLE
PHPDoc not generated in Models when Swagger generated

### ISSUE THREAD

**Issue by genesiscz** [InfyOmLabs/laravel-generator#802]
Hey, I guess that is not a wanted feature to not generate the @property fields when you enable swagger. The generateSwagger function replaces the DOCS so php doc is not placed correctly. Could we have a possibility to have them both?

PS: Also, how do I get the relations within the repository, eg. address in the users table marked by address_id in the Api resource?

**Comment by skys215** [comment]
For the second question, use `load()` method to get the relations.

**Comment by ShaileshInfyom** [comment]
@genesiscz this issue can not produce anymore. docs generated properly in model
![image](https://user-images.githubusercontent.com/28335166/151520297-af8b3103-9a3c-4b50-938a-6ddcbec11b14.png)


Feel free to re-open the issue with more details if you are still facing this issue.

**Comment by genesiscz** [comment]
But phpdoc `@property` tags are omitted, aren't they?
