### ISSUE TITLE
DataTables not listing records

### ISSUE THREAD

**Issue by arif-sb** [InfyOmLabs/laravel-generator#804]
Hi,
i have installed the package and every things goes well except datatables, when ever i use --datatables=true listing page shows nothing.

like
php artisan infyom:scaffold Invoice --fromTable --tableName=invoices --ignoreFields= --datatables=true 

without datatables every thing is working as expected - i am using infyomlabs laravel-generator 6.0 with laravel 6.0 on php 7... 
i will be great full to have you support in resolving this issue if its on my end.

here are is my composer json part.
 "name": "laravel/laravel",
    "type": "project",
    "description": "The Laravel Framework.",
    "keywords": [
        "framework",
        "laravel"
    ],
    "license": "MIT",
    "require": {
        "php": "^7.2",
        "fideloper/proxy": "^4.0",
        "laravel/framework": "^6.0",
        "laravel/tinker": "^1.0",
        "infyomlabs/laravel-generator": "6.0.x-dev",
        "infyomlabs/adminlte-templates": "6.0.x-dev",
        "laravelcollective/html": "^6.0",
        "doctrine/dbal": "~2.3",
        "yajra/laravel-datatables-buttons":"^4.6",
        "yajra/laravel-datatables-html":"^4.4",
        "yajra/laravel-datatables-oracle":"~9.0",
        "appointer/swaggervel": "dev-master",
        "infyomlabs/swagger-generator": "dev-master",
		"infyomlabs/generator-builder": "dev-master"
    },

**Comment by shailesh-ladumor** [comment]
@arif-sb watch this tutorial https://www.youtube.com/watch?v=YC0YXrAF4SA&list=PL0wCC44AhrC3JHzcB5qmjYkm70OaoKegghow to use datatable with generator. hope it's help..
