### ISSUE TITLE
Not Found The requested resource /services was not found on this server.

### ISSUE THREAD

**Issue by king1254** [InfyOmLabs/laravel-generator#807]
Not Found
The requested resource /services was not found on this server.
![Capture](https://user-images.githubusercontent.com/40822571/76143291-5f10a800-6087-11ea-9ac9-a3686459a0cc.JPG)
![ROUTE](https://user-images.githubusercontent.com/40822571/76143304-794a8600-6087-11ea-8ff7-14edb6fbba0a.JPG)

**Comment by skys215** [comment]
It seems not laravel-generator's problem.
Did you enabled Rewrite module on your nginx/apache/IIS?
Goggle has more answer.
