### ISSUE TITLE
Template not synced to field name changes

### ISSUE THREAD

**Issue by skys215** [InfyOmLabs/laravel-generator#809]
I found out that the `toggle-switch` is renamed as `toggle_switch` here:
https://github.com/InfyOmLabs/laravel-generator/commit/5a5fc19463259c71ad24ef65d864b4b2fb4e535e#diff-565f0798385c7246ec36d01b2f4f67be

But both in `adminlte-templates` and `coreui-templates` remains `toggle-switch.stub`.
This causes the fields uses toggle switch won't generate.

P.S. The related part of document also need to be updated.

**Comment by ajayinfyom** [comment]
Fixed to generate a toggle switch.
