### ISSUE TITLE
Question: is there a way to decide what data is sent during index and show?

### ISSUE THREAD

**Issue by codingquark** [InfyOmLabs/laravel-generator#81]
I want to respond with minimum data when `index` is called and want to return a detailed object when the `show` route is accessed. Any way to achieve it?

**Comment by codingquark** [comment]
I went through the code of `BaseRepository` and I think it's possible to decide by passing columns required and also using `$availableIncludes`. Any better way to do it?

**Comment by phillipmadsen** [comment]
He is working on a new fields file import that you can specify this in.

**Comment by codingquark** [comment]
Is there any link to it so that I can subscribe to it and close this thread?

**Comment by mitulgolakiya** [comment]
it is something related like #35

**Comment by mitulgolakiya** [comment]
Commited in master. Check with the latest code.

**Comment by phillipmadsen** [comment]
This is now controlled with inIndex and inForm in the fields-file.json file.
