### ISSUE TITLE
How to generate swagger annotations for your apis?  Please help

### ISSUE THREAD

**Issue by gillguy81** [InfyOmLabs/laravel-generator#813]
'add_on.swagger' => true this is true , 
but still swagger annotations not getting in API Controllers

I am using this command to generate : api_scaffold
php artisan infyom:api_scaffold Project --fromTable --tableName=projects

My composer.json
{
  "name": "laravel/laravel",
  "type": "project",
  "description": "The Laravel Framework.",
  "keywords": [
    "framework",
    "laravel"
  ],
  "license": "MIT",
  "require": {
    "php": "^7.2",
    "doctrine/dbal": "~2.3",
    "fideloper/proxy": "^4.0",
    "infyomlabs/adminlte-templates": "6.0.x-dev",
    "infyomlabs/generator-builder": "dev-master",
    "infyomlabs/laravel-generator": "6.0.x-dev",
    "infyomlabs/swagger-generator": "dev-master",
    "laravel/framework": "^6.0",
    "laravel/tinker": "^1.0",
    "laravelcollective/html": "^6.0",
    "tymon/jwt-auth": "^1.0",
    "yajra/laravel-datatables-buttons": "^4.6",
    "yajra/laravel-datatables-html": "^4.4",
    "yajra/laravel-datatables-oracle": "~9.0"
  },
  "require-dev": {
    "appointer/swaggervel": "^2.5",
    "barryvdh/laravel-ide-helper": "^2.6",
    "filp/whoops": "^2.0",
    "fzaninotto/faker": "^1.4",
    "mockery/mockery": "^1.0",
    "nunomaduro/collision": "^3.0",
    "phpunit/phpunit": "^8.0"
  },
  "config": {
    "optimize-autoloader": true,
    "preferred-install": "dist",
    "sort-packages": true
  },
  "extra": {
    "laravel": {
      "dont-discover": []
    }
  },
  "autoload": {
    "psr-4": {
      "App\\": "app/"
    },
    "classmap": [
      "database/seeds",
      "database/factories"
    ]
  },
  "autoload-dev": {
    "psr-4": {
      "Tests\\": "tests/"
    }
  },
  "minimum-stability": "dev",
  "prefer-stable": true,
  "scripts": {
    "post-autoload-dump": [
      "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
      "@php artisan package:discover --ansi"
    ],
    "post-root-package-install": [
      "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
    ],
    "post-create-project-cmd": [
      "@php artisan key:generate --ansi"
    ]
  }
}

**Comment by aydinbulut** [comment]
Enabling Swagger is not enough only, you need to install Swagger Specs Generator & Swagger UI package mentioned in the documentation but the required package is archived.

Documentation for [Enabling Swagger](https://labs.infyom.com/laravelgenerator/docs/7.0/generator-options#swagger) 

I installed L5-Swagger mentioned in #815 and it worked well so far.
