### ISSUE TITLE
`schema_files` has no default values in CommandData.php

### ISSUE THREAD

**Issue by skys215** [InfyOmLabs/laravel-generator#814]
I found that default value of `path.schema_files` attribute is not set in [here, CommandData.php](https://github.com/InfyOmLabs/laravel-generator/blob/211584cd0326ef770983d281833100a305f1e139/src/Common/CommandData.php#L225).

Which will cause that if config file is not published via `vendor:publish`, it will failed to get field file when using `--fieldsFile` option.

**Comment by ajayinfyom** [comment]
added default value for `schema_files` path
