### ISSUE TITLE
Swagger package is archived 

### ISSUE THREAD

**Issue by ayman-elmalah** [InfyOmLabs/laravel-generator#815]
https://github.com/appointer/swaggervel

this package is archived right now, you can use l5 swagger package instead

https://github.com/DarkaOnLine/L5-Swagger

**Comment by ajayinfyom** [comment]
we will update Swagger package soon.

**Comment by aydinbulut** [comment]
I am using L5-Swagger and it works well so far.

**Comment by medioseureka** [comment]
Question, the L5-Swagger is working with no additional configuration or do I have to write some Swagger notation because I have
`ErrorException : Required @OA\Info() not found`
and I have referred to [this](https://github.com/DarkaOnLine/L5-Swagger/issues/273) but it just no generate the API documentation, just the main controller.

**Comment by aydinbulut** [comment]
I am using Swagger 2.0 but with a fresh install it uses 3.0 and as far as I remember you have to specify @OA\Info() in one of the PHP classes under app/ directory. I faced this problem when I installed the first time.

**Comment by medioseureka** [comment]
Sorry if my question is dumb but, would you please give me an example, because InfyOmLabs generates `@SWG\Get` tag but the above package needs `@OA\` tag, it only generates the main controller where I put `@SWG\Get`.

**Comment by ajayinfyom** [comment]
@ayman-elmalah  @medioseureka @aydinbulut 
Added support for laravel 7 in Generator Swagger package. 

please refer Updated docs: https://labs.infyom.com/laravelgenerator/docs/6.0/generator-options

also, you can check the video from here: https://www.youtube.com/watch?v=5ILtqB1aR9g

**Comment by xwiz** [comment]
@ajayinfyom Sorry for reopening, why does the docs prefer swaggervel archived package instead of `darkaonline/l5-swagger` ? I'm curious because I want to check it out and wondering what might break.

**Comment by mitulgolakiya** [comment]
@xwiz there is no preference here, it was like, we have support for that package and it was working well. But not I see that for some reason it was archived. so I already forked the repo and now we are using our own forked version. But we can plan to move to some better package in the future.

Or you can do that and put a PR. :)

**Comment by medioseureka** [comment]
Hey awsome, thanks for the great job.
