### ISSUE TITLE
Locale Table Headers Lang Not Found

### ISSUE THREAD

**Issue by rabrowne85** [InfyOmLabs/laravel-generator#828]
There appears to be a discrepancy with how the locale is templated. In most the of the `coreui-templates` package template files it uses the reference to: `@lang('models/$MODEL_NAME_PLURAL_CAMEL$.singular')`.

However in the generation of the index table headers in the `helpers.php` file within the `laravel-generator` package, it uses: `$template = str_replace($variable, "@lang('models/$tableName.fields.$value')", $template);`.

If the table name is being specified as something different (`--tableName=`) to the model name then this causes an issue, as it's looking for two files under the `lang` folder `tablename.php` and `modelname.php`.

Personally I would go for the `tablename.php` option as this should generally be unique.

N.B. I've been using the `coreui-templates` package and I haven't checked the `adminlte-templates` package.

**Comment by ajayinfyom** [comment]
same issue: #793

**Comment by ajayinfyom** [comment]
Fixed
