### ISSUE TITLE
need to add deleted_at to fromTable cmd

### ISSUE THREAD

**Issue by phillipmadsen** [InfyOmLabs/laravel-generator#83]
it keeps coming up missing on the generation unless you use the make:auth but then it comes with the auth files.

**Comment by mitulgolakiya** [comment]
@phillipmadsen I am not able to get your issue. Can you describe it bit more ?

**Comment by phillipmadsen** [comment]
Sorry I  forgot to add If using softdeletes the table will need to have deleted_at included so you should make it default or an option. Everytime I  use the generator I  have to manually add it to the table.

**Comment by mitulgolakiya** [comment]
`softDelete` is already optional. Check it [here](https://github.com/InfyOmLabs/laravel-generator/blob/master/config/laravel_generator.php#L105). so if you are generating from table which doesn't have `deleted_at` column then make it false.

**Comment by phillipmadsen** [comment]
What im saying is if you use the softdelete table option then it requires a deleted_at field. Your package is not adding this like it should. 

softdeletes required deleted_at
your package is missing this part when using --softDeletes

so when you generate the crud and go to view the outcome there is a field missing error.

**Comment by mitulgolakiya** [comment]
@phillipmadsen Still I'm not able to get you issue. Can you post the following thing ?

1. Your existing database table on which you are running command
2. Command that you are running
3. Problematic files
4. Problem notes (Expected Result, Actual Result)

**Comment by firecentaur** [comment]
Hi there, I have the same issue.  When I generate the scafolding for an existing table, I then refresh the devtools page and click on the model name in the side bar.  When I do that I get an error message complaining that deleted_at field is unknown.  My table doesnt have this field. or updated_at or created_at.  Your code should ask to add these fields if they dont exist on the table.
