### ISSUE TITLE
php artisan infyom.publish:generator-builder 

### ISSUE THREAD

**Issue by rabol** [InfyOmLabs/laravel-generator#830]
Just trying to follow the documentation:

this command does not work:

php artisan infyom.publish:generator-builder

**Comment by vishalinfyom** [comment]
Hey @rabol please make sure you are performing all steps, or there are some config:cache issue, because its working totally fine for us.


![image](https://user-images.githubusercontent.com/33887755/78752550-f1131580-7991-11ea-9ff1-ba5883ce752a.png)

**Comment by rabol** [comment]
I found the issue... the service provider is not auto discovered - which is normal for all packages nowadays :)

**Comment by mitulgolakiya** [comment]
@rabol thanks for reporting. we will consider that.
