### ISSUE TITLE
infyom:rollback does not cleanup everything

### ISSUE THREAD

**Issue by rabol** [InfyOmLabs/laravel-generator#832]
The rollback command does not do a rollback of the db migration and it does not delete the migration file

**Comment by ajayinfyom** [comment]
we already mention that things in docs:  https://labs.infyom.com/laravelgenerator/docs/6.0/generator-commands#rollback.

you must be rollback migration by manually.

**Comment by rabol** [comment]
https://labs.infyom.com/laravelgenerator/docs/7.0/generator-commands

from the doc:

"If you have run migration on database, then better you rollback that migration first and then run infyom:rollback command, since it will delete migration file as well. Otherwise laravel can throw error about missing migration files."

as you can see,it is say that the migration file will be deleted, but the file is not deleted
