### ISSUE TITLE
--fieldsFile want to create a new schema file

### ISSUE THREAD

**Issue by rabol** [InfyOmLabs/laravel-generator#833]
When using the --fieldsFile the scaffold command still want to overwrite the input file

e.g.

php artisan infyom:api_scaffold --fieldsFile=test.json Test

then at the end the command asks to do migration and asks if you want to overwrite the test.json file

**Comment by aydinbulut** [comment]
The tool generates all files from scratch in each attempt even if you specify `--fieldsFile`, that is why it asks. It will generate the same test.json you have even if it overwrites.

**Comment by mitulgolakiya** [comment]
@aydinbulut @rabol The purpose of that is, we support multiple locations for input files, but only one destination location to save file and even that can be configured.

That's why it asks for confirmation if file exists.

So IMO, it's fine.

**Comment by rabol** [comment]
I would agree if the --fieldsFile was not specified on the command line as a parameter, but since it is specified, there is no need to generate/save it again - It was just used as input so nothing has changed
