### ISSUE TITLE
[Enhancement]: "use Illuminate\Http\Response;" instead of  "use Response;" because phpstan throws error

### ISSUE THREAD

**Issue by aydinbulut** [InfyOmLabs/laravel-generator#834]
Can we use the below suggestion in the controllers or wherever it is being used?

`"use Illuminate\Http\Response;" instead of  "use Response;"`

I am using PHPStan to analyze the code and `use Response;` fails. 

![image](https://user-images.githubusercontent.com/2726365/78766729-4f3ff880-7992-11ea-97f8-00fb276d2cb3.png)

I put it to the `ignoredErros` list for now but it would be great to do so. BTW, I tried to update stubs but it broked things and I don't remember. But I can reproduce it and provide information about that if you don't know it yet.

**Comment by sloumat** [comment]
"Illuminate\Support\Facades\Response;" instead of "use Response;"

**Comment by mitulgolakiya** [comment]
Fixed and not relevant since we are not using the `response()` function in v5.0.0
