### ISSUE TITLE
[Bug]: If model has 2 words in the name PhpDoc and route paths are generated different.

### ISSUE THREAD

**Issue by aydinbulut** [InfyOmLabs/laravel-generator#836]
My JSON file is UserRole.json

I did run
`php artisan infyom:api_scaffold --fieldsFile=UserRole.json UserRole`

routes/api.php
`Route::resource('user_roles', 'UserRoleAPIController');`

routes/web.php
`Route::resource('userRoles', 'UserRoleController');`

The first difference is different route paths for API and WEB. Hence, API endpoints don't match the generated paths.

![image](https://user-images.githubusercontent.com/2726365/79053808-c0a8d100-7c48-11ea-8763-dbbd5ddee436.png)

If I fix the route in `routes/api.php` then `UpdateUserRoleRequest` fails since I am using a unique attribute in my model. Below line  is generated code but it fails because `$this->route("user_role")` doesn't match any route.

`$rules['slug'] = $rules['slug'].",".$this->route("user_role");`

Am I missing something about naming in the documentation?

Also, I tried like below and still the same.
`php artisan infyom:api_scaffold --fieldsFile=User_Role.json User_Role`

**Comment by ruanpepe** [comment]
Same error from #793

**Comment by mitulgolakiya** [comment]
Fixed.
