### ISSUE TITLE
[L7] Datatables is not showing for the table

### ISSUE THREAD

**Issue by Saneesh** [InfyOmLabs/laravel-generator#843]
Hello,
I want to list my records with datatables.
step 1: `add_on.datatabled = true`
step 2:  executed the command `php artisan infyom:api_scaffold Product`

But when I checked in the admin panel after adding a product it is not showing data with datatables.

Am I missing something?

Regards,
Saneesh

**Comment by ShaileshInfyom** [comment]
@Saneesh Have you installed datatable packages? here is a [tutorial ](https://www.youtube.com/watch?v=YC0YXrAF4SA&list=PL0wCC44AhrC3JHzcB5qmjYkm70OaoKegg) maybe help.

**Comment by ShaileshInfyom** [comment]
also, one more thing is your command should be `php artisan infyom:scaffold Product`  not `php artisan infyom:api_scaffold Product`

**Comment by Saneesh** [comment]
Hello @ShaileshInfyom,
Thank you so much for your quick reply.
In composer
```
"maatwebsite/excel": "^3.1",
"phpoffice/phpspreadsheet": "^1.12",
"yajra/laravel-datatables-buttons": "^4.9",
"yajra/laravel-datatables-html": "^4.0",
"yajra/laravel-datatables-oracle": "~9.0"
```
In providers of app.php
```
Yajra\DataTables\DataTablesServiceProvider::class,
Yajra\DataTables\HtmlServiceProvider::class,
Yajra\DataTables\ButtonsServiceProvider::class,
```
In aliases of app.php
`'DataTables' => Yajra\DataTables\Facades\DataTables::class,`

in laravel_generator.php
`add_on.datatabled = true`


`php artisan infyom:scaffold Car`


I have followed the video as well. But still I'm not able to see the Datatables.
Note: I'm using `Laravel 7`

**Comment by Saneesh** [comment]
`table.blade.php` is created as follows
```
@section('css')
    @include('layouts.datatables_css')
@endsection

{!! $dataTable->table(['width' => '100%', 'class' => 'table table-striped table-bordered']) !!}

@push('scripts')
    @include('layouts.datatables_js')
    {!! $dataTable->scripts() !!}
@endpush
```


But the records added to the table is not showing

**Comment by ShaileshInfyom** [comment]
@Saneesh do not specify `--datatables=true` because you already enabled in config.
try  `php artisan infyom:scaffold News` also check console

**Comment by Saneesh** [comment]
Im using Laravel 7
if I'm not giving `--datatables=true` in the command it wont creates datatables related code even though I have added it in the config.

Is there any other settings I'm missing?

for datatables do I need to give something extra?

**Comment by ajayinfyom** [comment]
Hello @Saneesh 

Have you published Data tables tags ?? 
maybe that's a problem in your case.
let me know its work or not after published vendor.

![image](https://user-images.githubusercontent.com/30411745/82112538-59140300-976b-11ea-9380-340132489b9a.png)

**Comment by Saneesh** [comment]
Thank you so much for your effort!
I have published with `0`, same results.
I'm not seeing anything related to datatables(like table sort actions).

![Screenshot from 2020-05-16 14-37-21](https://user-images.githubusercontent.com/1501763/82115922-88cf0500-9783-11ea-9dbb-7ea16923bc4b.png)

Regards,
Saneesh.

**Comment by ajayinfyom** [comment]
I'm sure you are missing something, I have just tested a data table with Laravel 7.0.

Please try with all steps in a new project. 

![image](https://user-images.githubusercontent.com/30411745/82117458-a6a16780-978d-11ea-86ff-cf2b0210c85d.png)

**Comment by ajayinfyom** [comment]
@Saneesh  if you have the same issue in a new project then you can report here.

**Comment by quannetwork** [comment]
@ajayinfyom Can I have one small question? For now, the generated datatable doesn't have the show button, as we can see on your screenshot. So how can I add that show button, similar to the [demo of datatable](https://datatables.yajrabox.com/eloquent/basic).

![image](https://user-images.githubusercontent.com/8580008/83851518-b1bc3780-a73c-11ea-82af-42596f68f8e6.png)


> I'm sure you are missing something, I have just tested a data table with Laravel 7.0.
> 
> Please try with all steps in a new project.
> 
> ![image](https://user-images.githubusercontent.com/30411745/82117458-a6a16780-978d-11ea-86ff-cf2b0210c85d.png)

**Comment by RayhanYulanda** [comment]
> I'm sure you are missing something, I have just tested a data table with Laravel 7.0.
> 
> Please try with all steps in a new project.
> 
> ![image](https://user-images.githubusercontent.com/30411745/82117458-a6a16780-978d-11ea-86ff-cf2b0210c85d.png)

What datatable version do you used? Because there is big different from current version with old version. The current version not using button array anymore but using the button class

**Comment by mitulgolakiya** [comment]
@RayhanYulanda I think we previously tested it with Yajra Datatables 7.
