### ISSUE TITLE
No primary key is created for a non-standard key name

### ISSUE THREAD

**Issue by noxeone** [InfyOmLabs/laravel-generator#844]
I created the API from the file, wrote in it a non-standard name id
When requested through /api/{model_name}/{id} error:

> Column not found: 1054 Unknown column '.id' in 'where clause' 

It is necessary to add to the model class:

`protected $primaryKey = "{my_id}";`

**Comment by ajayinfyom** [comment]
Fixed.

**Comment by noxeone** [comment]
I found new problems with non-standard key name!
Create new issue or write here?
