### ISSUE TITLE
Another problem with non-standard key name

### ISSUE THREAD

**Issue by noxeone** [InfyOmLabs/laravel-generator#849]
I also found errors associated with a non-standard key name.

In the scaffold template files located: \resources\views\ {model_name}
table.blade.php and edit.blade.php need to replace

`$modelName->id`
to
`$modelName->new_id`

**Comment by ajayinfyom** [comment]
@noxeone Can you please try with the latest code. 
Its already fixed.  #844

**Comment by ajayinfyom** [comment]
If you getting still issue then you can report here.
