### ISSUE TITLE
[5.8] wrong/missing HTML class names

### ISSUE THREAD

**Issue by fatihmert** [InfyOmLabs/laravel-generator#850]
Hi;

When I noticed I couldn't create with relationship column on generate builder. 

HTML render;
![html render](https://i.hizliresim.com/bJjmfA.png)

_resources\views\infyom\generator-builder\builder.php_

```javascript
$('.relationItem').each(function () {
    relationFieldArr.push({
        relationType: $(this).find('.drdRelationType').val(),
        foreignModel: $(this).find('.txtForeignModel').val(),
        foreignTable: $(this).find('.txtForeignTable').val(),
        foreignKey: $(this).find('.txtForeignKey').val(),
        localKey: $(this).find('.txtLocalKey').val(),
    });
});
```

You can see that the HTML output is wrong according to the codes above. _drdRelationType_, _txtForeignModel_ etc..

My composer require section following this;
```json
"require": {
    "php": "^7.1.3",
    "fideloper/proxy": "^4.0",
    "laravel/framework": "5.8.*",
    "laravel/tinker": "^1.0",
    "infyomlabs/laravel-generator": "5.8.x-dev",
    "laravelcollective/html": "^5.8.0",
    "infyomlabs/adminlte-templates": "5.8.x-dev",
    "infyomlabs/swagger-generator": "dev-master",
    "appointer/swaggervel": "dev-master",
     "doctrine/dbal": "~2.3",
    "infyomlabs/generator-builder": "dev-master"
},
```

**Comment by ajayinfyom** [comment]
@fatihmert Can you please explain whats exactly problem.

`You can see that the HTML output is wrong according to the codes above. drdRelationType, txtForeignModel etc..` what its meaning ??
there already given all classes name in HTML code.

btw, I have tested with crud with a relationship. seem to look it's working perfectly.

**Comment by mitulgolakiya** [comment]
We do no longer support 5.8
