### ISSUE TITLE
api

### ISSUE THREAD

**Issue by perfectwebtech** [InfyOmLabs/laravel-generator#852]
hello

i have query regarding this

1) how i can use uuid any document or guidance ? regarding api i want to use uuid 

2) as well for backend is there way i can done  backend on rest api ? something crud operation via rest api 

3) is there relationship  menu each other auto generator look like in users have few table relationship so in menu activity can be possible there they user activity log user last login history something like this ? 
4) how swagger document generator something 500 erorr when i try it

**Comment by mitulgolakiya** [comment]
1) you can customize the templates and update them to use UUID. Find the docs here: https://labs.infyom.com/laravelgenerator/docs/7.0/publish-templates

2) I don't understand the question properly. But you can generate two things. Either full CRUD with blade files or just Api.

3) There is not support like that as of now.

4) I think you will be missing something in the swagger setup. Check the exact steps here: https://labs.infyom.com/laravelgenerator/docs/7.0/generator-options
