### ISSUE TITLE
Table attribute 'id' does not exist. With Datatables

### ISSUE THREAD

**Issue by joaocarlos** [InfyOmLabs/laravel-generator#862]
I am trying to use InfyOm in my project. I have an existing database. It worked with normal tables, but when I use DataTables it keeps me giving this error:

`Facade\Ignition\Exceptions\ViewException
Table attribute 'id' does not exist. (View: /vagrant/myproject/laravel/adminlte/resources/views/predios/table.blade.php)`

The table has an id column as a primary key. I have also another laravel instance with DataTables, and it is working as usual.

Any thoughts?

**Comment by ajayinfyom** [comment]
@joaocarlos what steps performance for DataTables ?.
and Can you please share table.blade.php file.

**Comment by ajayinfyom** [comment]
Maybe this video can help you: https://www.youtube.com/watch?v=YC0YXrAF4SA

Or re-open the issue with more details please.

**Comment by Logatto** [comment]
to solve this problem check if you have `{!! $dataTable->table(['id'=>'predios', ... ` in /views/predios/table.blade.php

**Comment by amritms** [comment]
for future viewers:
make sure you have set primaryKey in your model if you have custom primary key. ```protected $primaryKey = '<custom primary key>';```
