### ISSUE TITLE
infyom.publish:layout generates empty menu.blade.php

### ISSUE THREAD

**Issue by fmgrafikdesign** [InfyOmLabs/laravel-generator#863]
I followed the tutorial from https://labs.infyom.com/laravelgenerator/docs/7.0/boilerplates with the core-ui theme but ended up with an empty menu.blade.php file. Regenerating does not fix the problem.

**Comment by fmgrafikdesign** [comment]
I just found out regenerating is what *causes* the problem. Is there a way besides scaffolding every model again to recreate the correct menu.blade.php file from existing models?

**Comment by ajayinfyom** [comment]
No, there's no any way to regenerate all menus  and also its not good to recreate all menus on every generated scaffold.

**Comment by HuyNguyen206** [comment]
I also facing the same issue with Laravel 8.
Are there any ways to fix this issue?
