### ISSUE TITLE
 Generate scaffold for users with custom fields using artisan infyom.publish:user

### ISSUE THREAD

**Issue by thewebartisan7** [InfyOmLabs/laravel-generator#864]
Hi,

For generate scaffold of users I see there is command `php artisan infyom.publish:user`

But how to include custom fields because there is only default Laravel fields running this command.

Thanks

**Comment by ajayinfyom** [comment]
@thewebartisan7  there's not support yet to publish user module with custom fields. 
you can modify after published.
