### ISSUE TITLE
Get validated() from request instead of all()

### ISSUE THREAD

**Issue by thewebartisan7** [InfyOmLabs/laravel-generator#865]
Would be better to get $request->validated() fields from request instead of $request->all()

For better security and also for check validation.

Now:

```php
    public function store(CreateUserRequest $request)
    {
        $input = $request->all();

        /** @var User $user */
        $user = User::create($input);

        Flash::success('User saved successfully.');

        return redirect(route('users.index'));
    }
```

After:

```php
    public function store(CreateUserRequest $request)
    {
        $input = $request->validated();

        /** @var User $user */
        $user = User::create($input);

        Flash::success('User saved successfully.');

        return redirect(route('users.index'));
    }
```

**Comment by thewebartisan7** [comment]
You must also add for all fields used in forms almost one rule "nullable"
So validated() method will return it.

**Comment by mitulgolakiya** [comment]
@thewebartisan7 @ajayinfyom can someone tell me why we need this exactly? Because we have validation rules in the Custom Request file. so if validations are not passed then it will not reach the controller at all.

So can anyone highlight here why this is needed? Because IMO, this change forces us to add rule `nullable` for all the fields, otherwise as said, it will not return that input field.

Feel free to re-open this issue with explaination.

**Comment by thewebartisan7** [comment]
@mitulgolakiya the `validated()` method will not validate again the request but will return only validated fields, while `request()->all()` will return all.

As you know a mass assignment is secure *only* when you correctly set `$fillable` and `$guarded`, which is pretty fine way to prevent unwanted assignaments.

Another example could be that you have set `$fillable` or `$guarded` but there are two forms for the same model, where a form can be edited by users, but not other. He could just pass the not authorized fields to form which he has access, and so assign attributes that he can't. 

Is only required to add `nullable` to fields without any validations, it should not be hard to do. Could be added programmatically when missing any validations.
