### ISSUE TITLE
Add public $timestamps = false; when there is NOT timestamps

### ISSUE THREAD

**Issue by thewebartisan7** [InfyOmLabs/laravel-generator#866]
Add `public $timestamps = false;` when there is NOT timestamps

**Comment by ajayinfyom** [comment]
@thewebartisan7 you can set timestamps false from laravel_generator config file.

https://labs.infyom.com/laravelgenerator/docs/7.0/generator-options#timestamps

**Comment by thewebartisan7** [comment]
As I understand this is globally for all scaffold. But when I use from JSON without any timestamp, then I expect that $timestamp = false are added automatically. But is not big problem.
Thanks
