### ISSUE TITLE
Is there a way to specify views to be generated?

### ISSUE THREAD

**Issue by phillipmadsen** [InfyOmLabs/laravel-generator#87]
Wondering it there is a way to specify views that are to be generated. 

example:  
```
php artisan infyom:api_scaffold Profile index show --fieldsFile='resources/model_schemas/Profile.json' 
```
which makes all crud files but with only index.blade.php and show.blade.php and only index and show methods in the controller and routes?

**Comment by mitulgolakiya** [comment]
@phillipmadsen I have added option `--views` to specify to generate only specific views.

You can specify any comma separated values from this like: `--views=index,create,edit,show`.
