### ISSUE TITLE
Fail! Use of undefined constant STDIN - assumed 'STDIN' (this will throw an Error in a future version of PHP)

### ISSUE THREAD

**Issue by RayhanYulanda** [InfyOmLabs/laravel-generator#877]
Is it an error or just warning?

**Comment by mitulgolakiya** [comment]
@RayhanYulanda Can you post more details where you are getting and when?

**Comment by ItsAnubhav** [comment]
"Undefined constant 'STDIN'"
I was using the GUI Builder when I rolled back a migration and tried to regenerate with the same name. This method is being called.
https://github.com/InfyOmLabs/laravel-generator/blob/3e40e345534c2a8f98a2178fb69bc9e9b826a3d8/src/Commands/BaseCommand.php#L283
