### ISSUE TITLE
Infyom view generator stuck in my last input

### ISSUE THREAD

**Issue by RayhanYulanda** [InfyOmLabs/laravel-generator#878]
I tried to generate another column but it cant, stuck in my last input and cannot force migrate too
Any ideas?
![image](https://user-images.githubusercontent.com/15263594/88482038-ee601e80-cf88-11ea-8314-92a565161fec.png)

**Comment by mitulgolakiya** [comment]
@RayhanYulanda I think you already have that migration exist. Delete that existing migration and try it again.
