### ISSUE TITLE
New features to create dynamic variables and basic validation rules

### ISSUE THREAD

**Issue by fabiomlferreira** [InfyOmLabs/laravel-generator#879]
I'm a former Yii2 programmer and I miss alot when we generate a model to have some basica validation rules based on the field information from the database, for example if is a string with 255chars and required it should generate the rule like this
`'title' => 'required|string|max:255,`
if is not required should create something like this
`'title' => 'nullable|string|max:255,`

Do you have plans to add it?

The second question is more tricky I want to add something like this to all my models
```
/**
     * Attribute labels
     *
     * @var array
     */
    public static function attributeLabels()
    {
        return [
            'id' => __('Id'),
            'member_type_id' => __('Member Type Id'),
            'name' => __('Name'),
            'title' => __('Title'),
        ];
    }
```
This is a function to have the names of each attribute to use on the views instead of writing everytime the same __("atribute") and to pass to validation to get the corrent message on validation, but I don't know how can I create a dynamic variable that generate this 
```
'id' => __('Id'),
            'member_type_id' => __('Member Type Id'),
            'name' => __('Name'),
            'title' => __('Title'),
```

In the end on my .stub files I want to have something like this
```
public static function attributeLabels()
    {
        return [
            $ATTRIBUTE_LABELS$
        ];
    }
```

Is this possible? How can i generate a new dynamic variable and access the attributes from database and iterate through it.

**Comment by mitulgolakiya** [comment]
#858 Merged.
