### ISSUE TITLE
Really need a Boolean option 

### ISSUE THREAD

**Issue by phillipmadsen** [InfyOmLabs/laravel-generator#88]
```
$table->boolean('confirmed');
```
provides a simple true false response. 

example uses are:

is_published
has_option
activate_section

**Comment by phillipmadsen** [comment]
**Also needs to generate:**
```
    protected $casts = [
        'is_admin' => 'boolean',
    ];
```
**Example Uses:**
```
$user = App\User::find(1);

if ($user->is_admin) {
    //
}
```

**Comment by phillipmadsen** [comment]
Checkbox works but need both choices true false.  This would just need checked  which would output true if checked and needs just the field name and no options.

**Comment by mitulgolakiya** [comment]
@phillipmadsen check with the latest code. its done.
