### ISSUE TITLE
Feature request: allow custom template to be loaded from all vendor name

### ISSUE THREAD

**Issue by thewebartisan7** [InfyOmLabs/laravel-generator#882]
Actually custom theme can only be loaded from infyomlabs vendor, so I can't make make a portable theme inside another vendor namespace.

The only way is to load it using symlink from local folder, example:

```
{
        "type": "path",
        "url": "packages/infyomlabs/custom-theme",
        "options": {
            "symlink": true
        }
    }
```

**Comment by mitulgolakiya** [comment]
@thewebartisan7 Good point. we will check on making this change.

**Comment by mitulgolakiya** [comment]
Fixed: Check docs here: https://labs.infyom.com/laravelgenerator/docs/7.0/configuration#scaffold-templates

and here: https://labs.infyom.com/laravelgenerator/docs/7.0/publish-templates#custom-templates

**Comment by thewebartisan7** [comment]
Thanks works perfectly now.
