### ISSUE TITLE
[Doc] What is config option tables_searchable_default 

### ISSUE THREAD

**Issue by thewebartisan7** [InfyOmLabs/laravel-generator#883]
For what it's used tables_searchable_default?
Is not on documentation here https://labs.infyom.com/laravelgenerator/docs/7.0/configuration and seem only used in GeneratorForeignKey class added to defaultSearchable.
Thanks

**Comment by mitulgolakiya** [comment]
@thewebartisan7 that flag makes all fields default searchable except primary key and timestamps. I will update the docs.

Thanks for capturing it.

**Comment by mitulgolakiya** [comment]
@thewebartisan7 the docs are updated and you can check it here: https://labs.infyom.com/laravelgenerator/docs/7.0/configuration#options
