### ISSUE TITLE
Get $FIELD_NAME$ in table_header

### ISSUE THREAD

**Issue by thewebartisan7** [InfyOmLabs/laravel-generator#887]
I can't find an easy solution to get $FIELD_NAME$ in table_header.stub
Would be possible to add it?
In my case I need to know $FIELD_NAME$ for add sorting/ordering by making <th> clickable with ?sort=$FIELD_NAME$
Thanks

**Comment by mitulgolakiya** [comment]
support is already there. I just modified `table_header.stub` content to `<th>$FIELD_NAME_TITLE$ - $FIELD_NAME$</th>` and I can see the result as `<th>Title - title</th>`.

**Comment by thewebartisan7** [comment]
Sorry, I forgot to mention that work fine with table_header.stub
But when localized is enabled, the file table_header.stub $FIELD_NAME$ is translated string.
Example of output of $FIELD_NAME$:

`@lang('models/articles.fields.title')`

Also $FIELD_NAME_TITLE$ render:

`@lang('models/articles.fields.title')`

**Comment by thewebartisan7** [comment]
@mitulgolakiya not sure if you get notification of my last comment since issue is closed

**Comment by thewebartisan7** [comment]
@see https://github.com/InfyOmLabs/laravel-generator/pull/891
@mitulgolakiya

**Comment by mitulgolakiya** [comment]
@thewebartisan7 PR merged. Thanks for your effort 👍
