### ISSUE TITLE
Relation with Repository

### ISSUE THREAD

**Issue by Silviobramas** [InfyOmLabs/laravel-generator#890]
In my older laravel version i could do something like that in my Controler:
`public function edit($id){
       $bestellung = $this->bestellungRepository
                            ->with('produkte')
                            ->find($id);
}
` 
but after updating I get the error that the with methond can't be used. How do you sole it if you want to use eager loading?

**Comment by mitulgolakiya** [comment]
@Silviobramas Right now there is no way to do that. I think what you can do is, you can add one more method in `app/Repositories/BaseRepository` something like this,

```
public function findWith($id, $with, $columns = ['*'])
{
    $query = $this->model->newQuery()->with($with);

    return $query->whereKey($id)->first($columns);
}
```

Maybe that can help.

We are also planning some major releases in probably next month with Laravel 8 where we are planning to add `andersao/l5-repository` again to BaseRepository, but with more control. I'm also going to submit some features as a PR to that repository that we need.

But I think right now something like this may help you.
