### ISSUE TITLE
Where condition

### ISSUE THREAD

**Issue by emmadedayo** [InfyOmLabs/laravel-generator#894]
Hello everyone, please how i can i use where condition statement here 
$foloCashouts = $this->foloCashoutRepository->all(
            $request->except(['skip', 'limit']),
            $request->get('skip'),
            $request->get('limit')
        );
and in general $foloCashouts = $this->foloCashoutRepository->where('condition','id'); is not working also I get this error Call to undefined method App\Repositories\FoloCashoutRepository::where() in file

**Comment by aydinbulut** [comment]
You should use allQuery() instead of all()

**Comment by mitulgolakiya** [comment]
@emmadedayo we are going to add repository support again. so this will work after that. Right now you can use the solution that @aydinbulut suggested.
