### ISSUE TITLE
Class notfound

### ISSUE THREAD

**Issue by zkenstein** [InfyOmLabs/laravel-generator#896]
Hello, 
I tried to installing the package following the documentation . But when artisan publish it return the error Class Not found for Flash and InfyOm. Anyone have this issue, I am running on Laravel 6.6.3

**Comment by mitulgolakiya** [comment]
@zkenstein Laravel 6 has been used with lots of developers and nobody has this issue. If you still have an issue then re-open this issue with more details on what you are specifying into your compser.json.

Thanks.
