### ISSUE TITLE
Is it compatible with laravel 8?

### ISSUE THREAD

**Issue by faizananwerali** [InfyOmLabs/laravel-generator#898]
Before I start new project, is this compatible with laravel 8? according to docs it's compatible with laravel 7 but no mention of laravel 8.

**Comment by mitulgolakiya** [comment]
yes, doc is already there for Laravel 8, https://labs.infyom.com/laravelgenerator/docs/8.0/installation

**Comment by genesiscz** [comment]
> yes, doc is already there for Laravel 8, https://labs.infyom.com/laravelgenerator/docs/8.0/installation

Could you make it work for both 7 and 8? I can't update because there's no release for this package so I use dev-develop. Would that break anything?

**Comment by genesiscz** [comment]
EDIT: Disregard my previous question, I guess I can just use branch 7.0
