### ISSUE TITLE
Route [verification.notice] not defined. 

### ISSUE THREAD

**Issue by cpasqualini** [InfyOmLabs/laravel-generator#899]
Hi!

I've added `->middleware('verified')` to a route in `routes/web.php`, expecting to require a verified session 

This works on another project with Laravel 7.x and LaravelGenerator 7, but in this brand new project, with laravel 8.x and laravelgenerator 8.x throws a `Route [verification.notice] not defined.` exception.

Now, I check'd [Release Notes 8.0](https://labs.infyom.com/laravelgenerator/docs/8.0/releases) and there is no information on supporting Laravel 8.x

I'm using:

> `"infyomlabs/laravel-generator": "8.0.x-dev",`
> `"laravel/framework": "^8.0",`

Is this a compatibility issue? does it have a known fix or workaround

Thanks!

**Comment by cpasqualini** [comment]
Please nevermind the first part, it was an error mixing 'verified' (wrong) with -middleware('auth'), it seems this was insufficient caffeine issue ;-)

The Laravel 8.x compatibility stands though

**Comment by mitulgolakiya** [comment]
Great. Then closing it.
