### ISSUE TITLE
Sugestion - Migration versioning

### ISSUE THREAD

**Issue by iboinas** [InfyOmLabs/laravel-generator#9]
Hello Mitul,

First of all, congrastulations for this package, is awesome, especially because of allowing project-specific configurations and templating. Wonderful.

I have sugestion, that think is easily achievably (using laravel collections).
For a given migration, check if table already exists on DB.
If not, goes as today.
If it exists, goes to different abstraction, where compare schema, and makes migration accordingly.

What do you think?

**Comment by mitulgolakiya** [comment]
This is a good idea but maybe not for everyone. will leave it up to a user to make those migration changes.
