### ISSUE TITLE
Laravel 8.x  and API

### ISSUE THREAD

**Issue by cpasqualini** [InfyOmLabs/laravel-generator#900]
Hi!

Using Laravel 8.x with laravel-generator 8.0, the API throws a 500 error:

> Illuminate\Contracts\Container\BindingResolutionException: Target class [API\App\Http\Controllers\API\ModelAPIController] does not exist. in file /path/to/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 811

It gets working if change back suggested change in RouteServiceProvider.php as:

```
              Route::prefix('api')
                 ->middleware('api')
                 ->as('api.')
                 //->namespace($this->namespace."\\API")
                 ->namespace($this->namespace)
                 ->group(base_path('routes/api.php'));
```

Thanks

**Comment by mitulgolakiya** [comment]
@cpasqualini Check out the new docs: https://labs.infyom.com/laravelgenerator/docs/8.0/installation#update-api-routes

Thanks for catching this up.

**Comment by cpasqualini** [comment]
No, it does not work:

`Illuminate\Contracts\Container\BindingResolutionException: Target class [App\Http\Controllers\API\App\Http\Controllers\API\ModelAPIController] does not exist. in file /path/to/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 811`

**Comment by mitulgolakiya** [comment]
can you past screenshot here? what you have written in RouteServiceProvider?

**Comment by blite** [comment]
likely your generated route was like 
```
Route::resource('properties', App\Http\Controllers\API\PropertyAPIController::class);
```
change it to 
```
Route::resource('properties', PropertyAPIController::class);
```
