### ISSUE TITLE
Document --localized on installation#publish or make it a default

### ISSUE THREAD

**Issue by cpasqualini** [InfyOmLabs/laravel-generator#901]
Hi again

Please change the documentation on [infyom:publish](https://labs.infyom.com/laravelgenerator/docs/8.0/installation#publish) step, reflecting that if the project needs localization, must be executed with `--localized` as documented in [Advanced Options/Localization](https://labs.infyom.com/laravelgenerator/docs/8.0/localization)

An alert and a link I think will do the job.

(If you ask, for non English speakers like my team, the localized should be the default option)

Thanks!

**Comment by mitulgolakiya** [comment]
@cpasqualini added.

**Comment by cpasqualini** [comment]
Thanks Mitul

Yes, you added in [Run Publish Layout Command](https://labs.infyom.com/laravelgenerator/docs/8.0/publish-layout#publish-command)

But not in [Installation -> Publish](https://labs.infyom.com/laravelgenerator/docs/8.0/installation#publish)

May be is a misinterpretation, but I execute:

```
php artisan infyom:publish --localized
php artisan ui bootstrap --auth
php artisan infyom.publish:layout --localized
```
Note the --localized on both 

Thanks!
