### ISSUE TITLE
change parameter before validating

### ISSUE THREAD

**Issue by Silviobramas** [InfyOmLabs/laravel-generator#903]
I want to change a parameter before validating.
in My Controller store function i have following code:
`
public function store(CreateLaborgeraetewartungRequest $request){
$input = $request->all();
$input['pruefer_id']=Auth::user()->id;
...
}
`

But before I get there. The program redirects back to the create route because the required parameter pruefer_id is missing.
Thta hapens because the program calls the CreateLaborwartungRequest file before
`
public function rules()
    {
        return Laborgeraetewartung::$rules;
    }

    public function messages()
    {
        return Laborgeraetewartung::$messages;
    }
`

Is there a way to change that order? That i can manupulate that parameter before validating?

**Comment by mitulgolakiya** [comment]
I think this is kind of out of scope question from generator. Maybe you need to customize the code after generation if you have that kind of custom requirements.
