### ISSUE TITLE
API tests template factory call

### ISSUE THREAD

**Issue by lucasgrana** [InfyOmLabs/laravel-generator#905]
In the API test template (templates/api/test/api_test.stub), version 8.0, the factories are called the Laravel 7 way, e.g.:

$$MODEL_NAME_CAMEL$ = factory($MODEL_NAME$::class)->make()->toArray();
$edited$MODEL_NAME$ = factory($MODEL_NAME$::class)->make()->toArray();

I think it should be replaced by

$$MODEL_NAME_CAMEL$ = $MODEL_NAME$::factory()->make()->toArray();
$edited$MODEL_NAME$ = $MODEL_NAME$::factory()->make()->toArray();

And so on

**Comment by mitulgolakiya** [comment]
Just pushed the update.
