### ISSUE TITLE
Override controller infyom from my template controller

### ISSUE THREAD

**Issue by RayhanYulanda** [InfyOmLabs/laravel-generator#909]
Can i customize the controller from mine? I want to add such as `Gate::authorize('profile_read')` for permission. and how to add parameter?

**Comment by RayhanYulanda** [comment]
I have tried using `php artisan infyom.publish:templates` but after run it, it give an error
Fail! file_get_contents(D:\__Boilerplate\adminlte-generator-7.0-tes\vendor/infyomlabs/swagger-generator/templates/model_docs/model.stub): failed to open stream: No such file or directory

**Comment by mitulgolakiya** [comment]
@RayhanYulanda you can publish templates and then make changes into templates based on your needs. Here you can find docs for that. https://labs.infyom.com/laravelgenerator/docs/8.0/publish-templates

**Comment by RayhanYulanda** [comment]
Thanks! @mitulgolakiya
