### ISSUE TITLE
Is it possible to publish the common.errors blades?

### ISSUE THREAD

**Issue by dhcmega** [InfyOmLabs/laravel-generator#910]
Hi
I want to use this package with `--no-dev`, so they are not installed in production.
The only limitation is that the blades for errores are not installed so I get: No hint path defined for [adminlte-templates]

I solved it by copying them to views/vendor/adminlte-templates/ and then adding this line to my AppServiceProvider:
```php
$this->loadViewsFrom(__DIR__.'/../views', 'adminlte-templates');
```

Is there a better/cleaner way?

Thanks!

**Comment by mitulgolakiya** [comment]
The cleaner way will be, you publish templates and customize them to use your errors.blade.php.

I think the only templates you need to publish will be `create.stub` and `edit.stub`.

Where you can remove this line,

`@include('adminlte-templates::common.errors')`

And put a line to include your view. After doing this, whatever new CRUD you create, that will be created with your modified include statement.

So you don't need that file anymore. Let me know if it helps.
