### ISSUE TITLE
php artisan infyom:rollback $MODEL_NAME$ $COMMAND_TYPE

### ISSUE THREAD

**Issue by Sanjeev-Singla** [InfyOmLabs/laravel-generator#914]
This command is not working properly. Givin error file_get_contents(C:\xampp\htdocs\laravel-infyom\resources\views/layouts.menu.blade.php): failed to open stream: No such file or directory

Which is not creating menu in layouts/menu.blade.php, so we did changes in /vendor/infyomlabs/laravel-generator/src/Common/GeneratorConfig.php at line :542 to $this->addOns['menu.menu_file'] = config('infyom.laravel_generator.add_on.menu.menu_file', 'layouts/menu.blade.php');

Then it starts working

**Comment by vishalinfyom** [comment]
Hello @Sanjeev-Singla 

we have just tested it and its working fine for us.

![image](https://user-images.githubusercontent.com/33887755/100496195-3762f200-3178-11eb-9f67-9e872e76f03c.png)


may be you have did custom changes, that's why its not working
