### ISSUE TITLE
Add php 8 support

### ISSUE THREAD

**Issue by C0kkie** [InfyOmLabs/laravel-generator#918]
Hello,

is it possible to add support for php 8?

**Comment by mitulgolakiya** [comment]
@C0kkie have you tried this package with PHP 8? Are you facing any error in installation or CRUD generation with PHP 8?

**Comment by C0kkie** [comment]
If i want to update my packages with composer i get


  Problem 1
    - Root composer.json requires infyomlabs/adminlte-templates 8.0.x-dev -> satisfiable by infyomlabs/adminlte-templates[8.0.x-dev].
    - infyomlabs/adminlte-templates 8.0.x-dev requires php ^7.3 -> your php version (8.0.0) does not satisfy that requirement.       
  Problem 2
    - Root composer.json requires infyomlabs/laravel-generator 8.0.x-dev -> satisfiable by infyomlabs/laravel-generator[8.0.x-dev].  
    - infyomlabs/laravel-generator 8.0.x-dev requires php ^7.3 -> your php version (8.0.0) does not satisfy that requirement.     

cuz i bumped my laravel to php 8  https://blog.laravel.com/laravel-php-8-support

**Comment by C0kkie** [comment]
@mitulgolakiya

**Comment by lorvent** [comment]
a solution like https://github.com/laravel/laravel/blob/develop/composer.json#L11 could help.

**Comment by C0kkie** [comment]
yep should be enough

**Comment by C0kkie** [comment]
https://github.com/InfyOmLabs/laravel-generator/pull/920 @mitulgolakiya

**Comment by C0kkie** [comment]
Also https://github.com/InfyOmLabs/adminlte-templates/pull/63

**Comment by mitulgolakiya** [comment]
PHP 8 Support added.
