### ISSUE TITLE
Test cases with scaffold

### ISSUE THREAD

**Issue by valoma** [InfyOmLabs/laravel-generator#919]
Hi,

Is there a way to generate test cases without generating the api? I am using only scaffold with the repository pattern.

**Comment by mitulgolakiya** [comment]
@valoma Generator generates test cases for APIs and for repositories only. It doesn't generate test cases for scaffolds. so it doesn't make sense to generate test cases without generating APIs.

Can you share a practical use case over here, why you need test cases without API?
