### ISSUE TITLE
can we override generators like we can override templates?

### ISSUE THREAD

**Issue by vesper8** [InfyOmLabs/laravel-generator#92]
I find it very useful that you allow us to publish the templates and then override the ones we want with our own templates.

But is it possible to do the same thing with the generators? Right now I am editing the ones inside the vendor package but this is not ideal as my changes are lost everytime I run composer update.

For example I would like to override /vendor/infyomlabs/laravel-generator/src/Generators/Scaffold because I want to generate a DataTable.blade.php as well as a ModelDataTable.php class.

Is there a better way? Like adding my own service provider.. well to be honest it would be much easier if you just let us do it like you do with the templates. Is that possible?

Thanks!

**Comment by john5db** [comment]
he is working on it 

https://github.com/InfyOmLabs/laravel-generator/issues/50

**Comment by vesper8** [comment]
Yea I know, I saw that and it's great he's going to bake in datatables. But that doesn't answer my question here. What is the best way to override the generators? And if he could make it easy for us to override them in a similar manner to how we override the templates that would be helpful for the future. There may certainly be other cases where users will want to add their own additional stub files.

**Comment by mitulgolakiya** [comment]
@vesper8 really its a great idea to have some detailed architecture level details of this package like how things are actually running. I will document that out once we complete our first milestone.

Also, we have some plans about having some more templates for popular themes and frameworks. so we  are in the process of that. Once we complete 2-3 packages for that then we will have a better idea for documentation like which things are required to be documented.

so I will get it done once everything is in place.

**Comment by Ricardogolosito** [comment]
Hi! i've been searching in the documentation, and haven't found the way to do it. @mitulgolakiya how can we populate, to override, the generators? 
Thanks in advance for all your wonderful job!!!

**Comment by deadmouse** [comment]
I think this is not possible yet. Publishing templates does not publish generators :(

**Comment by vishalinfyom** [comment]
@vesper8 Support added : https://infyom.com/open-source/laravelgenerator/docs/8.0/publish-templates#publish-templates

Thanks
