### ISSUE TITLE
Translation for persian language farsi

### ISSUE THREAD

**Issue by wikiccu** [InfyOmLabs/laravel-generator#922]
Hello
I would ask you is there any plan for translation to the Persian/farsi language  
is it ok if I send a new language and translation files for this project?

**Comment by mitulgolakiya** [comment]
@wikiccu you're most welcome to do that. We use .md files that we have internally, but you send us a readme file for that and we can plan for the translations.

**Comment by wikiccu** [comment]
Thank you, dear @mitulgolakiya 
I was about sending translation for locale/en files and if there are documentation files such as :
Readme.MD or other MD files I can translate them to Persian too.
I'll send my PR for it as soon as possible
