### ISSUE TITLE
Date value initialisation in edit form

### ISSUE THREAD

**Issue by Tetrafarmakos** [InfyOmLabs/laravel-generator#925]
The date field in edit form does not get the selected FORMAT.
The create works fine, but in the format: 'DD-MM-YYYY' a 08-12-2020 date appears as 20-12-2008 in edit form.

**Comment by ShaileshInfyom** [comment]
you should format date like,
  ```  {!! Form::text('balance_date',$tag->balance_date->format('d-m-Y'), ['class' => 'form-control','id'=>'edit_balance_date']) !!}```

Ref:
![image](https://user-images.githubusercontent.com/28335166/150930971-9eca09a8-706a-43fe-9db7-86ebf8c57b07.png)
