### ISSUE TITLE
Tutorial for add packages to laravel and this project?

### ISSUE THREAD

**Issue by NightZpy** [InfyOmLabs/laravel-generator#93]
I'm very interested in extend this package (pull request via), but don't find a good tutorial for this! 
Someone has some good tutorials ?

**Comment by john5db** [comment]
you can check docs here 
http://labs.infyom.com/laravelgenerator/docs/introduction

you can also check older version docs (it is easy to understand)
https://github.com/mitulgolakiya/laravel-api-generator/blob/master/installation.md

**Comment by NightZpy** [comment]
@john5db oh my friend, don't understand me. I want tutorials for colaborate with this package. Then i need some tutorial for make packages for laravel!

**Comment by john5db** [comment]
sorry . I misunderstood you.
there are no tuts for collaboration with this package right now . you can get some info from @mitulgolakiya who is developing this package.

for package development there are many tuts 
some references
http://amitavroy.com/justread/content/articles/developing-package-laravel-51-%E2%80%93-part-1
http://laraveldaily.com/how-to-create-a-laravel-5-package-in-10-easy-steps/

**Comment by mitulgolakiya** [comment]
@john5db We have it in a queue. Where we are going to start a blog, where we will post detailed tutorials for using various features with videos and even the tutorials like how exactly package is working, how someone can extend it and develop even his own packages.

You can track it here: https://github.com/InfyOmLabs/laravel-generator/issues/118
