### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by phillipmadsen** [InfyOmLabs/laravel-generator#930]
Make the swagger prefix configurable in the config. 

```
     * @SWG\Get(
```
If we make it configurable it can tie into other already made systems easier. For instance I use this:
```
     * @OA\Get(
```

**Comment by mitulgolakiya** [comment]
We are planning to move it to OpenAPI Spec 3 and will try to stick to it.

It has been discussed here. https://github.com/InfyOmLabs/swagger-generator/issues/5

We are planning to get it released by next week.
