### ISSUE TITLE
Email template, no such file or directory 

### ISSUE THREAD

**Issue by bitsjuanleal** [InfyOmLabs/laravel-generator#931]
error when running
`php artisan infyom.publish:layout`

Error:
`\vendor/infyomlabs/adminlte-templates/templates/scaffold/auth/email.stub): failed to open stream: No such file or directory`

With package:
`"infyomlabs/adminlte-templates": "^2.0"`

I also get an error to reset, password and verify templates.

only works with the package:
`"infyomlabs/adminlte-templates": "^1.0"`

**Comment by mitulgolakiya** [comment]
@bitsjuanleal Can you let us know which version of generator you are using?

Also the commit hash of laravel-generator from your compsoer.lock file?

**Comment by rcarvs** [comment]
Hi @mitulgolakiya 
The same problem happens with me too. I'm using the version: 8.0.x-dev. A more detailed trace from error:

` ErrorException 

  copy(/var/www/vendor/infyomlabs/adminlte-templates/templates/scaffold/auth/email_locale.stub): failed to open stream: No such file or directory

  at vendor/infyomlabs/laravel-generator/src/Commands/Publish/PublishBaseCommand.php:20
     16▕         if (file_exists($destinationFile) && !$this->confirmOverwrite($destinationFile)) {
     17▕             return;
     18▕         }
     19▕ 
  ➜  20▕         copy($sourceFile, $destinationFile);
     21▕ 
     22▕         $this->comment($fileName.' published');
     23▕         $this->info($destinationFile);
     24▕     }

      +16 vendor frames 
  17  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))` 

If you want I can try to solve the problem and send a pull request.

**Comment by bitsjuanleal** [comment]
Hi @mitulgolakiya

I'm using the version 8.0.x-dev in composer.json: 
`"infyomlabs/laravel-generator": "8.0.x-dev"
![image](https://user-images.githubusercontent.com/43354754/104032792-acc0da00-519c-11eb-95f6-3cbef6c40757.png)


it is the same version that I have in the composer.lock file
![image](https://user-images.githubusercontent.com/43354754/104032622-666b7b00-519c-11eb-8f53-a15af756444f.png)

**Comment by mitulgolakiya** [comment]
I just pushed a fix in 8.0 branch. Check it again @bitsjuanleal @rcarvs
