### ISSUE TITLE
Document

### ISSUE THREAD

**Issue by bappi2097** [InfyOmLabs/laravel-generator#933]
I am recently working on Infyom and when I reading your documentation I have seen this
" Support for all Laravel versions 5.5, 5.6, 5.7, 5.8, 6.0 & 7.0"
So, my question is, is there no support for Laravel 8? Or document has not updated yet.

**Comment by mitulgolakiya** [comment]
It supports 8.0. we will fix it soon. Good catch.

**Comment by vishalinfyom** [comment]
Hello @bappi2097 we have added documentation for laravel 8 too

Here you go : https://infyom.com/open-source/laravelgenerator/docs/8.0/introduction

Thanks
