### ISSUE TITLE
GUI version of this plugin

### ISSUE THREAD

**Issue by john5db** [InfyOmLabs/laravel-generator#94]
It would be nice to have GUI version of this plugin.
in GUI you will do less mistakes, and don't have to type again and again.

sometime i misspell in CMD and hit enter then i can't rollback it will generate all files and i have to delete all files one by one and follow whole procedure again.

** There should be a feature of delete last scaffold to delete all files of last scaffold.
 a command maybe  `php artisan infyom:delete Post --type=scaffold_api`

**Comment by mitulgolakiya** [comment]
GUI version is already in progress and almost 30-40% completed. But it will take a bit long, so it's in 0.2 milestone. Maybe I will ship it in around 1 month.

And about rollback stuff, we already have an issue here: https://github.com/InfyOmLabs/laravel-generator/issues/43

**Comment by john5db** [comment]
Thanks.

**Comment by mitulgolakiya** [comment]
First Beta is out. [Here](http://labs.infyom.com/laravelgenerator/docs/generator-gui-interface) is the doc.

**Comment by mitulgolakiya** [comment]
I would like to hear the thoughts from the community. Will create a separate issue in [GUI Version](https://github.com/InfyOmLabs/generator-builder) repo.
