### ISSUE TITLE
Multiple Delete Option

### ISSUE THREAD

**Issue by rebootcode** [InfyOmLabs/laravel-generator#941]
We don't have multiple delete option.

Is it possible to have this feature or can be done using any tweak?

**Comment by mitulgolakiya** [comment]
@rebootcode you can publish the templates and then customize controller, route, and repository if needed and add a function for multiple delete options. Find a doc here: https://www.infyom.com/open-source/laravelgenerator/docs/8.0/publish-templates

**Comment by rebootcode** [comment]
RIdiculously answered and doesn't make sense.

**Comment by mitulgolakiya** [comment]
@rebootcode Read the docs properly and then try to understand how the generator actually works with templates, then it will make sense.

And show some respect to the author who is answering your question here for free and built this whole tool for free to be used. This needs a huge amount of investment of time.
The above comment should have a better way to be made even if it doesn't make sense.
