### ISSUE TITLE
Many issues with the generator

### ISSUE THREAD

**Issue by BurningDog** [InfyOmLabs/laravel-generator#945]
Hi! Firstly, thanks for making an awesome product! I'm finding it quite useful and have recommended it to others.

That said, I found many issues in normal usage when following the installation and usage documentation at https://www.infyom.com/open-source/laravelgenerator/docs/8.0/ which seem to be major bugs. I could list each of these as a new issue on GitHub, but I didn't want to overwhelm the issue queue.

I'm using latest Laravel and latest version of the Infyom Generator. I'm not using the boilerplate, although I've had to refer to it in many cases.
- [x]  Issue 1
 ### Missing laravelcollective/html

https://www.infyom.com/open-source/laravelgenerator/docs/8.0/installation#add-aliases says to add the following to `config/app.php`:

```php
'Form'      => Collective\Html\FormFacade::class,
'Html'      => Collective\Html\HtmlFacade::class,
'Flash'     => Laracasts\Flash\Flash::class,
```

but neglects to mention that there is a package which needs to be installed in order for them to work:

```sh
composer require laravelcollective/html
```

This package is already installed in the [`composer.json` in the boilerplate](https://github.com/InfyOmLabs/adminlte-generator/blob/8.0/composer.json)
- [x]  Issue 2
 ### Missing files

A number of base files are missing, perhaps I missed somewhere in the setup documentation where they're generated? These files are all present in the [adminlte-generator boilerplate](https://github.com/InfyOmLabs/adminlte-generator) - I had to copy them manually into my project:

* `App\Http\Controllers\AppBaseController`
* `App\Repositories\BaseRepository`
* `Tests\ApiTestTrait`
- [x]  Issue 3
### Handling file uploads

This seems to be left as an exercise to the developer? When I make the `htmlType` for a field to be `file` then an HTML file input is used for the generated CRUD controller, but instead of saving the file correctly, it merely leaves it in `/private/tmp` as the temporary filename. I was expecting to see it saved as a file within Laravel.
- [x]  Issue 4
### Rollback command doesn't roll back all files

The rollback command only partially works.
- [x]  Issue 5
### The generated migration is very basic

The generated migration doesn't specify a primary key (even if `"primary": true,` is set in the field json, and `--fieldsFile=` is used as the scaffold). This must be added manually.

In addition, there's no ability to set fields as nullable when using a fields file, so this needs to manually done in the migration. It would be useful if the documentation mentioned that.
- [x]  Issue 6
### Incorrect path

https://www.infyom.com/open-source/laravelgenerator/docs/8.0/generator-options#fields-from-file says that the path to the sample json file is
`vendor\infyom\laravel-generator\samples\fields_sample.json` which is incorrect, it's
`vendor/infyomlabs/laravel-generator/samples/fields_sample.json`
- [x]  Issue 7
### Undocumented model_schema directory

At https://www.infyom.com/open-source/laravelgenerator/docs/8.0/generator-options#fields-from-file
 it should be made clear that `resources/model_schemas/` can be used to put generated json files in to use for model generation. I had to read the code to work that out.
- [x]  Issue 8
### Generated models

The generated models have extra, unnecessary line breaks in the file which I need to manually remove.

When Swagger comments are added as documentation, they overwrite the comments left which document all of the model's attributes. If I want those comments, I have to run 2 separate Infyom generation commands, copying the attributes after the first one and manually adding them back in after the 2nd.
- [x]  Issue 9
### Other spacing issues

When a controller is generated, the first lines in the class read:

```php
    /** @var  ExampleRepository */
    private $exampleRepository;
```

It should be:

```php
    /** @var ExampleRepository */
    private $exampleRepository;
```

or even better,

```php
    private ExampleRepository $exampleRepository;
```

### Indentation in generated factories

The indentation of generated factories is incorrect - the first attribute is correct, all of the following aren't.
- [x]  Issue 10
### Route prefix incorrect

In `api.php` I have

```php
Route::group(['prefix' => 'admin'], function () {
    Route::resource('about_us_pages', App\Http\Controllers\API\AboutUsPageAPIController::class);
});
```

but actually it should be 

```php
Route::group(['prefix' => 'v1'], function () {
    Route::resource('aboutUsPages', App\Http\Controllers\API\AboutUsPageAPIController::class);
});
```
- [x]  Issue 11
### Tests

Neither generated API tests nor Repository tests work out of the box. Firstly, `phpunit.xml` has to be configured to include them:

```xml
        <testsuite name="API">
            <directory suffix="Test.php">./tests/APIs</directory>
        </testsuite>
        <testsuite name="Repositories">
            <directory suffix="Test.php">./tests/Repositories</directory>
        </testsuite>
```

 Then, each test needs to use `DatabaseMigrations`.
- [x]  Issue 12
### Generated API urls

Regarding the API url generated - e.g. `/api/v1/blogPosts` - https://blog.restcase.com/5-basic-rest-api-design-guidelines/ notes that

> It is recommended to use the spinal-case (which is highlighted by RFC3986), this case is used by Google, PayPal, and other big companies.

The url generated should be `/api/v1/blog-posts`
- [x]  Issue 13
### v1 isn't in URL

It's not clear that `v1` won't be in the url by looking at the config:

```php
    /*
    |--------------------------------------------------------------------------
    | API routes prefix & version
    |--------------------------------------------------------------------------
    |
    */

    'api_prefix'  => 'api',

    'api_version' => 'v1',
```

In what sense is `v1` a route prefix if it's not used in the actual route?

In fact, `route` must be set to `v1` in `prefixes` like so:

```php
    'prefixes' => [

        'route' => 'v1',  // using admin will create route('admin.?.index') type routes

        'path' => '',

        'view' => '',  // using backend will create return view('backend.?.index') type the backend views directory

        'public' => 'public',
    ],
```

It's not clear to me each option does, and the comments don't help explain it either. Please be more descriptive.
- [x]  Issue 14
### Laravel style guide

The generated Blade templates should follow the Laravel style - see https://github.com/laravel/laravel/blob/8.x/resources/views/welcome.blade.php which uses 4 spaces, not 2. Since I have my IDE set up correctly, as soon as I edit one of those files it gets entirely reformatted.
- [x]  Issue 15
### `appointer/swaggervel` is abandoned

https://github.com/appointer/swaggervel is abandoned. The package to use instead is probably https://github.com/DarkaOnLine/L5-Swagger

### Overall workflow

It's nearly impossible that a developer knows exactly what all fields will be upfront, and only uses the generation process once. It would be useful to show a non-trivial example where:

* some initial fields are created
* the model etc is generated
* the API docs are viewed via Swagger, and Postman is used to query the API
* a new field is added
* the initial scaffolding is rolled back (it's not obvious exactly what gets rolled back and what doesn't)
* a new generation command, including what to ignore this time around (e.g. `--skip=menu`)
* work on the migration file, then on next generation do a `--skip=migration`

**Comment by ShaileshInfyom** [comment]
@BurningDog 

![image](https://user-images.githubusercontent.com/28335166/150978415-55367f04-5125-4ba8-882d-bcefed34dff9.png)
it's already menstion in docs. 

![image](https://user-images.githubusercontent.com/28335166/150978521-1a7e88bd-767f-4d3a-9df1-07c3cc6d7003.png)

https://infyom.com/open-source/laravelgenerator/docs/8.0/installation#add-packages

**Comment by ShaileshInfyom** [comment]
@BurningDog 
This is not a valid issue. you need to refer docs properly. These files are generated by the command, you should review this doc. or you can watch tutorials here https://www.youtube.com/playlist?list=PL0wCC44AhrC3JHzcB5qmjYkm70OaoKegg
https://infyom.com/open-source/laravelgenerator/docs/8.0/installation#publish

![image](https://user-images.githubusercontent.com/28335166/150978855-cfb9738a-c581-444c-83e3-bdc2e31f84a9.png)

**Comment by ShaileshInfyom** [comment]
@BurningDog it's depend on OS
![image](https://user-images.githubusercontent.com/28335166/150979509-919017fe-500e-479e-8a57-19f317ba8037.png)

**Comment by ShaileshInfyom** [comment]
@BurningDog it would be good to give more details for the following issue. which files are not rollbacked?
**The rollback command doesn't roll back all files**
The rollback command only partially works.

**Comment by ShaileshInfyom** [comment]
@BurningDog issue no 5. primary key mentioned in model
![image](https://user-images.githubusercontent.com/28335166/150980575-e4648a3a-2c36-4c6d-9713-5708da3d845c.png)

**Comment by ShaileshInfyom** [comment]
@BurningDog issue no 7. you can find doc here https://infyom.com/open-source/laravelgenerator/docs/8.0/generator-options#save-model-schema

**Comment by ShaileshInfyom** [comment]
@BurningDog Regarding API routes. we update docs soon with v1 here https://infyom.com/open-source/laravelgenerator/docs/8.0/installation#update-api-routes

**Comment by ShaileshInfyom** [comment]
@BurningDog  we will plan a letter
![image](https://user-images.githubusercontent.com/28335166/151500658-916c6f9f-4d4a-4697-8319-ac101d13c97a.png)

**Comment by ShaileshInfyom** [comment]
@BurningDog Generator only generates input. you need to implement store and move file logic your end.
![image](https://user-images.githubusercontent.com/28335166/151500718-11afebfc-f3ed-4366-89b0-72e305e3b2a6.png)

**Comment by ShaileshInfyom** [comment]
@BurningDog Test generate for API. you need to configure php.unit manually 
![image](https://user-images.githubusercontent.com/28335166/151502055-5fa88dc5-7dd1-45d5-ac18-0cd2e557b180.png)
