### ISSUE TITLE
Datatables index page seems to be broken

### ISSUE THREAD

**Issue by MrOldham101** [InfyOmLabs/laravel-generator#946]
When scaffolding a new resource either using an existing table, a new table or the GUI (beta) with the datatables option set to true, the produced index view does not seem to load any data. The table renders properly along with any name adjustments however there are no rows listed ( even though there are clearly rows in the database ). I have looked at the back end code and compared it to the yajra/laravel-datatables documentation and I cannot see anything wrong with the implementation. I have even looked into the queries being ran using PHP debugbar and can see the correct query to return all the data is being ran however seemingly never makes it to the view.

**Comment by benmaynardemc** [comment]
I have this same issue and have been banging my head against it for a couple of days, did you find a solution?

**Comment by mlajx** [comment]
I think I found out why this is happening.

When a file is generated by the infyom command, `resources/views/{name}/table.blade.php` is created and there are:

```blade
@push('third_party_scripts')
    @include ('layouts.datatables_js')
    {!! $dataTable->scripts() !!}
@endpush
```

but `@push` is used for `@stack` ([doc](https://laravel.com/docs/8.x/blade#stacks)) and `resources/views/templates/app.blade.php` has `@yield('third_party_scripts')`.

So when I change `@yield('third_party_scripts')` to `@stack('third_party_scripts')`, the table worked normally.

**Comment by vishalinfyom** [comment]
Hello @mlajx we will look into this issue.

**Comment by vishalinfyom** [comment]
Hello @mlajx we just fixed the issue and pushed on dev.

Thanks
