### ISSUE TITLE
Missing Option In Config Documentation

### ISSUE THREAD

**Issue by MrOldham101** [InfyOmLabs/laravel-generator#948]
There is no documentation on the resources option within the config file. The default value is false however if this is talking about resource routes then I wish to enable it however do not know what effect this will have on my application

**Comment by vishalinfyom** [comment]
hello, @MrOldham101 we have provided all the documentation here, as it's not a good habit to add documentation in code.

Resources option is for API resources: https://laravel.com/docs/8.x/eloquent-resources.

Hope this helps.

Thanks
