### ISSUE TITLE
Datatables does not work with Infyom in laravel 8

### ISSUE THREAD

**Issue by aymanalhattami** [InfyOmLabs/laravel-generator#949]
Datatables does not work with Infyom. I use laravel 8, and I followed these links to install datatables with laravel and infyom 

https://www.infyom.com/open-source/laravelgenerator/docs/8.0/generator-options       
https://www.infyom.com/blog/how-to-use-datatables-in-infyom-laravel-generator      
https://github.com/yajra/laravel-datatables        
https://github.com/yajra/laravel-datatables-buttons    
https://github.com/yajra/laravel-datatables-html

**Comment by mitulgolakiya** [comment]
What is the exact problem or error that you are facing?

**Comment by aymanalhattami** [comment]
I found the solution
It was in the table.blade.php

use 
```
@section('third_party_scripts')
    @include('layouts.datatables_js')
    {!! $dataTable->scripts() !!}
@endsection
```

instead of 
```
@push('third_party_scripts')
    @include('layouts.datatables_js')
    {!! $dataTable->scripts() !!}
@endpush
```

**Comment by anirudha2143** [comment]
Create the new database from the scratch 👍🏻

**Comment by anirudha2143** [comment]
I think it will do
