### ISSUE TITLE
Is laravel-generator 8.0.x-dev not actually available for Laravel 6 and 7?

### ISSUE THREAD

**Issue by cawecoy** [InfyOmLabs/laravel-generator#950]
Hi!

[Laravel Generator 8.0 docs says it has "Support for all Laravel versions 6.0, 7.0 & 8.0"](https://www.infyom.com/open-source/laravelgenerator/docs/8.0/introduction), but I can't install it via composer in my Laravel 6 app because `infyomlabs/laravel-generator 8.0.x-dev requires illuminate/support ^8.0 ->  satisfiable by laravel/framework[8.x-dev]`.

So, I guess laravel-generator 8.0.x-dev is not actually available for Laravel 6 and 7. The docs might be fixed.

Thanks.

**Comment by vishalinfyom** [comment]
Hello @cawecoy 

As you are using laravel 6, you have to use related version of infyom generator. here you can find all guide for laravel 6 version installation.

https://infyom.com/open-source/laravelgenerator/docs/6.0/installation

Hope this helps.
