### ISSUE TITLE
wrong routing with prefix

### ISSUE THREAD

**Issue by samraskul** [InfyOmLabs/laravel-generator#951]
when I run this command:

`php artisan infyom:scaffold Category --prefix=admin --fieldsFile=infyom\Category.json
`
in web.php you will see this route:
`Route::resource('categories', App\Http\Controllers\Admin\Admin\CategoryController::class, ["as" => 'admin']);
`
but it should be:
`Route::resource('categories', App\Http\Controllers\Admin\CategoryController::class, ["as" => 'admin']);
`
so remove one `\Admin`

**Comment by vishalinfyom** [comment]
Hello @samraskul 

we are using that prefix for views/controllers and etc. so right not its not possible to do that change, as lots of other users are also using that option.

Thanks
