### ISSUE TITLE
Why generator generates table id with  integer? Where laravel defaults uses  Big integer.

### ISSUE THREAD

**Issue by findridoy** [InfyOmLabs/laravel-generator#953]
I was facing a problem using this code:

$table->forerignId('market_id')->constrained();

This gives me error. coz laravel assume that my market table id is big integer but infyom generated table with integer.

**Comment by vishalinfyom** [comment]
Hello @findridoy right now we are generating ids as an integer as per laravel previous versions. we will consider your feedback and try to make the id to big int if possible.

Thanks
