### ISSUE TITLE
Missing required parameter for [Route: $tablename.destroy] 

### ISSUE THREAD

**Issue by jmllubes** [InfyOmLabs/laravel-generator#956]
Hello I tried several times with fresh install and when I generate models from tables I can't access in any url from models , it prints this error:
 Illuminate\Routing\Exceptions\UrlGenerationException
Missing required parameter for [Route: usuaris.destroy] [URI: usuaris/{usuari}] [Missing parameter: usuari]. (View: C:\xampp\htdocs\laravelbiblioteca\resources\views\usuaris\table.blade.php)

But I can use api resource and it works perfectly. I dont know where is the problem. If you can help me thank you.

**Comment by vishalinfyom** [comment]
Hello,

Which laravel version you are using ?

**Comment by jmllubes** [comment]
> Hello,
> 
> Which laravel version you are using ?

Im using 8.x but I found the problem, I was generating models from tables and it makes id field as a primary key, so I was to make custom primary key to fix that.
