### ISSUE TITLE
Datatable no show table 

### ISSUE THREAD

**Issue by burotica49** [InfyOmLabs/laravel-generator#958]
Hello,

I have tried several times to make the CRUD file with datatables work. The data is saved in the table but when displaying the page, the table remains empty.

I have successfully installed Button plugin and HTML Plugin

Installation by AdminLTE Template / PHP 7.4.16

Best regard

**Comment by mitulgolakiya** [comment]
@burotica49 if it's still not resolved, I will recommend watching this video and hopefully, it should be resolved.

https://www.youtube.com/watch?v=YC0YXrAF4SA
