### ISSUE TITLE
Parameter on GUI builder

### ISSUE THREAD

**Issue by RayhanYulanda** [InfyOmLabs/laravel-generator#959]
How can i get txtpaginate on GUI builder to infyom-generator-templates? Can i just add $paginate$? 
Or where can i see the variable that can i take for the template?

**Comment by vishalinfyom** [comment]
Hii,

please note that right now we are supporting the pagination on normal views only,

As data tables views are itself coming with pagination.

You can get more info at here : https://infyom.com/open-source/laravelgenerator/docs/8.0/generator-options#paginate-records

Thanks
