### ISSUE TITLE
Upgrade from laravel 7 to laravel 8

### ISSUE THREAD

**Issue by RayhanYulanda** [InfyOmLabs/laravel-generator#961]
Is there any guide for upgrade?

**Comment by mitulgolakiya** [comment]
@RayhanYulanda generator does not intend to provide an upgrade of laravel apps. You need to upgrade your laravel application to version 8 and then use Laravel Generator's 8.0 branch to generate new CRUDs.

**Comment by RayhanYulanda** [comment]
Oke, thanks a lot! @mitulgolakiya
