### ISSUE TITLE
Edit not working in generated api

### ISSUE THREAD

**Issue by sbn111** [InfyOmLabs/laravel-generator#962]
Hi sir,

I was generated api using **php artisan infyom:api member** command.

And the command successfull. Add, delete, get and list is working properly. 

But edit is not working. Kindly help to solve the issue and let me know if I done anything wrong.

I am using laravel version 7 and infyom laravel generator version 7.

I tried it in postman, Received the following error, I created api with only two column name and email.
In that name is required field.
Check the screenshot - [Click to see screenshot](https://prnt.sc/13s8kiu)

It showing the name field is required error response, But the name field is already filled.
If I remove required for name column, It just returning the data like get request, but not updated

Waiting for your reply

Hope explained clearly

Thank you

**Comment by shailesh-ladumor** [comment]
@sbn111 i think you trying with form data. Please try with row and pass json in put request from postman. See example here https://images.app.goo.gl/DF2YZQ4eKWZbYaPK7

**Comment by sbn111** [comment]
> 
> 
> @sbn111 i think you trying with form data. Please try with row and pass json in put request from postman. See example here https://images.app.goo.gl/DF2YZQ4eKWZbYaPK7

Thank you it worked. Really appreciate your quick response. I starting to see your youtube videos
