### ISSUE TITLE
[Feature] Generate seeder and faker on GUI

### ISSUE THREAD

**Issue by RayhanYulanda** [InfyOmLabs/laravel-generator#964]
I need to make seeder and faker when i generate the crud and i didnt get any idea where should i change it in config. Can you help me?

**Comment by RayhanYulanda** [comment]
https://github.com/InfyOmLabs/laravel-generator/issues/912

**Comment by vishalinfyom** [comment]
@RayhanYulanda you can use this option to generate seeder : https://infyom.com/open-source/laravelgenerator/docs/8.0/generator-options#generate-seeder

And use this option to generate factory : https://infyom.com/open-source/laravelgenerator/docs/8.0/generator-options#generate-factory

Hope it helps :)
