### ISSUE TITLE
Datatable does not show row

### ISSUE THREAD

**Issue by Dri372** [InfyOmLabs/laravel-generator#967]
I installed Infyom on Laravel 8 and try to use datatable
folowing this link https://www.youtube.com/watch?v=YC0YXrAF4SA

I am able to create data, but I see **no row** and my page is not like the example
        ◦ No searsch button
        ◦ No buttons (Create, Export, …) below Articles in the upper left
        ◦ No msg : « No data available »

I put  my example here but it should be good if so can put a link of a good example in order for me (and others in the same case) to debug.

**Comment by Dri372** [comment]
I read more in detail this post and the solution in it.
https://github.com/InfyOmLabs/laravel-generator/issues/843
I forgot to publish datatable add_on html & buttons

**Comment by khlewesamer** [comment]
i face that i fix it by by change the name of @push('third_party_scripts') to @push('scripts') , so u need to be sure from that , i notice there is no httpe request on Network console , and u can directly replace whole js @push section with the following lines  : 
```
<script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.3.1/js/dataTables.buttons.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.3.1/js/buttons.bootstrap.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.3.1/js/buttons.colVis.min.js"></script>
<script src="{{ asset('vendor/datatables/buttons.server-side.js') }}"></script>
    {!! $dataTable->scripts() !!} 
```

i hope that help some one
