### ISSUE TITLE
Datatable action buttons bug

### ISSUE THREAD

**Issue by Dri372** [InfyOmLabs/laravel-generator#971]
Laravel 8 

**Action buttons are not displayed.**

    • In resources/views/es1s/datatables_actions.blade.php, for instance for Edit button
        ◦ `<i class="glyphicon glyphicon-eye-open"></i>	`	icon not found

**Solution**
        ◦ <i class="far fa-eye"></i>
            ▪ Use font Awesome as view without datatable option
        ◦ Or in layouts/datatables_css.blade.php
```
            ▪ <!--link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.6.2/css/buttons.bootstrap4.min.css"-->
            ▪ <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
```

**Comment by vishalinfyom** [comment]
Hii,

We already have fixed that issue into our latest release of admin LTE templates.
Here : https://github.com/InfyOmLabs/adminlte-templates/commit/7d909f4f558bea332fa50bdb44e9a740bd24f624

Thanks
