### ISSUE TITLE
DataTable - Search by Column

### ISSUE THREAD

**Issue by Dri372** [InfyOmLabs/laravel-generator#972]
Hi All,

I did not find any option to generate a DataTable with "Search Column".

Does anybody know if is possible? If not I'm looking advice how to add this (which part of code to modify?)

Thank in advance.

**Comment by Dri372** [comment]
How I did it (with a little modification in yajra/datables-html/builler - see Step 5)

 - 0-https://datatables.net/examples/api/multi_filter.html
        ◦ reference example 
- 1-php artisan infyom.publish:templates
- 2-resources/infyom/infyom-generator-templates/scaffold/views/datatable_body.stub
```
datatable_body.stub 
@section('third_party_stylesheets')
    @include('layouts.datatables_css')
@endsection

{{-- $dataTable->table(['width' => '100%', 'class' => 'table table-striped table-bordered']) --}}
{!! $dataTable->table(['width' => '100%', 'class' => 'table table-striped table-bordered'],true) !!}  {{-- drawFooter --}}
```

- 3  config/datatables-html.php

```
<?php
return [
    /*
     * The script template used by infyom datatable
     */
    # 'script' => 'datatables::script',
    'script' => 'layouts/script',
];
```

- 4 resources/views/layouts/script.blade.php
```
$(document).ready(function() {
    // Setup - add a text input to each footer cell
    $("#dataTableBuilder tfoot th").each( function () {
        var title = $(this).text();
        $(this).html( "<input type=\'text\' placeholder=\"Search\" />" );
    } );
});

$(function(){window.{{ config('datatables-html.namespace', 'LaravelDataTables') }}=window.{{ config('datatables-html.namespace', 'LaravelDataTables') }}||{};window.{{ config('datatables-html.namespace', 'LaravelDataTables') }}["%1$s"]=$("#%1$s").DataTable(%2$s
        ,initComplete: function () {
            // Apply the search
		this.api().columns().every( function () {
                var that = this;	
                $( "input", this.footer() ).on( "keyup change clear", function () {
                    if ( that.search() !== this.value ) {
                        that
                            .search( this.value )
                            .draw();
                    }
                } );
            } );
        }
	} ); }
);
```
- 5     • vendor/yajra/laravel-datatables-html/src/Html/Builder.php
```
    public function generateScripts()
    {
        $parameters = $this->generateJson();
$parameters=substr($parameters,0,strlen($parameters)-1);	# remove the last } in order to add a parameter
        return new HtmlString(
            sprintf($this->template(), $this->getTableAttribute('id'), $parameters)
        );
    }
```

**Comment by adiatma85** [comment]
Is this still on? If this exist, ones can generate views so easliy without add search column manually

**Comment by Dri372** [comment]
Hi @adiatma85 , it works nice, only thing the little modification in yajra package (point 5)

**Comment by adiatma85** [comment]
Sorry for late response, but the does maintainer acknowledged a PR with change in yajra package as you mentioned above?
Nevertheless,  I think it's worth to make a PR for this
Thanks

**Comment by Dri372** [comment]
does maintainer acknowledged a PR`

As you can see this issue is still opened, not reviewed by the maintainer.

`with change in yajra package`

Change like this is not a good  solution, the maintainer will probably not accept as is.

`
worth to make a PR for this`

No, see previous answer and the fact that the modification in yajra is Ok but make the package not working without Infyom/DataTable

`
Last but not least`
One step after on step, consider this just as a working workaround , after review the maintainer can have an other idea or tag as 'tip' or open the wiki and transfer ot it.

Regards.

**Comment by ShaileshInfyom** [comment]
you can follow the above solution or see this video tutorial  https://youtu.be/UCyoZ0To-ik
