### ISSUE TITLE
Use the --fromTable command with htmlTypes 

### ISSUE THREAD

**Issue by kevin4dhd** [InfyOmLabs/laravel-generator#978]
Hello I am looking for a way to use the FromTable command and to be able to assign the htmlTypes for example select or radiobuttons since they are all generated as text, if someone knew the trick or how I have to do it it would be very helpful

**Comment by mitulgolakiya** [comment]
@kevin4dhd I will say you first generate the CRUD with `--fromTable` and save the model files. Then you can modify the model files with HTML types you want and then regenerate the CRUD again from `--fromFile` option.

Let me know if that helps.
