### ISSUE TITLE
Error - Naming the application

### ISSUE THREAD

**Issue by 3runoDesign** [InfyOmLabs/laravel-generator#98]
When you change the application name using `php artisan app:name`, occurs exception. Because it can not find the controller.

**Comment by vesper8** [comment]
yea this bug is ooooold.. I reported it like 6 months ago on the previous project. I hope it will be fixed along with #70 as it is kind of related.

**Comment by mitulgolakiya** [comment]
After changing namespace of your application, are you updating your namespaces in `config/infyom/laravel_config.php` ? It's documented over here: http://labs.infyom.com/laravelgenerator/docs/advanced/config-file#namespaces

**Comment by 3runoDesign** [comment]
Doesn't work! @mitulgolakiya does not find the file:
https://github.com/InfyOmLabs/laravel-generator/blob/master/src/Controller/AppBaseController.php#L5

**Comment by mitulgolakiya** [comment]
@3runoDesign ok, will fix it.

**Comment by mitulgolakiya** [comment]
resolved in latest version.
