### ISSUE TITLE
This package contains a huge bug when generating "unique" validation data AND "trying to update"

### ISSUE THREAD

**Issue by chegmarco1989** [InfyOmLabs/laravel-generator#987]
Hello.

When trying to generate a CRUD with a "**unique**" validation role, we are faced with a serious Bug when updating the data that I even exposed on Stackoverflow [https://stackoverflow.com/questions/70194002/laravel-8-column-was-not-found-when-i-try-to-update-my-data-however-my-update-me](https://stackoverflow.com/questions/70194002/laravel-8-column-was-not-found-when-i-try-to-update-my-data-however-my-update-me) to have a reliable correction but in vain.

The final solution I found is to just use "**required**" as the validator role. And when I removed the "**unique**" role to keep the "**required**".

How then to integrate "**unique**" validations of the data in the database without ever having during the update of the data already created, a return of the following error:

`**C:\laragon\www\btechimmo\
Illuminate\Database\QueryException
SQLSTATE[42S22]: Column not found: 1054 Unknown column '1' in 'where clause' (SQL: select count(*) as aggregate from `posts` where `1` = Maison 1)
http://127.0.0.1:8000/posts/1**`

**???**

**Comment by vishalinfyom** [comment]
Hii @chegmarco1989 

Will you please send us the exact steps to produce the issue?

i mean from the beginning, which commands i have to run and with which params?

**Comment by chegmarco1989** [comment]
**The problem occurs when you try to update the data created from Admin. So it is at the level of the Update method and especially when you generate the data with as a** `unique` **rule (following this video seuence: [https://youtu.be/8VuEzoz42BQ?t=233](https://youtu.be/8VuEzoz42BQ?t=233)) :**

> php artisan infyom:api_scaffold Post
> 
> Field: (name db_type html_type options) []:
>  > title string:unique text
> 
>  Enter validations:  []:
>  > required|unique:posts

**And now login to admin and post data. Then, once created, try to edit them. You will be unable to modify your data and will see the error displayed:**

> C:\laragon\www\btechimmo\ Illuminate\Database\QueryException SQLSTATE[42S22]: Column not found: 1054 Unknown column '1' in 'where clause' (SQL: select count(*) as aggregate from postswhere1 = Maison 1) http://127.0.0.1:8000/posts/1

**Comment by ShaileshInfyom** [comment]
@chegmarco1989 we are not able to reproduce the issue. 
Yes, you need to change the Rules in the edit request.  get validation error while edit time if not change but it's not break anything. you can get error looks like,
![image](https://user-images.githubusercontent.com/28335166/150976198-550ed09f-cf71-4830-bda8-70f0a41cbce6.png)

You need to change in edit request. 
UpdatePostRequest.php
```
  public function rules()
    {
        $rules = [
            'title' => ['required', 'unique:posts,title,'.$this->route('id')],
        ];

        return $rules;
    }
```

**Comment by chegmarco1989** [comment]
Thanks.
