### ISSUE TITLE
[Feature]: Add Laravel ^9.0 support for all InfyOmLabs Packages

### ISSUE THREAD

**Issue by robertmarney** [InfyOmLabs/laravel-generator#991]

**Comment by mitulgolakiya** [comment]
@robertmarney we are planning it to be done by end of next week for all of our packages.

**Comment by mitulgolakiya** [comment]
## Generator Core Packages

- [x] [laravel-generator](https://github.com/InfyOmLabs/laravel-generator)
- [x] [laravel-generator-helpers](https://github.com/InfyOmLabs/laravel-generator-helpers)
- [x] [swagger-generator](https://github.com/InfyOmLabs/swagger-generator)
- [x] [generator-builder](https://github.com/InfyOmLabs/generator-builder)

## Template Packages

- [x] [adminlte-templates](https://github.com/InfyOmLabs/adminlte-templates)
- [x] [stisla-templates](https://github.com/InfyOmLabs/stisla-templates)
- [ ] [coreui-templates](https://github.com/InfyOmLabs/coreui-templates)

## Template Boilerplates

- [ ] [adminlte-generator](https://github.com/InfyOmLabs/adminlte-generator)
- [ ] [stisla-generator](https://github.com/InfyOmLabs/stisla-generator)
- [ ] [coreui-generator](https://github.com/InfyOmLabs/coreui-generator)


## Laravel UI Packages

- [x] [laravel-ui-adminlte](https://github.com/InfyOmLabs/laravel-ui-adminlte)
- [x] [laravel-ui-stisla](https://github.com/InfyOmLabs/laravel-ui-stisla)
- [ ] [laravel-ui-coreui](https://github.com/InfyOmLabs/laravel-ui-coreui)

## Other Packages

- [x] [laravel-envato](https://github.com/InfyOmLabs/laravel-envato)
- [x] [laravel-calendar-events](https://github.com/InfyOmLabs/laravel-calendar-events)
- [ ] [laravel-payumoney](https://github.com/InfyOmLabs/laravel-payumoney)
- [x] [laravel-upcitemdb](https://github.com/InfyOmLabs/laravel-upcitemdb)
- [x] [laravel-routes-explorer](https://github.com/InfyOmLabs/laravel-routes-explorer)

**Comment by robertmarney** [comment]
Thank you!

**Comment by Buhadod** [comment]
Dears,

Thank you for working on this feature. Any update yet about the release ?

Regards,
Abdulla

**Comment by mitulgolakiya** [comment]
@Buhadod yes, Most of the packages which are marked as checked above are done.

**Comment by skys215** [comment]
Not sure why files are deleted in InfyOmLabs/adminlte-templates/tree/develop/templates/scaffold/layouts in this [commit](https://github.com/InfyOmLabs/adminlte-templates/commit/7ee6c3980b0e3be3129d65541bfc907a2ae51cf5).
Several command can't be run because of missing stub files.

**Comment by mitulgolakiya** [comment]
@skys215 Those files are removed because, in the newer version, template packages are dependent on respective laravel-ui packages.

For example,

`adminlte-templates` has dependency of `laravel-ui-adminlte`. Check here: https://github.com/InfyOmLabs/adminlte-templates/blob/v4.0.0/composer.json#L23

so we don't need to manage double scaffolding. But realized that, it is breaking the localized version. so that will need to be fixed.

If you really understand it, then you are welcome to place a PR :)
Or We will plan it.
