### ISSUE TITLE
[Feature]: Configuration for layout views

### ISSUE THREAD

**Issue by theanadimukt** [InfyOmLabs/laravel-generator#992]
When working with custom admin template package, I am having different layout structure such as app and guest with sidebar, navbar, footer, main content section. 

It would be great if you guys provide a list of publishable views config option in `laravel_generator.php` config file instead of hardcoding in `LayoutPublishCommand.php` file.

https://github.com/InfyOmLabs/laravel-generator/blob/c00a3eaf54a9b59e581772220145bb2199ad86d5/src/Commands/Publish/LayoutPublishCommand.php#L67

Thanks for the stunning package 😊

**Comment by mitulgolakiya** [comment]
Related to https://github.com/InfyOmLabs/laravel-generator/issues/471

**Comment by mitulgolakiya** [comment]
https://github.com/InfyOmLabs/laravel-generator/issues/471#issuecomment-1193604980

Check this. Now, LayoutPublishCommand has been removed. You can use customized views from the vendor directory and adjust the structure manually after the layout publishes via laravel-ui-adminlte.
