### ISSUE TITLE
Rollback does skip some files from purging

### ISSUE THREAD

**Issue by theanadimukt** [InfyOmLabs/laravel-generator#993]
I have been facing two issues with rollback. 

1. When I ran the command, console displayed `invalid rollback type` warning and processed it to delete files.

`php artisan infyom:rollback ContentBlocks scaffold_api`

![image](https://user-images.githubusercontent.com/25764632/153441041-1dd98fc6-f11a-4b66-bdc9-b7c16f76c7bc.png)

2. The command had skipped 2 files from the process.

`ContentBlocksDataTable.php`
`datatables_actions.blade.php`

**Comment by mitulgolakiya** [comment]
It has been fixed in the latest version.
