### ISSUE TITLE
[Bug]: syntax error, unexpected token "?" when using console command

### ISSUE THREAD

**Issue by hazwan91** [InfyOmLabs/laravel-generator#996]
I have issue on generate scaffold/api/api_scaffold and this is what its show.

![Capture](https://user-images.githubusercontent.com/97268905/158919645-d80fe1c5-d9ad-4aa6-bfb7-a833e76a2314.PNG)

I am using Laravel 9 & php 8.1.3

![Capture](https://user-images.githubusercontent.com/97268905/158919836-89bd553b-ea26-4774-bcf8-8a1bb7a0da75.PNG)

I have follow the exact step of installation on the docs but not using the boilerplate since there's no 9.0 tree branch for all templates.

Please help.

**Comment by mitulgolakiya** [comment]
@hazwan91 It looks like, somehow, the install command has messed up RouteService Provider.

- Have you run the install command twice?
- Can you let me know what exact steps you followed?
- Can you post your RouteServiceProvider here?

**Comment by hazwan91** [comment]
> Have you run the install command twice?

No. In fact, i did try to install again before replying this.

> Can you let me know what exact steps you followed?

This is the exact steps that i did:

1. `composer create-project laravel/laravel example-app`
2. open the app with code editor, and open composer.json
3. based on this docs, [https://infyom.com/open-source/laravelgenerator/docs/9.0/installation#installing-into-existing-laravel-projects](url), i choose `Installing into existing Laravel Projects`
4. add the following packages: `"infyomlabs/laravel-generator": "^4.0"` & `"infyomlabs/adminlte-templates": "^4.0"`
5. then add `"doctrine/dbal": "~2.3"`
6. on terminal, run `composer update`
7. and run `php artisan vendor:publish --provider="InfyOm\Generator\InfyOmGeneratorServiceProvider"`
8. last one for setup is run `php artisan infyom:publish` (i think this part cause the problem)
9. then i just type `php artisan infyom`

Then the problem occured shows.

> Can you post your RouteServiceProvider here?

````
<?php

namespace App\Providers;

use Illuminate\Cache\RateLimiting\Limit;
use Illuminate\Foundation\Support\Providers\RouteServiceProvider as ServiceProvider;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\RateLimiter;
use Illuminate\Support\Facades\Route;

class RouteServiceProvider extends ServiceProvider
{
    /**
     * The path to the "home" route for your application.
     *
     * This is used by Laravel authentication to redirect users after login.
     *
     * @var string
     */
    public const HOME = '/home';

    /**
     * Define your route model bindings, pattern filters, etc.
     *
     * @return void
     */
    public function boot()
    {
        $this->configureRateLimiting();

        $this->routes(function () {
            Route::prefix('api')
                ->middleware('api')
                ->group(base_path('routes/api.php'));

            Route::middleware('web')
                ->group(base_path('routes/web.php'));
        });
    }

    /**
     * Configure the rate limiters for the application.
     *
     * @return void
     */
    protected function configureRateLimiting()
    {
        RateLimiter::for('api', function (Request $request) {
            return Limit::perMinute(60)->by($request->user()?->id ?: $request->ip());
        });
    }
}
Route::prefix('api')
                ->middleware('api')
                ->as('api.')<?php

namespace App\Providers;

use Illuminate\Cache\RateLimiting\Limit;
use Illuminate\Foundation\Support\Providers\RouteServiceProvider as ServiceProvider;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\RateLimiter;
use Illuminate\Support\Facades\Route;

class RouteServiceProvider extends ServiceProvider
{
    /**
     * The path to the "home" route for your application.
     *
     * This is used by Laravel authentication to redirect users after login.
     *
     * @var string
     */
    public const HOME = '/home';

    /**
     * Define your route model bindings, pattern filters, etc.
     *
     * @return void
     */
    public function boot()
    {
        $this->configureRateLimiting();

        $this->routes(function () {
            Route::prefix('api')
                ->middleware('api')
                ->group(base_path('routes/api.php'));

            Route::middleware('web')
                ->group(base_path('routes/web.php'));
        });
    }

    /**
     * Configure the rate limiters for the application.
     *
     * @return void
     */
    protected function configureRateLimiting()
    {
        RateLimiter::for('api', function (Request $request) {
            return Limit::perMinute(60)->by($request->user()?->id ?: $request->ip());
        });
    }
}
````

**Comment by mitulgolakiya** [comment]
I just tried the same steps and I'm not able to reproduce the problem. It looks like in your case, command is failed to find the,

```
Route::prefix('api')
                ->middleware('api')
```

so it attached the content twice. The final content of RouteServiceProvider should be,

```
<?php

namespace App\Providers;

use Illuminate\Cache\RateLimiting\Limit;
use Illuminate\Foundation\Support\Providers\RouteServiceProvider as ServiceProvider;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\RateLimiter;
use Illuminate\Support\Facades\Route;

class RouteServiceProvider extends ServiceProvider
{
    /**
     * The path to the "home" route for your application.
     *
     * This is used by Laravel authentication to redirect users after login.
     *
     * @var string
     */
    public const HOME = '/home';

    /**
     * Define your route model bindings, pattern filters, etc.
     *
     * @return void
     */
    public function boot()
    {
        $this->configureRateLimiting();

        $this->routes(function () {
            Route::prefix('api')
                ->middleware('api')
                ->as('api.')
                ->group(base_path('routes/api.php'));

            Route::middleware('web')
                ->group(base_path('routes/web.php'));
        });
    }

    /**
     * Configure the rate limiters for the application.
     *
     * @return void
     */
    protected function configureRateLimiting()
    {
        RateLimiter::for('api', function (Request $request) {
            return Limit::perMinute(60)->by($request->user()?->id ?: $request->ip());
        });
    }
}
```

Try to replace this content in your RouteServiceProvider and it should work.

Also, can you let me know which OS you are using?

**Comment by mitulgolakiya** [comment]
@hazwan91 also, if you can do the following om your local machine, then I can confirm the problem.

1. Go to `vendor/infyomlabs/laravel-generator/src/Commands/Publish/GeneratorPublishCommand.php`
2. Find the function `updateRouteServiceProvider`
3. Replace the function with the following code

```
    private function updateRouteServiceProvider()
    {
        $routeServiceProviderPath = app_path('Providers'.DIRECTORY_SEPARATOR.'RouteServiceProvider.php');

        if (!file_exists($routeServiceProviderPath)) {
            $this->error("Route Service provider not found on $routeServiceProviderPath");

            return 1;
        }

        $fileContent = file_get_contents($routeServiceProviderPath);

        $search = "Route::prefix('api')".PHP_EOL.str(' ')->repeat(16)."->middleware('api')";

        $apiRouteIndex = strpos($fileContent, $search);

        if ($apiRouteIndex === false) {
            $this->error('Could not find api route in RouteServiceProvider.php');

            return 1;
        }

        $beforeContent = str($fileContent)->before($search);
        $afterContent = str($fileContent)->after($search);

        $finalContent = $beforeContent.$search.PHP_EOL.str(' ')->repeat(16)."->as('api.')".$afterContent;
        file_put_contents($routeServiceProviderPath, $finalContent);

        $this->info('RouteService Provider Updated');

        return 0;
    }
```

And repeat the same steps above that you provided and let me know the output on the console?

Thanks.

**Comment by hazwan91** [comment]
Hmm weird as you have not facing this problem

I am using Windows 10, and Laragon

After i replace my RouteServiceProvider.php with yours, its working and on my terminal shows this.
![Capture](https://user-images.githubusercontent.com/97268905/159117242-0cc56926-ef65-4853-92b1-4646031cc515.PNG)

Also i did like you asked and update the `updateRouteServiceProvider` with your code. I replace this code **BEFORE** i do the step no.7 based on the step that i provide before.

Then on the step no. 9, it shows like this

![Capture](https://user-images.githubusercontent.com/97268905/159117348-c69f84a0-d495-49f2-a491-0fdc2e695978.PNG)

But it still works when i run `php artisan infyom` as it shows list of command

![Capture](https://user-images.githubusercontent.com/97268905/159117385-3e12f4b1-6d45-4fa5-a8b5-6e82f95f9392.PNG)

**Comment by hazwan91** [comment]
It seems i don't have any problem for now. Just need to update my RouteServiceProvider.php for fresh install.

Thanks. Hope it get fixed so that i don't have to update RouteServiceProvider.php everytime i create new project.

**Comment by mitulgolakiya** [comment]
@hazwan91  You need to run `php artisan infyom:publish`
